### ISSUE TITLE
Random blank space displayed in between Settings page options

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1000]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.17.0 ,  Test Flight Build V1.17.0 
**Repro on devices:** Google Pixel 4a (11.0), Redmi Note 8 (9.0), Vivo v11 pro (10), Redmi Note 8 (10.0),  iPhone 12 (14.7.1),iPhone XR (14.6)
**Testing Account:**   (515) 444 0200 / [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B5)
**Repro Steps:**
1.Launch the application &  login with the test account.
2. Tap on “Hamburger Menu”  & select “Settings” option
3. Scroll down & observed that
**Current Behavior:**  Blank space displayed in between Terms Of Service options
**Expected Behavior:**  Blank space should not displayed between any options of Settings page
**Impact:** Bad user experience
**Investigation:** Also we have observed that, In Android user is able to see blank space in between “Share Analytics” & “Legal” sections
**Attachment:** [RandomBlankSpace](https://drive.google.com/file/d/1Hu8WLSmq3Sq9xnwc9WRXfxDZApv47wfe/view?usp=sharing)

**Comment by lisaqyli** [comment]
@ValoraQA  Can someone give me access to the attachment? I can't open it with my Valora account

**Comment by ValoraQA** [comment]
Hey @lisaqyli Can you please send your Valora account ID so we can share our folder with you to check all attachments ?

**Comment by lisaqyli** [comment]
lisa.li@valoraapp.com

**Comment by ValoraQA** [comment]
Hey @lisaqyli We have shared access to our folder to your lisa.li@valoraapp.com Valora account ID.
Thanks..!!

**Comment by lisaqyli** [comment]
Closing b/c it's the intended design

**Comment by ValoraQA** [comment]
Hey @lisaqyli, thank you vey much for the information.
