### ISSUE TITLE
User not able to receive 3 8digit codes to complete verification on the confirm page. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1009]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.18,Test flight build V1.18.0(72)
**Does not repro build version** Test flight build V1.17.0,Android internal build V1.17
**Repro on devices:** Samsung Galaxy M31(10), Vivo v11 pro (10), iPhone 6+(12.5.4), Google Pixel 4a (11.0) 
**Repro Steps:**

1. Launch the application & complete onboarding process.
2. Enter valid phone number & tap on start button
3. Complete captcha & wait 2 mins on confirming screen
4. Make sure user should on confirm page 
5. Observe 

**Current Behavior:**  User not able to receive codes 
**Expected Behavior:**  User should be able to receive the codes 
**Impact:** User get blocked to complete the verification flow 
**Attachment:** [CodesNotReceived.MP4](https://drive.google.com/file/d/1rNsRTiDZXoe_riykm_P1aO2HYpJp_T26/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D96](https://valora.testquality.com/project/12128/result/2469005/defect/8146).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D97](https://valora.testquality.com/project/12128/result/2469298/defect/8147).

**Comment by MuckT** [comment]
@ValoraQA what happens when attempting to resend codes?

**Comment by MuckT** [comment]
@ValoraQA please retest; there was an issue with Komenci which should now be resolved.

**Comment by ValoraQA** [comment]
Hey @MuckT I have verified this  issue using Test Flight build V1.18.0 &  Android Internal build V1.18.0 & observed following:
**Observation:** 

**Android&iOS 1st attempt:** 

- [ ] User not able to receive 3 codes after completing timer screen & redirect to "Confirm" page
- [ ] Also after tapping on "Resend All Messages" button user get only one verification link instead of 8 digit codes & not able to get other two links.
- [ ] Also after tapping on "Resend  Messages"  button no any links received & after sometime user got "Confirmation Error" popup. 
[Attachment](https://drive.google.com/file/d/1PPYZ39w2zaB745zSVSzcemA1_lfIa02O/view?usp=sharing)

**Android&iOS 2nd attempt:** 

- [ ] User not able to receive 3 codes after completing timer screen & redirect to "Confirm" page
- [ ] After tapping on "Resend All Messages" button user redirecting to timer screen & stays on timer screen with 00:00 timer  even 2mints timer completed for longer time 
[Attachment](https://drive.google.com/file/d/1zK0lXrj8_5jlVDVjaigGxFqjXXhTRGXi/view?usp=sharing)


**Verified On Devices:** iPhone 12 (14.7.1),iPhone XR (14.6), Redmi Note 8 (9.0)

**Comment by ValoraQA** [comment]
Hey @MuckT I have verified this  issue using Test Flight build V1.18.0 &  Android Internal build V1.18.0 & observed following:
**Observation:** 

**Android&iOS on 1st attempt:** 

- [ ] User not able to receive 3 codes after completing timer screen & redirect to "Confirm" page
- [ ] Also after tapping on "Resend All Messages" button user get only one verification link instead of 8 digit codes & not able to get other two links.
- [ ] Also after tapping on "Resend  Messages"  button no any links received & after sometime user got "Confirmation Error" popup. 
[Attachment](https://drive.google.com/file/d/1PPYZ39w2zaB745zSVSzcemA1_lfIa02O/view?usp=sharing)

**Android&iOS on 2nd attempt:** 

- [ ] User not able to receive 3 codes after completing timer screen & redirect to "Confirm" page
- [ ] After tapping on "Resend All Messages" button user redirecting to timer screen & stays on timer screen with 00:00 timer  even 2mints timer completed for longer time 
- [ ] Also after waiting for longer time on "00:00" timer screen user got "Confirmation Error" popup. 
[Attachment](https://drive.google.com/file/d/1zK0lXrj8_5jlVDVjaigGxFqjXXhTRGXi/view?usp=sharing)


**Verified On Devices:** iPhone 12 (14.7.1),iPhone XR (14.6), Redmi Note 8 (9.0)

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Test Flight build V1.18.0 & Android Internal build V1.18.0 & observed that the issue is fixed now.

**Devices:** Google Pixel 4a (11.0), iPhone 12 (14.7.1), iPhone 6+ (12.4.5), Vivo V11 pro (10)
