### ISSUE TITLE
User not able to see the “Remind” button on invitation CTA for old invites. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1016]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.18,Test flight build V1.18.0(72)
**Does not repro build version** Test flight build V1.17.0,Android internal build V1.17
**Repro on devices:** Samsung Galaxy M31(10), Vivo v11 pro (10), iPhone 6+(12.5.4), Google Pixel 4a (11.0) 
Test account:  (680) 333 1978 / [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
Precondition: Make sure user should have some older invites 
**Repro Steps:**

1. Launch the application & login with given test account 
2. Go to home page 
3. Tap on view all button on Invitation CTA
4. Observe older invites & new invite

**Current Behavior:** User not able to see the remind button on invitation cta
**Expected Behavior:**  User should able to see remind for older invites
**Impact:** User get blocked to remind
**Attachment:** [RemindButton.PNG](https://drive.google.com/file/d/1l3RF7rjmVI4gDfolD3p1KfGrhJDalMmi/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Test Flight build V1.18.0 & Android Internal build V1.18.0 & observed that the issue is still reproducible.

**Devices:**iPhone 12 (14.7.1), iPhone 6+ (12.4.5), Vivo V11 pro (10)
**Attachment:** [remind button issue.jpg](https://drive.google.com/file/d/1UNm8d_pd3m8F243W67cHkgjUx-KS1R0V/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA, some clarification on this issue: If the account was restored with existing invitations the remind button will not be present.
