### ISSUE TITLE
[Regression]:User redirects to “Phone number” screen on typing wrong spelling of word in account key & tapping “Restore” button second time without modifying the wrong word to correct word.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1019]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.18.0 
**Does not repro build version:** Testflight Build V1.18.0, Android Playstore Build V1.17.0
**Repro on devices:** Google Pixel 4a (11.0), Redmi Note 8 (10.0), Redmi Note 8 (9.0)
**Does not repro devices:** iPhone 12 (14.7.1), Google Pixel 4a(11.0)
**Testing Account:**   Account Key: gather secret proof essence text sunny inform zone second luxury evidence raccoon expire link thrive spy female spread fame symptom grass consider arena region

**Pre-condition:** 
1. User must have installed the application.
2. User must have completed education flow & is on “Restore Existing Wallet” screen.

**Repro Steps:**

1. Enter 24-words account key in account key section.
2. Enter spelling of one word of account key wrong EG: seceret.
3. Tap on “Restore” button.
4. “Some words in the account key are not valid..” error appears.
5. Again Tap on “Restore” button & observe the bug.

**Current Behavior:** User is redirected to “Phone number” screen on tapping “Restore” button second time without modifying the wrong spelling of word to correct word.

**Expected Behavior:** User must be redirected to “Phone number” screen on tapping “Restore button” second time after modifying the wrong spelling of word to correct one.

**Impact:** Bad user experience as user gets redirected to Phone number screen on tapping restore button second time without modifying the word.

**Investigation:** This issue is not reproducible in Android playstore build V1.17.0 & Test flight build V1.18.0, as the user remains on “Restore Existing Wallet” screen on tapping “Restore” button second time without modifying the account key with correct word.

**Attachment:** [Wrong spelling issue.mp4](https://drive.google.com/file/d/1B-CwLDSHe8NKAaV5IwhMX7VrqT5aOuu-/view?usp=sharing)

**Comment by gnardini** [comment]
Do you have logs or the address of the inviter and invited accounts?

**Comment by ValoraQA** [comment]
Hi @gnardini, We have captured and attached the logs below.

**Device:** Google Pixel 4a (11.0)
**Logs:** [celo_logs.txt](https://drive.google.com/file/d/14tFzDx8HPb9n3fRKrUziwwEGerhXbzyL/view?usp=sharing) 
Thanks..!!

**Comment by MuckT** [comment]
@gnardini from the logs it looks like the nemonic was matched to an account via autocorrection.

```
Info [2021-08-24T04:21:46.002Z] import/saga@attemptBackupPhraseCorrection/Found correction phrase with balance in attempt 1
Info [2021-08-24T04:21:46.002Z] ValoraAnalytics/Tracking event wallet_import_phrase_correction_success with properties: {"timestamp":1629778906002,"sessionId":"1208add0f26df7717336318ac6cd607e215222c7e052c55f6ec7f5f641345c","userAddress":"","celoNetwork":"mainnet","attemptNumber":1}
Debug [2021-08-24T04:21:46.011Z] tokens/saga@fetchTokenBalanceInWeiWithRetry/Account 0xEeEFcfB4758ade804aF2e10a2905934999F67D37 cEUR balance: 0
```

**Comment by MuckT** [comment]
@ValoraQA this looks like the nemonic auto correct is working as expected.

**Comment by ValoraQA** [comment]
Hey @MuckT, thank you very much for the information.
