### ISSUE TITLE
Invalid contact does not appear in the contacts list on “Send”screen with all other contacts. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1027]
**Frequency:** 100%
**Repro on build version:** Test flight build V1.18.0, Android Internal Build V1.18.0
**Repro on devices:**iPhone 12 (14.7.1), Google pixel 4a (11.0)

**Pre-condition:** 

1. User must have installed & login into application.
2. User must have allowed contacts permission and must have one invalid contact saved.

**Repro Steps:**

1. Launch the app.
2.Tap on “Send” button from home screen.
3.User navigates to “Send” screen with list of contacts & observe the bug

**Current Behavior:** Invalid contact does not appear in the contacts list on “Send” screen with all other contacts. 
 
**Expected Behavior:** Invalid contact should appear in the contacts list on “Send” screen with all other contacts. 

**Impact:** Bad user experience. 

**Investigation:** This issue is not reproducible while requesting amount after sending cUSD to another user

**Attachment:** 
[Invalid contacts issue.mp4](https://drive.google.com/file/d/1L5H6OZvKMgBqfemermMqwh6NpyNQd_DS/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA can attach logs related to this issue?

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D106](https://valora.testquality.com/project/12128/result/2471006/defect/8185).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D107](https://valora.testquality.com/project/12128/result/2470991/defect/8186).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D109](https://valora.testquality.com/project/12128/result/2471027/defect/8188).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D110](https://valora.testquality.com/project/12128/result/2471042/defect/8189).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D268](https://valora.testquality.com/project/12128/result/2524797/defect/8471).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D450](https://valora.testquality.com/project/12128/result/2545955/defect/8758).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D451](https://valora.testquality.com/project/12128/result/2545940/defect/8759).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D474](https://valora.testquality.com/project/12128/result/2545708/defect/8809).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D655](https://valora.testquality.com/project/12128/result/2573830/defect/9276).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D659](https://valora.testquality.com/project/12128/result/2573845/defect/9297).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D774](https://valora.testquality.com/project/12128/result/2590600/defect/9440).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D778](https://valora.testquality.com/project/12128/result/2590615/defect/9444).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D783](https://valora.testquality.com/project/12128/result/2590577/defect/9451).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D876](https://valora.testquality.com/project/12128/result/2614299/defect/9679).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D880](https://valora.testquality.com/project/12128/result/2614314/defect/9683).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D892](https://valora.testquality.com/project/12128/result/2611601/defect/9699).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D893](https://valora.testquality.com/project/12128/result/2611616/defect/9700).
