### ISSUE TITLE
Buy & Sell From CELO Exchange Fail Every Other Time

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1043]
### Current behavior
Buy & Sell from celo exchange fail every other time

### Desired behavior
Buy and Sell should work every time

### Steps to Reproduce

1. Navigate to Exchange: Menu -> Celo
2. Purchase Celo
3. Observe results - purchase successful
4. Purchase Celo
5. Observe results - purchase fails
6. Repeat the above steps with Sell

### Versions
v1.18 iOS and Android Devices

### Logs
[exchange_error.txt](https://github.com/valora-inc/wallet/files/7069276/exchange_error.txt)

### Tasks
- [ ] Fix bug
- [ ] Add e2e tests to ensure that problem doesn't surface again

**Comment by isabellewei** [comment]
seems like the gas estimation is causing an error somehow 🤔 not sure why but will look into it further
