### ISSUE TITLE
Hide invite item in side menu

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1044]
### What would you like?
Hide the invite item in the side menu because of concerns it might confuse users with the launch of invite rewards.

**Comment by ValoraQA** [comment]
Hi @gnardini , We have verified this task on latest Android internal build V1.19.0 & Testflight build V1.19.0 (1029460203) and updated the status in below sheet;
**Sheet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1673025569

**Devices:** iPhone 12 (14.7.1), Google Pixel 2XL (11.0)

**Comment by ValoraQA** [comment]
Hi @gnardini , We have verified this task on latest Android internal build V1.19.0 & updated the status in below sheet.

**Sheet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1673025569

**Devices:** Redmi Note 8 (10.0)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R98](https://valora.testquality.com/project/12128/testcase/299601/requirement/11869).

**Comment by ValoraQA** [comment]
Hey @gnardini We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**iOS (13.0):**
-  https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485153

**Verified On Devices:** iPhone SE (13.6.1)
CC : @MuckT
