### ISSUE TITLE
Make phone number verification in the onboarding flow remotely configurable

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1050]
We should be able to turn on/off the phone number verification in the onboarding flow remotely, based on user's location.
For example, since we know that success rate for phone number verification in Brazil is just 30%, we should be able to remove it from the onboarding flow for that country.

Probably a good way to do that is to have the feature flag in Firebase where we can set filters on a country level.

Once we have this config, we can launch an experiment (in Brazil, for example) to see how this will affect the onboarding funnel pull through.

**Comment by cajubelt** [comment]
duplicates #1838
