### ISSUE TITLE
Remove Contact matchmaking screen

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1052]
### Current behavior
There is a screen to import contacts that Google is complaining about.

### Desired behavior
There is no screen to sync contacts.

### Steps to Reproduce
Verify your phone number, see that you jump to the success screen directly.

### Versions
All

**Comment by ValoraQA** [comment]
Hey @gnardini  , We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Gsuite.

**GSuite Link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=129895685

**Verified On Devices:** Redmi note 8 (10.0), iPhone 12 (14.7.1)
CC: @MuckT

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R97](https://valora.testquality.com/project/12128/testcase/299600/requirement/11868).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**iOS (13.0):**

- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485152

**Verified On Devices:** iPhone SE (13.6.1)
CC : @gnardini
