### ISSUE TITLE
Support Multiple tokens in Valora

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1061]
Product Requirements Document: https://www.notion.so/valora-inc/PRD-Support-for-multiple-tokens-in-Valora-9d6eca94b0844b948777325caeff194f

Designs: https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Balances-on-the-Home-Screen?node-id=0%3A1

**Comment by ellenwoconnor** [comment]
@kathaypacific can this epic be closed out? it seems like all the work is completed

**Comment by kathaypacific** [comment]
Yes! the only thing left i can think of is removing the remote config flag for the old transaction feed (there was a big refactor of the home feed and there is still a lot of old code for the feed that doesn't support multi tokens) - i'll create a separate issue for that
