### ISSUE TITLE
Display total balance on the home screen

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1062]
Add to the home screen the total sum of all assets that user holds.
Remove balances from the side menu.
It is OK if some tokens that user holds don't have a price, just skip them.

 [the mockups](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Balances-on-the-Home-Screen?node-id=562%3A7723) 

For now, ignore the error cases but make sure to include all the scenarios where the user holds 0-N tokens.

**Comment by jeanregisser** [comment]
See the [latest designs](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Balances-on-the-Home-Screen?node-id=716%3A17899).
