### ISSUE TITLE
Fix WalletConnect universal deeplink

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1065]
WalletConnect universal deeplink on mobile is not working.

Steps to reproduce on mobile (iOS):
1. Open https://app.sushi.com
2. Connect Wallet
3. Select `Connect Wallet`
4. Look for `Valora` (page 4) and tap it 
<img src="https://images.zenhubusercontent.com/5f8d54cb717387f606ed5dce/3dd82802-3388-42f9-80f2-4fa75c6eb01f" width="50%" />
5. Notice it opens the browser to a 404 page on valoraapp.com instead of opening Valora with the WalletConnect flow
<img src="https://images.zenhubusercontent.com/5f8d54cb717387f606ed5dce/718630b9-3bed-45d0-a020-35722980e60b" width="50%" />

This is because the universal deeplink metadata is not setup on valoraapp.com.

Android uses `wc://` links on mobile which Valora is already registered to handle.
The OS should prompt the user to select the app to open when handling such links.
Unless the user has selected to always handle `wc://` links with a specific app.

We should check both iOS and Android handle the mobile-to-mobile flow with WalletConnect.

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Android Alfajores build V1.20.1, Test flight Alfajores build 1.20.1 (163277387) & updated the status in below sheet.

Sheet Link: https://docs.google.com/spreadsheets/d/1kJdb-eT69OM35LQUIpBKMI5MXNG-oXVaYoflX6XmGfA/edit#gid=1803698288

Devices: iPhone 12 (14.7.1), Redmi Note 8 (10.0), iPhone 6+ (12.5.4), OnePlus 7t (11.0)

**Observation:**

New query : [Link](https://github.com/valora-inc/wallet/issues/1196)

CC: @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Android Alfajores build V1.20.1, Test flight Alfajores build 1.20.1 (163277387) & updated the status in below sheet.

Sheet Link: https://docs.google.com/spreadsheets/d/1kJdb-eT69OM35LQUIpBKMI5MXNG-oXVaYoflX6XmGfA/edit#gid=1803698288

Devices: iPhone 12 (14.7.1), Redmi Note 8 (10.0), iPhone 6+ (12.5.4), OnePlus 7t (11.0)

New query : [Link](https://github.com/valora-inc/wallet/issues/1196)

CC: @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT we have updated the observations in PR [#1113](https://github.com/valora-inc/wallet/pull/1113) for above ticket
Thanks !!

CC: @tarikbellamine
