### ISSUE TITLE
Fix no feedback when scanning WalletConnect QR codes

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1066]
Scanning WalletConnect QR codes with Valora doesn't always work and provides no feedback when it fails.

The WalletConnect QR codes processing involves asynchronous operations in Valora.
Currently there is no feedback provided to the user of this async process.

We should provide visual feedback while processing and in case of an error.

WalletConnect QR codes can be tested with https://use-contractkit.vercel.app/

**Comment by aleksey-nov** [comment]
Another communication on QR code scanning screen:

- when scanning started;
- when loading started.
- when connection was established - user has to go back to browser and we need to inform them about it.

Types of errors with WC:

- the most often error is the timeout.
- another error is that user cancelled the connection on the other side
- no internet connection.
