### ISSUE TITLE
Investigate issues with use-contractkit

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1068]
[use-contractkit](https://use-contractkit.vercel.app/) is being used by more projects interacting with Valora but it doesn't always work.

Most common issue is the QR code not loading:
<img src="https://images.zenhubusercontent.com/5f8d54cb717387f606ed5dce/cecb0862-7f99-473a-8c3c-cd5b10727368" width="50%" />

The work here is really about investigating and collaborating with the people working on it (@AlexBHarley) to make it more reliable.

**Comment by jeanregisser** [comment]
Related investigations: https://valora-app.slack.com/archives/C029Z1QMD7B/p1630570849018400

**Comment by MuckT** [comment]
An issue with contract kit & Valora [User not able to scan QR code using use-contractkit from scan section of connected apps. #1106](https://github.com/valora-inc/wallet/issues/1106).
