### ISSUE TITLE
Scale on Edit photo page does not reduce less than 32% on trying to reduce while setting profile photo.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1072]
**Frequency:** 100%
**Repro on build version:** Andoird Alphajores Build V1.18.3 
**Repro on devices:** Google pixel 2XL (11), google pixel XL (10), Moto g5s Plus (8.1) 

**Pre-condition:** 
1. User must have freshly installed application.
2. User must have complete education flow & user is on “Create account Step 1 of 5” screen

**Repro Steps:**
1. Launch the app.
2. Tap on “Add Photo” icon from “Create account Step 1 of 5” screen.
3. Tap on “Choose from library” option & allow permission.
4. Select any photo and user is redirected to “Edit photo” screen.
5. Tap on scale option at button, try to adjust scale manually & observe.

**Current Behavior:** Scale on Edit photo page does not reduce less than 32% on trying to reduce while setting profile photo.

**Expected Behavior:** Scale on Edit photo page should reduce below 32% on trying to reduce while setting profile photo.

**Impact:** Bad user impact

**Attachment:** 
[Scale issue.mp4](https://drive.google.com/file/d/1RcxyeTLk_kphRKHTJPNuukHpW71bh8VC/view?usp=sharing)

**Comment by gnardini** [comment]
This is fine for now, thanks!
