### ISSUE TITLE
 “Connect Contacts” screen not displayed after pasting attestation codes successfully from “Confirm” page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1073]
**Frequency:** 100%
**Repro on build version:** Alfajores build V1.18.3
**Repro on devices:**  Samsung Galaxy J5 Prime (8.0), Google Pixel 2XL (11.0),  iPhone 12(14.7.1),
**Testing Account:** (515) 808 5659/[Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B73)
**Repro Steps:**
1. Launch the application & completing onboarding process
2. Start verification process & user should received 3 attestation codes
3. Paste all 3 valid codes & wait for sometime
4. Observed that,
**Current Behavior:** User redirects to Home screen after last code accepting successfully
**Expected Behavior:** User should redirect to “Connect Contacts” screen 
**Investigation:** Also we have  verified same issue while Restoring account with verified phone number
**Impact:** User unable to sync contacts while Signing up/in
**Attachment:** [ConnectContactsScreenNotDisplayed.wmv](https://drive.google.com/file/d/1ibDCQreVrsehVEJNQFwM0L2vPx1ItKzj/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA the "Connect Contact" screen was removed in 1.18.3. Once we get more feedback from the Google Playstore we'll have a better idea of the expected behavior. For now this is expected in 1.18.3.

**Comment by ValoraQA** [comment]
Thanks for Confirmation:)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D259](https://valora.testquality.com/project/12128/result/2524761/defect/8452).
