### ISSUE TITLE
[Query] Confirming screen appears with timer , when user taps on “<” back button on enter pin screen after tapping of Resend all messages from confirm page.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1082]
**Frequency:** 100%
**Repro on build version:** Play store build V1.18.3, App store Build V1.18.0, Test flight build V1.17.0, V1.16.0 
**Repro on devices:** Redmi Note 8 (10.0), Samsung Galaxy J5 Prime (8.0), Google Pixel 2 XL (11.0), iPhone 12 (14.7.1) 

**Pre-condition:** 
1. User must have installed the app.
2. User must be on the “Confirm” page in create account flow.

**Repro Steps:**
1. Launch the app.
2. Tap on “Resend All Messages” from confirm page.
3. Tap on “<” back  button on enter pin page & observe that  

**Current Behavior:** Confirming screen appears with timer , when user tap on back button on enter pin screen after tapping of Resend all messages from confirm page.  

**Expected Behavior:** Confirming screen should not appear when user tap on back button on enter pin screen.

**Impact:** Bad user experience.

**Attachment:** 
[Confirming Screen Issue.mp4](https://drive.google.com/file/d/1hwhv_uoB85jcqj3wFAcml6QJP6m9PooD/view?usp=sharing)

**Comment by gnardini** [comment]
What should happen exactly? Thanks for reporting but I'm not sure what the best experience here is.

cc @aleksey-nov @nityarao
