### ISSUE TITLE
When a user selects a flag can we show the country code on the number field by default as a prefix.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1087]
**Frequency:** 100%
**Repro on build version:** Android play store  V1.18.3, App store build V1.18.0
**Repro on devices:** One plus 7T (11.0) , iPhone 6+ (12.5.4), Samsung Galaxy M01 Core (10.0), iPhone 12 (14.7.1) , Samsung Galaxy J5 Prime (8.0)

**Pre-condition:**
1. User must have a freshly installed application.
2. User must have complete education flow & user is on “Phone number verification page 4 of 5” screen

**Repro Steps:**
1. Launch the app.
2. Create a new account and perform Steps 1 to 3
3. On step 4: On the phone confirmation page, click on the country flag field.
4. Select any country and it will show the flag accordingly on the phone number verification page.

**Current Behavior:** After selecting any flag it shows the flag on the phone number verification field

**Expected Behavior:** It should show only the selected flag with country code on the phone number verification field eg: if the user selects the US flag then can we show +1 on the phone number verification field.

**Investigation:**
1.If the user enters a number along the country code then the flag is not changing as per the country code
Eg : Country flag is India , user enters UK number along 44 (which is UK country code) , it does not change the flag to UK
2. If we show the prefix then the user would understand that country flag needs to be changed
3. If user enters the number along with country code while prefix is also seen, then we can discard the country code number

**Impact:**
1. If the user tries to remove the number using backspace of keyboard the country code is repeating multiple times
2. Provided with prefix seen on field user would get an idea and will enter mobile directly instead of entering it with country code

**Attachment:** 
[Phone number verification field.jpg](https://drive.google.com/file/d/1d9f5xay0g-LMPEsM8rFXXV6ud9S6vbDR/view?usp=sharing)

**Comment by gnardini** [comment]
Thisis agood idea but I don't think we have the bandwidth to implement it now :/
