### ISSUE TITLE
Valora should respect system font settings and rescale appropriately.

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#109]
### Expected Behavior

Valora should respect system font settings and rescale appropriately.

### Current Behavior

There is an overlap between the transaction amount and the account number. See screenshot attached + screenshot of font size settings in the OS

![Screenshot_20210309-162133_Settings.jpg](https://images.zenhubusercontent.com/60005dfc77558b950d71dca4/14797e9d-a08d-4a41-aa92-9daecaf2388c)![tempFileForShare_20210309-162033.jpg](https://images.zenhubusercontent.com/60005dfc77558b950d71dca4/1083dcf3-6778-4115-ae2e-3223ed4bc1c8)

**Comment by Celoqa** [comment]
Hi @aleksey-nov We have field same related issue about font size https://github.com/celo-org/celo-monorepo/issues/6357

**Comment by MuckT** [comment]
Adding a link to an issue tracking various font size and localization issues #277

**Comment by MuckT** [comment]
Closed with Misc Accessibility #913.
