### ISSUE TITLE
[analytics] Enable user parameters tracking for firebase thorough segment 

### ISSUE THREAD

**Issue by grvalora** [valora-inc/wallet#1097]
Hello,

We are currently missing the tracking of key features for firebase. 

**1. User ID tracking
2. User Parameters tracking** 

Segment supports both the functions via the identity tracking as per the link here : https://segment.com/docs/connections/destinations/catalog/firebase/#identify

Please set **User ID** variable for firebase as a wallet address 
and enable following **parameters** as a **user properties**.  sharing the key names below and the values should match the description. Update the values as soon as the information is available and/or the values changes (updates).

**loginStatus** :	Send login status of user. yes if logged in else no	
**userLanguage** :	send the two digit ISO language code of the user in lower case	
**userAddress** :	user address in lower case	
**userPhoneCode** :	Send phone country code of the user or else undefined if not available	
**CELOBalance** :	send the float value of the celo balance	
**cUSDBalance** :	send the float value of the cusd balance	
**cEURBalance** :	send the float value of the ceur balance	
**country** :	Send the three digit (Alpha-3 code) of the countries based on phone country code	
**deviceOptin :**	Whether the phone is optin to for notifications	
**advertisingCode :**	Grab the IDFA or ADID of the device if enabled in lower case	
**deviceId :**	Generate custom device ID to be used as identifier across different sources	
**appVersion :**	Version of the app	
**appId :**	ID of the app	
**appName :**	Name of the app	
**fiatCurrency :**	Default currency of the app customer in lower case	
**phoneVerification :**	Whether phone verification is complete
**accountBackupCompleted** : yes or no mentioning whether a user has verified their address.
 
More details about the variables can be seen here in the google sheets tracking spec document
https://docs.google.com/spreadsheets/d/11ElhqmnRfeBgwuaAYPqx0e7GsT2WQfH1ei5szQKS1uM/edit#gid=1048963559&range=A1

ENG:
* **User ID parameter** is set to take the wallet address of the user in lower case 
* As soon as the app starts the **user id and other user properties** are called via the identity class function
* Should any of the user property changes while the user is active on the app, the user property is updated to the new value. 
* [Current traits](https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/analytics/saga.ts#L18) we're sending to Segment

AC:
- [ ] User segmentation based on country, asset balances, language etc
- [ ] ensure all events have the User ID (*i.e.*, the wallet address) easing the event debugging

**Comment by silasbw** [comment]
How do the ACs relate to Firebase?

**Comment by silasbw** [comment]
It looks like we're already "Please set User ID variable for firebase as a wallet address" (or at least we think we are): https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/analytics/saga.ts#L39

Have you looked at that data?

**Comment by grvalora** [comment]
Yes @silasbw , I can see user ID being set on both Segment and Firebase
then the only other requirement is for the second part.

About ACs realted to firebase, we are using segment for the data streaming to firebase. So any changes in segment will impact host of other tools like firebase, adjust & clevertap

![image.png](https://images.zenhubusercontent.com/610c15c3d406bbe75388a732/9cc604e4-da77-41f4-80a0-06978be3acb4)

**Comment by silasbw** [comment]
Overlaps with https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/305
