### ISSUE TITLE
[Query] : We have observed that if the font size is max then scroll bar is not seen on PIN page is that fine ?

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1102]
**Frequency:** 100%
**Repro on build version:** Ios build version : 1.19.0
**Repro on devices:** Iphone 6+ (V:12.5.4) , iPhone 12 (14.7.1)
**Pre-condition:** 
1. User must have freshly installed application.
2. User must be on Create account page 

**Repro Steps:**
1. Change font size setting to max from phone settings
2. Launch the app
3. Perform the steps and go to step 2 of 5 Create Pin page

**Current Behavior:** Scroll bar is not seen on PIN pages

**Expected Behavior:** If the font size are largest scroll bar should be seen on PIN pages

**Investigation:** 
- The scroll bar is not seen where ever the PIN pages are applicable

**Impact:** 
- User wont be able to scroll the page incase if the device screen size is small

**Attachment:** [scrollbarnotseen.mp4](https://drive.google.com/file/d/13f1rLEkxw0UeTplE5GMHJFY_swk6weIE/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA It's expected that scroll bar is no longer present see expected results in 'Pin pad scroll on iOS #248'
