### ISSUE TITLE
“<” arrow & “X” icon displayed instead of  “Cancel”  & “Edit” buttons while exchanging CELO

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1103]
**Frequency:** 100%
**Repro on build version:** Android internal build & Testflight Build V:1.19.0
**Does Not Repro on build version:** Android Play Store build v1.18.3 , App store build V1.18.0
**Repro on devices:** OnePlus 7T (11.0), Iphone 6+ (12.5.4), Samsung Galaxy J5 Prime (8.0), Samsung Galaxy M01 Core (10.0)
**Testing Account:**(680) 333 1978/[Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
**Pre-condition:** User  should have some cUSD & CELO balance in account
**Repro Steps:**
1. Launch the application & login with the test account
2. Redirect to Buy CELO total page by tapping on “Buy” button
3. Observed that, 
**Current Behavior:** User is able to see “<” arrow & “X” icon at top LHS & RHS side of Buy CELO total page
**Expected Behavior:** User should able to see “Cancel” & “Edit” button at top side of page
**Investigation:** Also we have observed same issue for “Sell CELO” page
Also for iPhone 12 (14.7.1) we have observed that "Cancel" & "<" arrow displayed instead of "Cancel" & "Edit" button
**Attachment:** [Cancel&EditButtonNotDisplayed](https://drive.google.com/file/d/1iWS6mSprzK5rzwWLnIPpL74iJhbD_e2x/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA
|Text Size | Expected Behavior for Buy & Sell CELO |
|----|----|
|Large| “<” arrow & “X” icon at top LHS & RHS respectively |
|Default| “<” icon & “Cancel” text at top LHS & RHS respectively |

**Comment by ValoraQA** [comment]
Hey @MuckT, thank you very much for the information. We will update the test cases accordingly.
