### ISSUE TITLE
Handle error situations when displaying tokens

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1125]
Once #1062 is done, we need to handle errors when fetching the balance of a token fails.
The most common one is probably being offline, but we should also handle just random failures on one of the calls to fetch balances, probably add some sort of retrying mechanism.

See the [mockups here](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Balances-on-the-Home-Screen?node-id=562%3A7723) and ask the design or product teams if you have any questions.

**Comment by MuckT** [comment]
We could use [promise-retry](https://www.npmjs.com/package/promise-retry) or [ts-promise-retry](https://www.npmjs.com/package/ts-retry-promise) to handle retries with a backoff.
