### ISSUE TITLE
“Payment Received You have received 0.02 cUSD” in notification appears in blue banner after signing up using France phone number with invite received with amount

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1129]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.19.0, Test flight build V1.19.0
**Repro on devices:** Redmi Note 8 (9.0), OnePlus 7T (11.0), iPhone 12 (14.7.1)

**Pre-condition:** 
1. User must have received amount invite for the France phone number
2. User must be on “confirm” page in create account flow 
3. User received 3 8 digit codes with same invited France phone number.

**Repro Steps:**
1. Enter all the 3 8-digit Confirmation codes in the confirm page.
2. User is redirected to home screen after some time.
3. Invite funds are received after some time & observe

**Current Behavior:** “Payment Received You have received 0.02 cUSD” in notification appears in blue banner after signing up using France phone number with invite received with amount 

**Expected Behavior:**“Payment Received You have received <amount> cEUR” must appear in notification in blue banner after signing up using France phone number with invite received with amount 

**Impact:** Bad User experience.

**Attachment:** 
[cUSD payment issue.mp4](https://drive.google.com/file/d/18GqOjtE5JXX_St04IzT5Q7kVCb4CrfAK/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA invite rewards are currently only received in cUSD - Working as intended.

**Comment by ValoraQA** [comment]
Hey @MuckT Need some clarification as in Home feed we are able to see "€0.01" amount after claiming amount. But only in In-App CTA it displayed 0.02 cUSD. So is it expected ? 
Can we get more information for this like Figma screen or something like that ?
**Thanks..!!!**
