### ISSUE TITLE
[Query] Should we show "Allow Valora to receive messages" permission pop up after user is redirected to the OTP page ?

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1139]
**Frequency:** 100%

**Repro on build version:** Android internal build Version: 1.19.0 Ios Testflight build Version : 1.19.0

**Repro on devices:** OnePlus 7T (V:11.0) , iPhone 6+ (V:12.5.4), Redmi Note 8 (10.0) , iPhone 12 (14.7.1)

**Pre-condition:** 
1. User must have freshly installed application.
2. User must have selected create account 
3. User must have entered name and click on next 

**Repro Steps:**
1. User is redirected to phone number page
2. Now enter valid phone number and click on start 
3. Confirmation screen will be seen 
4. After 2 minutes it will show OTP page

**Current Behavior:** After Otp are received it automatically reads and are seen on the numeric field

**Expected Behavior:** It should ask permission to access messages and read OTP automatically 

**Investigation:** 
1] For many applications this permission is asked to access messages whereas Valora application directly auto reads the OTP without permission
 
**Impact:** : Permission popup should mandatory for security purpose

**Attachment:** [otp_page.jpg](https://drive.google.com/file/d/1BqKV8YwBW5PPx66RVyGiIbr3IyvK4QX2/view?usp=sharing)

**Comment by MuckT** [comment]
[Relevant Playstore requirements](https://support.google.com/googleplay/android-developer/answer/10208820?hl=en#zippy=%2Cpermitted-uses-of-the-sms-and-call-log-permissions); however, we are using an SMS retriever as directed by Google so we do not need to add additional permission requirements. [Read more about SMS Retriever API here](https://developers.google.com/identity/sms-retriever/overview).

@etuleu can you confirm this is correct regarding Google permissions?
