### ISSUE TITLE
Upgrade Node version from Node 12 to Node 16

### ISSUE THREAD

**Issue by noisypigeon** [valora-inc/wallet#1144]
Things to be updated:
- Github workflows
- CI machines
- downstream dependencies

**Comment by silasbw** [comment]
Is it OK to aim for Node.js 16 initially: it's LTS, 17 is brand spanking new (so it might have issues), and I'd like to spend our "node.js upgrade cycles" on getting all our projects to Node.js 16.  Sound reasonable?

**Comment by noisypigeon** [comment]
Yeah sure sounds good!
