### ISSUE TITLE
Upgrade React Native version

### ISSUE THREAD

**Issue by noisypigeon** [valora-inc/wallet#1145]
ENG:
- @jeanregisser might have some tips for doing the upgrade easily

AC:
- [ ] wallet uses version 0.66.X+ of React Native
- [ ] CI passes reliably
- [ ] Run some ad-hoc smoke tests on an iOS device and an Android device

**Comment by MuckT** [comment]
@kathaypacific I believe we should target 0.65.x as it looks like Detox support isn't quite there yet for 0.66.x. [Detox PR for 0.66.x support](https://github.com/wix/Detox/pull/3035).
