### ISSUE TITLE
[M3] Integrate Persona into cash-in flow - To be broken down

### ISSUE THREAD

**Issue by tarikbellamine** [valora-inc/wallet#1160]
As a prerequisite to using our in-house liquidity solution, users must first complete KYC through Persona. We will be integrating the Persona screens into the cash-in and cash-out flows to make that process seamless for users.

Designs: https://www.figma.com/file/2GviFls4HMHzf686hOviOh/Add%2C-Withdraw%2C-Spend?node-id=1326%3A6

AC:
- [ ] Persona is shown during the cash-in flow if a user hasn't KYC'ed
- [ ] Persona is not shown during the cash-in flow if the user has KYC'ed
- [ ] Persona is only shown to users with a US IP address (in-house liquidity will only be available to US users)
- [ ] User is directed to a "verification pending" screen if a manual review is required
- [ ] User is directed to a "contact support" screen if KYC fails

**Comment by cajubelt** [comment]
redundant with m1
