### ISSUE TITLE
"Escrow Payment Received" activity is displayed instead of “Reward received” activity in recent activity of user B when user B signup & claims the invite amount with the same phone number invited by user A.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1193]
**Frequency:** 100%

**Repro on build version:** Android Alfajores Build V1.20.1, Testflight Alfajores Build V1.20.1
**Repro on devices:** OnePlus 7T (11.0), Redmi note 8 (10.0), Redmi note 8 (9.0), iPhone 12 (14.7.1), iPhone 6+ (12.5.4)

**Testing Account:** 
Invite Sender(User A): +12163547758/ [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B10)

Invited User (User B): +44 7883196637/[Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)

**Pre-condition:** 
1. User A must have invited user B with new phone number by sending valid amount in invite.
2. User B must have received an invite, installed the app.
**Repro Steps:**
1. User B launches the app.
2. User B completes the create account flow by confirming the phone number which is invited by user A.
3. User B is redirected to home screen after creating account.
4. Invited amount get deposited in User B's Account.
5. Tap on invite amount received activity & observe. 

**Current Behavior:** "Escrow Payment Received" activity is displayed instead of “Reward received” activity in recent activity of user B when user B signup & claims the invite amount.

**Expected Behavior:** "Reward received” activity must be displayed in recent activity of user B when user B signup & claims the invite amount.

**Investigation:** This issue is repro for inviting user by both cEUR & cUSD amounts and signing up with same invited phone number and claiming invite amount.
.
**Impact:** Bad user experience.

**Attachment:** 
[Received reward activity issue.mp4](https://drive.google.com/file/d/1LsI9IwVjPsnNa0zfTql3vKGmjKXbeQl-/view?usp=sharing)

**Comment by gnardini** [comment]
This is expected. The `Reward received` text should show up when receiving a reward for inviting others. For example:

- User A invites user B by sending $10.
- User B joins Valora and claims the $10. In the feed it says 'Escrow Payment Received'
- User A should receive a $5 reward and it the feed it should say 'Reward received'.

Please note that this isn't live yet! So user A would not receive $5 yet for doing this. Also, if you test this in the future when we enable it, please return the $5 to `0xbc7378A2ceC46426378fC3857C0B82FEc276a155`

**Comment by ValoraQA** [comment]
Hey @gnardini, thank you very much for the information.
