### ISSUE TITLE
[Query] “Time out” error message appears with “Go Back” Button on scanning QR code using use-contractkit from scan section of connected apps.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1196]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.20.1 & Test flight Build V1.20.1
**Repro on devices:** OnePlus 7T (11.0), Redmi note 8 (10.0), Redmi note 8 (9.0), iPhone 12 (14.7.1), iPhone 6+ (12.5.4)

**Pre-condition:**
1. User must have opened https://use-contractkit.vercel.app/ in Browser.
2. User must have opened valora wallet QR code by tapping on connect button.
3. User must have installed app and login into the app.
 
**Repro Steps:**
1.Launch the app.
2.Tap on “Settings” option from hamburger menu.
3. Tap on “Connected Apps” option from settings screen.
4. Tap on “Scan” button from Connected Apps screen.
5. Scan the valora wallet QR code opened in browser & observe.

**Current Behavior:** “Time out” error message appears with “Go Back” Button on scanning QR code using use-contractkit from scan section of connected apps.

**Expected Behavior:** “Time out” error message should not appear scanning QR code using use-contractkit from scan section of connected apps.

**Investigation:** This issue is repro when user scans QR code for https://ubeswap.org/ also.

**Impact:** Bad user impact.

**Attachment:** [Timeout error appears.mp4](https://drive.google.com/file/d/1FjTPQ4mc480YmyN9vSUor0hN4dABfsgP/view?usp=sharing)

**Comment by gnardini** [comment]
Thanks for testing the connecting feature!
https://use-contractkit.vercel.app/ is running an outdated version and is expected not to work atm.

There are two different ways of connecting. The UI/UX is the same but we should test both because projects can use one or the other:
- WalletConnect v1 can be tested from https://app.sushi.com
- WalletConnect v2 can be tested from  https://use-contractkit-git-alexbharley-fix-wc-2-alexbharley.vercel.app/

Thanks!

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D814](https://valora.testquality.com/project/12128/result/2601472/defect/9537).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D815](https://valora.testquality.com/project/12128/result/2601473/defect/9538).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Internal Release build and Latest iOS Test Flight build V:1.24.1 and observed time out error is faced for "https://mento-fi-q5d61619k-celotools.vercel.app/"

**Observation** : When we deny the permission and again scan the same QR code, then time out error appears and then permission screen appears again 

**Devices**: Google Pixel 2XL (11.0), iPhone 12(14.7.1)

**Attachment**: (mentotimeouterror1.mp4)[https://drive.google.com/file/d/1CccAtAkd1_RHmdfO9Q0jC_0CGjqkKJRF/view?usp=sharing] (mentotimeoiuterror2.mp4)[https://drive.google.com/file/d/1Ccjl63MKdjs0dN_9Bq2AGbiX197P_Cqj/view?usp=sharing]

Thanks..!!
