### ISSUE TITLE
“Not Supported In Your Region” text displayed with provider name  while adding funds with different countries using VPN from “Add Funds” screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1197]
**Frequency:** 100%
**Repro on build version:** Test flight Build V1.20.1 using & Android Internal build V1.20.1
**Repro on devices:**  iPhone 12 (14.7.1), Redmi Note 8 (10.0), iPhone 6+ (12.5.4), Redmi Note 8 (9.0), OnePlus 7t (11.0), Samsung Galaxy J5 Prime (8.0)
**Testing Account:** (680) 333 1978/[Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B11)
**Pre-condition:** Make sure that user should have connected VPN to United States country
**Repro Steps:**
1. Launch the application & login with the test account
2. Go to “Add Funds”  screen from “Add & Withdraw” option in Hmburger Menu
3. Select “Celo Dollar (cUSD)”  as digital currency & Pay with “Bank Account” & tap on “Next” button
4. Now user is on “Add Funds Amount” page
5. Enter valid amount & tap on “Next” button
6. Observed that
**Current Behavior:** User is able to see Simplex provider with “Paying with the bank account is not supported in your region” text displayed 
**Expected Behavior:** User should not able to see any non-supported provider name in list as per PR #1112
**Investigation:** Also we have observed same issue for Xanpool provider 
**Impact:** Bad user experience as user able to proceed even that provider is not supported in their region
**Attachment:** [NotSupportedTextStillDisplayedWithProviderName](https://drive.google.com/file/d/1KGHT0-kbxHFLeaq6jNThDrd6xGTkd-gr/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Hi @ValoraQA please try again. I need to make a deployment to our backend

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D193](https://valora.testquality.com/project/12128/result/2515702/defect/8349).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D194](https://valora.testquality.com/project/12128/result/2515704/defect/8350).

**Comment by ValoraQA** [comment]
> 
> 
> Hi @ValoraQA please try again. I need to make a deployment to our backend

Hey @tarikbellamine We have re-verified this issue using latest Test flight Build V1.20.2 using & Android Internal build V1.20.2 & observed that issue is still reproduced.

**Attachment:** [TextStillDisplayedon1.20.2](https://drive.google.com/file/d/1DNR6FjRGl8-Zqvd6iQadfSMnR2gXYc2l/view?usp=sharing)

**Verified On Devices:** Redmi Note 8 (9.0), iPhone SE (14.2)
Thanks.!!

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D195](https://valora.testquality.com/project/12128/result/2516297/defect/8351).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D202](https://valora.testquality.com/project/12128/result/2515712/defect/8358).

**Comment by tarikbellamine** [comment]
Hi @ValoraQA in your video it shows "Bank account is not supported in your region". This is correct because bank account is not a valid option within the United States.

**Comment by ValoraQA** [comment]
Hey @tarikbellamine according to PR 1174 we are supposed to see providers which only support for that region without any text about not supported or Not currently available. But currently we are able to see both texts for VPN change to. [Attachment](https://drive.google.com/file/d/1db83uPAKnRZ19yQWY8-GI8ZVLyNjBiM-/view?usp=sharing)
Also FYI we are referring [this doc](https://docs.google.com/spreadsheets/d/1xFwtiq7h4PNKUbgtYppA4tWB7JciqZfGpWzkvaBEtXg/edit#gid=0) for supported countries with different providers. And we are updating status according to this doc. So can you please let us know where we get idea that which providers are not supported for bank accounts  & which actually supported. So it will be easy for us to test 
Thanks..!!

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D224](https://valora.testquality.com/project/12128/result/2515685/defect/8394).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D225](https://valora.testquality.com/project/12128/result/2515687/defect/8395).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D230](https://valora.testquality.com/project/12128/result/2515726/defect/8400).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D231](https://valora.testquality.com/project/12128/result/2515728/defect/8401).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D233](https://valora.testquality.com/project/12128/result/2516264/defect/8403).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D234](https://valora.testquality.com/project/12128/result/2516280/defect/8404).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D235](https://valora.testquality.com/project/12128/result/2516296/defect/8405).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D237](https://valora.testquality.com/project/12128/result/2516328/defect/8407).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D238](https://valora.testquality.com/project/12128/result/2516344/defect/8408).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D239](https://valora.testquality.com/project/12128/result/2516360/defect/8409).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D246](https://valora.testquality.com/project/12128/result/2515685/defect/8416).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D247](https://valora.testquality.com/project/12128/result/2515687/defect/8417).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D286](https://valora.testquality.com/project/12128/result/2530827/defect/8498).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D303](https://valora.testquality.com/project/12128/result/2530820/defect/8523).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D314](https://valora.testquality.com/project/12128/result/2535244/defect/8543).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D477](https://valora.testquality.com/project/12128/result/2545776/defect/8812).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D479](https://valora.testquality.com/project/12128/result/2545777/defect/8814).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D481](https://valora.testquality.com/project/12128/result/2545778/defect/8816).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D483](https://valora.testquality.com/project/12128/result/2545779/defect/8818).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D485](https://valora.testquality.com/project/12128/result/2545780/defect/8820).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D490](https://valora.testquality.com/project/12128/result/2545783/defect/8825).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D492](https://valora.testquality.com/project/12128/result/2545784/defect/8827).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D496](https://valora.testquality.com/project/12128/result/2545785/defect/8831).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D615](https://valora.testquality.com/project/12128/result/2571356/defect/9220).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D616](https://valora.testquality.com/project/12128/result/2571357/defect/9221).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D617](https://valora.testquality.com/project/12128/result/2571358/defect/9222).
