### ISSUE TITLE
WalletConnect V2 Crashing Valora

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1215]
### Current behavior
After connecting to WalletConnect V2 on ~~https://use-contractkit-git-alexbharley-fix-wc-2-alexbharley.vercel.app/~~ https://use-contractkit-c-labs.vercel.app/ if a user closes the app and attempts to relaunch the app crashes and the user cannot open the app.

### Desired behavior

After connecting via WalletConnect V2 user can close and open the app without crashing.

### Steps to Reproduce

1. Using Mainnet navigate to https://use-contractkit-c-labs.vercel.app/ in a mobile browser
2. Tap Connect
2. Select Valora
3. When prompted with "Open this page in Valora" "select "Open"
4. Close Valora after homescreen load
5. Open Valora
6. Observe Crash

### Error Message

Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"5798":{},"5799":{},"5800":{},"5801":{},"5802":{},"5803":{},"5804":{},"5805":{},"5806":{},"5807":{},"5808":{},"5809":{},"5810":{},"5811":{},"5812":{},"5813":{},"5814":{},"5815":{},"5816":{},"5817":{},"5818":{},"5819":{},"5820":{},"5821":{},"5822":{},"5823":{},"5824":{},"5825":{},"5826":{},"5827":{},"5828":{},"5829":{},"5830":{},"5831":{},"5832":{},"5833":{},"5834":{},"5835":{},"5836":{},"5837":{},"5838":{},"5839":{},"5840":{},"5841":{},"5842":{},"5843":{},"5844":{},"5845":{},"5846":{},"5847":{},"...(truncated keys)...":451}

### Versions
v1.20.1 v1.20.2 iOS

**Comment by ValoraQA** [comment]
Hey @MuckT on navigation to this URL : https://use-contractkit-git-alexbharley-fix-wc-2-alexbharley.vercel.app/ "404 Not found" error is displayed 
Verified on browsers : Microsoft edge V:93.0.961.65 , Google Chrome V: 94.0.4606.71, Safari V:14.7.1
**Attachments:** [WalletconnectV2iPhone.png](https://drive.google.com/file/d/1TXn_DbW_YU7gxsy8tQALt7xFHsgLG0F1/view?usp=sharing) [WallectconnectV2android.mp4](https://drive.google.com/file/d/1Gv5K4klhyqrjd8gfpgMf0djp03ytDHMC/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D220](https://valora.testquality.com/project/12128/result/2516558/defect/8385).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D220](https://valora.testquality.com/project/12128/result/2516558/defect/8386).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D220](https://valora.testquality.com/project/12128/result/2516558/defect/8387).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D220](https://valora.testquality.com/project/12128/result/2516558/defect/8388).

**Comment by MuckT** [comment]
@ValoraQA https://use-contractkit-c-labs.vercel.app/ is the new link to the contract kit

**Comment by MuckT** [comment]
Downgrading in priority until this issue is confirmed to reproduce.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using [new link](https://use-contractkit-c-labs.vercel.app/) on Test flight build V1.20.2 and observed that "Time out" error appears with "Go Back" button on scanning the QR code.

**Devices:** iPhone 12 (15.0)
**Attachment:** [Timeout error issue.mp4](https://drive.google.com/file/d/13Qmvxjrn704Q9oGEL3M1ULJQAUD4-_Aj/view?usp=sharing)
