### ISSUE TITLE
App Store / Play Store account migration

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1237]
# Overview

We're still using cLabs owned accounts for Valora on the App Store and Play Store.
We want to move them to a Valora owned account.

The new accounts have been created. The work remaining is around transferring the apps (Valora and Alfajores) minimizing the interruption for our users / internal users and engineers.

We don't expect any interruption to Valora users or new users downloading the app.

# Transfer conditions

There are a number of conditions for [transferring apps on the App Store](https://help.apple.com/app-store-connect/#/devaf27784ff). 
Highlights: the app must not be in review and TestFlight needs to be disabled.

And [similar for the Play Store](https://support.google.com/googleplay/android-developer/answer/6230247?hl=en).
Highlight: transfer requests are processed within 2 business days.

# Plan

Given the constraints, the current plan is to migrate the Alfajores app first and learn about any issue that may arise. And soon after transfer the Valora app.

This would be done directly after release 1.20 is made available publicly.
Expected to happen in the week between Oct 4th and Friday 8th.

- [x] Create new App Store and Play Store accounts
- [x] Review transfer conditions
- [x] Invite internal users and engineers to the new accounts
- [ ] Transfer iOS Alfajores app
- [x] Transfer Android Alfajores app
- [ ] Transfer iOS Valora app
- [x] Transfer Android Valora app
- [ ] Check/Update iOS signing secrets for our CI/CD pipeline
- [ ] Check/Update Android signing secrets for our CI/CD pipeline 
- [x] Check/update push notifications keys (FCM and CleverTap)
- [ ] Check/update TestFlight users
- [x] Check/update Android testing track users
- [ ] Check iOS app is listed under Valora, Inc.
- [x] Check Android app is listed under Valora, Inc.
- [ ] Check website links to Valora on the App Store / Play Store are working as expected

**Comment by kathaypacific** [comment]
Need to check if iCloud backup implemented with the cLabs account will tie us there forever. If so, there is new urgency for this task. @jeanregisser - @kathaypacific will create a spike ticket
