### ISSUE TITLE
Android: Create infrastructure config for provisioning Mac Stadium machines dynamically

### ISSUE THREAD

**Issue by istx25** [valora-inc/wallet#1259]
Currently the Mac Stadium machines are provisioned manually which is super fragile and there's not much insight into how one machine was configured to the next so there could be variance. To improve this, there will be a Shell script for iOS workers and one for Android workers. These scripts will be responsible for setting up a new host from beginning to end.

ENG:
- Try creating a runner to get the right process/set of commands down

AC:
- [ ] script in <https://github.com/valora-inc/infrastructure> that an engineer can run after creating a Macstadium machine that will configure all the dependencies for an Android GitHub runner.

**Comment by noisypigeon** [comment]
Related to #1431.

**Comment by noisypigeon** [comment]
#1437

**Comment by noisypigeon** [comment]
See #1440 and #1439.
