### ISSUE TITLE
Tapping on “Allow” button does nothing in Moola prompt in valora app when user tries wallet connect using url https://app.moola.market/ by mobile browser for unverified phone number accounts. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1278]
**Frequency:** 100%

**Repro on build version:** Testflight Build V1.21.0, 1.20.3 , Android Internal Build V1.20.3
**Repro on devices:** iPhone 12 (14.7.1) , iPhone 6+ (12.5.4), Redmi Note 8 (10.0), Redmi Note (9.0), Samsung Galaxy M40 (10.0)
**Browser version:** Edge V93.0, Safari V14.7.1, Safari V12.5.4, Chrome V94.0

**Does Not Repro on build version:** Test flight Build V1.21.0, 1.20.3, Android Internal Build V1.20.3
**Does Not Repro on devices:** iPhone 6+(12.5.4), iPhone 12 (14.7.1), Redmi note 8 (10.0)

**Pre-condition:** 
1. User must have installed the app and complete the onboarding flow by skipping phone number verification.

**Repro Steps:**
1. Launch https://app.moola.market/#/ in web browser.
2. Tap on “Connect Wallet” button.
3. Tap on “Valora” option.
4. Tap on “Allow” button from Moola prompt after getting redirected to valora app & observe the bug.

**Current Behavior:** Tapping on “Allow” button does nothing in Moola prompt in valora app when user tries wallet connect using Moola market url.

**Expected Behavior:** Tapping on “Allow” button Moola prompt must get closed & Moola dapp must get connected  in valora app when user tries wallet connect using Moola market url.

**Investigation:** The above issue is not reproducible when user tries to connect Moola dapp for valora accounts where Phone number is verified.

**Impact:** Bad user experience as tapping on “Allow” button does nothing.

**Attachment:** [Allow Button not working For Moola market.mp4](https://drive.google.com/file/d/1lWlotYgEDKMb_p74cgAxj9XPVRU5ICGr/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA please retest on v1.20.4.

**Comment by ValoraQA** [comment]
Hey @MuckT can you please look into it.

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Test flight Build V1.21.0, Android Internal Build V1.21.0 for Ubeswap dapp & Observed that ,Tapping on "Allow" button does nothing for https://app.ubeswap.org/#/swap, when user tries wallet connect by mobile browser for unverified account.  

**Devices:** iPhone 12(15.0), Redmi Note 8(9.0), Redmi Note 8(10.0)
**Attachment:** [1278 Ubeswap.mp4](https://drive.google.com/file/d/1PK92nLaWm_6Zb0uN9bgrCP_zHZ5O1pRY/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D421](https://valora.testquality.com/project/12128/result/2545257/defect/8721).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D422](https://valora.testquality.com/project/12128/result/2545261/defect/8722).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D428](https://valora.testquality.com/project/12128/result/2545258/defect/8729).

**Comment by ValoraQA** [comment]
> 
> 
> The error `dappkit/DappKitAccountScreen :: No phone number set up for this wallet` is not surfaced to the user, but is thrown from the app. Perhaps we should throw an error banner to the user when they attempt to use dapps without an attached phone number.

Hey, @tom we have tried for both "Moola" &"Ubeswap" without confirming the phone number. We have observed that nothing happens when the user taps on the "Allow" button on the permission prompt to connect Valora with a wallet.
FYI: We are able to proceed by tapping on Allow button by confirming the phone number

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D432](https://valora.testquality.com/project/12128/result/2545260/defect/8733).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D437](https://valora.testquality.com/project/12128/result/2540758/defect/8741).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D441](https://valora.testquality.com/project/12128/result/2545263/defect/8746).

**Comment by MuckT** [comment]
@ValoraQA please retest with a confirmed phone number.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue by confirming the phone number & observed that issue is fixed now.
**Verified On Devices:** Redmi Note 8 (9.0), One Plus 7T (11.0)
