### ISSUE TITLE
Wallet is not seen connected on desktop browser even after user scans the QR code and discards the pop up , while app is seen in connected apps page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1279]
**Frequency:** 100%
**Browser Info:** Chrome V94.0
**Repro on build version:** Test flight Build V1.21.0 , Android Internal Build V1.20.3
**Repro on devices:** iPhone 6+ (12.5.4), One plus 7T (11.0)

**Pre-condition:** 
1. User must have installed the valora app 
2. User must be on connected apps page
3. User must have browser app.sushi.com/swap

**Repro Steps:**
1. Click on Scan from RHS top corner
2. Scanner will open
3. On website click on connect to wallet
4. From the list select wallet connect
5. QR code will be generated 
6. Scan QR code and discard the QR code by clicking on cross button
7. Observe the connected apps page 
8. Observe the website, wallet should be seen connected 

**Current Behavior:** App is seen connected in valora, whereas on website it shows "connect to a wallet"
**Expected Behavior:**  App should be see connected in valora and account address should be seen on website
**Impact:** Bad user experience.
**Attachment:** 
[Browser Popup issue.mp4](https://drive.google.com/file/d/1_TotOtPQb20PP9J-I2en_pXkqPNfDauI/view?usp=sharing)
[Sushi app connected.jpg](https://drive.google.com/file/d/1-6N-hZR1myIFY7uHCGemppislWJpP4Ky/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA please retest on v1.20.4.
