### ISSUE TITLE
Error message displayed when a user tries to scan QR code shown on  “https://app.ubeswap.org/” web page on “Scan” page from "Connected Apps" section

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1285]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.20.4, Test Flight Build V1.20.4
**Repro on devices:** Redmi Note 8 (10.0), iPhone 6+ (12.5.4), iPhone 12(14.7.1),Redmi Note 8 (9),Oneplus 7t(11)
**Testing Account:**(680) 333 1978/[Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B11)
**Pre-condition:** Make sure that user should have restored account without verifying phone number
**Repro Steps:**
1. Launch the “https://app.ubeswap.org/” URL in desktop browser & tap on the “Connect to Wallet” button
2. Now user should be on the “Select Wallet” page with different options
3. Select the “Valora” option
4. Now user should be able to see the “QR code” screen
5. Now go to the “Scan” section of the “Connected Apps” option from Settings
6. Try to scan QR code displayed on desktop & wait for sometime
**Current Behavior:** “QR Code read failed. Reason” Wallet address invalid” error in the red banner displayed & user not able to connect wallet with Valora
**Expected Behavior:** QR code should be scan & user should able to connect wallet successfully
**Investigation:**
1. Also we have observed that no “Success” blue banner message is displayed on the home screen when the user connects the wallet from the mWeb browser successfully. 
2. Also we have observed same issue for  https://use-contractkit-c-labs.vercel.app/ URL
**Impact:** User gets blocked to connect wallet with Valora by scanning QR code
**Attachment:** [ErrorForScanningQRCode](https://drive.google.com/file/d/1di9uNvAkOwPvkuMYFIvYuFMm5zw1su99/view?usp=sharing)

**Comment by gnardini** [comment]
This is expected because we disabled WalletConnect v2. I agree the error text is not very clear though, but it's not unexpected.
