### ISSUE TITLE
Change rounding rules and number of displayed digits

### ISSUE THREAD

**Issue by ole-nov** [valora-inc/wallet#1307]
More context is on slack here: https://valora-app.slack.com/archives/C01CN6AUHGX/p1634918172001300
Or discord here: https://discord.com/channels/886972503560433675/887347605229695037/898005207517114428

Problem:

Because  we round down the price per cUSD/CELO that we show to the user,  amount * estimated exchange rate does not equal to total of the transaction. The difference is tiny on small numbers, but when users are exchanging/buying ~$5,000, the differnece is quite noticeable and looks like hidden fee to users.

ENG:
* See [this](https://github.com/valora-inc/wallet/blob/bfff5221c43214cbe495a0fc228ab2ec184e73cd/packages/mobile/src/components/TokenDisplay.tsx#L53), which is a centralized place to add rounding code
* This work does not include fees!  We will handle that case separately.

## Solution (AC)

Using terminology from [Wikipedia](https://en.wikipedia.org/wiki/Significant_figures)

### Design and rounding
**Fiat currencies.** 
- [ ] When the number is displayed in fiat currency in the activity feed or total balance, we show 2 decimals, rounded down. For example, $100.346 should appear as $100.34.

**Crypto currencies.**
- [ ] Stable and non-stable coins have the same rules. We should show 6 significant digits.
Examples:
CELO 12.334566778889 should be shown as cETH 12.3454
CELO 0.03452479348797 should be shown as 0.03452

Exceptions to the above rule:
- [ ] If an integer of the number has 5 digits or more, we should still show two decimals. Example: 12,345.56
- [ ] If an integer is 0 and 6 decimals are zeros, we should only show 2 significant digits. Example 0.00000045

Designs: https://www.figma.com/file/RGM6cZFbfEr1NuLZXnKhKl/Rounding-Guidelines?node-id=0%3A1

**Comment by silasbw** [comment]
To make sure I understand, here are some examples for crypto:

`1.00000000000045` -> `1.00000000000045` (if first 6 decimals are zeros, we should only show 2 significant digits. Example 0.00000045)
`12345678901234567.001` -> `12345678901234567.00` (If an integer of the number has 5 digits or more, we should still show two decimals. Example: 12,345.56)
`12345.123` ->`12345.1` (We should show 6 significant digits.)

Are these correct?

**Comment by aleksey-nov** [comment]
1. Hm. This is probably not what we want to do. In my opinion, we should display `1.00000000000045` as `1.00`.

2. `12345678901234567.001` -> `12345678901234567.00`. Yes, that's correct

3. No, because an exception rule says always to show at least two decimals. So `12345.123` should be displayed as `12345.12`

**Comment by jeanregisser** [comment]
Couple of feedback:
- When we display conversion rates (for instance "Celo Dollars @ €1.16"), the current proposal doesn't fully address the initial concern. If it's displayed rounded down with no indication, it won't add up. I don't yet have a definitive solution to this though. Happy to brainstorm though.
- I think we should detail when we prefix values with "~" to show it's an approximation

**Comment by aleksey-nov** [comment]
@jeanregisser added this another issue to tackle this problem: https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/1607

**Comment by silasbw** [comment]
Can we consider how we'll handle this too?  https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/1653

**Comment by MuckT** [comment]
Related QA query: https://github.com/valora-inc/wallet/issues/1802

**Comment by kathaypacific** [comment]
We accepted at planning that this issue probably needs some more clarification around the rounding rules for various scenarios, but it has been dragging on for a long time. So whoever picks this up will also need to do a little product/decision making work :)

**Comment by nityarao** [comment]
Just updated this with designs as we discussed this AM @kathaypacific
