### ISSUE TITLE
Update wallet default limit

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1319]
### What would you like?

Update wallet default transaction limit, follow up to valora-inc/wallet#1315, 

### Why is this needed?

In case firebase is disabled, the default should be higher.

**Comment by kathaypacific** [comment]
Closing in backlog spring clean May 2022

**Comment by MuckT** [comment]
@kathaypacific @ellenwoconnor should we reopen this and update the default daily limit?
