### ISSUE TITLE
After Send Flow while transaction is pending an 'Your balance is too low' banner briefly shows incorrectly.

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#1341]
### Current behavior

After clicking 'Send' in the Send/Request flow while the transaction is pending a 'Your balance is too low' alert briefly shows which seems very confusing. Despite this alert, the transaction processes fine and shows so in the Home view. 

It seems to happen when you try to send an amount > 50% of the total in your current wallet.  

I think the UI state is updating the wallets current funds before the transaction is actually processed which is triggering the alert that the user doesn't have enough funds to make the transaction.

**In this scenario i had $1.90 cUSD and was sending $1 to my Mom**
![IMG_9944](https://user-images.githubusercontent.com/8432644/139501396-352907e7-bd75-40f3-bdc5-66ea45ef2454.PNG)

### Desired behavior

The alert should not show when for this scenario.
### Steps to Reproduce

Send over 50% of the funds in your wallet to somebody and see the alert flash when you are redirected to the home view
### Versions

iPhone 12 Pro

**Comment by ValoraQA** [comment]
Hey @jh2oman We have verfied this issue using Android internal & Test Flight build V1.21.0 7 observed that we are able to repro this issue.
**Verified On Devices:**  One Plus 7T (11.0), iPhone 12 (15), iPhone 6+ (12.4.5), Redmi Note 8 (9.0)
**Attachment:** [ErrorForValidAmount](https://drive.google.com/file/d/17k99UrcWI9IBWLAQRqllsjAHYYIuIlM1/view?usp=sharing)
