### ISSUE TITLE
 [Query] Carousel and Image Overlaps on first walkthrough screen when font size is changed to Accessibility Maximum for Deutsch & Portugues languages.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1343]
**Frequency:** 100%

**Repro on build version:** Test flight Build V1.21.0
**Repro on devices:** iPhone 12 (15.0), iPhone 6+(12.5.4)

**Pre-condition:**
1. User must have changed the font size from the settings to accessibility maximum.
2. User must have installed the build and is on 1st Walkthrough Screen.

**Repro Steps:**
1. Tap on “English” option in top right corner
2. Select “Portugues” option from select language page.
3. User is redirected to 1st Walkthrough Screen & Observe the bug.
4. Tap on “Portugues” option in top right corner.
5. Select “Deutsch” option from select language page.
6. User is redirected to 1st Walkthrough Screen & Observe the bug.

**Current Behavior:** Carousel and Image Overlaps on first walkthrough screen when font size is changed to Accessibility Maximum for Deutsch & Portugues languages.

**Expected Behavior:** Carousel and Image must not overlap on first walkthrough screen when font size is changed to Accessibility Maximum for Deutsch & Portugues languages.
**Investigation:** This issue is not reproducible for English & Espanol Language

**Impact:** Bad user Experience.

**Attachment:** [New Font size issue.mp4](https://drive.google.com/file/d/1WaLbzuUxmexd_179SMkkeGIIwBdK02Mi/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D429](https://valora.testquality.com/project/12128/result/2545881/defect/8730).

**Comment by MuckT** [comment]
@ValoraQA this is expected as the content is in a scroll view. The other option is to put it all in a scroll view; however, this would push the next button and carousel dots below out of view on large texts, which is less desirable.
