### ISSUE TITLE
 [13 iOS Specific] Blank screen displayed when user browse “https://app.sushi.com/swap” in Safari/Edge browser

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1351]
**Frequency:** 100
**Repro on Browser:** Microsoft Edge (V 95.1020.40), Safari (V 13.6.1)
**Repro on devices:** iPhone SE (13.6.1), iPhone XR (13.2.3)
**Does Not Repro on devices:** iPhone SE (14.2), Redmi Note 8 (10.0), One Plus 7T (11.0), iPhone 12 (15)
**Repro Steps:**
1. Launch the "https://app.sushi.com/swap" URL in the Safari mWeb browser 
2. Wait for some time & observe that 
**Current Behavior:** Blank screen displayed on “app.sushi.com/swap” page
**Expected Behavior:** Page should load completely & user should able to proceed to connect wallet with Valora
**Investigation:** Also we have observed the same issue for the Microsoft Edge mWeb browser 
**Impact:** User gets blocked to connect to “app.sushi.com/swap” on specific OS’s
**Attachment:** [BlankScreenForSushi.mp4](https://drive.google.com/file/d/1GPpCQ2RB_PFpAsvFeYpH_JCJDo7S4WqZ/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D444](https://valora.testquality.com/project/12128/result/2540319/defect/8749).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D445](https://valora.testquality.com/project/12128/result/2540320/defect/8750).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D446](https://valora.testquality.com/project/12128/result/2545181/defect/8751).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D447](https://valora.testquality.com/project/12128/result/2545185/defect/8752).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D619](https://valora.testquality.com/project/12128/result/2571425/defect/9224).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D620](https://valora.testquality.com/project/12128/result/2571426/defect/9225).

**Comment by MuckT** [comment]
Raised a bug with Sushi Team and downgraded priority.

**Comment by ValoraQA** [comment]
Thanks fro confirmation:)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D717](https://valora.testquality.com/project/12128/result/2586980/defect/9378).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D796](https://valora.testquality.com/project/12128/result/2594545/defect/9473).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Test Flight Release Build V1.29.2 & observed the following:

"Blank screen is displayed" when user redirects to Poof and Talent Protocol Dapp from Dapp page.

**Devices:** iPhone XS Max(13.5.1), iPhone 7(13.3)

**Attachment:**
[PoofDapp.mp4](https://drive.google.com/file/d/1BVbxvryFpjRkuCLkp787KWSrcyyoRUzB/view?usp=sharing)
[Talent Protocol.mp4](https://drive.google.com/file/d/1AEyncZHY7GAyk7qwjdVrOmgTVitWY-wC/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Test Flight Release Build V1.30.1 & observed the following:

**Observation:**
- "Blank screen is displayed" when user redirects to Bittrex provider from cUSD and Cryptocurrency exchanges from Add & Withdraw page.

**Devices:** iPhone XS Max(13.5.1), iPhone 7(13.3)

**Attachment:**
[Bittrex.mp4](https://drive.google.com/file/d/1Iu8Dem1rhfWZl5tMT9mVKw1L-nKh3nMN/view?usp=sharing)

Thanks..!!
