### ISSUE TITLE
“abc this is a test” push notification displayed when user repeatedly switch between “Settings” & “Help” options after redirecting back from “FAQ” page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1353]
**Frequency:** 100%
**Repro on build version:** Test Flight Build v1.21.0
**Does Not Repro on build version:**  Android Internal Build V1.21.0
**Repro on devices:** iPhone SE (13.6.1), iPhone XR (13.2.3), iPhone 12 (15), iPhone SE (14.2), iPhone 6+ (12.4.5)
**Does Not Repro on devices:** Redmi Note 8 (9.0), One Plus 7t (11.0)
**Testing Account:**  (515) 808 5659 /[Recovery Phrase](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B71)
**Pre-condition:** Make sure that phone number should present in Hamburger Menu
**Repro Steps:**
1. Launch the application & log in with the test account
2. Tap on “Hamburger Menu” & redirect to the “support.valoraapp.com” page by selecting the “Frequently Asked Questions” option
3. Redirect back to Valora & select the “Settings” option from the Hamburger menu
4. Repeat step 2 & 3 for one more time & observe that 
**Current Behavior:** “abc this is a test” push notification  displayed when user taps on “Settings” option after redirecting back from the “Help” page
**Expected Behavior:** User should able to see “Settings” page as it is without any “abc this is a test”  push notification
**Investigation:** 
1. Also, we have observed the same issue when the user is on the prompt to accept wallet connect permission.
2. Also, we have observed the same issue while connecting the wallet by scanning QR code from a desktop browser
3. Also, we have observed the same popup randomly after creating an account throughout an application
**Impact:** Bad user experience
**Attachment:** [abcTestPopupRandomlyShows](https://drive.google.com/file/d/1oC1TZUgSu-C8huITm7NTifbAeKP2ONgD/view?usp=sharing)

**Comment by MuckT** [comment]
@jeanregisser do you have any context around this?

**Comment by jeanregisser** [comment]
Yes this was for testing CleverTap. I've stopped this. You shouldn't see it anymore.

**Comment by ValoraQA** [comment]
Hey @jeanregisser We have verified this issue using Test Flight Build V1.21.0 & observed that issue is fixed now.
**Verified On Devices:** iPhone XR (14.6), iPhone 6+ (12.4.5)
