### ISSUE TITLE
[M1] Follow up with Lisa (support) to figure out how will user understand why their kyc fails / how will they retry Persona

### ISSUE THREAD

**Issue by lisaqyli** [valora-inc/wallet#1378]
Spike into how we deal with kyc failures

How will the Persona error code reach CS? How will they interpret it? What kinds of errors should be handled in the UI rather than manually? Does Lisa know how to look up the error codes?

AC:
- clear understanding with support about plan for kyc failure handling
- ^this is documented in notion
- the "number of days" placeholder in the "pending" screen in the Persona KYC flow is filled in with our actual estimate for how long manual review will take
- What happens if the Persona status is `failed` (the number of allowed verification attempts has been exceeded and the individual can no longer continue)  https://docs.withpersona.com/docs/models-lifecycle

**Comment by cajubelt** [comment]
The logic for when manual review is needed is given by our persona workflow: https://app.withpersona.com/dashboard/workflows

**Comment by cajubelt** [comment]
from Lisa: in the app we can promise 4-5 biz days for manual review in KYC, in reality we will try for <1 biz day

**Comment by cajubelt** [comment]
looks like we no longer have in-app copy for the number of days for review, so I'm going to close this out
