### ISSUE TITLE
“Payment Sent” notification displayed instead of “CELO Withdrawal” on the feed from Home screen when user withdraw CELO

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#138]
**Frequency:** 100%
**Repro on build version:** Play store Build V 1.11.1 , App store Build V1.11.1
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone SE (13.6.1)
**Does not repro devices**
**Testing Account:**  (515) 808 5659 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B69)
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Withdraw CELO to user B.
3. Now open user B’s account & go to home screen.
4. Now users are able to see Recent activities.
5. Observed that,
**Current Behavior:**  “Payment Sent” notification displayed after withdrawing CELO.
**Expected Behavior:**  “CELO Withdrawal” notification should display on feed as a user redirected to the same screen after tapping on that activity.
**Impact:** Bad user experience.
**Investigation:** Also it is observed that “Payment Received” notification displayed on feed instead of “Deposit Received” when a user buys CELO.
**Attachment:**  [RecentFeedShouldSameAsScreenName.mp4](https://drive.google.com/file/d/1VgeUWZd8kw8vu3JHLiDkSys-knPwqEl8/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi I have verified this issue using latest Playstore build V1.15.2, Appstore build V1.15.2 & observed that issue is still reproduced.
**Verified On Devices:** iPhone SE 1st Generation (14.6), Redmi Note 8 (10.0)
