### ISSUE TITLE
[Query]  “Raise Account Send Limit” option is not displayed when user navigates to “Help” screen from Hamburger menu.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1401]
**Frequency:** 100%

**Repro on build version:** App store build V1.21.0, Test flight Build V1.21.0, V1.20.4, Android Internal Build V1.21.0, Android Play store Build V1.20.4 
**Repro on devices:** One plus 7T(11.0), Redmi Note 8 (9.0), iPhone 12 (15), Redmi Note 8 (10.0), iPhone XR (14.6)

**Pre-condition:** 
1. User must have installed the app and completed onboarding flow.
2. User must be on home screen.

**Repro Steps:**
1. Tap & open Hamburger menu from Home screen.
2. Tap on “Help” option from hamburger menu & Observe 

**Current Behavior:** “Raise Account Send Limit” option is not displayed when user navigates to “Help” screen from Hamburger menu.

**Expected Behavior:**“Raise Account Send Limit” option must be displayed when user navigates to “Help” screen from Hamburger menu.

**Impact:** Bad user experience. 

**Attachment:** [Raise account send limit issue.mp4](https://drive.google.com/file/d/1AbDtXeXZE_cFRGGW-O-A9UE88Gjm4wtJ/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D510](https://valora.testquality.com/project/12128/result/2552363/defect/8849).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D511](https://valora.testquality.com/project/12128/result/2552362/defect/8850).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D514](https://valora.testquality.com/project/12128/result/2554905/defect/8861).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D515](https://valora.testquality.com/project/12128/result/2554904/defect/8862).

**Comment by MuckT** [comment]
The daily transaction limit in the help menu has been removed by https://github.com/valora-inc/wallet/pull/1315.

**Comment by ValoraQA** [comment]
Thankx for confirmation:)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D651](https://valora.testquality.com/project/12128/result/2574071/defect/9272).
