### ISSUE TITLE
“Failure Sending Payment” red error banner displayed & user gets blocked to perform transaction with user B from “Sending” screen 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1438]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.22.0 & Test Flight build V1.22.0
**Does Not Repro on build version:** Play store build V1.21.0 & App store build V1.21.0
**Repro on devices:**   iPhone 12(15), Redmi Note 8 (9.0), One Plus 7T(11.0), Redmi Note 8 (10.0), iPhone XR (14.6), iPhone SE (14.8), iPhone 6+ (12.4.5)
**Testing Account:** (680) 333 1978/[Recovery Phrase](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B11)
**Pre-condition:** Make sure that user should have some cUSD & cEUR balance in account
**Repro Steps:**
1. Launch the application & log in with the test account
2. Tap on the “Send” button & select any valid contact to send an amount
3. Select cUSD amount from “Select Balance” & tap on the “Review” button
4. Now user should be on the “Sending” page
5. Tap on the “Send” button & enter a PIN 
6. Observe the bug
**Current Behavior:** “Failure Sending Payment” red error banner displayed & user gets blacked to send amount to user B 
**Expected Behavior:** User able to proceed & should able to  perform transaction successfully without any blockages
**Investigation:** 1. We have observed the same issue if we try to send money by scanning QR code
2. Also we have faced the same issue while sending the cEUR amount to user B
**Impact:** User gets blocked to make a transaction
**Attachment:** [BlockedToSendPayment.mp4](https://drive.google.com/file/d/1fEN04SHUykZis5mEOACik1juuwTUsWtP/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D544](https://valora.testquality.com/project/12128/result/2566389/defect/9027).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D545](https://valora.testquality.com/project/12128/result/2566390/defect/9028).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D547](https://valora.testquality.com/project/12128/result/2566391/defect/9030).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D548](https://valora.testquality.com/project/12128/result/2566392/defect/9031).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D550](https://valora.testquality.com/project/12128/result/2566393/defect/9033).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D551](https://valora.testquality.com/project/12128/result/2566394/defect/9034).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D553](https://valora.testquality.com/project/12128/result/2566395/defect/9036).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D556](https://valora.testquality.com/project/12128/result/2566403/defect/9039).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D557](https://valora.testquality.com/project/12128/result/2566396/defect/9040).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D558](https://valora.testquality.com/project/12128/result/2566406/defect/9041).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D559](https://valora.testquality.com/project/12128/result/2566397/defect/9042).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D560](https://valora.testquality.com/project/12128/result/2566398/defect/9043).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D561](https://valora.testquality.com/project/12128/result/2566407/defect/9044).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D562](https://valora.testquality.com/project/12128/result/2566399/defect/9045).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D563](https://valora.testquality.com/project/12128/result/2566400/defect/9046).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D564](https://valora.testquality.com/project/12128/result/2566401/defect/9047).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D565](https://valora.testquality.com/project/12128/result/2566402/defect/9048).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D566](https://valora.testquality.com/project/12128/result/2566410/defect/9049).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D567](https://valora.testquality.com/project/12128/result/2566411/defect/9050).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D568](https://valora.testquality.com/project/12128/result/2566412/defect/9051).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D569](https://valora.testquality.com/project/12128/result/2566413/defect/9052).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D570](https://valora.testquality.com/project/12128/result/2566415/defect/9053).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D571](https://valora.testquality.com/project/12128/result/2566416/defect/9054).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D572](https://valora.testquality.com/project/12128/result/2566414/defect/9055).

**Comment by jeanregisser** [comment]
This is now fixed.
`blockchain-api` needed to be deployed to the mainnet project.
See [slack thread with all details](https://valora-app.slack.com/archives/C02ATNHSVL0/p1636977047172600).

**Comment by ValoraQA** [comment]
Hey @jeanregisser We have re-verified this issue using Android internal build V1.22.0 & Test Flight build V1.22.0 & observed that issue is fixed now.
**Verified On Devices:**  iPhone 12(15), Redmi Note 8 (9.0), One Plus 7T(11.0), Redmi Note 8 (10.0), iPhone SE (13.6.1), iPhone 6+ (12.4.5)
