### ISSUE TITLE
[M2] Plaid Link Component Setup

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#1446]
Basic Flow:
User wants to link an account, call IHL to get a token, use the token to startup the Plaid Link Component, handle onSuccess hook and call IHL again to store the access token.

AC:
* Use the token to intialize the [Plaid Link Component ](https://github.com/plaid/react-native-plaid-link-sdk)
* Handle the [onSuccess](https://plaid.com/docs/link/react-native/#onsuccess
) hook from the Link Component
* Navigate the user to the 'Bank account linked' screen
* [Configure Plaid ](https://plaid.com/docs/link/customization/#account-select) to only allow one account to be linked

Not in Scope:
* call the POST /plaid/access-token/exchange IHL endpoint.
* Call POST /plaid/link-tocken/create endpoing on IHL
* handling the onExit or onEvent hooks
* Creating a counter-party with finclusive using the POST /account/counter-party endpoint

**Comment by cajubelt** [comment]
idea for breakdown:
- issue for get link token from IHL
- issue for 
```
Use the token to intialize the Plaid Link Component
Handle the onSuccess hook from the Link Component (console log)
```
- issue for actually calling the POST /plaid/access-token/exchange IHL endpoint
