### ISSUE TITLE
[M2] Handle Plaid Error Webhooks

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#1460]

**Comment by jh2oman** [comment]
Plaid has a variety of [Error Webhooks](https://plaid.com/docs/api/webhooks/) that we should listen to and update a users state. Specifically it is recommended that we listen for Item error: ITEM_LOGIN_REQUIRED and Item error: PENDING_EXPIRATION. 

AC:
* IHL listens for webhooks from Plaid for the above two errors
* If either of those two errors are detected, update the user state in Firebase accordingly.
* If the user state is in pending or login required, launch Plaid Link in update mode to have them fix the account.

Open Question:
* Where should the messaging go for this? How should the user be prompted to fix their account? (talk to Nitya)

**Comment by jh2oman** [comment]
It looks like we probably don't need this, since the information we get from Plaid is immutable (account number) as opposed to mutable things (like balance). For the time being we can ignore these

**Comment by aleksey-nov** [comment]
decided to close it because it is not needed
