### ISSUE TITLE
Host token logos on our own infra

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1500]
The logos we are currently using point to Ubeswap's GitHub repository, which could break if they change the format of the repo or decide to delete them.

To make this more robust, we can download the images and re-upload them to our own infra so we have control over the logos and can make sure that they never go down.

**Comment by MuckT** [comment]
@Gonza just a thought we could download and re upload to our own infrastructure. We can keep them up to date in our repo with a script on a cron job.

```
// Pseudo Code
FOR EACH token icon in Ubeswap's Github
  IF Error
    Don't update the icon in our infrastructure
  Else IF hash of the image from Ubeswap does not match the hash of our image OR we don't have that image
    Update or save a new icon
  Else
    Don't update the icon in our infrastructure.
```

**Comment by ellenwoconnor** [comment]
@dievazqu @gnardini is this issue still active? it looks like there are some older tickets that are linked and are now closed

**Comment by gnardini** [comment]
We never did this and it would be nice if we did. It's not a P0 but still something to track I think
