### ISSUE TITLE
Add 'dApp Directory' section to the admin dashboard

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1505]
In the Admin Dashboard: https://github.com/valora-inc/admin-dashboard/tree/master/src/home
we need to add a 'dApp Directory' section. This section will allow product people to remotely manage the content of the DeFi Directory section of the app. See the epic for more info on the future.

This section in the admin dashboard should allow creating new categories, creating new dApps and editing both categories and dApps. In this first issue we will only list the categories and dApps and we'll allow creating and updating in future ones.

For **categories**, the fields are:
- Name: Must be translatable to all of our supported languages. Check the notifications section for an example.
- Background Color: RGB string of the background color of the section title.
- Font color: RGB string of the color of the font.

For **dApps**, the fields are:
- Name: The name of the dApp. Translation is not necessary.
- Description: The description of the dApp. Must be translatable.
- Logo: The logo of the dApp, just a string. In the future we might want to allow uploading a picture and store it in Firebase Storage.
- Category Id: The id of the category.
- Link: A link to the dApp.

An endpoint will be created on the blockchain-api for us to read the existing categories and dApps on #1507.

AC:
- Users can see all existing dApps and categories in the admin dashboard.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
