### ISSUE TITLE
Add 'DeFi Explorer' screen to the app

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1506]
We want to add a new screen to the app from which users can see the existing dApps distributed by categories and interact with them. See the epic for more info on the future.

Here are the mockups: https://www.figma.com/file/zdK8XvxNXvTjxnM5V33pHw/dAPP-Directory?node-id=831%3A19659

Some notes and considerations:
- There must be an item in the side menu that opens this screen. Don't worry about the in-app notification since that's added dynamically from the admin dashboard.
- The information about the dApps and categories must be fetched from the endpoint that will be created on #1507. Check that issue for the fields that will be returned.
- The copy and icons doesn't look like it's finalized, so check with design/product before implementing, especially the  side menu icon, the info modal and the confirmation bottom sheet.
- For the bottom sheet, there's an example on the component `TokenBottomSheet` but it's not very extendable. You have three options: 
  - Create a new component and copy the necessary stuff. It's not a lot of code anyways.
  - Create a generic `BottomSheet` component that is shared by both.
  - Look for and use an existing library for the bottom sheet.

AC: 
- Users can open the 'DeFi Explorer' screen from the side menu and open the dApps that are available.
- The UI matches the mockups.
- This feature is unit tested.
- This feature should be initially only available behind a feature flag.

**Comment by silasbw** [comment]
The "API" is accessible via github raw:

```
curl https://raw.githubusercontent.com/valora-inc/dapp-list/main/src/valora-dapp-list.json
```

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our comment and observation in the ticket #1784
