### ISSUE TITLE
Create endpoint on blockchain-api to list categories and dApps.

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1507]
We need to create an endpoint that reads info from the postgres DB and returns it. See the epic description for more info on the overall goal of the feature.

First, we need to create the schema of the two entities we want to return:

The fields for **categories** are:
- Name: It must be translatable to all of our supported languages. I recommend storing it as a [json or jsonb in the db](https://www.postgresql.org/docs/9.4/datatype-json.html).
- Background Color: RGB string of the background color of the section title.
- Font color: RGB string of the color of the font.

Each category must be created with a unique ID.

The fields for **dApps** are:
- Name: The name of the dApp. Translation is not necessary.
- Description: The description of the dApp. Must be translatable (see above about storing it as json directly).
- Logo: The logo of the dApp, just a string.
- Category Id: The id of the category created in the other endpoint.
- Link: A link to the dApp.

Each dApp should also be created with a unique ID.

After creating a migration that adds those two tables, we can add some mock data manually to test and create and endpoint that returns all of it. The endpoint should return two lists: One of categories and one of dApps. No pagination or anything like that is required at this point.

AC:
- A migration file that creates the two new tables.
- The endpoint that lists all categories and dApps is implemented.
- Automated tests for the endpoint.

**Comment by silasbw** [comment]
We decided to start with https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/1710 (which has a PR at https://github.com/valora-inc/app-list/pull/1)

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
