### ISSUE TITLE
Add create and update endpoints for categories

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1508]
We need to create an endpoint that creates categories and another that updates them. See the epic description for more info on the overall goal of the feature.

For creating categories, the fields are:
- Name: It must be translatable to all of our supported languages. I recommend just checking the format of the object and storing it as a [json or jsonb in the db](https://www.postgresql.org/docs/9.4/datatype-json.html).
- Background Color: RGB string of the background color of the section title.
- Font color: RGB string of the color of the font.

Each category must be created with a unique ID that is returned to the caller.

For updating, the fields are the same plus the id of the category to update.

AC:
- The two endpoints described above implemented.
- Automated tests for the endpoints.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
