### ISSUE TITLE
Add create and update endpoints for dApps

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1509]
We need to create an endpoint that creates dApps and another that updates them. See the epic description for more info on the overall goal of the feature.

For creating dApps, the fields are:
- Name: The name of the dApp. Translation is not necessary.
- Description: The description of the dApp. Must be translatable (see above about storing it as json directly).
- Logo: The logo of the dApp, just a string.
- Category Id: The id of the category created in the other endpoint.
- Link: A link to the dApp.

Each dApp must be created with a unique ID that is returned to the caller.

For updating, the fields are the same plus the id of the dApp to update.

AC:
- The two endpoints described above implemented.
- Automated tests for the endpoints.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
