### ISSUE TITLE
Allow creating and updating categories in the admin dashboard

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1510]
In the newly created "dApp Directory" section of the Admin Dashboard we want to allow creating and updating categories. See the epic for more info on the future.

The fields for **categories** are:
- Name: It must be translatable to all of our supported languages. I recommend just checking the format of the object and storing it as a [json or jsonb in the db](https://www.postgresql.org/docs/9.4/datatype-json.html).
- Background Color: RGB string of the background color of the section title.
- Font color: RGB string of the color of the font.

When updating, we also need to send the category id we're updating.

Since this is for internal usage, there are no mockups or anything. Try to make it intuitive and simple to use but don't worry too much about making it pretty.

An endpoint will be created on the blockchain-api for us to create and update categories on #1508.

AC: 
- Users can create and update categories from the Admin Dashboard.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
