### ISSUE TITLE
Allow creating and updating dApps in the admin dashboard

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1511]
In the newly created "dApp Directory" section of the Admin Dashboard we want to allow creating and updating dApps. See the epic for more info on the future.

The fields for **dApps** are:
- Name: The name of the dApp. Translation is not necessary.
- Description: The description of the dApp. Must be translatable (just send a json with language as key and text as value).
- Logo: The logo of the dApp, just a string. In the future we might want to allow uploading a picture and store it in Firebase Storage.
- Category Id: The id of the category.
- Link: A link to the dApp.

When editing, we also need to pass the dApp id to the backend.

Since this is for internal usage, there are no mockups or anything. Try to make it intuitive and simple to use but don't worry too much about making it pretty.

An endpoint will be created on the blockchain-api for us to create and update categories and dApps on #1509.

AC: 
- Users can create and update dApps from the Admin Dashboard.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
