### ISSUE TITLE
Continuous loading appears on “Awaiting Payment” screen in Bidali page & User is blocked to buy gift card.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1521]
**Frequency:** 100%

**Repro on build version:** iOS Alfajores V1.22.1
**Repro on devices:** iPhone 12 (15.0), iPhone 6+ (12.5.4)

**Does Not Repro on build version:** iOS Alfajores 1.21.0
**Does Not Repro on devices:** iPhone 12 (15)
**Note:** For android alfa jores build V1.22.1 is not available.

**Pre-condition:** 
1. User must have installed the app and completed onboarding flow.
2. User must have sufficient balance in the account.
3. User must be on bidali screen. 

**Repro Steps:**
1. Tap on any brand.
2.  Select any option of gift card amount.
3. Tap on “Purchase” button.
4. Enter valid email address.
5. Tap on “Next” button & Observe.

**Current Behavior:** Continuous loading appears on “Awaiting Payment” screen in bidali page & User is blocked to buy gift card.

**Expected Behavior:**  Continuous loading must not appear on “Awaiting Payment” screen in bidali page & User must be able submit order.

**Impact:** Bad user experience as user is blocked to submit order

**Attachment:** [Not able to buy Gift Card.mp4](https://drive.google.com/file/d/1UKgG6EXSycVQ_rXZ83tTGbcjt_jG9YUX/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D672](https://valora.testquality.com/project/12128/result/2573987/defect/9312).

**Comment by MuckT** [comment]
@ValoraQA can you attach logs for this issue?

**Comment by ValoraQA** [comment]
Hey @MuckT, We have attached the logs for the issue below.

**Attachment:** [Celo logs.txt](https://drive.google.com/file/d/1sq721A0I0yC33gmQyqVWZKYebNYi_4LU/view?usp=sharing) 
**Device:** iPhone 12 (15.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest iOS Alfajores Build V1.22.2 & observed that the issue is fixed now.

**Device:** iPhone 12(14.7.1)
**Attachment**:[Able to buy gift card.mp4](https://drive.google.com/file/d/1DpLfkc6eZVuBS-ohqQxHL5bj8Qi3B1KH/view?usp=sharing) 
CC: @jeanregisser 
Thanks..!!
