### ISSUE TITLE
Implement flowType event paramter

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1524]
flowType : send the type of the screen where the interaction is happening. screen to flow type mapping is here

This is a spin off issue from #305

Aleksey, Jean, Gowtham to discuss wether we still need it.

AC:

**Comment by kathaypacific** [comment]
Closed in backlog spring clean May 2022

**Comment by kathaypacific** [comment]
Closed in backlog spring clean May 2022
