### ISSUE TITLE
Add authentication for dApp directory endpoints

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1526]
The create and update endpoints for both categories and dApps need to be authenticated so that only authorized users can call them. We are using Firebase Authentication in the admin dashboard so we should consider leveraging that in the blockchain-api for authentication.

This issue involves investigating how we can use Firebase Authentication in the blockchain-api and make sure that only users with access to the admin dashboard can call them. We are using custom claims for it, and authorized users should have the `productAdmin` claim set to `true`

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
