### ISSUE TITLE
[Query]: 0.01 balance should be seen in the "Total balances" section after User B downloads and registers on the app via invite link

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1530]
**Frequency :** 100%

**Repro on build version:** Android Internal Build V1.22.1 , iOS Test flight Build V:1.22.1

**Repro on devices:** OnePlus 7T(11.0), iPhone12(15), iPhone 6+(12.5.4), Redmi Note 8(9.0). Redmi Note 8(10.0), iPhone 12(15)

**Pre Condition:** 
1] User must have cUSD & cEUR balance in account
2] User A must have shared invite link with amount "0.01" to User B 

**Repro steps :**
1] User B downloads the app via invite link and registers on the application
2] User B is redirected to homepage and is able to see "funds transferred into your account" toast
3] User B is able to see transaction in recent activity feed
4] Observe "total balance" section seen on homepage

**Current behavior :** "Total balance" is seen as 0.00 although there is "0.01" amount available in user B wallet

**Expected behavior :** "Total balance" should be seen updated as "0.01" after the transaction is seen in recent activity

**Impact :**
- Bad user experience as user B has received amount "0.01" in the wallet however it is not appearing on the "total balance" section 

**Attachments:** [balance1.mp4](https://drive.google.com/file/d/1CtyN5vCL2psiA-9BiyxuKJnIlvJs9e_m/view?usp=sharing), [balance2.mp4](https://drive.google.com/file/d/1D20vLCklkHGKEO-8VQsuGvM2TX0LsM9q/view?usp=sharing)

**Comment by MuckT** [comment]
@gnardini should we change `gt` to `gte`? https://github.com/valora-inc/wallet/blob/5420e5c6ea4acdf66b2fbf6ffa3558659ba616fd/packages/mobile/src/tokens/selectors.ts#L32-L36

**Comment by gnardini** [comment]
Yup, that sounds good to me

**Comment by ValoraQA** [comment]
Hey @MuckT , we have observation related to CELO wherein if the CELO is less than "0.001" it is not seen in the asset page 
**Refer attachment :** [celo_not_seen.mp4](https://drive.google.com/file/d/1GL1f1UV25io7YiU2YVc0INfBizoMZ3s_/view?usp=sharing)

**Observation :** If the CELO balance is more than "0.001" then it is visible on the asset page 
**Verified on Device** : OnePlus 7T(11.0)
