### ISSUE TITLE
 “CELO” token/balance option not displayed while sending amount to User B  after tapping on “Dropdown icon” on Send Amount page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1538]
**Frequency:** 100%
**Repro on build version:** Android internal build and iOS test flight build V:1.22.1
**Repro on devices:** iPhone 12(15), One Plus 7T(11.0), Google Pixel 2XL (11.0), Samsung Galaxy F41  (11.0), Redmi Note 8 (9.0)
**Testing Account:**  (680) 333 1978 /[Recovery Phrase](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B13)
**Pre-condition:** Make sure that the user should have an account with all 3 types of tokens
**Repro Steps:**
1. Launch the application & log in with the test account
2. Now user should be on the “Home” screen
3. Redirect to the “Send Amount” page by tapping on the “Send” button by selecting contacts from a list
4. Now tap on “Dropdown” shown beside the “Send” title 
5. Observe the “Select Balance” popup
**Current Behavior:** Only “cUSD” & “cEUR” balances are displayed in the list even “CELO” balance present in the account
**Expected Behavior:** “CELO”  balance should be also displayed in a list on the “Select Balance” popup
**Investigation:** Also we have observed same issue while sending Request to user B 
**Impact:** Bad user experience as User B not able to Send/Request money
**Attachment:** [NotAbleToSeeCELOInList.mp4](https://drive.google.com/file/d/1f0KQtiPo1jJuAU4I3NL7BbUggp3Et8us/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this will be included in 1.23.x.

**Comment by ValoraQA** [comment]
Hey @MuckT We would check the above issue in V:1.23.x and update the status in the ticket
