### ISSUE TITLE
Allow filtering dApps

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1548]
We will want the dApps we show users to be somewhat customizable. For example, to show or not show for users of specific regions, to users with certain balances, etc. We have two options for doing it:

- Pass all the dApps to the frontend with the filters for each and let the frontend decide which ones to show.
- Have the frontend send a bunch of fields to the backend and make the backend decide which dApps to return to the app.

I like option two better because it allows us to send to the backend some relevant fields related to the user (like the fields returned by `getCurrentUserTraits` on `src/analytics/selectors` and decide later how to use those to filter since it would only require backend changes, which makes making changes easier.

For choosing the actual filters, we would need to make the UI of the Admin Dashboard allow setting this sort of thing. There's already examples for countries allow/deny lists for in-app notifications which is a popular filter and we can add new ones as needed. We can store these filters in a jsonb column in the database.

AC:
- Valora sends some generic properties of the user to the dApp directory endpoint.
- The Blockchain API allows adding filters to each dApp when creating/updating and uses them in the dApp listing endpoint. Only country filtering needs to be available right now, but the solution should be generic enough that it allows us to add new ones easily.
- The Admin Dashboard allows users to choose in which countries they want a dApp to show or not to show.

**Comment by kathaypacific** [comment]
This is no longer relevant as we decided on the dapplist in github approach
