### ISSUE TITLE
"Logs.txt" file is not being generated in mail body after user enters a message and clicks on submit button

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1555]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.22.3, Test flight build V1.22.3
**Repro on devices:** iPhone 12(14.7.1), OnePlus 7T(11.0) , iPhone 6+(12.5.4), Google Pixel 4a (12)

**Does Not Repro on build version:** Android Play store Build V1.21.0, Test flight build V1.22.1, Test flight build V:1.22.2
**Does Not Repro on devices:**  OnePlus 7T(11.0), iPhone 12(14.7.1), iPhone 6+(12.5.4)

**Pre-condition:**
1] User must have installed the app .
2] User must have completed onboarding flow.

**Repro Steps:**
1] Click on hamburger menu
2] Click on help option
3] Click on contact option
4] Click on message field and enter any message
5] Click on submit button and select any mailing option (Eg : mail , gmail) and observe the logs generated 

**Current Behavior:** "Log.txt" file is not seen generated on the mail body instead whole log is seen on the screen 
**Expected Behavior:** "Log.txt" file should be seen generated in the mail body

**Investigation :**
- The same behavior is faced when user shakes the device and continue the flow after clicking on contact support button 
- Blue banner is seen when user navigate back to app without sending the mail 

**Impact:** Bad User experience.
**Attachment:** [logs_textfile.mp4](https://drive.google.com/file/d/1Je9WveIr0quDB4gd_60oTb12XYKSuKRd/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D728](https://valora.testquality.com/project/12128/result/2590850/defect/9391).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D729](https://valora.testquality.com/project/12128/result/2590851/defect/9392).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D868](https://valora.testquality.com/project/12128/result/2616405/defect/9667).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D869](https://valora.testquality.com/project/12128/result/2616406/defect/9668).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using latest Android internal build V1.24.1, Test flight build V1.24.1 & observed that this issue is fixed for Android Platform & issue is still reproducible for iOS platform. For android platform "celo_logs.txt" file gets generated and attached in mail. For iOS platform no "log.txt" file is generated and the whole log is appearing in mail body.

**Devices:** iPhone 13 mini (15.1.1), iPhone XS Max (13.5.1), iPhone 12 (14.7.1), Google pixel XL (10.0), Google pixel 2xl (11.0)
**Attachment:** [Android fixed.jpg](https://drive.google.com/file/d/1PNK1YzhFAYaSC_7_8HubVlXMvL8ZHr-E/view?usp=sharing)
[iOS still repro.mp4](https://drive.google.com/file/d/1VCxZpYCph9DQsczrNS-5pFunE-mVBOWn/view?usp=sharing)

Thanks.!!

**Comment by MuckT** [comment]
@ValoraQA - Using Gmail on iOS the logs will be in the email body, but you select the native mail client the logs should be attached.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest iOS test flight Release build V 1.37.0 and observed that issue is fixed 

Observation : When user selects Email option then log file is seen generated whereas if Gmail is selected then whole log is seen as text instead of logs.txt file

Device : iPhone 12(14.7.1)

Attachment : [email.mp4](https://drive.google.com/file/d/19DjQ800SxghRuSrvF2UNiDAQ7mB4HRc1/view?usp=sharing)

Thanks..!
