### ISSUE TITLE
Wallet Connect V1 Actions Failing in Valora

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1556]
### Current behavior
Users are able to establish a connection via wallet connect; however, all actions on the connection are failing.

[Slack Thread](https://valora-app.slack.com/archives/C02E83RE802/p1638366055058100)

### Desired behavior
Users are able to perform all supported actions for WalletConnectV1.

### Steps to Reproduce
1. Connect to Sushi Swap via WalletConnect.
2. Attempt to swap tokens.
3. Observe timeout in Valora.

### Versions
This bug is present in 1.21.0 and 1.22.3; however, it was previously working on 1.21.0. This is not likely due to a change in the code but some misconfiguration.

**Comment by MuckT** [comment]
Restarting the iOS device appeared to resolve the issue.

**Comment by MuckT** [comment]
Created PR: [Apple app site association #222](https://github.com/valora-inc/valora-website/pull/222). To help with timeout issues.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest iOS Test flight Build V1.22.3 , iOS Alfajores Build V1.22.3, observed that "Insufficient Liquidity For this trade" error appears for test flight build  & "Time out" appears while connecting sushi dapp in iOS Alfa jores build V1.22.3.

**Related Query Link:**[#1196](https://github.com/valora-inc/wallet/issues/1196)
**Device:** iPhone 8(15.1)
**Attachment:** [Insufficient Liquidity error.mp4](https://drive.google.com/file/d/16iPFxikm4XWdrk8YaFw1wS1daqTgvuSI/view?usp=sharing)
Thanks..!!

**Comment by MuckT** [comment]
@ValoraQA would you please retest as #222 has been merged and deployed.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue on latest iOS Testflight build V: 1.23.3 and observed the following things
Observation : 
For iOS 15.1.1 : 
For iOS 14.7.1 : 
- If we connect wallet for the first time "balance is not seen" on the amount field 
- We refresh the page and its logged out, again we connect the wallet then "balance" is seen in the amount field
- After entering balance if we click on swap and confirm it , it directly loads valoraapp.com site instead of showing pop up as "open in valora"
- If we switch to valora app and approve the transaction and navigate back to safari browser then it shows valora site and if we click on browser back then again we are seen logged out 
Refer attachment : [appsushi_iOS14.mp4](https://drive.google.com/file/d/1zFwrJi7tKIYB9KHSnMiztVZVqVFvVBXA/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this should be resolved. Sushi swap has had some issues recently, can you try instead with [pooltogether](https://app.pooltogether.com/)?

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the issue in latest Android Internal release build and Latest iOS test flight release build V:1.24.1 and observed that

-**For iOS :** 
-"Time out" error is seen when we try to connect to quickswap.exchange site for and then refreshing the site and again trying to connect then it gets connected 

**For iOS and Android :**
- After connecting wallet , we are not able to see cUSD, cEUR , token in the list of the token mentioned 
- Also "Wrong Network" , "Please connect to the appropriate Matic network" is seen 

**Checked on Devices :** Google Pixel 2XL (11.0) , iPhone 13 mini (15.1.1) , iPhone 12 (14.7.1) , Google Pixel XL(10.0)

**Attachment :** [pooltogether.mp4](https://drive.google.com/file/d/18rWCTw2gLmFX36-HZC8oALBrE7cvMobW/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA it looks like [quickswap.exchang](https://quickswap.exchange) only supports Ethereum and Polygon. For PoolTogether make sure to use the v3 site, [PoolTogether - v3](https://v3.pooltogether.com).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the issue in latest Android Internal release build and Latest iOS test flight release build V:1.24.1 and observed that

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the issue in latest Android Internal release build and Latest iOS test flight release build V:1.24.1 and observed that

Observation : There is no option of swapping token as seen for V4 , hence we have performed the deposit flow on pooltogether V3

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the issue in latest Android Internal release build and Latest iOS test flight release build V:1.24.1 and observed that

Observation : There is no option of swapping token as seen on pool together V4 , hence we have performed the deposit flow on pool together V3 site as provided

Attachment : [pooltogether_v3](https://drive.google.com/file/d/19dhipTWCjOUejs1uKN14j_6Kl0KsnyfX/view?usp=sharing)
- Also let us know do we need to check other flow on pooltogether site 
Thanks ..!

**Comment by MuckT** [comment]
Closed by https://github.com/valora-inc/wallet/pull/1729
