### ISSUE TITLE
'Sign a transaction' failing with WalletConnect - Optional Gas Required

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1559]
### Current behavior
When creating e2e tests for WalletConnect 'Sign a transaction' was failing after accepting. 

### Desired behavior
WalletConnectV1 should handle sign transaction (eth_signTransaction)​ with or without gas [based on the docs](https://docs.walletconnect.com/1.0/quick-start/dapps/node#sign-transaction-eth_signtransaction).

### Steps to Reproduce
Reproducible on [e2e-walletconnect](https://github.com/valora-inc/wallet/tree/tomm/e2e-walletconnect).
1. Enable the test "Then is able to sign a transaction" in `usecases/WalletConnectV1.js`
2. `yarn install && yarn build && cd packages/mobile && yarn test:e2e:ios -f WalletConnect.spec.js`

### Relevant Logs With Gas Excluded
```
redux/saga@logger/{"type":"WALLETCONNECT/ACCEPT_REQUEST_V1","request":{"id":1638408490234137,"jsonrpc":"2.0","method":"eth_signTransaction","params":[{"from":"0x6131a6d616a4be3737b38988847270a64bc10caa","to":"0xe5f5363e31351c38ac82dbadead91fd5a7b08846","gasPrice":"0x1","value":"0x1","data":"0x"}]},"peerId":"d387e766-1327-4048-a49b-9c6c5317f5a7"}
WalletConnect/saga-v1@acceptRequest/"gas" is missing
ValoraAnalytics/Tracking event wc_request_accept_error with properties: {"timestamp":1638408492160,"sessionId":"42d817afd6f9d5be938253fad9904d460998f2a8da7fba4fb9ed476654692e","userAddress":"0x6131a6d616a4be3737b38988847270a64bc10caa","celoNetwork":"alfajores","sAccountAddress":"0x6131a6d616a4be3737b38988847270a64bc10caa","sWalletAddress":"0x6131a6d616a4be3737b38988847270a64bc10caa","sPhoneCountryCallingCode":"+1","sPhoneCountryCodeAlpha2":"US","sCountryCodeAlpha2":"US","sLanguage":"en-US","sTotalBalanceUsd":787.530008012507,"sTokenCount":3,"sOtherTenTokens":"","sCusdBalance":49.07247683830868,"sCeurBalance":165.29173707525877,"sCeloBalance":83.60204329621429,"sLocalCurrencyCode":"USD","sHasVerifiedNumber":false,"sHasCompletedBackup":true,"sDeviceId":"06D56C71-324C-4C3D-9B2B-21BA25B250B3","sAppVersion":"1.21.0","sAppBuildNumber":"82","sAppBundleId":"org.celo.mobile.test","sCurrentScreenId":"WalletConnectActionRequest","sPrevScreenId":"WalletHome","version":1,"dappName":"WalletConnectV1 E2E","dappUrl"<…>
```

### Relevant Logs with Gas Included
```
redux/saga@logger/{"type":"WALLETCONNECT/ACCEPT_REQUEST_V1","request":{"id":1638408969953139,"jsonrpc":"2.0","method":"eth_signTransaction","params":[{"from":"0x6131a6d616a4be3737b38988847270a64bc10caa","to":"0xe5f5363e31351c38ac82dbadead91fd5a7b08846","gasPrice":"0x2540be400","gas":"0x9c40","value":"0x1","data":"0x"}]},"peerId":"f701bb2f-44d4-4edc-bafb-3fc63f1cf838"}
WalletConnect/saga-v1@acceptRequest/One of the values "chainId", "gasPrice", or "nonce" couldn't be fetched: {"gasPrice":"0x2540be400"}
```

**Comment by ValoraQA** [comment]
Hey @MuckT We have gone through the doc provided in the ticket , however we are not getting idea how to repro the issue
Could you please let us know if we can reproduce the issue on front end so it can be helpful !!

**Comment by jmrossy** [comment]
I'm seeing this as well when trying to use WalletConenct v1 with Valora. Note, the error originates here: https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/wallets/wallet-base/src/signing-utils.ts#L70

**Comment by jmrossy** [comment]
I believe it's because WalletConnect's utilities remove the chainId:
https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/helpers/utils/src/ethereum.ts#L84

And Valora's handler for signing transactions does not do tx normalization in the way that the send tx handler does:
https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/walletConnect/request.ts#L33

**Comment by ValoraQA** [comment]
Hey @MuckT we have shared our observation in ticket #1729
