### ISSUE TITLE
Show the name of the invitee correctly in the transaction feed

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1574]
When inviting someone, the transaction feed shows the item as 'Unknown'. We need to query the blockchain to know which identifier was invited in that tx and use the local identifier to recipient cache to show the right name.

Also, when reclaiming invites it shows as unknown with a weird message. It would be cool to fix that too.

**Comment by kathaypacific** [comment]
Closing this as a duplicate of #2215
