### ISSUE TITLE
  [Query]  “Total balances” section is not displayed in Home screen when user opens the valora application. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1598]
**Frequency:** 100%

**Repro on build version:** App store Build V1.22.4, Android Internal Build V1.22.4, Test flight build V1.22.3,1.22.2
**Repro on devices:** iPhone 12(14.7.1), iPhone 13 mini (15.1.1), Samsung Galaxy A8+ (8.0), Google Pixel 2XL (11.0)

**Does Not Repro on build version:** iOS Alfa Jores Build V1.22.4
**Does Not Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1) 

**Pre-condition:** 
1. User must have installed the application and completed the onboarding flow.
2. User must have valid all the three balances cUSD, cEUR & CELO

**Repro Steps:**
1. Launch the app & observe the home screen.

**Current Behavior:** “Total balances” section is not displayed in Home screen when user opens the valora application & all the balances are displayed in Hamburger menu .

**Expected Behavior:** “Total balances” section must be displayed in Home screen when user opens the valora application.

**Impact:** Bad user experience.

**Attachment:** [Total Balance Section Not Displayed.mp4](https://drive.google.com/file/d/1Jmu6-c1Jv3GA9fv9MmdCLxg_N_zJ0qG5/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this is expected as we have disabled that flag in the remote config for now.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thank you very much for the update.
