### ISSUE TITLE
Fix token bottom sheet displays for large fonts & localization

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1601]
### Description
Some styling work is needed to make token bottom sheet display with large fonts / long language localizations.

<img src="https://user-images.githubusercontent.com/26950305/145450675-6cba5304-615b-4af0-a1d5-91c3b9f802a8.png" width="50%" height="auto" alt="Token bottom sheet with large font on iOS">

### User Stories 
As a user with visual impairment I want to be able to see the token bottom sheet balances clearly and in line so that I can select the token with an appropriate balance. 

### Acceptance Criteria

- Token bottom sheet displays items with roughly equal vertical space.
- Text is easily readable.
- Large font does not shift ratios of layout.

**Comment by kathaypacific** [comment]
Closed by https://github.com/valora-inc/wallet/pull/2346

@ellenwoconnor will create an ticket to do a sweep of the app to ensure all screens can handle large font
