### ISSUE TITLE
Transaction drilldown improvements

### ISSUE THREAD

**Issue by ole-nov** [valora-inc/wallet#1607]
[New designs](https://www.figma.com/file/RGM6cZFbfEr1NuLZXnKhKl/Rounding-Guidelines?node-id=0%3A1)

AC:
- Amount sent always displayed in crypto cryptocurrency transaction was made in;
- [crypto] price displayed in the fiat currency of choice with 3 decimals;
-Instead of a fee that expands, there is a network fee (current security fee) and exchange fee (if any), displayed in the fiat currency of choice with 3 decimals (rounded up);
- the changes are reflected on all of the following screens: transaction received, sent, buy celo flow.

**Comment by ellenwoconnor** [comment]
@nityarao there's a link to designs for this but for me at least it says the file doesn't exist. are these changes still relevant and if so is there a new link we can use?
