### ISSUE TITLE
Setup an experiment to remove education from the onboarding flow.

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1612]
[Experiment proposal in notion](https://www.notion.so/valora-inc/Remove-education-from-on-the-onboarding-flow-edf2be9017e645e18c21874ad6e28c6c)

Eng notes:
- Since this is the first screen of the app, we still don't have the feature flag values here, and it would be weird to show the screen and then remove it.
- One option is to extend the Splash Screen a few seconds the first time to fetch the value of the feature flag and then decide which screen to show first.

AC:
- experiment according to specs in the proposal is ready to launch from Firebase.

**Comment by cajubelt** [comment]
Lisa to add logging on how long it takes to fetch remote config
