### ISSUE TITLE
“Begin” button appears disabled when user navigates to “Verify your identify” section by clicking on “Link Bank Accounts” option from settings screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1619]
**Frequency:** 100%

**Repro on build version:** iOS Alfa jores Build V1.23.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1)
**NOTE:** Not verified on Android platform, as for android platform Latest Alfa jores build V1.22.4 is displayed.

**Pre-condition:** 
1. User have installed the app
2. User have complete onboarding flow without confirming phone number.
3. User must be on settings screen.

**Repro Steps:**
1. Tap on “Link Bank Accounts” option from settings screen.
2. Tap on “Connect” button from Connect phone number to continue screen.
3. Enter valid phone number & complete phone number verification flow.
4. Navigate to the Settings screen from the hamburger menu.
5. Tap on “Link Bank Accounts” & observe.

**Current Behavior:**  “Begin” button appears disabled when user navigates to “Verify your identify” section. 

**Expected Behavior:** “Begin” button must appear enabled when user navigates to “Verify your identify” section .

**Impact:** User will be blocked to complete the “Verify your identity” flow.

**Attachment:** [Begin Button Disabled.mp4](https://drive.google.com/file/d/1kl19eXjfFtyFigD-bCGZV013S4ekNqgt/view?usp=sharing)

**Comment by MuckT** [comment]
Downgraded priority as these are behind a feature flag and will not be visible to users in the next release.

**Comment by ValoraQA** [comment]
Hey @MuckT we are closing the above issue since this feature will not be present in upcoming builds as discussed in weekly meeting 

Thanks.!
