### ISSUE TITLE
Remove Education screen from onboarding flow

### ISSUE THREAD

**Issue by lisaqyli** [valora-inc/wallet#1626]
We decided to run a small experiment to remove the first 3 education sliders from the onboarding flow

Experiment Design: https://www.notion.so/valora-inc/Experiment-Design-Onboarding-50b74f06121d4db59a9b777989d22e21

AC:
- There is a remote config set up in firebase for education screen removal
-  The experiment is implemented in code base configured as required in Experiment Design
- The experiment is configured in Firebase according to Experiment Design

**Comment by aleksey-nov** [comment]
Duplicate of #1612
