### ISSUE TITLE
“Link Bank Accounts” option is not visible in Settings screen when user navigates to Settings screen from Hamburger menu

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1630]
**Frequency:** 100%

**Repro on build version:** iOS Alfa Jores build V1.23.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), iPhone XR (14.6)
**NOTE:** Not verified on Android platform, as for android platform Latest Alfa jores build V1.22.4 is displayed.

**Pre-condition:**
1. User must have installed the application
2. User must have completed on boarding flow & user is on home screen

**Repro Steps:**
1. Launch the app.
2. Tap & Open Hamburger menu
3. Tap on “Settings” option & observe.

**Current Behavior:**“Link Bank Accounts” option is not visible in Settings screen when user navigates to Settings screen from Hamburger menu

**Expected Behavior:** “Link Bank Accounts” option must be visible in Settings screen when user navigates to Settings screen from Hamburger menu

**Investigation:** This issue is repro when user completes onboarding flow with phone number confirmation & skips phone number confirmation also.

**Impact:** User will be blocked to check “Link Bank Accounts” flow.

**Attachment:** 
[Link Bank Account without phone number.mp4](https://drive.google.com/file/d/1I3asV5fMZuiIyWhkYVP5Pwnn__H0F5Dg/view?usp=sharing)
[Link Bank account with phone number.mp4](https://drive.google.com/file/d/1UyhungcJRehDJw9LL41_vkPbwSC3IfKd/view?usp=sharing )

**Comment by MuckT** [comment]
Downgraded priority as these are behind a feature flag and will not be visible to users in the next release.

**Comment by ValoraQA** [comment]
Hey @MuckT thanks for the information ..!
