### ISSUE TITLE
MAX button behaviour

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1651]
**Problem**: Let's say user has only CELO in their account. When they tap the MAX button to send all balance, they won't have any funds to pay the transaction fees and it will be reverted. 
To avoid this, when user taps the MAX button we should leave the estimated gas price amount to make the transaction.
So MAX = Total balance - Estimated Gas Amount

AC: User that has only Celo in their account, can send all of their balance minus transaction fee using the MAX button in the send flow.

**Comment by MuckT** [comment]
A bit more context and reproduction steps for the issue can be found in #1648.
