### ISSUE TITLE
Increase tap area on buttons

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1655]
It is very difficult to tap the switch button (the arrows to go from fiat to crypto input).
Increase the tap area for these buttons to the size that @nityarao suggests.

**Comment by nityarao** [comment]
I've got this in Figma as well! But the tap area for the buttons is 48x48 px

Generally I like to follow Apples HIG for this kind of stuff. https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/
