### ISSUE TITLE
Move config for multiple tokens to file on Github

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1656]
Atm there is an automated script that decided which tokens are displayed in Valora based on some rules (listed on ubeswap, has $20k in liquidity). After going live with this approach we have noticed few issues:
- It is not easy for the whole team to see the complete list of tokens that are now supported in Valora;
- in conditions of volatile market, tokens get delisted automatically and it causes inconveniences for the end user;
- the number of tokens that are not trade on ubeswap, but still should be included in Valora is higher than expected.

In one of our meetings we have discussed an alternative solution, that will help to resolve this problems. And this solution is the config file on github with the list of supported tokens. 
Product team (specifically PM of the retention squad) is responsible for maintaining this list.
External contributors can submit a PR to add their token to Valora and it can go live, as soon as PR reviewed and merged by member of product team.

Questions:
* Do we continue to show token **price** even if liquidity is low (_e.g._, pool has a $100 value)?
* Requirements around process for adding new tokens (_e.g._, accept community contributes, any sort of validation, etc)?  Especially if product team is reviewing PRs (vs engineering).

ENG:
- One way to sync token list: <https://github.com/valora-inc/address-metadata>
  - One issue is that this would override nodes that contain other useful metadata (e.g., USD price)
- Another approach is reaching directly from an "API" (i.e., github).  Make this a RemoteConfig variable.

AC:
- [ ] The Valora team can easily see the complete list of tokens
- [ ] Don't delist tokens automatically
- [ ] Show token amounts even if not listed on ubeswap (or another dex)

**Comment by dievazqu** [comment]
@aleksey-nov, I have a couple of questions:
Right now, we are filtering all liquidity pools with less than 20k to have a good accuracy on the token price. What is the expectation now that we will have this config? Should we still have the same logic to calculate the price? Or should we "force" the calculation for all the tokens listed there?
We are calculating the price only for tokens that are tradeable in ubeswap, so even we add new tokens in GH we won't have a price for them if they aren't tradeable. Are we ok with this?
