### ISSUE TITLE
Product Design QA Updates

### ISSUE THREAD

**Issue by nityarao** [valora-inc/wallet#1657]
A few updates from usability testing & design QA. Includes things like: 

Figma link: https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1459%3A38985

**Comment by MuckT** [comment]
### AC
- [ ] Make the touch target larger (48 px) & add a background to reinforce the touch target for Max and swap buttons.
- [ ] Move the max & swap icons closer to the center of the page. Make sure the icons are in line with the edge of the review button (24px from the edge).
- [ ] Move the icons closer to the numbers to help increase understanding of its action; icons should align with the top number.
