### ISSUE TITLE
Spike: alternatives for account recovery

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1673]
Does an easier solution exist for cloud account recovery? For example, could we just save someone's mnemonic to keychain?

In particular, I worry about the PIN encryption for the backup, since this has been a sore spot for users writing in to support. 

This is expected to be a product/eng collaboration since it involves seeing what's feasible/easy to implement, and significant UX considerations.

AC:
- competitive analysis is done on at least 3 other wallets offering account recovery (beyond vanilla mnemonic solutions)
- at least one alternative to the existing plan is documented in notion (for example, using keychain. but with more details. should include high-level engineering design too, but mainly focus on the UX)
- consensus is reached with product and activation eng on which we should choose

**Comment by cajubelt** [comment]
should also consider the impact of the biometrics features

**Comment by cajubelt** [comment]
There's an existing doc here that we should try to avoid duplicating effort with https://www.notion.so/clabsco/Other-Secret-Encryption-Services-9855fef039dc49f085e718abaf8f959b

**Comment by nityarao** [comment]
Thanks for the docs-- They definitely cover a lot of existing solutions out there for recovery with / without cloud backup. 

This was one of the options that I found that we haven't covered yet. Was super interesting actually, involving using a phone number to back up the recovery phrase. It's listed out in this article by a BTC wallet called "handcash" 

https://handcash.medium.com/handcash-goes-keyless-b86d27339254

From a UX standpoint, it feels promising, and also plays into one of Valora's existing value props. That being said, I don't know if this makes sense for us to do from a technical or security standpoint. I'll take some screenshots later today to go through what their recovery flow looks / feels like but super curious about what you guys think--- @cajubelt @silasbw

**Comment by cajubelt** [comment]
taking myself off as the eng co-owner in case someone else frees up earlier (don't want to leave this blocked while I'm out on vacation)

**Comment by cajubelt** [comment]
One alternative cloud backup approach would be to save the mnemonic to a password manager. I think anyone with a Google or iCloud account should be able to use [Google Smart Lock](https://developers.google.com/identity/smartlock-passwords/android) or [keychain](https://developer.apple.com/documentation/security/keychain_services).

Pros:
- no dependency on remembering your PIN
- lower risk of accidental deletion
- might be easier to implement than saving to iCloud / Google Drive (not actually sure)

Cons:
- no secondary encryption layer

**Comment by cajubelt** [comment]
@nityarao handcash is cool, definitely a good long-term model, though I have very little insight from the blog post into how it works lol

**Comment by cajubelt** [comment]
I think cLabs has some plans for a keyless experience that are partially complete

**Comment by cajubelt** [comment]
another straw-person proposal: store an encrypted mnemonic in a Valora database, and decrypt with a password saved in keychain/google smart lock

we could then implement the rate-limiting that cLabs' DOPE service is supposed to provide
