### ISSUE TITLE
Add "region" to User Properties

### ISSUE THREAD

**Issue by laurencedelisle** [valora-inc/wallet#1681]
**Description**
Add `region` to user properties to better target users in CleverTap. Specifically we want to be able to send a push notification to all our US users who are eligible to cash in with Ramp (e.g. in one of a group of states in the US)

**Related Issues**
Discussion on [slack](https://valora-app.slack.com/archives/C025Q9QG8JG/p1640210545178900?thread_ts=1640209542.178600&cid=C025Q9QG8JG)
[Notion](https://www.notion.so/valora-inc/Add-region-to-User-Properties-8d3c0063ed944a6eae9cc64554e0f278) 

AC:
- [ ] Able to send push notifications to users in the US who are eligible to cash in with Ramp

**Comment by silasbw** [comment]
We'll followup over slack.

**Comment by silasbw** [comment]
Closing, but feel free to re-open if this becomes a harder requirement.
