### ISSUE TITLE
Increase "deep link" capability for push notifications

### ISSUE THREAD

**Issue by laurencedelisle** [valora-inc/wallet#1682]
### Description
At the moment we can only direct a user to the cash in screen and home screen through push notifications via CleverTap. We need to expand our ability to directly push users into different parts of the app to help them through their user journey and activate them more effectively.

For example, for Supercharge we'd like to push them to:
- Verification Screen
- CELO Screen
- Help Screen

Places we'd like to deep link to for other retention campaigns (not limited to this list):
- Language screen
- dApp marketplace (once live)
- Recovery Phrase

ENG:
- Talk to Jean (the clevertap bindings are annoying)
- Should be possible to deeplink into _most_ screens based on some set of parameters from Clevertap (i.e., we don't need to implement specific deeplink support for every screen)

AC:

Able to deeplink to:
- [ ] Verification Screen
- [ ] CELO Screen
- [ ] Help Screen
- [ ] Language screen
- [ ] dApp marketplace (once live)
- [ ] Recovery Phrase

### Related Issues
Slack thread [here](https://valora-app.slack.com/archives/C025Q9QG8JG/p1639689901163900)
[Notion Ticket](https://www.notion.so/valora-inc/More-deep-link-ability-in-push-notifications-9ca983a5aaec4e8388c895fb21ff189b)

**Comment by laurencedelisle** [comment]
Some additions:
- setup recovery phrase page
- dapp marketplace home screen

**Comment by laurencedelisle** [comment]
Additions:
- KYC page

**Comment by MuckT** [comment]
It looks like these behaviors might already be largely supported in the [existing handleDeepLink generator function]( https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/app/saga.ts#L268-L272).

Some local testing on iOS with the following deep links were working; however, handling the secureOrigin is still a wip.
| Screen | Deeplink |
| ----- | -----  |
| Verification | celo://wallet/openScreen?screen=VerificationEducationScreen |
| Celo Education | celo://wallet/openScreen?screen=GoldEducation |
| Support | celo://wallet/openScreen?screen=Support |
| Language Selection | celo://wallet/openScreen?screen=Language |
| Dapp Marketplace | celo://wallet/openScreen?screen=DAppsExplorerScreen | 
| Recovery Phrase | celo://wallet/openScreen?screen=BackupPhrase | 
| Recovery Phrase Education | celo://wallet/openScreen?screen=BackupIntroduction |
