### ISSUE TITLE
"Rewards" to "Supercharge"

### ISSUE THREAD

**Issue by silasbw** [valora-inc/wallet#1686]
This experiment changes the text “Rewards” (with Celo coins icon) to “Supercharge” (with lightning bolt icon); and replaces the pill with a button.

ENG:
* [Experiment design](https://www.notion.so/valora-inc/Rewards-to-Supercharge-2ff750ad77884ffbb2837c61525e3477)
* Firebase RemoteConfig item that configures the four cohorts.
* The component that holds the icon and text is called `RewardsPill`

AC:
- [ ] Control: Current “Rewards” with coins pill
- [ ] Cohort 0: “Supercharge” with lightning bolt pill
- [ ] Cohort 1: “Rewards” with coins hamburger menu item
- [ ] Cohort 2: “Supercharge” with lightning bolt hamburger menu item

**Comment by silasbw** [comment]
We need icons:
* Large Coins icon
* Small supercharge icon
* Large supercharge icon

@nityarao

**Comment by tinka-peterka** [comment]
https://www.figma.com/file/31HUGhIHLXEm1qwVpHV1QR/?node-id=2428%3A50011

**Comment by silasbw** [comment]
...got a first pass on designs here: https://www.figma.com/file/31HUGhIHLXEm1qwVpHV1QR/CELO-Rewards?node-id=2428%3A50011
