### ISSUE TITLE
Cash In Button A/B testing variant

### ISSUE THREAD

**Issue by lisaqyli** [valora-inc/wallet#1687]
We want to add a variant for cash in button exp where user will be directed to cash in via Ramp. We have the hypothesis that although a large number of users were attracted by the supercharge campaign, they were not converted due to our weak cash in funnel. We also have the hypothesis that the reason why our cash in funnel is weak is because 1) our add fund page has too many options 2) some cash in providers flows are buggy. 

We plan to run an experiment on the cash in bottom sheet where users are directly deep linked to cash in via Ramp with a copy similar to "Cash in $10 via Ramp".

Preliminary Design: https://www.figma.com/file/faNNitxcCO7s7Wl8HY5Bdb/CICO-2.0?node-id=829%3A32874
Experiment Design: https://www.notion.so/Experiment-2-Change-CTA-to-Add-cUSD-cEUR-10-cbb3e82e2c2c4687a3bc7c42defe5cd9

AC:
- [ ] Finalize the design above w/ Nitya
- [ ] Make sure the copy on the design went through content / marketing
- [x] Define experiment proposal
- [ ] set up remote config on Firebase
- [ ] Add Remote config to wallet repo and change the copy
- [ ] Change the deep link for cash in bottom sheet when remote config is enabled

**Comment by jh2oman** [comment]
I really like this idea. Very directly ties into some of our core metrics.

Few questions come to mind quick:
Which view is the “Cash in bottom sheet”?
Any other ideas for where to place the button of the experiment?

**Comment by lisaqyli** [comment]
Nitya, Charlie and I just had a sync on ^ before heading out for holidays:
we agreed on the following:
1. We want to run 2 separate experiments: one on changing the deep link of add funds button to Ramp, the other on changing the copy of the cash in bottom sheet to advertise SuperCharge. Ramp deep link experiment will happen first.
2. Add fund deep link directs to Ramp's exchange page (no cash in flow pages in the middle)
3. We soft agreed on having the prefilled cash in amount to be $10. Amount is subject to change
4. The next steps are: finalizing the design, finalizing the copy, writing an experiment proposal.

Note: we plan to run a quick and inexpensive experiment so let's not spend too much time on this

**Comment by cajubelt** [comment]
next up: offline review (slack feedback)

**Comment by cajubelt** [comment]
should talk a little more about whether to change "add funds with Ramp" to "add funds"
