### ISSUE TITLE
 Text of Providers  in “Add & Withdraw page is not translated after selecting Espanol, Deutsch , Portuguese languages.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1691]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 12(14.7.1), Samsung Galaxy A8+(8), iPhone 13 mini (15.1.1), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.
2. User must have completed the onboarding process.
3. User must be on the Add & Withdraw Page.

**Repro Steps:**
1. Tap on the Add Funds.
2. Select Cello Dollar & Debit Card.
3. Enter the valid amount.
4. Tap on the Next button & observe.

**Current Behavior:** Text of Providers & text of Bidali  in “Add & Withdraw page is not translated  to Espanol language as the user selected language is Espanol.

**Expected Behavior:** Text of Providers & text of Bidali  in the “Add & Withdraw'' page  should be translated to Espanol language as the user selected language is Espanol.

**Observations:**
   - Text below Xanpool & Simplex Providers for Deutsch language. [Bank account => bankrekening], [debit or credit card => bankpas of creditcard]
[Simplex.jpg](https://drive.google.com/file/d/1v6dvpkwatbV17Lm2LsBGhdr4jMNxY-0_/view?usp=sharing ) , [Xanpool.jpg]( https://drive.google.com/file/d/17Bi834U-oIB_wC3xXW2qwEgC5UcLSeos/view?usp=sharing )
- Text below Xanpool & Simplex Providers for Espanol language. [Bank account => cuenta bancaria], [debit or credit card => tarjeta de débito o crédito]
[Simplex.jpg](https://drive.google.com/file/d/1_EP0126dtpN-Sc4uEQUZsaDya5CD7pvz/view?usp=sharing ), [Xanpool.jpg](https://drive.google.com/file/d/1GooJlvCT9kQus77gcw-IJHRmuL09o5US/view?usp=sharing )
- Text below Xanpool & Simplex Providers for Portuguese language.  [Bank account => conta bancária], [debit or credit card=>cartão de débito ou crédito]
[Simplex.jpg](https://drive.google.com/file/d/1odNjo-BqqjDPr-30pGxAef_w35unUQgS/view?usp=sharing ), [Xanpool.jpg](https://drive.google.com/file/d/1RXoZ567aGQDZmco2ddBsk917bSXKzpwe/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@ValoraQA @MuckT these are web views of the different providers' UI and are not available in languages that are not supported by them (only Simplex offers a localized experience for ES only) - it's not possible for us to localize these.

**Comment by ValoraQA** [comment]
Hey @mpgaarciaa, For Simplex provider, whole text under simplex provider option is getting translated only "bank account" text is not getting translated. For Xanpool provider, whole text under xanpool provider option is getting transalted only "debit or credit card" text is not getting translated. Is it expected behavior?
Thanks..!!

**Comment by mpgaarciaa** [comment]
@MuckT the issue here seems to be that the placeholder {{paymentMethod}} retrieves EN only, and the actual keys for this don't show in Crowdin.

**Comment by ValoraQA** [comment]
Hey @MuckT please comment on the above issue whether it is expected or not 
Thanks..!!

**Comment by mpgaarciaa** [comment]
@MuckT I think this issue is no longer necessary since we changed the CICO flow quite a bit, wdyt? if yes, feel free to close
