### ISSUE TITLE
 [Query]  Text of  “Licenses Page” in Settings screen is not translated after selecting Espanol, Deutsch , Portuguese languages.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1692]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 12(14.7.1), Samsung Galaxy A8+(8),  iPhone 13 mini (15.1.1), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.
2. User must have completed the onboarding process.
3. User must be on the Settings Page.

**Repro Steps:**
1. Tap on the Licenses option & observe.

**Current Behavior:** Text of  “Licenses Page” in “Settings  Page” is not translated  to Espanol language as the user selected language is Espanol.

**Expected Behavior:** Text of  “Licenses Page” in “Settings  Page”  should be translated to Espanol language as the user selected language is Espanol.

**Observations:** 
    - Text in the Licenses Page for Deutsch language. [Licences.jpg](https://drive.google.com/file/d/1JyyZsdGzIC42V_FEOwBkj2QbFBPkp6gO/view?usp=sharing )
    - Text in the Licenses Page for Espanol language. [Licences.jpg](https://drive.google.com/file/d/1dXkWUt20VYIclxXW8JIdNuzPyRenGy9b/view?usp=sharing )
    - Text in the Licenses Page for Portuguese language. [Licences.jpg](https://drive.google.com/file/d/10_3p8f1MVOjRSMVdsziNsOpsh5EPc3J4/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@ValoraQA @MuckT this doesn't need to be localized as it doesn't contain Privacy, Data Collection or other user facing legal disclaimers.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thank you very much for the information, We are closing this query as it is expected.
