### ISSUE TITLE
 “Version” text  in “Hamburger Menu ” is not translated after selecting Espanol, Deutsch , Portuguese languages.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1693]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12(14.7.1), Samsung Galaxy A8+(8), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.
2. User must have completed the onboarding process.

**Repro Steps:**
1. Launch the app.
2. Tap on the Hamburger Menu.
3.Scroll till the end of the Menu and observe.

**Current Behavior:** Text of  Recovery Phrase entered into the “Restore Wallet” page is not translated  to Espanol language as the user selected language is Espanol.

**Expected Behavior:**  Text of  Recovery Phrase entered into the “Restore Wallet” page should be translated to Espanol language as the user selected language is Espanol.

**Observations:** 
- Version text in Hamburger Menu  for Deutsch language. [Verison=> Ausführung][Version.jpg](https://drive.google.com/file/d/1fN4HRWu0HB_Sd40vUiY9HF0OZyiFe3KL/view?usp=sharing )
- Version text in Hamburger Menu  for Espanol language.[Verison=> versión]  [Version.jpg](https://drive.google.com/file/d/1fN4HRWu0HB_Sd40vUiY9HF0OZyiFe3KL/view?usp=sharing )
- Version text in Hamburger Menu for Portuguese language. [Verison=>versão]  [Version.jpg](https://drive.google.com/file/d/1z-kqvQ9e0iFZQrRKPFl9Ah0RH-xIDSUQ/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@kathaypacific this related to the PR you just created to fix this issue - tagging you in case you need to close or follow up on this.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Alfajores build V1.24.0 , Test flight Alfajores Build V1.24.0 & observed that "Version" text in hamburger menu is displayed translated for Espanol & Portuguese language, but "Version" text in hamburger menu is not displayed transalted for Deutsch language. Hence we are re-opening the issue.

**Devices:** iPhone 13 mini (15.1.1), Google Pixel 2XL (11.0), iPhone 12 (14.7.1)
**Attachment:** [Deutsch language issue.jpg](https://drive.google.com/file/d/1TyO-KhlIAl_jc0nRZg0EjLetr7ZGgoNG/view?usp=sharing)

Thanks..!!

**Comment by kathaypacific** [comment]
> Hey @MuckT, We have verified this issue using Latest Android Alfajores build V1.24.0 , Test flight Alfajores Build V1.24.0 & observed that "Version" text in hamburger menu is displayed translated for Espanol & Portuguese language, but "Version" text in hamburger menu is not displayed translated for Deutsch language. Hence we are re-opening the issue.
> 
> **Devices:** iPhone 13 mini (15.1.1), Google Pixel 2XL (11.0), iPhone 12 (14.7.1) **Attachment:** [Deutsch language issue.jpg](https://drive.google.com/file/d/1TyO-KhlIAl_jc0nRZg0EjLetr7ZGgoNG/view?usp=sharing)
> 
> Thanks..!!

Hi @ValoraQA please note that although incorrect, the German translation for "version" is currently "version" 🙈 i've attached a screenshot of the code, you can see that the translation file has the locale "de" (german).

![Screenshot 2022-01-06 at 16 13 42](https://user-images.githubusercontent.com/20150449/148404851-731b66c1-4e48-499e-9286-0bf6ac79f661.png)

In this case, the translation functionality is working as expected but the translation itself is wrong. the translation can be changed in Crowdin at any time, so i don't think this is a valid issue anymore.

**Comment by mpgaarciaa** [comment]
Hey @MuckT @kathaypacific @ValoraQA please note this is actually the correct translation into DE, as it's the term used in apps, app store listings and release notes in German across industries. Feel free to close this issue.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thank you very much for the information.
