### ISSUE TITLE
 Text of  Recovery Phrase entered into “Restore Wallet” page is not translated after selecting Espanol, Deutsch , Portuguese languages. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1694]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12(14.7.1), Samsung Galaxy A8+(8), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.
2. User must be on the “Restore wallet” page on restore account flow.

**Repro Steps:**
1.Enter the valid recovery phrase text in the textbox and observe.

**Current Behavior:** Text of  Recovery Phrase entered into the “Restore Wallet” page is not translated  to Espanol language as the user selected language is Espanol.

**Expected Behavior:**  Text of  Recovery Phrase entered into the “Restore Wallet” page should be translated to Espanol language as the user selected language is Espanol.

**Observations:** 
- Text of  Recovery Phrase entered into the Restore Wallet page for Deutsche language. [Recovery phrase in Restore wallet screen.jpg](https://drive.google.com/file/d/1nzE7niTc0kIPsMRVc6c8qGHrfyxu_rD7/view?usp=sharing )
- Text of  Recovery Phrase entered into the Restore Wallet page for Espanol language.[Recovery phrase in Restore wallet screen.jpg](https://drive.google.com/file/d/1p0oJdZH4bQmnCCJTkU5Oc2LQPiLG4rEm/view?usp=sharing )
- Text of  Recovery Phrase entered into the Restore Wallet page for Portuguese language.[Recovery phrase in Restore wallet screen.jpg](https://drive.google.com/file/d/1H3Cyk84qgWXzZTZd9skDRDlf5SZGi4SX/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@ValoraQA @MuckT I don't have access to the screenshots -already requested it. Can you confirm that you're referring to the actual seed phrase? If so, the current behavior is expected, and the Recovery Phrase will always be in the language in which it's first set up, regardless of the language users choose afterward.

**Comment by ValoraQA** [comment]
Hey @mpgaarciaa, we have given access to the requested screenshots.
Thanks..!!

**Comment by mpgaarciaa** [comment]
@MuckT this is a false error - feel free to close.

**Comment by ValoraQA** [comment]
Hey @MuckT, As a user perspective, cannot we have the words of recovery phrase translated in respective languages?
