### ISSUE TITLE
 Text of  "Recovery Phrase" page is not translated after selecting Espanol, Deutsch , Portuguese languages. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1695]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 13 (15.1.1), iPhone 12(14.7.1), Samsung Galaxy A8+(8), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.
2. User must have restored the account.

**Repro Steps:**
1.Launch the app.
2.Tap on Hamburger Menu.
3.Tap on Recovery Phrase option & observe.

**Current Behavior:**Text in the "Recovery Phrase" page is not translated to Espanol language as the user selected language is Espanol.

**Expected Behavior:** Text in the "Recovery Phrase" page should be translated to Espanol language as the user selected language is Espanol.

**Investigation:** Text of Recovery phrase are not translated in Deutsch , Espanol, Portuguese languages while completing the recovery phrase setup flow.

**Observations:** 
-   1. Text in the Recovery Phrase for Deutsch language. [Recovery Phrase.jpg](https://drive.google.com/file/d/1e5bNz4VI7anpStpgQk5knYnveY3gj9WS/view?usp=sharing )
-    2. Text in the Recovery Phrase for Portuguese language. [Recovery Phrase.jpg](https://drive.google.com/file/d/1pDS4eNPq4UfgKSNPMltIwjtaI7bh9l5P/view?usp=sharing )
-   3. Text in the Recovery Phrase for Espanol language. [Recovery Phrase.jpg](https://drive.google.com/file/d/1uswO_ysLo4HLer1Fi2bwICz9Jclu3PLN/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@ValoraQA I don't have access to the screenshots -already requested it. Can you confirm that you're referring to the actual seed phrase? If so, the current behavior is expected, and the Recovery Phrase will always be in the language in which it's first set up, regardless of the language users choose afterward.

**Comment by ValoraQA** [comment]
Hey @mpgaarciaa, we have given access to the requested screenshots.
Thanks..!!

**Comment by mpgaarciaa** [comment]
@MuckT this is a false error - feel free to close.

**Comment by ValoraQA** [comment]
Hey @MuckT, As a user perspective, cannot we have the recovery phrase text translated in respective languages?
