### ISSUE TITLE
“Pin” text in "Create a PIN" page is not translated after selecting Espanol, Deutsch , Portuguese languages.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1696]
**Frequency:** 100%

**Repro on build version:** Test flight Alfajores Nightly build V1.23.0, Android Internal Alfajores Nightly build v.1.23.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12(14.7.1), Samsung Galaxy A8+(8), OnePlus 7T (11)

**Pre-condition:** 
1. User must have selected the Espanol language while opening the application.

**Repro Steps:**
1.Launch the app.
2.Tap on create account and perform flow till create a pin page.
3.Enter a PIN & observe.

**Current Behavior:** “PIN” Text in the Create a Pin page is not seen translated to Espanol language as the user selected language is Espanol. 

**Expected Behavior:** “PIN” Text in the Create a Pin page should be seen in Espanol language.

**Investigation:** “PIN” text in the Enter a Pin page on Send flow, Request flow, Recovery Phrase, Buy CELO, Sell CELO , Withdraw CELO , Change PIN screens is not translated in Deutsch , Espanol, Portuguese languages.

**Observations:** 
- “PIN” text in the Create a Pin page for Deutsche language. [Pin => Stift] [Pin.jpg](https://drive.google.com/file/d/152zvNCMgDDbfWppqYp5pTGjf9Yqs_BfT/view?usp=sharing )
- “PIN” text in the Create a Pin page for Portuguese language. [Pin => alfinete] [Pin.jpg](https://drive.google.com/file/d/1AUcV7fcvaaR4AXzhUYJo_e_zmc0HEE4g/view?usp=sharing )
- “PIN” text in the Create a Pin page for Espanol language. [Pin => alfiler] [Pin.jpg](https://drive.google.com/file/d/1kXD5Plwc3YeDAs9V1x6pkpTdbvj54c2R/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@ValoraQA @MuckT this is actually a **false error, PIN should remain as is across languages** as it's a commonly used term in apps - suggested translations actually refer to "pin" as the metal pin that you use for sowing.

**Comment by mpgaarciaa** [comment]
@MuckT this is a false error - feel free to close.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thanks for the information. We are considering this behavior as expected behavior.
