### ISSUE TITLE
Use DEK from geth wallet instead of redux everywhere

### ISSUE THREAD

**Issue by isabellewei** [valora-inc/wallet#17]
### Expected Behavior

When the DEK is used in the app, it should be from the native geth wallet instead of the redux store. Also consider securing the DEK with a passphrase

### Current Behavior

Currently we only do this for uploading and downloading profile info, but not other DEK functions (ex. comment encryption). Currently the passphrase is an empty string

**Comment by lisaqyli** [comment]
DEK - data encryption key, dataEncryptionKey.ts

1. delete dataEncryptionKey from State in web3/reducer.ts
2. fix all type errors
3. switch to use getWallet to get the encryption key
getWallet example:  profileInfo.ts
