### ISSUE TITLE
 [Query]  Extra “,” comma  is displayed in the title of the third walkthrough screen when user navigates to third walkthrough screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1707]
**Frequency:** 100%

**Repro on build version:** Appstore build V1.23.3, Android internal build V1.23.3
**Repro on devices:** iPhone 13 mini (15.1.1), Google pixel XL (10.0)

**Pre-condition:** 
1. User must have installed the application.
2. User must be on second walkthrough screen “with valora, it’s easy..” title.

**Repro Steps:**
1. Tap on “Next” button from the second walkthrough screen & observe.

**Current Behavior:** Extra “,” comma  is displayed in the title of the third walkthrough screen 

**Expected Behavior:** Extra “,” comma  must not be displayed in the title of the third walkthrough screen .

**Impact:** Bad user impact.

**Attachment:** [Extra comma.jpg](https://drive.google.com/file/d/1si3F45iP2jADMLcLaY_xd_xOo0XETrZ_/view?usp=sharing )

**Comment by mpgaarciaa** [comment]
@MuckT @ValoraQA this is actually not an error, the oxford comma is pretty common in English and don't think it impacts readability or trust for our users. Maybe check in with Lukas though?

In any case, localized languages are correct,  no changes needed there.

**Comment by ValoraQA** [comment]
Hey @MuckT, thank you very much for the information.
