### ISSUE TITLE
 [Query] User A is receiving cUSD or cEUR amount from User B when User A request CELO from User B & user B completes send flow from the CELO request CTA by tapping on Send button from the same CTA.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1718]
**Frequency:** 100%

**Repro on build version:** Test flight nightly build V1.24.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1)

**Pre-condition:**
1. User A & B must have installed the app and completed on boarding flow 
2. User B must have valid CELO balance.
3. User A must be on enter amount page in request flow.

**Repro Steps:**
1. For User A:Tap & Open “Select Token” popup from top RHS.
2. For User A: Select CELO option from “Select token” popup
3. For User A: Enter valid amount and complete the request flow.
4. For User B: Tap on “Send” button from CELO request CTA & complete the send flow.
5. For User A: Wait for some time & observe.

**Current Behavior:**   User A is receiving cUSD or cEUR amount from User B when User A request CELO from User B & user B completes send flow from the CELO request CTA

**Expected Behavior:**   User A must  receive CELO  from User B when User A request CELO from User B & user B completes send flow from the CELO request CTA

**Investigation:** This issue cannot be checked in android platform because, for android platform “Select token” drop down on enter amount page in request flow is not displayed in Android Nightly build V1.24.0 

**Impact:** Bad User experience, as User A after requesting CELO for User B, receives cUSD or cEUR amount, when user B sent the amount.

**Attachment:** 
[CELO request issue.mp4](https://drive.google.com/file/d/1yEAAKFw7-o-_EeJMAMmeBwIiCT2r5GP5/view?usp=sharing) 
[User A payment received.jpg](https://drive.google.com/file/d/1kUbgk7W-ZcF4s-FNFq53ZDrc-ZEr_xH_/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this is an issue with the remote config. CELO should not be listed as a core token and as such users should not be able to request payment in CELO. I'll update the remote config on Alfajores, please retest when able.

> This issue cannot be checked in android platform because, for android platform “Select token” drop down on enter amount page in request flow is not displayed in Android Nightly build V1.24.0

This sounds like a separate issue and should be filed.

**Comment by MuckT** [comment]
@ValoraQA FYI the remote config in Alfajores has not been updated yet, so this issue will still be present.

**Comment by ValoraQA** [comment]
Hey @MuckT thanks for the information, also we will raise separate ticket for the Android Platform wherein "select token" drop down is not seen

**Comment by ellenwoconnor** [comment]
Feature request for the request flow

**Comment by ellenwoconnor** [comment]
Unclear whether we still want request feature, if we do then we should think about this scenario
