### ISSUE TITLE
  “Estimated fees” changes automatically on “Sending” screen when user taps on “Send” button for completing sending flow. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1727]
**Frequency:** 100%

**Repro on build version:** Android Alfajores Nightly V1.24.0,  iOS test flight Alfajores Nighlty V1.24.0
**Repro on devices:** Google Pixel 2XL (11.0), Google Pixel XL (10.0),  iPhone 12 (14.7.1), iPhone 13 mini (15.1.1)

**Pre-condition:** 
1. User must have installed the app & complete onboarding flow.
2. User must have valid balance
3. User must be on Sending screen on sending flow

**Repro Steps:**
1. Tap on “Send” Button on send screen & observe

**Current Behavior:**  “Estimated fees” changes automatically on “Sending” screen when user taps on “Send” button for completing sending flow.  

**Expected Behavior:**  “Estimated fees” should not change  automatically on “Sending” screen when user taps on “Send” button for completing sending flow. 

**Investigation:** This issue is reproducible for iOS platform when user send cEUR currency. 

**Impact:** Bad user experience.

**Attachment:** [EstimateChnages.mp4](https://drive.google.com/file/d/1FcOaNFbe0VTEhOhlPWmfWR-YZ30e1oLk/view?usp=sharing)

**Comment by MuckT** [comment]
@gnardini have you seen this behavior before?

**Comment by gnardini** [comment]
I haven't, this is really weird 🤔 
Looking at the code I found other stuff which looks wrong (I'll open up a PR for it), but nothing that would explain this. I also couldn't reproduce the error locally. Is this reproducible 100% of the time for you @ValoraQA ? Can you try to reproduce as well @MuckT ?

**Comment by gnardini** [comment]
Accctually, it might be related. The fee currency was being chosen somewhat randomly, so updating the token balance might have changed the currency used and there was a bug when using a non cUSD token currency. I'd appreciate if you could give another test at this after the fix I'm about to put out

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified this issue on Android Alfajores Build V: 1.24.0 and iOS Alfajores Build V:1.24.0 and observed that issue is still reproducible.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the issue on latest Android Internal Build V:1.24.1 and latest iOS Test Flight build V:.1.24.1 and observed that issue is fixed  

**Observation :** Estimated fees amount is not changing after clicking on sending button from send amount page 
**Devices :** iPhone 12(14.7.1) , Google Pixel (11.0)

**Attachment :** [amount_not_changing.mp4](https://drive.google.com/file/d/17uZxIA-IH9MggzvrH3eOW-wq-YPP-Mre/view?usp=sharing)

CC: @gnardini
