### ISSUE TITLE
Add support for paying fees cReal

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1747]
cReal is the new 'core' stable coin that was launched recently by cLabs. It is pegged 1:1 to fiat currency Brazilian Real.
Native in this context means that it is possible to pay transaction fees in cReal in te same way as cEUR, cUSD, CELO.

While the token is supported by Valora out of the box, paying transaction fees in cReal requires additional development.

Celo foundation will do a marketing push for cReal at the end of January. If we will have full support for cReal, we can piggy back on their marketing campaigns and gain some additional traction in the market that is already second biggest for Valora.

Eng notes:
- Looks like we just need to add cREAL to the CURRENCIES list on `src/utils/currencies.ts` but that may cause other changes that need taken care of.

AC:
- [ ] It is possible to pay transaction fee in cREAL.
- [ ] Document engineering process for a adding support for new stable coins (i.e., so that an external contributor could easily do it)

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our comment in the ticket #1835
