### ISSUE TITLE
Clean up cash in bottom sheet V1 remote configs

### ISSUE THREAD

**Issue by lisaqyli** [valora-inc/wallet#1753]
Cash in bottom sheet V1 has been fully rolled out. We need to clean up the experiment

AC:
- [ ] Move the config of which regions cash in bottom sheet should be shown from firebase to wallet codebase
- [ ] cashInButtonExpEnabled is deleted from firebase console and the wallet client no longer fetches the value of cashInButtonExpEnabled from firebase

**Comment by cajubelt** [comment]
delaying this until we've been able to discuss feature flag retirement in general
