### ISSUE TITLE
 “Send “ and “Request” buttons on Home screen are not enabled while creating an account when phone number confirmation is skipped.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1757]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.24.0, Test Flight Build V1.24.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Samsung Galaxy A8+(8.0), One plus 7t(11.0), Google Pixel 2XL(11.0), iPhone 6+(12.5.4)

**Does Not Repro on build version:** Android Play store Build V1.23.3, Android internal build  V 1.24.0,  Test flight Build V1.23.3, V1.24.0
**Does Not Repro on devices:** One plus 7t(11.0), Google Pixel 2XL(11.0), iPhone 13 mini (15.1.1),  iPhone 6+(12.5.4)

**Pre-condition:** 

  1. User must have installed the app.
  2. User must be on the Phone Number Screen while creating a new account.

**Repro Steps:**

 1. Tap on the “Skip” button from the top right corner from the “Phone number screen”.
 2. Tap on the “Skip for now” button from “Are you sure?” popup.
 3. User navigates to the home screen & observe.

**Current Behavior:** “Send” and “Request” buttons on the Home screen are not enabled while creating an account when phone number confirmation is skipped.  

**Expected Behavior:** “Send” and “Request” buttons on the Home screen must get enabled while creating an account when phone number confirmation is skipped. 

**Investigation:** 

 1. While creating an account by confirming the  phone number,  “Send” and “Request” buttons are not enabled.
 2. “QR code” button besides the Request button appears enabled but is not tappable.
 3. This issue is not reproducible while the user restores an account having some account balance.
 
**Impact:** Bad user experience as the user is not able to tap on the Send and request button after creating a new account.

**Attachment:** [Send and receive button.mp4](https://drive.google.com/file/d/1osz_msUktakZuOc2ALQzUR3g9QHxDHgT/view?usp=sharing )

**Comment by gnardini** [comment]
This is on purpose for sending since you can't send if you have no balance. Requesting should work though

**Comment by ValoraQA** [comment]
Hey @MuckT, Thanks for the information.

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our observation in the ticket #1809
