### ISSUE TITLE
[Query] How to connect on"mento.finance" site if user visits the link via Desktop / Mweb as there is no option of "Wallet connect"

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1760]
**Frequency**: 100%
**Repro on build version**: Android Internal build V:1.24.0 ,iOS TestFlight build V:1.24.0
**Repro on device** : OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1),  iPhone 13mini(15.1.1), Google Pixel 10XL(10.0)

**Pre-condition:**
1] User must have installed the application
2] User must have completed onboarding process
3] User must have some balance in the account
4] User must be on settings page 

**Repro Steps:**
1] Open "mento.finance" link in Desktop / mWeb
2] Click on connect a wallet

**Current Behavior:** we get to see only : Ledger , Install MetaMask , Install Celo Extension Wallet

**Expected Behavior:** There is no option to connect a valora wallet to the link

**Investigation:**
- ON Mweb there is no option to connect the valora wallet to the given link

**Attachments :** [Desktop.jpg](https://drive.google.com/file/d/1f5XqU49MUjhbqcanAzudeRZHFuJxFK3Z/view?usp=sharing) 
[mweb.mp4](https://drive.google.com/file/d/13_OIO7e3FB8UD_skC8auknuN1i0K1pzL/view?usp=sharing)

**Comment by gnardini** [comment]
No way to connect mento.finance to Valora right now. If you need cREAL the way to do it is using MetaMask and sending the cREAL back to your Valora account :/

**Comment by jmrossy** [comment]
@ValoraQA You can test mento-fi with the pre-release version here:
https://mento-fi-q5d61619k-celotools.vercel.app/

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the issue on Latest Android Internal Release build and Latest iOS Test Flight Internal Build V:1.24.1 and observed that we are able to swap tokens on "https://mento-fi-q5d61619k-celotools.vercel.app/"
We have also commented on the ticket : #1729
