### ISSUE TITLE
Update copy in Activity feed to be more Supercharge-focused

### ISSUE THREAD

**Issue by hdenisse** [valora-inc/wallet#1768]
### Description
Each week users receive supercharge rewards which are shown in their activity feed and push notifications as CELO Rewards received. We want to update the copy to be more Supercharge-focused

### User Stories 
As a Valora user, I want to clearly connect rewards to the supercharge program so I know what I'm participating.

## Change request
Current:
Sender: Celo Network
Comment: Weekly Rewards
Logo: Celo icon

Update to:
Sender: Supercharge
Comment: Weekly Rewards
Logo: Supercharge bolt icon

Not sure what the copy is in the push notification but it should also be updated please!

**Comment by kathaypacific** [comment]
Closing for backlog spring clean May 2022
