### ISSUE TITLE
[Query] Will "cREAL" to be seen in the "select token" pop up while sending the money to another user 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1770]
**Frequency**: 100%
**Repro on build version**: Android Internal build V:1.24.0 ,iOS TestFlight build V:1.24.0 , Android Internal build V:1.24.1 ,iOS TestFlight build V:1.24.1 
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1), iPhone 13mini(15.1.1), Google Pixel 10XL(10.0)

**Pre-condition:**
1] User must have installed the application
2] User must have completed onboarding process
3] User must have cUSD / cEUR / CELO balance in the account
 
**Repro Steps:**
1] Tap on send button from home screen
2] Select a contact and go to enter amount page
3] tap on the "select token" dropdown and observe

**Current Behavior:** We get to see cUSD /cEUR /CELO /TT in the dropdown pop up 

**Expected Behavior:** cREAL should also be seen in send flow along with other tokens 

**Investigation:**
- On request flow cREAL is seen even though balance is $0.00 and user is able to select it
- after user B has requested cREAL then on User A send amount page will cREAL to be seen along with cUSD and cEUR 

**Attachments** : [cREAL.mp4](https://drive.google.com/file/d/14FIcv3h-ZC4ZALqgePGsnB5RMM8BTx_q/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA cREAL should be included in the list now as the associated backend work has been completed. Please retest on. v1.25.2.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above query on Latest Android Internal release build V:1.25.2 and latest iOS testflight release build V:1.25.2 and observed that cREAL is not seen after clicking on the "edit link" to select the token for sending the amount 

**Observation :** 
-Only cUSD and cEUR tokens is seen in the pop up appearing even though user has cREAL token balance 
- cREAL Token are not seen in both flows ,new request arrived and for existing request , when user clicks on send button from inAPP CTA

**Attachment :** [cREAL](https://drive.google.com/file/d/1JIxFeTobfK94Vx8z4g5o9qAEj0ucosxd/view?usp=sharing)

**Devices :** OnePlus 7T(11.0), iPhone 12(14.7.1) , Google Pixel (11.0)
