### ISSUE TITLE
“Purchased CELO" activity is showing in the recent tab on home screen instead of Sold CELO activity when the user sells the CELO and activity gets completed.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1773]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.24.1, Test Flight Build V1.24.1, V1.24.0
**Repro on devices:** iPhone 13 mini (15.1.1), Samsung Galaxy A8+(8.0), iPhone 6+(12.5.4),Google Pixel XL(10.0), iPhone 12 (14.7.1)

**Does Not Repro on build version:** Android Play store Build V1.23.3,  Test flight Build V1.23.3
**Does Not Repro on devices:** Google Pixel 2XL(11.0), iPhone 13 mini (15.1.1),  iPhone 6+(12.5.4), Samsung Galaxy A8+(8.0)

**Pre-condition:** 

  1. User must have installed the application and have completed the onboarding flow .
  2. User must have some amount of CELO balance in their account.
 
**Repro Steps:**

 1. Tap on “CELO” from Hamburger menu.
 2. Tap on the “SELL” button.
 3. Enter a valid amount & complete the sell CELO flow.
 4. Sold CELO confirming activity appears in CELO screen 
 5. Open the Home screen and observe the activity in recent activity.
 
**Current Behavior:** “Purchased CELO” activity is showing in recent tab on home screen when user sell the CELO

**Expected Behavior:**  “Sold CELO” activity must be seen in recent tab on home screen when user sell the CELO

**Investigation:**  After the CELO is sold the purchased activity changes  to “Sold CELO” activity.

**Impact:** Bad user experience

**Attachment:** [Sell CELO.mp4](https://drive.google.com/file/d/1AZAQEJPTZy3WDRiLQZLKo-e1piTE8Bhf/view?usp=sharing )

**Comment by ellenwoconnor** [comment]
No longer relevant w/ in app swaps
