### ISSUE TITLE
 Valora Nightly & Valora Alfajores nightly build crashes when user opens the application after installing the application

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1789]
**Frequency:** 100%

**Repro on build version:** Android Nightly V1.24.0, Android Alfa jores Nightly V1.24.0
**Repro on devices:** Google Pixel XL (10.0), Google Pixel 2XL (11.0), One Plus 7T(11.0), Samsung Galaxy m40 (10.0)

**Does Not Repro on build version:** iOS Testflight Nightly V1.24.0, iOS Testflight Alfa jores Nightly V1.24.0
**Does Not Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1)

**Pre-condition:** 
1. User must have installed the app.

**Repro Steps:**
1. Open the app by tapping on app icon & observe.

**Current Behavior:**  Valora Nightly & Valora Alfajores nightly build crashes when user opens the application after installing the application 

**Expected Behavior:**  Valora Nightly & Valora Alfajores nightly build must not crashe when user opens the application after installing the application 

**Investigation:** This issue is not reproducible for iOS platform.

**Impact:** Bad user experience as user will be blocked to open the application.

**Attachment:** [Android App crashing.mp4](https://drive.google.com/file/d/1IeM7SEvW2Ht5OwUlp85084Pp1l2F_IEp/view?usp=sharing)

[Crash logs](https://drive.google.com/file/d/1GahWT0bfZXkboPO3fvk5BpihkWnbu2ia/view?usp=sharing )

**Comment by MuckT** [comment]
@ValoraQA just to confirm this is occurring on nightly builds and not the 1.24.1 release correct?

**Comment by ValoraQA** [comment]
Hey @MuckT, Yes the crash issue is not reproducible for Android Internal Build V1.24.1 & application is crashing for Valora Nightly V1.24.0 & Valora Alfajores Nightly V1.24.0 only.

**Comment by MuckT** [comment]
@ValoraQA can you please retest on the most recent nightly build?

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Nightly Build V1.24.0, Alfa jores Nightly Build V1.24.0 & observed that this issue is fixed now. Application is not crashing on app launch after installing the app on android platfrom.

**Devices:** Google Pixel XL (10.0), Samsung Galaxy A8+ (8.0)
**Attachment:** [Nightly Builds Not Crashing.mp4](https://drive.google.com/file/d/1J6hBdYo-6i9bQGWmkZzPUJxjSlE_hlk3/view?usp=sharing)
Thanks..!!
