### ISSUE TITLE
 “Step 1 of ” text appears instead of “Step 1 of 3” for Create account screens when user navigates through steps screens of create account flow

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1796]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.24.1, Android Play store Build V1.23.3, Test flight build V1.24.1, V1.24.0, 1.23.3
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Samsung Galaxy A8+(8.0), Google Pixel 2XL (11.0) 

**Pre-condition:** 
1. User must have installed the application.
2. User must be on “Step into the future of crypto with valora” screen

**Repro Steps:**
1. Tap on “Create new account”, tap on “Accept” button & observe.
2. Tap on “Next” button after entering valid name & observe.
3. Enter valid PIN twice & observe.

**Current Behavior:**  “Step 1 of ” text appears instead of “Step 1 of 3” for Create account screens when user navigates through  steps screens of create account flow

**Expected Behavior:** “Step 1 of 3” text must appear for Create account screens when user navigates through  steps screens of create account flow

**Investigation:** This issue is reproducible for restore account steps screens also

**Impact:** Bad user impact.

**Attachment:** 
[Create Account steps issue.mp4](https://drive.google.com/file/d/16zL3UHCbs5MteRcDLGdalOPH82hcs19c/view?usp=sharing )
[Restore Account Steps issue.mp4](https://drive.google.com/file/d/10CMsre1EecUXlPMsfcr_FDOHkMB4cPv_/view?usp=sharing )

**Comment by MuckT** [comment]
@gnardini I also cannot reproduce the issue. @ValoraQA can we get a retest on todays nightly build?

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue using Latest Android Nightly Build V1.24.0, Test flight Nightly Build V1.24.0 (1642431291) & observed that issue is not Reproducible.
**Note:**  We have re-verified this issue using Latest Android Internal Build V1.24.1, Test flight Build V1.24.1 & observed that the issue is still reproducible for both platforms

**Devices:** Google Pixel XL (10.0), iPhone 13 mini (15.1.1)
**Attachments:** 
[Nightly Create account.jpg](https://drive.google.com/file/d/1IQgj82f3r5HGlhoscP5fGCGlUH1HBaKL/view?usp=sharing)
[Nightly Restore Account.jpg](https://drive.google.com/file/d/19V845ob6I0HbVnnG14_PO0TTtODrDEnz/view?usp=sharing)
CC: @gnardini 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue using Latest Android Internal Release Build V1.25.1, Test flight Release Build V1.25.1 & observed that the issue is fixed. "Step 1 of 3" text appears for create account screens when user navigates through steps screens of create account flow. 
Hence we are closing this issue.

**Devices:** iPhone 13 mini (15.1.1), Google pixel 2XL(11.0), iPhone 12 (14.7.1), Google Pixel XL (10.0), iPhone 7 (13.3)

**Attachments:** 
[Create Account Flow.jpg](https://drive.google.com/file/d/1IQgj82f3r5HGlhoscP5fGCGlUH1HBaKL/view?usp=sharing)
[Restore Account Flow.jpg](https://drive.google.com/file/d/19V845ob6I0HbVnnG14_PO0TTtODrDEnz/view?usp=sharing)
Thanks..!!
