### ISSUE TITLE
New requests should display at top when the user taps on the “View All” button from “# Pending requests” screen.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#180]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.12.1(1004294341),  Test flight build V1.12.1(50
**Repro on devices:** Samsung M40 (10.0), Samsung Galaxy A5(7.0),  iPhone XR (14.2),  iPhone 6+ (12.4.5)
**Tested Account:**  (680) 208 0265 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B66)

**Pre-condition:** User B should have many requests in lists (5+ requests)
 **Repro Steps:**
1. Launch the application & login with a test account.
2. Send request to user B from user A
3. Now go to user B’s “# Pending Requests” In-app CTA & tap on “View All” button
4. Observed that,
**Current Behavior:** Latest request’s position is not at top of all list 
**Expected Behavior:**  Either nothing should display or the “Confirming” page should open until the transaction does not complete successfully when the user taps on Confirming activity.
**Impact:** Bad User experience.
**Attachment:** [NewRequestPosition.mp4](https://drive.google.com/file/d/1sf1Zoa9SyUpZ9C8cb2beYMguhFizTNlH/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @jeanregisser I have verified this issue using latest Appstore build V1.15.2 & Android Internal Build V1.15.2 and found issue is still repro.
- New requests should display at top when the user taps on the “View All” button from “# Pending requests” screen
Verified on Devices: iPhone SE 1st Generation(14.6), Redmi Note 8 (10.0)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest iOS Test Flight Release build and Android Internal release build V 1.41.0  and observed that issue is fixed

Observation: Latest request is seen on the top of the requested amount list 

Attachment : [request.mp4](https://drive.google.com/file/d/1pitQ5EdJq1GDX7OFH5hU1yBqaF12kRam/view?usp=sharing)

Device : Google Pixel 2XL(11.0), iPhone 12(14.7.1)

Thanks.!
