### ISSUE TITLE
Add pagination in the new TransactionFeed.

### ISSUE THREAD

**Issue by dievazqu** [valora-inc/wallet#1808]
The current status is that the blockchain-api returns the first 100 transactions when a user requests the feed. So, we need to add pagination, to allow the user to see more than 100 transactions.

In order to do it, we need to start using the pagination of blockscout (see the docs at https://explorer.celo.org/graphiql), and add pagination to our endpoint (tokenTransactionsV2).

Then we need to start consuming the endpoint with pagination from the app. (Should we do this in another issue?)

**Comment by MuckT** [comment]
@dievazqu would this be an infinite scroll so that when we reach the bottom of near the bottom, say 80th, of the first 100 transactions we fetch the next 100?

**Comment by dievazqu** [comment]
@MuckT I think it would be nice to have some feedback from product team (maybe @aleksey-nov?). But I think we should assume that the list has to be an infinite scroll. If we can start fetching the next 100 while scrolling in the current transactions, it would be awesome. Another option, would be to fetch the next batch if we reach the bottom of the list (if that makes the implementation simpler).

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our observations in the PR #2251 
Thanks..!
cc: @dievazqu
