### ISSUE TITLE
User should redirect to the Home screen when the user taps on “Done” button from the “Bidali” screen.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#181]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.12.1(1004294341),  Test flight build V1.12.1(50
**Repro on devices:** Samsung M40 (10.0), Samsung Galaxy A5(7.0),  iPhone XR (14.2),  iPhone 6+ (12.4.5)
**Tested Account:**  (715) 575 8688 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B12)

**Pre-condition:** Users should redirect to Bidali screen from In-app CTA.
**Repro Steps:**
1. Launch the application & login with a test account.
2. Now go to Bidali notification “Now Available” with the Buy Now & Dismiss button.
3. Now tap on the “Buy Now” button.
4. Now the user should be on the “Bidali” screen.
5. Now tap on the “Done” button on the top left corner.
6. Observed that, 
**Current Behavior:** User redirect to “Add and Withdraw” landing screen.
**Expected Behavior:**  Users should redirect to Home screen as the user travelled Bidali using In-app CTA.
**Impact:** Bad User experience.
**Attachment:**
[UserShouldRedirectToHomeScreen.mp4](https://drive.google.com/file/d/1v30saA_h2YvDG205E-0Lfhc_uLWNJL39/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi, We have verified this issue using latest Playstore build V1.15.2 & Appstore build V1.15.2 & observed that issue is still reproduced.
**Verified On Devices:** iPhone SE 1st Generation (14.6), Redmi Note 8 (10.0)
