### ISSUE TITLE
Enable Editing of Default Remote Configs from Settings

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1817]
### Description
Adding menu item under developer settings that allows the editing of remote config default values on a local device. This does not change the remote config values in Firebase, but allows a user to edit local default the remote config values.

### User Stories 
- As a developer or tester, I want to be able to adjust the default configs so that I can accurately features.
- As a developer or tester, I want to be able to opt in or out of A/B testing experiments so that I can accurately test in both cases.

### Acceptance Criteria
- [ ] From developer settings a user should be able to to opt in and out of experiments.
- [ ] From developer settings a user should be able to toggle default remote configs that are boolean values.
- [ ] From developer settings a user should be able to enable / disable fetching of remote configs.
- [ ] Form developer settings a user should be able to reset remote configs to the default values.
- [ ] From developer settings a user should be able to edit values stored in JSON.
- [ ] From developer settings a user should be able to view all currently set remote config values, possibly as a JSON, for easier collaboration in triage and debugging.

**Comment by MuckT** [comment]
@ValoraQA can you take a look at this and see if it there are acceptance criteria that are missing from this feature that would aid in testing?

**Comment by ValoraQA** [comment]
Hey @MuckT, Thanks you very much for the user stories & acceptance criteria, We are reviewing and will get back to you if any update needed.
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT, We have gone through all the acceptance criteria, it looks good & below mentioned are our acceptance criteria feedback: 

-  As Developer / QA able to search the remote configs/feature flags from Search bar. 

- As Developer / QA should be able enable/disable feature flags for whole component. 
Suggestion : We should have component wise feature flags so if we need to enable / Disable feature flag for whole component then we can do it. 

- As Developer / QA check that feature flags name must be relevant to feature name & unique.

Can you please check & provide your feedback for the same. 

Thanks..!!

**Comment by ellenwoconnor** [comment]
This seems like it will be covered by https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/2162. Can you take a look and let me know whether there remain gaps?

**Comment by MuckT** [comment]
#2162 captures the requirements well with two caveats:
- We should use a more accessible friendly gesture e.g. five taps in quick succession.
-  We should button have a way to reset all the remote configs to default values.

**Comment by kathaypacific** [comment]
Since #2162 covers the requirements, I will close this ticket. Sorry @MuckT i didn't realise this ticket already existed when we created 2162!
