### ISSUE TITLE
“Your Name and Picture Saved Successfully” message displayed even if the user updated only profile name from Settings.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#182]
**Frequency:** 100%
**Repro on Devices:** Samsung M40 (10.0), Samsung Galaxy A5(7.0),  iPhone XR (14.2),  iPhone 6+ (12.4.5)
**Repro version :** Android Internal Build V1.12.1(1004294341),  Test flight build V1.12.1(50
**Login credential :** 515 444 0200 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)
**Repro Steps:**
1. Launch the application & login with test account.
2. Now go to Settings & tap on “Edit Profile” option.
3. Now change only profile Name & tap on “Save” button.
4. Observed that,  “Your Name and Picture Saved Successfully” displayed even user not make changes in profile picture.
**Query :** Relevant message related to changes should display
**Attachment:** [MessageShouldBeRelevant.mp4](https://drive.google.com/file/d/11dtmvImHK-wdtXSQU4Kv2hinXP_xEctg/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi, We have verified this issue using latest Playstore build V1.15.2, Appstore build V1.15.2 & observed that issue is still reproduced.
**Verified On Devices:** iPhone SE 1st Generation (14.6), Redmi Note 8 (10.0)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D126](https://valora.testquality.com/project/12128/result/2471227/defect/8212).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D141](https://valora.testquality.com/project/12128/result/2485912/defect/8261).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D281](https://valora.testquality.com/project/12128/result/2525038/defect/8487).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D454](https://valora.testquality.com/project/12128/result/2545813/defect/8764).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D652](https://valora.testquality.com/project/12128/result/2574000/defect/9273).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D656](https://valora.testquality.com/project/12128/result/2574037/defect/9277).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D788](https://valora.testquality.com/project/12128/result/2590808/defect/9456).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D895](https://valora.testquality.com/project/12128/result/2615534/defect/9702).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D899](https://valora.testquality.com/project/12128/result/2612829/defect/9712).
