### ISSUE TITLE
New Dapps section

### ISSUE THREAD

**Issue by silasbw** [valora-inc/wallet#1827]
ENG:
- https://www.figma.com/file/zdK8XvxNXvTjxnM5V33pHw/Dapps-Page?node-id=1479%3A37798

AC:
- [ ] New Dapps section shows at the top of the Dapps Explorer
- [ ] Behind a feature flag that is a list/array of categories to show by ID (show all existing categories except for 'new dapps')
- [ ] Tapping on a dapp records analytics
  - [ ] Wallet Address
  - [ ] Geo / IP
  - [ ] Language
  - [ ] dapp category ID (if too cumbersone consider cutting)
  - [ ] dapp ID
  - [ ] ability to distinguish from taps to same dapp in other sections
  - [ ] order in horizontal (will always be zero for _now_)
- [ ] Impressions records (when you open Dapp Page)
  - [ ] Wallet Address
  - [ ] Geo / IP
  - [ ] Language
  - [ ] dapp category ID
  - [ ] dapp ID

**Comment by nityarao** [comment]
I can't seem to edit! But here's the figma link-- 

https://www.figma.com/file/zdK8XvxNXvTjxnM5V33pHw/Dapps-Page?node-id=1403%3A50832
