### ISSUE TITLE
Daily price change on the TokenList screen

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1840]
[Experiment proposal
](https://www.notion.so/valora-inc/Daily-changes-in-token-prices-on-the-Token-List-screen-6e228ab5728f4f43a34d4bdd9b88f171)
[Design](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1713%3A60226)

AC:
- [ ] The daily price changes are displayed on TokenList screen;

- [ ] Experiment is setup in firebase

**Comment by nityarao** [comment]
Just added updated figma link to this
