### ISSUE TITLE
M1: Query ODIS and encrypt mnemonic

### ISSUE THREAD

**Issue by lisaqyli** [valora-inc/wallet#1846]
Valora will use the user chosen PIN and a locally generated salt value to query ODIS. The resulting hardened key will be used to encrypt the account key mnemonic.

AC: 
- [ ] PIN and a locally generated salt value will be used query ODIS
- [ ] The return value is used to encrypt mnemonic
- [ ] also able to decrypt mnemonic

**Comment by cajubelt** [comment]
TODO add details on how decryption works

**Comment by cajubelt** [comment]
TODO link to docs
