### ISSUE TITLE
[M2] Avoid allowing user to connect bank account before Finclusive KYC complete

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1873]
As an end-user, I need to be able to connect my bank account with Plaid (step 2 in the "link bank account" UI) ONLY once it's possible to do so, i.e. once my Finclusive compliance check has completed.

One way we could do this:
- upon finishing the Persona flow and navigating back to the link bank account screen, query IHL for the user's finclusive compliance check status
- if pending, set a timeout to query again in a few seconds and show the "pending" status in the meantime
- do this for every subsequent visit to the link bank account screen (just try twice... we probly don't need continuous polling since if it isn't done in a few seconds, it's probly held up for manual review)

AC:
- step 2 visible in link bank account flow only once Finclusive KYC is complete
- Settings screen also updated
- Finclusive KYC rejected case is handled
- the UI is still reasonably responsive (doesn't require app restart to update, for instance)

Notes:
- Could do this polling from IHL or a cron job (like, while user is in pending finclusive state query every N minutes)

**Comment by ValoraQA** [comment]
Hey @MuckT we have commented our observations in #2059 
CC : @cajubelt 

Thanks.!!
