### ISSUE TITLE
Amount is not getting reset to '0' when user selects other token from the dropdown on enter amount page.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1880]
**Frequency**: 100%

**Repro on build version:** Android Internal build V:1.25.0 ,iOS TestFlight build V:1.25.0
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1), iPhone 13mini(15.1.1)

**Pre-condition:**
1] User must have installed the application
2] User must have completed on boarding flow 
3] User must have multiple token balance in the account 
 
**Repro Steps:**
1] Tap on send button from homepage and select a contact / enter address / scan QR code of another user 
2] It redirects to enter amount page
3] Enter a valid amount in the amount field 
4] Tap on dropdown from RHS corner of the page and select other token 
5] Observe the amount field

**Bug :** The amount is not getting reset to 0 on selcting other token from dropdown.

**Expected Behavior**: If user has entered '1' in amount field and selects other token then it should change to '0'

**Observation :**
- For Single token there is back button to change amount to 0 on long press and also there is no dropdown to select other token

**Attachments :** [reset.mp4](https://drive.google.com/file/d/1E7qWmr-d1lh_zNyzkJsJWiHh1HOmbWdK/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this will be fixed in 1.26.x by https://github.com/valora-inc/wallet/pull/1925.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue on latest Android Internal release build V:1.27.0 and latest iOS testflight release build V:1.27.0 and observed that amount is getting reset to '0' when user selects other token from the dropdown on enter amount page. Hence we are closing this issue.


**Attachment:** [Reset.mp4](https://drive.google.com/file/d/1dy4HbfE3oCrHyBPqyvQwWfBJwfdey6ff/view?usp=sharing)

**Devices:**  iPhone 13 mini(15.1.1), Redmi Note 7 Pro(10.0), iPhone 6+(12.5.5)

Thanks..!!
