### ISSUE TITLE
“Sushi swap” dapp name is not displayed in connection prompt in Valora app when user tries to connect the sushi swap to valora app

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1889]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.25.1, iOS Test flight Release build V1.25.1
**Repro on devices:** iPhone 13 mini (15.1.1), Google Pixel 2XL(11.0), One plus 7T(11.0), iPhone XR(14.6)

**Pre-condition:** 
1. User must have installed the app & completed on boarding flow.
2. User must have opened https://app.sushi.com/swap in web browser.

**Repro Steps:**
1.Tap on Connect to wallet button from web page.
2. Select Wallet Connect button.
3. Select “Valora” option from “Choose your Preferred Wallet” popup & observe when user redirects to valora app.

**Bug:**  “Sushi swap” dapp name is not displayed in connection prompt in Valora app when user tries to connect the sushi swap to valora app

**Expected Behavior:**  “Sushi swap” dapp name must be displayed in connection prompt in Valora app when user tries to connect the sushi swap to valora app

**Investigation:** 
1. Dapp name option is not displayed in list of connected apps screen when sushi dapp is connected. 
2. "Success! Please go back to  to continue" is seen on the homepage after connecting the DApp

**Impact:** Bad user impact.

**Attachment:** 
[Sushi Connection Prompt.jpg](https://drive.google.com/file/d/1V72-gZY41gtUkWa_VkIHhRPVFYWNx3zy/view?usp=sharing )
[Connected App screen.jpg](https://drive.google.com/file/d/1Nau2MAjFzDgCyuDQNlY61cUF-xAO61WR/view?usp=sharing )

**Comment by MuckT** [comment]
@ValoraQA this appears to be a bug with Sushi swap and not Valora.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build and Test flight Release Build V1.28.1 & Observed that the issue is fixed now. “Sushi swap” dapp name is able to see in connection prompt in Valora app when user tries to connect the sushi swap to valora app.

**Devices:** Samsung Galaxy A9 pro (8.0), iPhone 13 mini(15.1.1), iPhone 6+(12.5.5), Google Pixel 2XL(11.0)

**Attachments:** [Sushi.mp4](https://drive.google.com/file/d/10DJfilbIveWA2q1QqnxwN-0jQD8RECfl/view?usp=sharing)

Thanks..!!
