### ISSUE TITLE
"Could not calculate fee" error is seen when user has created account and visits add funds enter amount page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1895]
**Frequency:** 100%

**Repro on build version:** Android Playstore Build V: 1.24.1 
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0)

**Does not repro on build version** : Android Internal Release Build V:1.25.1 ,iOS Internal TestFlight Release Build V:1.25.1, ,iOS Appstore Build V:1.24.1
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1)

**Pre-condition:**
1] User must have installed the playstore build V:1.24.1
2] User must have completed on boarding flow 
3] User must have balance in the account 
4[ User must be on homepage

**Repro Steps:**
1] tap on send button from home page
2] Enter a valid amount and select any token 
3] click on review button 
4] redirects to send amount page and observe send button

**Bug :** "Could not calculate fees" error is seen and send button is seen enabled 

**Expected Behavior :** User should be able to send money to another user 

**Observation:** Estimated fees is not getting calculated when user is on send amount page 

**Attachment :** [sendamount.jpg](https://drive.google.com/file/d/1G8pejtehEr1h9mKlDPv2mX8O94SRrcIX/view?usp=sharing)
[iOS works fine.mp4](https://drive.google.com/file/d/1G8rIMHnhbgIQ4mw3JJz9h5fYCUOWXsvL/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA we might close this due to the fact it is no longer reproducible in 1.25.x, but this is useful for debugging #1911.

**Comment by ValoraQA** [comment]
Hey @MuckT here is the logs attached pertaining to this issue 
Attachment : [log](https://drive.google.com/file/d/1HLndo7Ax3cf8CxBE1hTZuRexBO3KHZyu/view?usp=sharing)

**Comment by MuckT** [comment]
@Valora QA this should not reproduce in v1.25.2. Can you update the status with that release and close if no longer reproducible?

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android Internal release build and latest iOS TestFlight build V:1.36.0 and observed issue is faced again , hence we are reopening the bug 

**Observation :** 
- "Could not calculate fees rate" alert is seen when we navigate to enter amount page for add & withdraw flow when user has created fresh account 

**Note :** The above issue is not replicated in V:1.35.0 , and also changing the priority of the bug to P3
- Also when user has balance in the account then we do not get to see any alert on any enter amount page

**Steps to Replicate:**
1] Tap on Add & Withdraw from Hamburger menu
2] Select Add funds / withdraw funds 
3] select cUSD /cEUR
4] tap on next 
5] on enter amount page alert is seen

**Attachment :** [alert.mp4](https://drive.google.com/file/d/1JKbHJyVpVaPEaToHVvGS_XMlGyEh4-g5/view)

**Devices :** iPhone 12(14.7.1), Google Pixel 4a(12.0), iPhone 13 mini(15.1.1), Google Pixel 2XL (11.0)

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android Internal release build and latest iOS TestFlight build V:1.38.0 and observed issue is faced again

Attachment : [issue.mp4](https://drive.google.com/file/d/1MoDQ_Dop-9aLesIpk9dWS_kXJAxOZLno/view?usp=sharing)

Device : Google Pixel 2XL(11.0) , Google Pixel 4a(12.0), iPhone 12(14.7.1)
