### ISSUE TITLE
Create fallback redirect on valoraapp.com for iOS users who land there when using WC

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1904]
Problem: ios users land to valoraapp.com/wc?.....  instead of Valora mobile app, when trying to connect Valora to some dapp in the browser.

Expected behavior: when someone lands at valoraapp.com/wc we should automatically redirect them to the Valora app via deep link using the parameters from the URL where they landed.

there should be a copy saying that the user now will be redirected to the Valora app + button to download Valora if it is not installed on the device.

**Comment by kathaypacific** [comment]
Closing in backlog spring clean May 2022.

The in-app browser reduces the impact of this
