### ISSUE TITLE
QR Scanner - Can't send tokens from payment data

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1914]
### Current behavior
Scanning QR codes for multitoken support is throwing errors in [Sentry](https://sentry.io/organizations/valora-inc/issues/2978478494/events/?environment=co.clabs.valora&project=1250733&referrer=alert_email).

### Desired behavior
No unexpected errors during multi-token send flow.

### Steps to Reproduce
WIP

### Versions

iPhone 7 on iOS 13.3 - Valora v1.25.1

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Test flight release build V1.25.1 & observed that user is able to send all tokens by scanning QR code from the account having valid balance of tokens and "Send" button appears disabled for the account having zero balance.

**Device:** iPhone 7 (13.3)
**Attachments:** 
[Send flow of account having valid balance.mp4](https://drive.google.com/file/d/130MTHuKG82SSNuDPqAFqYXIQLlcbIyky/view?usp=sharing)
[Send button for zero balance acc.jpg](https://drive.google.com/file/d/1ui4-lUeUKvddPzMN3FU_vYZMjqWqhYUx/view?usp=sharing)
Thanks..!!
