### ISSUE TITLE
Few components are not seen for Persona flow in Android application as compared with iPhone 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1915]
**Frequency :** 100% 

**Repro on build version:** Android Internal Alfajores Build V:1.25.1 
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0),

**Does not repro on build version :** iOS Internal TestFlight Alfajores Build V:1.25.1
**Does not repro on device :**   iPhone 12(14.7.1)

**Pre-condition:**
1] User must have installed the application
2] User must be on settings page

**Repro Steps:**
1] Tap on the get access from "link bank accounts" and observe every page

**Bug :** Few of the components are not seen on Android App as compared with iOS app

**Expected Behaviour :** The components should be seen on both the platforms in same manner

**Observations :** 
1a] On iOS the text appears "Verify your identity" whereas on android "Valora would like to verify your identity"
1b] On iOS "Pass verification" toggle is seen whereas on Android Toggle is not seen 
1c] On iOS "Get started" text is seen on button whereas in Android "Begin Verification" text is seen 
**Attachment :** [Persona1](https://drive.google.com/file/d/1nIi9x2QUUWpUtEfo7-PMabkjlY4NE8bx/view?usp=sharing)

2a] On iOS "Country of Government ID" text is seen whereas for Android the text is not seen
2b] On iOS there is very much space between dropdown and "Select country" button whereas on Android there is no space between two things 
2c] On iOS there is "X" button seen whereas on Android the cross button is not seen 
**Attachment :** [Persona2](https://drive.google.com/file/d/1P4p7wFB5vdU0zBkbzDIVpxZpnY2pczvU/view?usp=sharing)

3a] On iOS "All countries" text is seen whereas on Android Extra space is seen on country selection page
3b] On iOS "Select Country" button is seen whereas on Android No button is seen if we click on any country it gets selected 
**Attachment :** [Persona3](https://drive.google.com/file/d/1flWhXwE0IlETFFfAbZefqZ5u8wgRQu2T/view?usp=sharing)

4a] On iOS "Review the front of iD" text is seen whereas on Android "Review the front"
4b] On iOS "Retake" and "looks good" button are seen in oval shape whereas on Android it in rectangular shape 
4c] On iOS "Looks Good" button is seen in blue color whereas on Androud it is seen in green color
4d] On iOS the Pop up appears after clicking on any of id whereas the pop up does not appear on android app
**Attachment :** [Persona 4](https://drive.google.com/file/d/1vwxbQ8DqvfCisJOq9GqqM732TYM-Ro6m/view?usp=sharing)

5] On iOS "Camera icon" is seen with "Get started" button whereas on Android only "Get Started" is seen 
**Attachment :** [Persona5](https://drive.google.com/file/d/1ogKMfX4K9s1jvK8U-nnRTTeLPb-LpNoo/view?usp=sharing)

6] On iOS "verified" tick mark is seen smaller as compared to Android app
**Attachment :** [Persona 6](https://drive.google.com/file/d/1DpsP78j8XtI69OyqCW0Q8akk_a7hNkvt/view?usp=sharing)

7] For iOS the text are appearing as left side aligned for majority of page whereas for Android we are able to see middle aligned and also few statements are seen in bold format
**Attachment :** [Persona 6](https://drive.google.com/file/d/1DpsP78j8XtI69OyqCW0Q8akk_a7hNkvt/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Android Alfa jores Build V1.25.2, iOS Test flight Alfa jores build V1.25.2 & observed that "X" button is not displayed on Top RHS on "Processing" screen for Android Platform & "X" button is displayed on iOS platform on "Processing" screen, tapping on it user can skip person flow.

**Devices:** Google Pixel XL (10.0), Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1) 
**Attachment:** [X button issue.jpg](https://drive.google.com/file/d/1nxqBlj_1bDD0BR-wiv-5mV54kiaCySBh/view?usp=sharing)
Thanks..!!

**Comment by MuckT** [comment]
@lisaqyli @cajubelt wanted to make sure that you have seen this.

**Comment by ValoraQA** [comment]
Hey @MuckT we are closing the above issue since this feature will not be present in upcoming builds as discussed in weekly meeting

Thanks.!
