### ISSUE TITLE
 User is not able to scan QR code after the user taps on the Request button from the homepage by creating new  accounts with verified and unverified phone number.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1917]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.25.1, iOS Test flight Release build V1.25.1
**Repro on devices:** iPhone 7 (13.3), iPhone 13 mini(15.1.1),Google Pixel 2XL (11.0), Samsung Galaxy A8+(8.0)

**Pre-condition:** 
1. User must have installed the app 
2. User must have completed the onboarding flow by tapping the “Create new account” button.

**Repro Steps:**
1. Tap on request button from homepage
2. Tap on the QR icon present in the top right corner in the request screen.
3. Scan the QR code and observe.

**Current Behavior:**  User is not able to scan QR code after the user taps on the Request button for verified and unverified phone number.

**Expected Behavior:** User should be able to scan QR code after the user taps on the Request button for verified and unverified phone number.

**Investigation:**
1. User is not able to scan QR code and also no error message appears.
2. User is able to send request by scanning QR code by restoring account having valid balance.
3. User is able to send request by adding address in request screen for new account created also.

**Impact:** Bad user impact as user is not able request by scanning qr code.

**Attachment:**
[Verified number.mp4](https://drive.google.com/file/d/1OqlHGbhRclKz6Pk0jpjuxPx1IIqOBnME/view?usp=sharing )
[Unverified number.mp4](https://drive.google.com/file/d/1ViJ1gnkGIw6CNo2lndg0l7pdtIcYeEby/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT,  We have verified this issue on Latest Android Internal Release Build V1.25.2, iOS Test flight Release build V1.25.2 & observed that the issue is reproducible on both iOS and android platforms. User is not able to scan QR code after the user taps on the Request button from the homepage by creating new accounts with verified and unverified phone number.

**Devices:** Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel XL(10.0) 
Thanks..!!

**Comment by MuckT** [comment]
@gnardini I've been able to confirm this behavior when requesting from a new account. All QR scans are treated as an outgoing send.

**Comment by MuckT** [comment]
@ValoraQA this will be in 1.26.x.

**Comment by ValoraQA** [comment]
Hey @MuckT  we have already commented on #1957 and observed that user is able to scan QR code after tapping on request button from homepage after creating new account
