### ISSUE TITLE
 [Query] Should Swap button appear on enter amount screen when user have only single currency cUSD balance, As it appears in application, but it is not displayed in enter amount page in figma screens

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1924]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.25.2, Test flight Release build V1.25.2
**Repro on devices:** iPhone 13 mini (15.1.1), Google Pixel XL (10.0), Google Pixel 2XL(11.0), iPhone 12 (14.7.1)

**Pre-condition:** 
1. User has installed the application
2. User has completed onboarding flow
3. User must on enter amount page
4. User must single token cUSD balance in the account

**Repro Steps:**
1. Tap on Send Button
2. Select valid contact & observe the enter amount screen.

**Query:** Swap button is appearing on enter amount screen when user have only single currency cUSD balance in application

**Expected Behavior:**  Swap button is not displayed on enter amount screen when user have only single currency cUSD balance in Figma screens

**Impact:** Bad User impact.
**Attachment:** 
[Single token cUSD.jpg](https://drive.google.com/file/d/1dD9uWCe-J7yqOMwSmgK8kgsK5aVmd7fd/view?usp=sharing)  
[Figma Screen Link](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1481%3A45126)

**Comment by MuckT** [comment]
@nityarao maybe, you can comment. I left this out as the amount of work v.s. the impact didn't seem balanced. This would only impact users with USD / only cUSD | users with EURO and only cEUR | users with Brazilian real / only cREAL. If we would like to address this in a later PR we can, otherwise feel free to close this issue with a comment.
