### ISSUE TITLE
Placeholder - name/profile pic flakiness

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1930]
needs investigation and scoping before refinement 

https://valora-app.slack.com/archives/C018VLA3YAK/p1643906368413359 

Sentry errors related to this:
Most frequent one: 
- https://sentry.io/share/issue/d24cfb5430c0498eb173a92f162c7893/
(look at the 'Additional Data' section for _some_ details)

Other related ones: 
- https://sentry.io/share/issue/c22415d3d00d457880dc984451b43188/ 
- https://sentry.io/share/issue/bd1cfe4765e24cdc9dfa5eb128603490/

**Comment by lisaqyli** [comment]
Remember to change this line of code in case name is removed from onboarding flow
