### ISSUE TITLE
Users should be able to fulfill payment requests in cREAL

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1931]
### Current behavior
Users can only fulfill payment requests in cUSD & cEUR.

### Desired behavior
Users are able to fulfill payment requests in cUSD, cEUR & cREAL.

### Steps to Reproduce
Perquisites: Requestee account has a balance of cREAL.

1. Request Payment from an account.
2. From the requestee account attempt to fulfill the payment request.
3. Tap the currency on the request confirmation request
4. Observe options available in the token bottom sheet - cUSD & cREAL.

### Versions
v1.25.2 - Mainnet and Alfajores

**Comment by ValoraQA** [comment]
Hey @MuckT We have provided our observation in the ticket id #1770 as we had previously raised query for the above issue and we have verified it in Android Internal release build and iOS Testflight Release build V:1.25.2
