### ISSUE TITLE
Overlap of text in Transaction Feed

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1932]
### Current behavior
Long comments without line breaks can overlap transaction amounts in the transaction feed. This can happen more often in longer languages e.g. Russian.

### Desired behavior
Long strings do not cover transaction amounts.

### Steps to Reproduce
1. Send a transaction with a long comment without word breaks.
2. Observe transaction in main feed.

### Screenshot
<img src="https://user-images.githubusercontent.com/26950305/152435282-18960985-a5bf-455a-b0d2-0229b2074b05.png" width="50%" height="auto">

### Versions
v1.25.2 iOS & Android

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified above issue on Android internal release build V:1.25.2 and iOS testflight release build V:1.25.2 and observed issue is reproducible

Observation : Text overlapping is seen incase of long comment and we have already raised issue [buglink](https://github.com/valora-inc/wallet/issues/1795)

Note : Previously it was only faced on the iOS platform , on V:1.25.2 it is faced on both the platforms 

Devices : OnePlus 7t(11.0), Google Pixel (11.0) , iPhone 12 (14.7.1) , iPhone 13 Mini (15.1.1)

Attachment : [longcomment](https://drive.google.com/file/d/1JBgcvLAaQHzvVA5a8lmzIBm-7tIf5v9n/view?usp=sharing)
