### ISSUE TITLE
“Games” section is seen cropped on Dapps page when user access it from the Hamburger menu.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1939]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V 1.25.2 , Android Alfajores build V.1.25.2, Test Flight Release Build V 1.25.2, Test flight Alfajores build V.1.25.2
**Repro on devices:** iPhone 7(13.3), Samsung Galaxy A8+(8), Google Pixel 2XL(11.0), iPhone 12(14.7.1)

**Pre-condition:** 

  1] User must have installed the application & completed the onboarding flow
  2] User must be on the Homepage.
  
**Repro Steps:**

  1] Tap on Hamburger menu and select the "Dapps" section.
  2] Scroll down and observe.
 
**Bug:** “Games” section is seen cropped on the Dapps page when user access it from the Hamburger menu.
**Expected Behavior:** “Games” section should not be cropped on the Dapps page when user access it from the Hamburger menu.

**Investigation:**

  1] Previously we were only able to see Ubeswap, Moola and Bidali, however we are able to see multiple other things as well.
  2] NFTs section is seen blank.
  
**Impact:** Bad user impact.

**Attachment:** [iOS behaviour.mp4](https://drive.google.com/file/d/1araqxXDJ2W24jDvgS6hImqQHN8kZ0Zhi/view?usp=sharing)
[Android.jpg](https://drive.google.com/file/d/1sbAZmzU5U8rPPZ_7s0bDoIjcCwLB37nB/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA can you please retest 1.26.0 and close if no longer reproducible.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue on latest Android Internal release build V:1.26.0 and latest iOS testflight release build V:1.26.0 and observed that issue is fixed.

**Observation :** Games section is not seen cropped and also all the categories are seen on Dapps page

**Attachment :** [Dapps.mp4](https://drive.google.com/file/d/1QyyEvEVo82RT94GHwC0aZvP5Gd3O7b-e/view?usp=sharing)

**Devices :** iPhone 12(14.7.1) ,Google Pixel(11.0)

Thanks..!!
