### ISSUE TITLE
User is redirected to homepage after performing the deeplink flow using provided link in the PR

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1940]
**Frequency** : 100%

**Repro on build version:** Android Internal Release Build V:1.25.2 ,iOS Internal TestFlight Release Build V:1.25.2
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1)

**Pre-condition:**
1] User must have installed the application

**Repro Steps:**
1] In browser open the "celo://wallet/pay?address=0xB2539a7dcc69a0B28c7Ca73f1D2FF06b9d59E5b9&displayName=Test&currencyCode=KES&amount=0.1" link 
2] Select "open in valora" / Select valora application and observer

**Bug** : User is not redirected to review / send amount page after performing deeplink flow 

**Expected Behaviour** : User should be redirected to send amount page instead of homepage

**FYI :** [PRlink](https://github.com/valora-inc/wallet/pull/1912)

**Impact :** Bad user experience 

**Attachment** : [deeplink](https://drive.google.com/file/d/1j9e_AAkPSOE21IMJohqLC0PO90hxm3DP/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA are you still able to reproduce this error? I am no longer seeing it reproducible with the provided link.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Internal Release Build V1.25.2, Test flight Release build V1.25.2 & observed that it is still reproducible from the provided url1: [link1](celo://wallet/pay?address=0xB2539a7dcc69a0B28c7Ca73f1D2FF06b9d59E5b9&displayName=Test&currencyCode=KES&amount=0.1) & user is redirected to Sending screen for kotani pay url2: [Link](celo://wallet/pay?address=0xA269CBa6a88Af7fCa81a1F3DEAeA14Fc79809F00&displayName=Faith%20Nyanaro&currencyCode=KES&amount=41&comment=sending+kes:+41+to+My+kotani+wallet)

**Devices:** iPhone 13 mini (15.1.1), Google Pixel 2XL (11.0)
**Attachment:** [Url1.mp4](https://drive.google.com/file/d/1WFyJ2thfJQ5AaWEXJIQCjW46Tau009At/view?usp=sharing)
[Kotani pay Url2.mp4](https://drive.google.com/file/d/1Qfg5p2UO-ZPsXcehTDrbcYs4SUe7es7J/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android internal release build V:1.29.2 and latest iOS Testflight Release build V:1.29.2 and observed that issue is fixed

Observation : User is navigated to send amount after performing deep link using the above mentioned URL
Attachment : [url](https://drive.google.com/file/d/1RgLfXQE9xqyu8EakfBw5RdlpDoKu2ZAR/view?usp=sharing]
Device : Google Pixel 2XL(11.0) , iPhone 12(14.7.1)

Thanks.
