### ISSUE TITLE
1.25 Design Review Items

### ISSUE THREAD

**Issue by nityarao** [valora-inc/wallet#1953]
Looked through 1.25 and found the following design bugs 

* Dapps Menu Icon & Word are not aligned in the Main Menu (item 4 in the Figmas and @nityarao will provide a new icon)

Figma link for screenshots & final designs : https://www.figma.com/file/zdK8XvxNXvTjxnM5V33pHw/Dapps-Page?node-id=1660%3A40204

Already complete:
* Card Styles--   The shadows on homecards are too dark, adjust to match the “Soft Shadow Light” styling 
* Iconography --   The external link icon is too small in app. It should measure 24 x 24

**Comment by nityarao** [comment]
@aleksey-nov Just tagging you here for visibility

**Comment by MuckT** [comment]
@nityarao it looks like the icon used has extra space at the bottom. I've checked and the text is aligned to center, but the Dapps icon is not. Here's a screenshot were I swapped out the icon with the one form home.

<img src="https://user-images.githubusercontent.com/26950305/153071647-af0fbde8-74a0-462a-b931-fe17ce26c242.png" width="50%" height="auto" />
