### ISSUE TITLE
[Query] Should Add Funds Pop up must appear on the Homepage when user has completed onboarding flow by confirming phone number

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1960]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.25.2, Test flight Release build V1.25.2,V 1.25.1, Android Playstore build V 1.24.1
**Repro on devices:** iPhone 7 (13.3), Samsung Galaxy A8+(8.0), Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1)

**Pre-condition:** 

  1. User has installed the application.
  2. User must be on the Create account /Restore account selection page.
  
**Repro Steps:**

 1. Tap on Create account.
 2. Complete the onboarding process by confirming the phone number.
 3. User is redirected to the Homepage and observe.
 
**Query:** Add Funds Pop up is not appearing on the Homepage when user has completed onboarding flow by confirming phone number.

**Expected Behavior:** Add Funds Pop should appear on the Homepage when user has completed onboarding flow by confirming phone number.

**Attachment:** [AddFund.mp4](https://drive.google.com/file/d/1T78b8_Jr2OIgeUns3-v1iRkBhUtKs-pv/view?usp=sharing)

**Comment by MuckT** [comment]
@jh2oman has this experiment from https://github.com/valora-inc/wallet/pull/1736 changed recently?
