### ISSUE TITLE
Bugfix: Opening transfer push notification opens the wrong screen

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1968]
The notification-service is sending a field `tokenAddress` to the app, but the app is expecting a `currency` field and since it can't find one it defaults to cUSD. This causes any transfer push notification to open a screen that says cUSD is the transfer token even if it's not.

AC: 
- Opening a transfer push notification opens the review screen and shows the right amount/token
  - The wallet should probably use the new [TransactionDetailsScreen](https://github.com/valora-inc/wallet/blob/2b28b691640c52bdeeb1b49a7751c5bdf3b764fe/src/transactions/feed/TransactionDetailsScreen.tsx#L62) which directly supports `tokenAddress`

**Comment by kathaypacific** [comment]
Wanted to note, i transferred 114 TT to another wallet, and that wallet received the push notification "You have received 0 TT" - looks like the token value in the notification is the fiat value since there is no usdPrice for TT? maybe something quick we can sneak into this issue?

**Comment by gnardini** [comment]
I think that might also be related to the decimals. TT token has 10 decimals instead of the usual 18, so it might be dividing the amount by the wrong value.

Either way we can include it here I think :)
