### ISSUE TITLE
[FC UI] Vendor configs

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1979]
As a developer trying to run queries across FC vendors (like get quotes from all of them), I need access to a list of vendors and static fields for each one (like name, icon, base URL, ...).

Eng:
- this issue involves writing a schema for provider static info, as well as deciding/implementing where the static info should live
- options for where the static info could live: in code in the wallet repo (would take longer to change though), firebase, an IHL endpoint, a cloud function
- if an endpoint is called, we should save caching as an optimization for later (just call the endpoint every time for now)

AC:
- a function exists in the wallet repo that can be used to get a list of all FC vendors and static info on each one
- info on each vendor is enough for anticipated use cases (display list of providers, query for quotes from each provider, post KYC info to the provider, ..., initiate/monitor a transfer with the provider)

**Comment by cajubelt** [comment]
my preference is to use a cloud function for this, though it's probably not *too* bad to put in firebase since it's not user data...

**Comment by jophish** [comment]
My preference is probably to use a cloud function for this as well, since we _may_ want to include dynamic data here at some point. My hope is that these configs will be as absolutely lightweight as possible, however. Also good to lean away from our Firebase dependency, anyways.

**Comment by cajubelt** [comment]
lets start with json and optimize later with cloud function (TODO create issue for cloud function)

**Comment by cajubelt** [comment]
I decided to write a cloud function after all as part of this ticket, since it was very quick. next up is the helper in the wallet
