### ISSUE TITLE
Retry transactions when they don't get included 

### ISSUE THREAD

**Issue by asaj** [valora-inc/wallet#198]
### Expected Behavior

Valora should be able to gracefully handle the case where a transaction that it signed+broadcast was not mined. Under high load, this may happen when the gas price minimum increases beyond the gas price included in the signed tx.

### Current behavior
No retry logic

**Comment by MuckT** [comment]
Closing as this as retries are now possible: https://github.com/valora-inc/wallet/pull/4373
