### ISSUE TITLE
[FC UI] Mock FC API for integration testing

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1980]
As a developer working on an FC API, I need to be able to test my UI changes against a mock API.

Eng:
- this could be a set of cloud functions or a single server running on app engine

AC:
- mock API exists with dummy responses for every endpoint in a FC cash-in flow
- API should do auth checks but otherwise just return dummy successes for now
- configuration for this mock vendor should be added to vendor configuration on alfajores (see #1979)
- includes deployment

**Comment by jophish** [comment]
My vote here is for an app engine service; we'll be able to reuse the API skeleton that we generate, as well as the auth middlewares from #468. It's a lot also less of a headache (imo) than maintaining a new cloud function for each endpoint.

**Comment by jophish** [comment]
Another thought is that if, for testing purposes, we want to have multiple mock vendors to test out different UIs/flows, we could "hack" support for this into a single API, by having every path in the API prefaced by a mock provider identifier, e.g. `awesome-fiat-connect-implementation.com/:providerName/quote/in`, and set the base path for each provider in the vendor configs to e.g. `awesome-fiat-connect-implementation.com/reallyGoodCICOProvider/`. Implementation-wise, we could just have some lame dictionary lookup within the API mapping `providerName` to their response for each endpoint.

**Comment by cajubelt** [comment]
@satish-ravi what else is needed here? anything?

**Comment by satish-ravi** [comment]
@cajubelt I guess from the AC, just the deployment PR is left. Was adding endpoints to change mocks in scope for this ticket?
