### ISSUE TITLE
[FC UI] Provider selection UI

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1983]
As an end-user trying to cash in, I need to be able to choose between FC providers.

NOTE: for an MVP we can omit the following:
- country selector (just use cloud function for user location for now)
- filters
- "best rate" and "fastest" tags
- info modal next to "external providers are supported by Valora"

It will look something like this, check with Nitya for the latest
![Screen Shot 2022-02-09 at 3.10.27 PM.png](https://images.zenhubusercontent.com/6111ac24d41f1f9b126e0988/1ff594ae-abc5-477b-b987-32d9564b27da)

AC:
- basic version of provider selection screen

**Comment by cajubelt** [comment]
should confirm omissions are ok with Aleksey/Nitya during refinement

**Comment by jophish** [comment]
What do you mean by `info modal next to "external providers are supported by Valora"`?

**Comment by cajubelt** [comment]
might be able to trim this down by borrowing more from existing provider selection

**Comment by cajubelt** [comment]
closing since it duplicates #2196, @jh2oman feel free to reopen if I'm mistaken here
