### ISSUE TITLE
[FC UI] Link bank account form UI

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1984]
As a user trying to cash-in with a FC-compliant CICO provider, I need to be able to provide my fiat account details in Valora. 

Eng:
- this form can be hardcoded to the first fiat account schema we get from a payment provider (ideally Paychant). If none are available by the time this is started, a fictitious one can be used based on Finclusive account info requirements.
- that said, it should be implemented with some amount of flexibility in mind, i.e. the fiat account schema can be taken as a prop and used to populate the fields in the form, something like that

Will look something like this:
![image.png](https://images.zenhubusercontent.com/6111ac24d41f1f9b126e0988/00624371-8fc3-4bc1-a678-97b934d2dfef)

(latest UI should be [here](https://www.figma.com/file/S8xGHk2ge9R9YMXgIl5uPV/Fiat-Connect?node-id=37%3A6977))

AC:
- form for entering bank account info is implemented

**Comment by jophish** [comment]
Like with the KYC stuff, I think this is also slightly blocked on us having mock typings available in the wallet for KYC schemas.
