### ISSUE TITLE
[FC UI] Generate FC typings

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#1993]
The work to create the FC API wrapper module (#1978) _should_ be orthogonal to the actual UI development, but if #1978 includes adding typings for FC responses/schemas/etc. to the wallet, then the UI work is somewhat blocked, since UI components will require certain FC-specific information to be passed as props.

This ticket is for generating and adding typings for FC objects/entities/schemas to the wallet repo, such that #1978 and the UI tickets can be worked on concurrently. For entities such as KYC schemas, account types, and account schemas (which are not currently defined by the spec), we should come up with sensible mock defaults and include them in the typings.

AC:
* Sensible mock defaults for currently undefined FC entities
* FC typings added to wallet repo

**Comment by cajubelt** [comment]
the typings exist, though not in the wallet repo. there is a separate issue for putting the typings in their own NPM module, which can then be imported by the wallet repo-- so I'm going to close this issue out

**Comment by cajubelt** [comment]
(that issue is here: https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/2058 )
