### ISSUE TITLE
Enter Pin and/or FaceID Served on All Cold Opens

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2000]
### Current behavior
In 1.26.0 Face ID / Pin entry is attempted on all app opens even if require pin on app open is disabled.

### Desired behavior
Face ID / Enter pin should not served on cold app opens if not enabled by the user.

### Steps to Reproduce
1. (Optional) Enable FaceID from settings.
2. Disable require pin on app open from settings.
3. Close and open the app. 
4. Observe FaceID / Pin prompt

### Versions
iOS v1.26.0

### Notes 
- These should not be served on app opens as they provide the user with a false sense of security as opposed to the 'Require Pin on App Open Prompt'
- These prompts be easily bypassed with 2 Failed Face ID's and tapping Pin Back. Screens such as the backup phrase or if 'Require Pin on App Open' is enabled cannot be bypassed this way.

**Comment by ValoraQA** [comment]
Hey @MuckT , We have Verified this issue using Latest iOS Test flight Alfa jores Build V1.26.0 & observed that the above issue is not reproducible for us. When we *Enable use face ID toggle & Disable require PIN for app open toggle* and cold open the app no enter pin and/or face id is appearing and also on kill and relaunch the app face ID and/or enter pin is not appearing.

Also, when we *Enable both use face ID & require pin for app open toggles* and then we cold open valora app enter pi and/or face ID pop is not served, but when we kill and relaunch the app after that face ID popup appears 

*Devices:* iPhone 13 mini (15.1.1), iPhone 12 (14.7.1)
*Attachment:* 
[Disable Require PIN toggle.mp4](https://drive.google.com/file/d/1G5nx5--9u58VWatCBJHzMu2jbDxOQg-M/view?usp=sharing)
[Both Toggle Enabled.mp4](https://drive.google.com/file/d/1QIAU2vJSQOP8fZi3wsqGCs7kSESCRTiH/view?usp=sharing)
Thanks..!!
