### ISSUE TITLE
How to access Nom Space domain since user is not able to see any relevance after entering "hello.nom" after entering text in the search bar 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2005]
**Frequency :** 100%

**Repro on build version:** Android Internal Release Build V:1.26.x,iOS Internal TestFlight Release Build V:1.26.x
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 12(14.7.1)

**Pre-condition:**
1] User must have installed the application
2] User must have completed onboarding flow
3] User must have some balance in the account 
4] User must be on homepage

**Repro Steps:**
1] Tap on send button 
2] Allow access to contacts 
3] Enter Text as "Hello.nom" as mentioned in PR (#1872) and observe

**Query :** "No contacts" found is seen after user enters the text "hello.nom" for nom space

**Expected Behaviour :** User should be able to see the contact (if it has been added in backend or hardcoded)

**Investigation:** 
- Since no contact is seen can you please provide the account address so that we can complete the flow and verify whether it is working or not 

Attachment : [nom](https://drive.google.com/file/d/1Q0R5N9CM_4xdy0xasZ6bHc4x7xjzQnws/view?usp=sharing)

**Comment by MuckT** [comment]
@gnardini @dievazqu I've tested nom lookups on mainnet and alfjaores with 1.26.0 and I am seeing the same results as posted above.

Mainnet  - `muckt.nom`
Alfajores - `valora-test.nom`

**Comment by dievazqu** [comment]
Hey @MuckT, is it possible to obtain the exactly commit they are testing? Because, I just try this in my local emulator, and it's working:

https://user-images.githubusercontent.com/12504748/155370000-7988b443-5d51-48fb-989f-64809242c767.mov



Important: `Hello.nom` is not a valid nom space, please use `Brian.nom` or `valora-test.nom` in alfajores.

**Comment by MuckT** [comment]
@dievazqu it should be based off https://github.com/valora-inc/wallet/commit/71a90e2d90e895bf57ce1b4d7d33de2f25dfcf89 for the 1.26.0 release.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android internal release build and iOS testflight release build V:1.28.1 and observed that issue is fixed

Attachment : [nom_issue_fixed](https://drive.google.com/file/d/1QKjtOA2jTThd39RrqNg8oABs9ZQtHATN/view?usp=sharing)
Devices : Google Pixel 2XL(11.0) , iPhone 13 Mini (15.1.1)

Thanks.!!
