### ISSUE TITLE
Supercharge update: Total rewards recieved

### ISSUE THREAD

**Issue by ole-nov** [valora-inc/wallet#2026]
For users who are supercharging now, display how many rewards they have claimed in the past.  sum of all previous distributions received in crypto currency (probably 1 stable coin)

Designs: TBA.
[More context on slack](https://valora-app.slack.com/archives/C025Q9QG8JG/p1644979501316339)

ENG:
- [ ] Calculate every time screen is open (many network requests potentially) vs caching total and fetching when screen open (more complexity)
- [ ] @gnardini has a list of addresses that do yield distributions
- [ ] get txs from "yield addresses" to wallet address for every token

**Comment by kathaypacific** [comment]
@nityarao designs TBC
