### ISSUE TITLE
Redirect iOS users from valoraapp.com to the app

### ISSUE THREAD

**Issue by ole-nov** [valora-inc/wallet#2027]
Problem:
For some iOS users, when they connect to the dapp via WalletConnect, WC deep link is not working as expected and instead of Valora they are landing to valoraapp.com/wc?{some_parameters}.

Solution:
Since we have the parameters, we are able to create a deeplink and automatically open Valora for them via deeplink.
Additionally, users might land on this page if there is no Valora installed on their device. In this case we want to show them a CTA to download Valora.

Design: TBA

**Comment by nityarao** [comment]
https://www.figma.com/file/U1Xd3uOPGFfcZnYeLMhx0o/Wallet-Connect-Fixes?node-id=803%3A1066

**Comment by kathaypacific** [comment]
I will ask Lisa for some numbers to assess impact, moving back to backlog for now

**Comment by kathaypacific** [comment]
Update: seems to be happening quite frequently https://valora-app.slack.com/archives/C02DY3RK79T/p1642604619032400?thread_ts=1642603482.030300&cid=C02DY3RK79T

seems to be a random iOS issue http://www.openradar.me/radar?id=4999496467480576 - there is a long list of comments there, may be something helpful there.

https://valora-app.slack.com/archives/C029Z1QMD7B/p1647418941937749?thread_ts=1647417113.376249&cid=C029Z1QMD7B
