### ISSUE TITLE
[M1] Update IHL auth in wallet to use private key to encrypt JWT payload sent to IHL

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2029]
Long story short, we realized that while the FiatConnect spec requiring the user to have a DEK registered might makes sense for Valora, it's otherwise too strict of a requirement on the end user. We decided to transition FC auth to using simple public/private key signing using the user's typical private key. If we ever plan on wrapping Finclusive in a FiatConnect API, then, we'll need to modify IHL's auth to match this, since it too currently requires a DEK (which is where the phone number verification requirement comes from).

This ticket is for updating the JWT generation/signing for IHL in the wallet to use the user's private key rather than their DEK private key.

Eng:
- note that EOA (public key) will need to be added as a parameter for helpers calling IHL (so that the public key can be included in the JWT)

AC:
* IHL auth in the wallet is refactored to encrypt the JWT payload with the user's private key.
* integration test against Alfajores IHL with auth turned on (can be run manually)

**Comment by cajubelt** [comment]
can look at older implementation for this, though Jean said that we were doing it wrong, so watch out for that

**Comment by cajubelt** [comment]
Jacob will add link to the old PR

**Comment by cajubelt** [comment]
Jean's comment on Jacob's old PR: https://github.com/valora-inc/wallet/pull/1613#discussion_r770635796
