### ISSUE TITLE
[M1] Use EOA as identifier throughout PFP integration in the wallet

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2030]
Currently, we use the user's MTW address as an identifier throughout our PFP integration. Since we now will be sending a user's EOA address to IHL, we need to change the wallet integration to use the EOA address as an identifier, replacing the MTW address wherever it appears. This includes:

* In requests to IHL
* As an identifier in Firebase

Once we change the identifier in Firebase, we need to update the Firbase security rules for the `in-house-liquidity` node to only allow reads from users who's EOA address matches the identifier in Firebase. (Can copy over from other nodes with the same rule.)

AC:
* Wallet refactored to use EOA address instead of MTW for PFP integration
* Firebase rules updated
* manual integration tests against IHL with auth turned on should pass

**Comment by cajubelt** [comment]
assuming for now that IHL changes will not be needed (Charlie will confirm)

**Comment by cajubelt** [comment]
(if any IHL changes needed-- like variable naming-- it should go into separate issue)

**Comment by cajubelt** [comment]
@lisaqyli will push her dev branch
