### ISSUE TITLE
Amount received blue banner is not displayed on home screen when user A send the amount to user B. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2047]
**Frequency:** 50%

**Repro on build version:** Test Flight Release Build V 1.26.0.
**Repro on devices:** iPhone SE(14.8.1), iPhone 13 mini(15.1.1)

**Does Not Repro on build version:** Test Flight Release Build V 1.27.0., Android Internal Release build V 1.27.0.
**Does Not Repro on devices:** Samsung Galaxy A8+(9.0), Google Pixel XL (10.0), iPhone 12 (14.7.1), Redmi Note 7 Pro (10.0)

**Pre-condition:** 

  1. User must have installed the application & completed the onboarding flow
  2. User A must have some balance in their account.
  
**Repro Steps:**

 1. For User B: Open the App and it should be homepage
 2. For User A: Send valid amount to User B
 3. For User B: Wait for some time and observe on the Home screen. 

**Bug:** User B is not able to see the Blue banner on Home screen when User A sends an amount.

**Expected Behavior:**  User B should be able to see the Blue banner on the Home screen when User A sends an amount.

**Impact:** Bad user impact.

**Observations:**

1. Sometimes we are able to see Blue Banner. [Blue banner seen.mp4](https://drive.google.com/file/d/1D8ufnede95L7gbjtPcu6ApMiHgVy-mbd/view?usp=sharing)

**Attachment:** [Blue banner not seen.mp4](https://drive.google.com/file/d/1BXbbmbd6mx1u1J9J9omtEzJxI2fdsl-1/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA please test on 1.27.2 and 1.28.x when available.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on latest Test flight release build V1.27.2 & observed that the issue is partially reproducible.

**Frequency**: 50%

**Repro on Device:** iPhone SE 2020 (14.8.1)
**Does not Repro on Device:** iPhone 12(14.7.1)

**Attachment:** [Blue banner not seen.mp4](https://drive.google.com/file/d/16NRwe6JgSNjQL-UJMUeIO_Icd370cY4I/view?usp=sharing)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on latest Test flight release build V1.42.0 & latest Android Internal Release Build V 1.42.0 and observed that the issue is reproducible.

**Observation:**
- For both the platform user is not able to see Amount received Blue banner on home screen when user A send amount to user B 

**Repro on Device:** iPhone 13 mini(15.1.1), iPhone 6+(12.5.5), Google Pixel 4a(12.0), Google Pixel XL(10.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on latest Test flight release build V1.42.0, latest Android Internal Release Build V1.42.0, Android Playstore Build V1.41.0 and iOS Appstore Build V1.41.0 and observed that the issue is reproducible.

**Observation**:
- For both the platform user is not able to see Amount received Blue banner on home screen when user A send amount to user B

**Repro on Devices:** iPhone 13 mini(15.1.1), iPhone 6+(12.5.5), Google Pixel 4a(12.0), Google Pixel XL(10.0)

**Attachment:** [Blue banner.mp4](https://drive.google.com/file/d/1zrDLo55aHXlXCSat332Kc4arY3-uE1PQ/view?usp=sharing)

Thanks..!!
