### ISSUE TITLE
 “Identity verification is not currently available…” error appears in red banner  when user navigates to “Start supercharging” screen by tapping on Rewards from hamburger menu.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2048]
**Frequency:** 100%
**Repro on build version:** Android Internal release build V1.27.0, Test flight release build V1.27.0
**Repro on devices:** Google Pixel XL (10.0), Google Pixel 2 XL (11.0), iPhone 12 (14.7.1), iPhone 13 mini (15.1.1)

**Pre-condition:** 
1. User must have installed the app
2. User must have completed the onboarding flow by skipping phone number confirmation.

**Repro Steps:**
1. Tap & open Hamburger menu.
2. Tap on “Rewards” pill on top RHS in hamburger menu & observe.

**Bug:** “Identity verification is not currently available…” error appears in red banner  when user navigates to “Start supercharging” screen

**Expected Behavior:**  “Identity verification is not currently available…” error must not appears in red banner  when user navigates to “Start supercharging” screen

**Investigation:** Same red banner error appears when user navigates to “Start supercharging” screen on tapping “Rewards” from hamburger menu after user confirms phone number and adds valid balance.

**Impact:** Bad user impact as unnecessary error appears in red banner.

**Attachment:** [Red Banner issue.mp4](https://drive.google.com/file/d/1evVrakWk6uoh4tXn9i1oGP3PuSWgRXw4/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this could be an issue with ODIS or related to the linked PR. Please retest in 1.27.2.

**Comment by ValoraQA** [comment]
Hey @MuckT,  We have verified this issue on latest Android internal release build V1.27.2, Test flight release build V1.27.2 & observed that the issue is fixed now.  Hence we are closing this issue.

- No error appears when phone number is not verified & user is navigating to "Start supercharging" screen by tapping on rewards from hamburger menu.
- No error appears when phone number is verified & user redirects to "Start supercharging" screen by tapping on rewards from hamburger menu.

**Devices:**  Google Pixel 4a (12.0), iPhone SE 2020 (14.8.1), iPhone 12 (14.7.1), Redmi Note 7 Pro (10.0), Google Pixel 2XL (11.0)
**Attachment:** [No error appear.mp4](https://drive.google.com/file/d/13Zk2iKAi_DFOSqDIrtllVL8RTKCZv8SZ/view?usp=sharing) 
Thanks..!!
