### ISSUE TITLE
 [Query] Walkthrough screens flow are appearing when user installs the valora app and opens the app and selects any language option

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2049]
**Frequency:** 80%

**Repro on build version:** Android Internal release build V1.27.0, Test flight release build V1.27.0
**Repro on devices:** Google Pixel XL (10.0), One plus 7T (11.0), iPhone 12 (14.7.1), iPhone 13 mini (15.1.1)

**Does Not Repro on build version:** Android Internal release build V1.27.0, Test flight release build V1.27.0 
**Does Not Repro on devices:** Google Pixel 2 XL (11.0), iPhone 13 mini (15.1.1)

**PR:** [link](https://github.com/valora-inc/wallet/pull/1936)

**Pre-condition:** 
1.User must have freshly installed the valora app.

**Repro Steps:**
1.Open valora app
2. Tap on “English” option from “Select language” screen & observe.

**Query:** Walkthrough screens flow are still appearing when user installs the valora app and opens the app and selects any language option

**Expected Behavior:** Walkthrough screens flow must not appear when user installs the valora app and opens the app and selects any language option.

**Impact:** Bas user impact.

**Attachment:** [Walkthrough screen.mp4](https://drive.google.com/file/d/1Y1ZghxNiAsvbU9ijuataY6-DsOtxAYPd/view?usp=sharing )

**Comment by MuckT** [comment]
@ValoraQA this is an experiment when 50% of users will not see the walkthrough screens. If the results of the experiment are positive we will look at removing the screens entirely.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thank your very much for the information.
