### ISSUE TITLE
[Query] : Will the "Version: 1.27.x" to be seen in the settings menu as it is not seen currently 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2052]
**Repro on build version:** Android Internal release build V1.27.0, Test flight release build V1.27.0
**Repro on devices:** Google Pixel XL (10.0), One plus 7T (11.0), iPhone 12 (14.7.1), iPhone 13 mini (15.1.1)

**Pre-condition:**
1.User must have freshly installed the valora app.
2. User must have completed onboarding flow 

**Repro Steps:**

1. Tap on hamburger menu
2. Tap on settings , scroll the page and observe

**Query:** Will the "Version : 1.27.x" to be seen in the settings menu ? as currently it is not seen 

**Expected Behavior:** "Version : 1.27.x" to be seen in the settings menu as per the mentioned [PR](https://github.com/valora-inc/wallet/issues/1997)

**Attachment:** [settings.mp4](https://drive.google.com/file/d/1VqAigzhxE3z2FF5lxX1_rvFsYZ0-sgD9/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA This would be the under the hamburger menu below the Account Address.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thanks for the update, the version number appears below the account address in the hamburger menu only.
Hence we are closing it.
Thanks...!!
