### ISSUE TITLE
Finalize FiatConnect naming scheme and update specification to match

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2055]
Currently, there's a discrepancy between the naming scheme used in the starter API typings and the specification itself. Once we've finalized the naming scheme in the starter API repo, we should go back and update the specification to align with it.

AC:
* Naming scheme for types/events finalized in the starter API
* Specification updated to match

**Comment by cajubelt** [comment]
@jophish is this still relevant? I'm not really sure what this issue is talking about
