### ISSUE TITLE
Move FiatConnect types to their own repo, publish on NPM, and import into wallet/starter API

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2058]
Once we've merged in the initial FiatConnect starter API, we should separate out the typings that need to be shared among our different repos. This will require us to create a new repo in the fiatconnect org to hold the typings, publish them as an NPM package, and then require that package in the wallet and starter API repos.

AC:
* New typings repository created in fiatconnect org
* NPM package published
* typings package required in wallet and fiatconnect-api-starter repos

**Comment by cajubelt** [comment]
swapping this for #1978 since it blocks it, discussion here: https://valora-app.slack.com/archives/C02KBT0DAHJ/p1645835598934979
