### ISSUE TITLE
Add Google Analytics to NFT viewer

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#2065]
@grvalora please add GA code that we should add and names for events. We want to track:
- views of nfts.valoraapp.com
- events on 'Paste&search'
- events on download Valora button
- landings to search results directly
- number of nfts held by address
???

**Comment by MuckT** [comment]
Closed by: https://github.com/valora-inc/nft-viewer/pull/14

**Comment by MuckT** [comment]
@grvalora are the events in https://github.com/valora-inc/nft-viewer/pull/14 sufficient to generate these analytics?

**Comment by grvalora** [comment]
@MuckT : Can you also send the User address as one of the parameter for the events ( in lower case please). I am not sure if we are going to introduce any languages for this page, if that is going to happen could you add that parameter as well .?

**Comment by MuckT** [comment]
@grvalora when I tried to send the user address to GA, it converted it to a int for some reason. Have you seen that before?
