### ISSUE TITLE
Replace background image at nfts.valorapp.com

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#2066]
According to updated [design specs](https://www.figma.com/file/BcVDiz7kBZysAPy2s0vtb2/Hackathon%3A-NFT-Browser?node-id=1168%3A4844)

**Comment by MuckT** [comment]
@nityarao what design do we want to go with form the figma specs I see several options.

**Comment by MuckT** [comment]
This work is currently paused.
