### ISSUE TITLE
 [Query]  List of Photo ID options is not displayed on Upload a photo Id in the Persona flow, when user selects American Samoa option from Country of Government ID dropdown.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2091]
**Frequency:** 100%

**Repro on build version:** Android Alfajores build V1.27.3, Test flight Alfajores build V1.27.3
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 6+(12.5.5), Samsung Galaxy A9 Pro(8.0), Redmi Note 7 pro(10.0)

**Pre-condition:** 

  1.User must have installed the app and completed the onboarding flow by confirming the phone number.
  2. User must be on the settings page. 
  
**Repro Steps:**

 1. Tap on the get access from "link bank accounts" .
 2. Tap on the Begin button from Step 1 “Verify your Identity”.
 3. Tap on the Get Started button.
 4. Tap & Open Country of Government ID dropdown and select “American Samoa”.
 5. Tap on Select Country button and observe. 
 
**Query:**  List of photo ID options is not displayed on Upload a photo Id screen in Persona flow when user selects American Samoa country for Identity Verification.

**Expected Behavior:** List of options must be displayed on Upload a photo Id screen in Persona flow when user selects American Samoa country for Identity Verification.

**Attachment:** [Country.mp4](https://drive.google.com/file/d/1TvpmG4q2xYUus-5WBGqTODEAdN8Zv84R/view?usp=sharing)

**Comment by MuckT** [comment]
@jh2oman have you seen this?
