### ISSUE TITLE
[M2] Add missing Copy to Step 1

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2111]
In the Linked Bank Account Screen when step one is complete (aka the user has been approved through kyc) we currently always say "We succesfully verified your identity. We’ll let you know when you can finish linking your bank account." even when step 2 is available.

AC:
* When step two is available and step one is complete the description should say https://www.figma.com/file/DAcpLsmPdeHT9Gt4eXhtWe/Finclusive-(US)?node-id=697%3A14090

**Comment by cajubelt** [comment]
copy may be changed a bit
