### ISSUE TITLE
"Invalid QR code scanned ...." error is seen if we scan the QR code generated after clicking on purchase button for a product seen on "https://sandbox-celo-demo-store.demo.firstdag.com"

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2156]
**Frequency :** 100%

**Repro on build version:** iOS Internal TestFlight Alfajores Build V:1.28.0, V:.1,28.1
**Repro on device :** iPhone 12(14.7.1) , iPhone 13mini (15.1.1)

Pre-condition:
1] User must have downloaded the alfajores application 
2] User must be on homepage 
3] user must have completed onboarding flow
4] user must have some funds in the account 

**Repro Steps:**
1] Navigate to website "https://sandbox-celo-demo-store.demo.firstdag.com" on desktop browser
2] tap on purchase for any product , QR code will be seen generated 
3] Go to application and click on QR code scannner
4] Scan the QR code and observe

**Bug :** Error is seen when we try to scan the QR code which is generated on the website 
**Expected Behaviour :** Error should not be seen when we scan the QR code and it should redirect user to send amount page 

**Note** : We are not able to see latest Alfajores build V:1.28.x for Android Platform.

**Investigation :**  
- Same error is faced if we try to scan the QR code from Send , request , homepage 
- QR code error is seen twice after coming back from scan page 

**Attachment :** [Qrcode](https://drive.google.com/file/d/1pernmFyAFOMfhMK0xuuQ2E97knhJWqvc/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Test flight Alfajores Build V1.28.1 & Android Alfajores Build V1.28.1 & observed that on scanning the QR code and performing transaction Payment sent is seen on the recent activity page but Processing payment is seen on the website.

**Device:** iPhone 12(14.8.1),iPhone 13 mini(15.1.1), Redmi Note 7 Pro(10.0)

**Attachment:**
[QR code scanner.mp4](https://drive.google.com/file/d/10kcBhU59SmB1u1HJ0GcB63hrUkOdZgOw/view?usp=sharing)

Thanks..!!

**Comment by MuckT** [comment]
@ValoraQA can you retest on v1.29.1 when available using https://prod-celo-demo-store.demo.firstdag.com?

**Comment by ValoraQA** [comment]
Hey @MuckT We have tried scanning QR code for the link https://prod-celo-demo-store.demo.firstdag.com/ and observed an error after scanning the QR code even if user has balance in the account or no balance in the account 

Attachment : [ErrorforscanQR.mp4](https://drive.google.com/file/d/1cvCbMfFezZ2-fWF7gn8Z30aC0A8IFY43/view?usp=sharing)

**Comment by ellenwoconnor** [comment]
Feature is no longer supported, we should consider removing it from the codebase
