### ISSUE TITLE
SPIKE: Investigate/implement websocket solution for monitoring on-chain events

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2163]
Rather than having partners poll for transfer events on the blockchain, we should encourage them to use a monitoring solution with websockets. We'd like to provide them with a minimal example script that implements this functionality that they can use as reference.

Unfortunately, Forno drops websocket connections every 20 minutes. Even if we have auto-reconnects enabled, there's still the possibility that a block will be missed while reconnecting. A draft PR for a websocket script can be found [here](https://github.com/fiatconnect/api-starter/pull/3). This ticket is to investigate how to handle reconnections, while ensuring that any blocks that were mined while attempting to reconnect are checked for relevant events. This ticket should be timeboxed; if we can't figure out a solution in a reasonable amount of time, we should drop the example script entirely, rather than providing partners with code that has the potential for bugs.

AC:
* give up after 3hrs
* Websockets example script handles reconnecting and checking for missed blocks, if time allows
* manual test has been run that confirm the script handles reconnection and any blocks that were missed during the disconnect interval (such as by turning wifi off for 10 seconds)

**Comment by cajubelt** [comment]
thinking about this again, I think this is lower pri than some other things we're doing right now

**Comment by cajubelt** [comment]
putting it into icebox for now, lmk if you disagree @jophish
