### ISSUE TITLE
Sanity E2E tests

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2165]
### Description
Perform e2e sanity testing on a variety of OS versions.

### User Stories 
As a user I want to be able to load the transaction feed on my device so that I can start using Valora.

### Acceptance Criteria
E2E tests should run a sanity check -  complete onboarding and check that the transaction feed loads without a crash:
- [ ] Android 5 - 12
- [ ] iOS 12.4 - 15.3

**Comment by kathaypacific** [comment]
@MuckT sorry i forget the context of this, but isn't this already covered by the e2e tests implicitly already? or did we plan to run these sanity tests for some other purpose?
