### ISSUE TITLE
Manage homecards in Clevertap

### ISSUE THREAD

**Issue by lukasawagner** [valora-inc/wallet#2170]
### Description

Currently we create our home cards in the admin dashboard. This method gives us limited functionality with how we can customize our home cards. 

We want to migrate our home card materials to clever tap where we will have more functionality. 
The functionality we wish to add is to show home cards to specific user segments. Currently in the admin dashboard, we can only segment home cards by certain countries or by the App version. In the future we want to customize the user journey through home cards, so that a user who has just onboarded sees different home cards than a user who has been using the app and want to see the newest features. 

### Info
- Essentially the "native display" functionality allows Clevertap to send key-value pairs to the app.
- Content managers should be using "Custom key value" as the type of native display campaign
- Content managers in Clevertap will need to be aware of which keys the app requires, for each type of component (homecards only for now, but this can easily be scaled to handle more types of components in the future)
- The keys for homecard properties in Clevertap are [here](https://www.notion.so/valora-inc/Creating-a-home-card-in-CleverTap-28fcfc4d93b14c48933cf9a29be6e716) - feel free to update them during implementation

### AC
- [ ] The app should handle Clevertap "native display" campaigns

### Eng
- [ ] Implement listeners for native display content in the wallet https://developer.clevertap.com/docs/react-native-advanced-features#native-display
- [ ] Upon receiving native display content from Clevertap, the content should be used to generate homecards. The existing rules should apply (the content from Clevertap should be sorted according to priority and merged with the homecards hard coded into the app)
- [ ] The mechanism for receiving home cards from admin dashboard can be removed
- [ ] The [notion doc](https://www.notion.so/valora-inc/Creating-a-home-card-in-CleverTap-28fcfc4d93b14c48933cf9a29be6e716) is updated if there were changes to the expected key values
- [ ] The app should keep track of which notifications have been dismissed by the user, and retain the selection.
- [ ] The app should persist the homecards, so that the previous homecards can be displayed while the content from clevertap is being fetched

**Comment by MuckT** [comment]
Link to [Pre-Refinement Doc](https://docs.google.com/document/d/1CJ_pJnTIZpEOEC84VwY8sEUUPQPCmh1fUALqDLjdY40/edit#).

**Comment by ellenwoconnor** [comment]
@lukasawagner is there a motivating use case we can pin this to, i.e. a user-facing feature we want to release imminently that depends on this? if not i'll deprioritize until we come across one

**Comment by lukasawagner** [comment]
@ellenwoconnor Yes actually! Currently we need more functionality to segment home cards to Supercharge users. There are several different supercharge home cards, and currently we have to hard code a home card to segment it. Also this is part of our in-app life cycle GTM initiative.
