### ISSUE TITLE
make NFTs discoverable

### ISSUE THREAD

**Issue by silasbw** [valora-inc/wallet#2173]
Experiment design:
* https://www.notion.so/valora-inc/Discoverable-NFT-viewer-7f2f4628099c473eacdfcf3e28a581d2

Design:  https://www.figma.com/file/BcVDiz7kBZysAPy2s0vtb2/NFTs?node-id=1301%3A4416

As a new user
ISBAT see NFTs easily from the assets page
so that I can get a more comprehensive view of the contents of my portfolio before I've become acquainted with dapps 

ENG:
- Consider using a webview and rendering the existing NFT dapp

AC:
- [x] Assets page has an additional tab for "Collectibles" or "NFTs"
- [x] Clicking on tab opens the NFT experience in app
- [x] It should be possible to measure how many users saw the assets page
- [x] It should be possible to measure how many users viewed the NFT viewer from the assets pag
- [x] It should be possible to measure how many users viewed the NFT viewer from the dapps page
- [x] Feature should be under a remote config experiment in Firebase

**Comment by ValoraQA** [comment]
Hey @MuckT  we have provided our observations and comment in PR #2632
