### ISSUE TITLE
[analytics] Add events for supercharge claim flow

### ISSUE THREAD

**Issue by grvalora** [valora-inc/wallet#2177]
### Description
We need additional tracking for the tracking the supercharge rewards claim flow. Going forward supercharge rewards are not automatic and users need to be able to claim them manually. 

### User Stories 
Events related to notification shown and claim initiate are needed. Please add the following events. 

- [ ] 1. ** notification_shown** : when the notification impression is shown.
- [ ] 2. ** claimed_reward** : when the claim reward cta is clicked on the rewards screen
- [ ] 3. **claimed_reward_complete** :  when user successfully claims the reward. 

Parameters are needed for the events. Adding the parameters for every event individually. In addition to the parameters below, also include the common events being sent along with other events. 

notification_shown : 

1. notification_id : same value as send with the notification_select event

claimed_reward_complete : 

1. claim_amount_usd : amount in usd equivalent that user has claimed. 
2. claim_amount : amount in token equivalent that user has claimed. 
3. claim_token : token code of the claimed  amount  example cusd, ceur, creal

### Acceptance Criteria
The above three events should fire upon user interaction along with the events.

**Comment by gnardini** [comment]
Done on https://github.com/valora-inc/wallet/pull/2088
