### ISSUE TITLE
“Phone number Step 3 of 2” screen appears automatically when user kills and relaunches the alfa jores application after creating an account by new create account flow.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2183]
**Frequency:** 100%

**Repro on build version:** Android Alfa Jores Build V1.28.1, iOS Test flight Alfa Jores Build V1.28.1 
**Repro on devices:** Samsung Galaxy F41 (11.0), Google Pixel 2XL (11.0), iPhone SE2020 (14.8.1), iPhone 13 mini (15.1.1), Google Pixel XL (10.0), iPhone 12 (14.7.1)

**Pre-condition:** 
1.User must have installed latest build.
2.User must be on home screen after completing create new account flow.

**Repro Steps:**
1.Kill, relaunch the app & observe.

**Bug:**  “Phone number Step 3 of 2” screen appears automatically when user kills and relaunches the applicattion after creating an account by new create account flow.

**Expected Behavior:** “Phone number Step 3 of 2” screen must not appear automatically when user kills and relaunches the application after creating an account by new create account flow.

**Investigation:**  This issue is also reproducible in both iOS & android platforms, when user restores the account and kill , relaunch the app.

**Impact:** Bad user impact.

**Attachment:** [Phone number screen.mp4](https://drive.google.com/file/d/1VotlalAsNOldMGiQXx85ZnMmjBhDnQj6/view?usp=sharing )

**Comment by MuckT** [comment]
@lisaqyli we might want to disabled phone verification experiment based on these findings and those in #2224.

**Comment by ValoraQA** [comment]
@MuckT Also adding onto the above issue, if we create a new account and try to access the persona flow it asks us to connect the phone number 

Attachment : [connect.mp4](https://drive.google.com/file/d/111RtkPoKzdPBCYqBy975Y6XtJX0gCkf4/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT we are able to see phone number verification page when we kill the app and reopen it and also Step 4 of 3 is seen instead of Step 3 of 3 on Latest Alfajores Build V: 1.29.2 

Attachment : [phone.mp4]()

**Comment by jh2oman** [comment]
@ValoraQA
>  when we kill the app and reopen it and also Step 4 of 3 is seen instead of Step 3 of 3

I am unable to repro. Can you try deleting the app completely and try again?
> If we go to rewards page and click on connect number then also phone number verification page is seen

This is expected behavior. Phone verification is just skipped during onboarding for this experiment, but the user still must connect their phone number for things like Rewards

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue Latest Android Alfa jores build V1.29.2, Test flight Alfa jores build V1.29.2 & observed the following:

- For iOS platform when user create a new account we are able to see phone number verification page when we kill the app & reopen it and also Step 4 of 3 is seen instead of Step 3 of 3 & for iOS platform "Phone number" screen is not appearing on kill & relaunch when user restores the account.
- For Android platform "Phone number" screen is not appearing on kill and relaunch the app when user restores or creates new account.

**Devices:** iPhone SE 2020 (14.8.1), Google Pixel 2XL (11.0), Google Pixel 4a (12.0)
**Attachment:** [2183.mp4](https://drive.google.com/file/d/1MmzmiE3oYV3Zk-62XJNtJpoC6OUEbVsQ/view?usp=sharing)
CC: @jh2oman 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue Latest Android Alfa jores build V1.32.0, Test flight Alfa jores build V1.32.0 & observed the following so we are reopening the issue

- For iOS platform when user navigates to phone number confirm page Step 4 of 3 is seen instead of Step 3 of 4.
- For Android platform when user navigates to phone number confirm page Step 3 of 2 is seen instead of Step 2 of 3.

**Devices:** iPhone 13 mini(15.1.1), Google Pixel 2XL (11.0), Google Pixel 4a (12.0)

**Attachment:** [iOS.jpg](https://drive.google.com/file/d/1w3aKGbPUv9ZwnVsxHF3XMM2uz-Ic6Ija/view?usp=sharing)
[Android.jpg](https://drive.google.com/file/d/1Ouzhi-bp5PUEVWwl6Q4-wy4XU8PbEtNF/view?usp=sharing)

Thanks..!!
