### ISSUE TITLE
[M3] cash-in navigation: connect link bank account flow with cash-in flow

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#2185]
As a user trying to cash in:
- If I haven't linked my bank account already, I need to reach the link bank account steps UI when I attempt to cash in and I choose Finclusive as a provider option
- if I have, I need to reach the review purchase UI

See FiatConnect UI designs [here](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A16749) (which this should be compatible with)

AC:
- both cases from the description are handled

**Comment by jh2oman** [comment]
The UI parts of this ticket can probably be taken by this epic which does general UI prep for fiatconnect & PFP https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/2194

**Comment by jh2oman** [comment]
New AC proposal:
* IHL should be called alongside the existing provider cloud functions to get quotes in the Select Payment UI
* If they have not yet linked an account, then the user is directed to the Link Bank account page
* If they have linked a bank account it should show up in the `Linked Account` section of the Select Payment screen. Clicking it should take the user to the 'Review' Screen

**Comment by cajubelt** [comment]
I talked with Jacob and the "linked account" section thing is outdated^
