### ISSUE TITLE
Improve disclaimer copy when opening a dapp

### ISSUE THREAD

**Issue by silasbw** [valora-inc/wallet#2187]
We'd like to encourage users to reach out to dapps when there is a problem (instead of Valora support).  We believe that tweaking the disclaimer when opening a dapp from the dapps page is a good thing to try.

AC:
- [ ] Update copy according to design

**Comment by silasbw** [comment]
@nityarao did you have a suggestion on this?

**Comment by MuckT** [comment]
Hopefully https://github.com/valora-inc/wallet/pull/2267 provides a bit of clarity that this is an outside application.
