### ISSUE TITLE
Create new metadata for existing providers

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2195]
The UI for the new 'Select Payments' screen and 'Review' screen requires richer metadata than we currently have for existing providers. Based on the designs it looks like two more data points are needed: `estimatedTime` and `kycRequirements`.

AC:
* The new metadata for all existing providers is stored somewhere and available to consume in-app

ENG:
* Should probably get Lukas to approve the specific wording of the data beforehand
* Some of them may be tricky and we may need to default to being vague. For example, Ramp's KYC requirements are very complex https://support.ramp.network/en/articles/441-what-are-the-kyc-limits
* This metadata can probably go in firebase since other existing CICO metadata such as providerLogo is already stored there. Could also be hardcoded into cloud functions

**Comment by cajubelt** [comment]
I suggest we avoid dumping more stuff into firebase realtime db if at all possible. The cloud function solution sounds reasonable, especially if we can make it very similar or identical to the FiatConnect quote endpoint, so we can re-use more code in getting quotes from all the providers

**Comment by cajubelt** [comment]
@jh2oman can you clarify this? "Should probably get copy to approve all of the data beforehand"

**Comment by jh2oman** [comment]
> Should probably get copy to approve all of the data beforehand

The metadata is a bit subjective so I think copy should have a look beforehand. For example, which providers get 3-5 days, which get 2-3 days. Ramp sometimes requires nothing, sometimes ID, but can also require proof of income if you're withdrawing enough. What do we put down for that?

**Comment by jh2oman** [comment]
Decide early in implementation whether to do Firebase or Cloud function

**Comment by jh2oman** [comment]
Kicked off convo [here](https://valora-app.slack.com/archives/C029MMTD529/p1649780264076809) 
[spreadsheet here](https://docs.google.com/spreadsheets/d/1Ujk_oMwGPY6dP75F41_-PZcsx6XOFIMoLcAS3kE9p5M/edit#gid=0)
