### ISSUE TITLE
Create new 'Review' Screen

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2197]
Add in the new 'Review' Screen needed for the returning user CICO flow.

[Figma](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=950%3A17659)

AC:
* Create the new screen only for existing providers
* Clicking 'change' takes you to the provider selection screen

ENG:
* This screen is very similar to the Transaction Review screen, so it could be used as a reference. Also check out simplex cash in. looks similar
* https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/2198 is a different ticket that actually creates the returning user flow. For this ticket, assume that the data on which provider is the default one comes from state or props.

**Comment by cajubelt** [comment]
could we split the "change" feature out of this to reduce scope?

**Comment by cajubelt** [comment]
duplicates #2334
