### ISSUE TITLE
Create the CICO returning user flow

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2198]
[Figma
](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A18450)

AC:
* After users successfully cash in/out with a provider, save it in state and use that provider as a default in the returning user flow with the ‘Review’ screen
* Probably separate defaults for cash in and cash out.
* If there is an issue with the quote from the default provider, go to the select payment screen instead

ENG:
* Just the returning user flow part could be released as an experiment. Needs to be discussed, but plan on putting this behind a feature flag to hedge our bets that it will be an experiment.
* I've heard that our 'cash in success' events in the app are a bit lossy since they require users to redirect back to the app. Use the same method anyways??

**Comment by cajubelt** [comment]
cash in success events will be significantly better with FC partners fwiw, since there isn't a redirect back to the app

**Comment by cajubelt** [comment]
another AC from today's sync: if a user has connected their bank account with PFP, then Finclusive appears as their default cash-in option (even if they haven't cashed in yet with them)

**Comment by jh2oman** [comment]
^ out of scope for this epic since its on the PFP/Fiatconnect integrations
