### ISSUE TITLE
Small copy change to 'Add Funds' Screen

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2199]
AC:

[Figma](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A16749)

* Add funds => Add [currency] in the header
* [Currency] next to the total on the right

**Comment by lisaqyli** [comment]
The cUSD next to the total amount on the right seems repetitive to me, I'll bring up to Nitya

**Comment by lvsuttie** [comment]
For now, let's keep the cUSD next to the amount so that its clear to the user the units. Even though we have cUSD at the top of the page, users will be drawn to the conversion they see in the last line. Being explicit about units helps build user trust.

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our observations in PR #2309 
Thanks..!
Cc: @lisaqyli
