### ISSUE TITLE
Calculate Fees based on Market Value

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2200]
In the Select Providers page, taking 'Fees' from the quotes as the full story is a bit naive. Partners can also introduce shadow fees by changing the rates of exchange. For example they could force you to always pay $1.01 for 1 cUSD. We should calculate the fees we display taking into consideration the rate.

AC:
* Fees in the Select Payments screen are calculated based on the market value of the exchange
* These fees can be seen broken down in the details of the Review Screen.

Notes:
* In the detailed breakdown, what do we call 'Bad rate fee' :P. Do we instead just show the exchange rate? 
* If a provider has negative fees based on the market value, what do we do?

**Comment by cajubelt** [comment]
> If a provider has negative fees based on the market value, what do we do?
I suggest we show 0 and maybe emit an analytics event

> In the detailed breakdown, what do we call 'Bad rate fee' :P. Do we instead just show the exchange rate?
I was imagining a single "composite fee" number being calculated as follows:
`compositeFee = max(0, fixedFee + amount * (actualRate - marketRate))`

**Comment by satish-ravi** [comment]
Should we do the calculation server side, in case we want to change this in future? Also, could this be a potential experiment, showing composite fees vs raw numbers?

**Comment by jh2oman** [comment]
@cajubelt and I discussed this ticket and decided that it would be best to wait until we integrate FiatConnect into the wallet to implement this. We'll be able to make a much more informed decision then as to whether it should be server side or client side.
