### ISSUE TITLE
[Invites v2] Analytics 

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2208]
### Description
We probably want to track some events to help us understand user behaviour better. Need to chat to Gowtham about what kind of events are needed once the user flow is finalised

Analytics Requirements

- [x] Ability to retrieve who was exposed to the treatment
    - [x] Push notification send/view/click data — we need this in celo-mobile-mainnet
    - [x] Home card impressions for the experiment should be emitted - `notification_impression` with id of notification card (you choose this when creating the homecard through admin dashboard)
    - [x] Banner impressions in send flow should be emitted - `invite_banner_impression`
- [x] Ability to determine who sent an invitation and how much money they sent  - `send_confirm_send`
- [x] Ability to determine who was rewarded for an invitation - `invite_reward_created`
- [x] Ability to determine who was the inviter for any rewarded invitees (or conversely, who was the invitee for any rewarded inviter) - `invite_reward_created` contains properties for this
- [x] Ability to measure completion rates for key tasks
    - [x] App opens (exists app_launched)
    - [x] new event for “account funded” defined specifically as user going from a zero to nonzero balance (nice to have - cash in type added as metadata - exchange, provider, transaction) (define "zero balance" as less than $0.01 USD, this event is triggered on total balance change) - `account_funded`
    - [x] new event for “account liquidated” defined specifically as user going from nonzero to zero balance (define "zero balance" as less than $0.01 USD) - `account_liquidated`
    - [x] User claims their supercharge rewards (exists `rewards_screen_cta_pressed`)
    - [x] User completes a dapp transaction (ideally metadata on which type of dapp/transaction) (exists `dappkit_request_accept_success` and `wc_request_accept_success`)
    - [x] User sends money via send flow (exists `send_confirm_send`)

### Acceptance Criteria

- Audit list above for any gaps
- Add instrumentation for anything that is new/missing
- Update the notion doc with details on the data to be used for each of the above (e.g., the event name, or the metadata) 

### Eng

**In the wallet:**
- [x] Home card impressions for the experiment should be emitted
- [x] Banner impressions in send flow should be emitted
- [x] new event for “account funded” defined specifically as user going from a zero to nonzero balance (nice to have - cash in type added as metadata - exchange, provider, transaction) (define "zero balance" as less than $0.01 USD, event is triggered on total balance change)
- [x] new event for “account liquidated” defined specifically as user going from nonzero to zero balance

**In the invite rewards project:**
- [x] Ability to determine who was rewarded for an invitation - needs to be done on the BE
- [x] Ability to determine who was the inviter for any rewarded invitees (or conversely, who was the invitee for any rewarded

**Comment by ellenwoconnor** [comment]
(updated event names slightly to reflect some feedback from retro)

**Comment by kathaypacific** [comment]
hey @ellenwoconnor how essential is it to have the cash in type added as metadata for the "account funded" event? from the wallet it is most correct to watch the total account balance to dispatch the account funded/liquidated events, but the balance is refreshed asynchronously so it is hard to know what event triggered it. with some effort i think we can do it, but we already have cash in/out and transaction events for the user so could we get this information with a funnel instead of metadata?
