### ISSUE TITLE
Figure out precise requirements for FiatConnect Alfajores deployment and test suite

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2212]
We currently require FiatConnect partners to have a deployment of their API on testnet for (integration) testing purposes, but we don't specify precisely what the behavior of that API should be. For example, rather than having all endpoints succeed at all times on testnet, we should probably specify some mechanism by which a client can trigger failures on certain endpoints. This PR is for coming up with a specification of how the testnet deployment should behave, such that clients are able to test all relevant behavior of the API.

While designing this, thought should also go into how we can run a standardized integration test suite against testnet deployments. For example, testnet deployments should probably support all the same crypto/fiat types, KYC/FiatAccount schemas as the mainnet deployment; a test suite should probably take these in as parameters, rather than assuming that every provider's API will support transfers for the same type of currencies/KYC/FiatAccount schemas. We should figure out how a test suite might look, what data it will require from each partner, how to handle mocking data for KYC/account schemas, etc.

Following the above point, this ticket also covers coming up with a "comprehensive" list of tests that an integration test suite should implement; passing this test suite is an indicator of FiatConnect-compliance. This will be especially important as more partners integrate, and for awarding Connect the World incentives. This does not cover actually implementing such a test suite, just figuring out what one ought to test for.

AC:
- doc outlining testing process Valora can use to verify functionality of an FC API
- process should be able to be used by partners themselves, or anyone (Celo Foundation for instance)

**Comment by cajubelt** [comment]
some initial thoughts:
- different kyc schemas and account schemas will be used per partner
- need to be able to simulate kyc failure, transfer failure

**Comment by cajubelt** [comment]
user story: need to be able to verify that api is up to spec

**Comment by cajubelt** [comment]
former AC (so we can write other issues as needed) :

AC:
 * Spec updated with specific requirements for an Alfajores deployment
 * Scope of potential future test suite determined and made available internally
