### ISSUE TITLE
Implement "full flow, transfer out" integration test for FiatConnect APIs

### ISSUE THREAD

**Issue by jophish** [valora-inc/wallet#2214]
This ticket is for implementing the "full flow, transfer out" tests for FiatConnect, described [here](https://github.com/fiatconnect/docs/blob/main/e2e-plan.md#full-flow-transfer-out-webhooks); this includes both the webhook and polling cases. A starter repo is available [here](https://github.com/fiatconnect/fiatconnect-validate).

In the future we may open source these tests, so partners can use them to test their own implementations. (Deciding whether to do this is outside of the scope of this issue. May reinforce the perception that Valora handles QA...)

AC:
 * Full flow, transfer out tests are written and added to the repo linked above. 
 * Includes test for polling and test for webhook
 * different sets of mock data / schemas / config can be supplied by a json file so we can test different providers

**Comment by cajubelt** [comment]
Silas started this here https://github.com/fiatconnect/fiatconnect-validate

**Comment by cajubelt** [comment]
plan is here: https://github.com/fiatconnect/docs/blob/main/e2e-plan.md
