### ISSUE TITLE
User is not able to see Recently used Dapps on the Homepage after navigating to an external Dapp via Dapps section

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2222]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.28.1, Test flight Release Build V1.28.1 
**Repro on devices:** Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Redmi Note 7 Pro(10.0)

**Does Not Repro on build version:** Android Alfajores Build V 1.28.1, iOS Alfajores Build 1.28.1
**Does Not Repro on devices:** Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Redmi Note 7 Pro(10.0)

**Pre-condition:** 

  1.  User must have installed the application and completed the onboarding flow.
  2. User must be on the Homepage.
  
**Repro Steps:**

 1. Tap on Hamburger menu.
 2. Tap on the Dapp option.
 3. Select any Dapp option and tap on the “Go to dapp name” button.
 4. Tap on the Device back button.
 5. Tap on the Home page from the Hamburger menu and observe.
 
**Bug:**  User is not able to see Recently used Dapps on the Homepage after navigating to an external Dapp via Dapps section

**Expected Behavior:** User should be able to see Recently used Dapps on the Homepage after navigating to an external Dapp via Dapps section

**Attachment:** [Dapps.mp4](https://drive.google.com/file/d/1ZxL3F6ve3YIcIH1MQxBi85NtqJAztfiB/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on  Latest Test Flight Release build V1.29.2, Android Internal Release Build V1.29.2, Test Flight Alfajores Build V 1.29.2 and Android Alfajores Build V 1.29.2 & observed the following:

- Recent Dapps Section is visible on Home screen for Alfa jores build V1.29.2 on both iOS and Android Platform.
- Recent Dapps Section in not Visible on Home screen for Release build V1.29.2 on both iOS and Android Platform.  

**Devices:** Google Pixel 2XL (11.0), iPhone SE 2020 (14.8.1), iPhone 7 (13.3), Google Pixel 4a (12.0)
Thanks..!!

**Comment by MuckT** [comment]
@ValoraQA The maxNumRecentDapps was behind a feature flag and has now been bumped to 8 on mainnet as such the recently used Dapp Section should now be visible on 1.29.2. Please reopen if it is not visible.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.29.2 & Test flight Release Build V 1.29.2 and observed that the issue is fixed now. User is able to see Recently used Dapps on the Homepage after navigating to an external Dapp via Dapps section, hence we are closing the issue.

**Devices:** iPhone 13 mini(15.1.1), iPhone XR(14.6), Google Pixel 2XL (11.0), Google Pixel XL (10.0)

**Attachments:** [Dapps.mp4](https://drive.google.com/file/d/1wab57iJO-FaS-tUpPIA2_hcsx0NDlco-/view?usp=sharing)

Thanks..!!
