### ISSUE TITLE
When user scan QR code without phone number verification it asks to connect phone number for purchasing a product

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2224]
**Frequency:** 100%

**Repro on build version:** Android Alfajores build V1.28.1, Test flight Alfajores build V1.28.1
**Repro on devices:** iPhone 12 (14.7.1), iPhone 13mini(15.1.1), Redmi Note 7 pro(10.0), Google Pixel 2XL (11.0)

**Pre-condition:** 

  1.User must have installed the app.
  2. User must have skipped the phone number verification
  3. User must be on the Homepage.
  4. User must have some funds in the account.
  
**Repro Steps:**

  1. Navigate to the website "https://sandbox-celo-demo-store.demo.firstdag.com/" on the desktop browser.
  2. Tap on Pay with cUSD for any product , QR code will be seen generated
  3. Tap on the QR code scanner from the Homepage.
  4. Scan the QR code and observe.
  
**Query:**   Should connect phone number popup should be displayed when user scan qr code if the  phone number is not verified.

**Expected Behavior:**  User should be able to  purchase the product without confirming phone number.

**Attachment:** [Connect phone number.mp4](https://drive.google.com/file/d/16vQRFTetV0kgaFfSHTS7lD2SG9o9nahv/view?usp=sharing)

**Comment by MuckT** [comment]
@jeanregisser can you comment on this I also saw the same behavior when testing the merchants payments.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest iOS alfajores build and Latest Android Alfajores build V:1.37.0 and observed that issue is fixed

Observation : Even without phone number verification user is able to complete the payment

Attachment : [payment.mp4](https://drive.google.com/file/d/1sQ7ZarfCZknhMV9YqkWothFqiPqLImXr/view?usp=sharing)

Device : Google Pixel 2XL(11.0) , iPhone 12(14.7.1)
Thanks
