### ISSUE TITLE
Ensure exchanges are up to date

### ISSUE THREAD

**Issue by lvsuttie** [valora-inc/wallet#2228]
For some users, exchange is their only option to cash in. We want to ensure we have the most up-to-date list of exchanges for all supported asset based on the user's IP address.

[CICO Pipeline doc](https://www.notion.so/valora-inc/4064d282a04c4dde80d83bb85b37dbc9?v=9f3b0cac8a944e42bc14da87881e2188) will take some time to get up to date.  In the meantime, we will prioritize a few specific exchanges and markets in this ticket

AC:
- Users see the correct list of exchanges if they are from: US, Brazil, UK, Philippines, Nigeria, Spain
- For global exchanges, all users in supported countries can view.

**Comment by cajubelt** [comment]
more important part is to be able to stay current with a list of providers (secondary goal: filter by what's available in the user's geo)
