### ISSUE TITLE
[Query] ”Celo Tax ” dapp name is not displayed in connection prompt in Valora app when user tries to connect the celo tax  to valora app 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2236]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.28.1, iOS Test flight Release Build V1.28.1 
**Repro on devices:**  iPhone 13 mini (15.1.1), Samsung Galaxy A9 Pro(8.0), iPhone 6+(12.5.5)

**Pre-condition:** 
1.User must have installed the app & completed onboarding flow.
2.User must have opened https://www.celo.tax/ in a web browser.
3.User must have received wallet connect prompt for celo tax in application.

**Repro Steps:**
1.Check the wallet connect prompt UI and tap on the “Allow” button from the connect prompt for Celo Tax finance.
2.Navigate to the “Connected Apps” sections from the settings screen and observe.

**Query:** “Celo Tax ” dapp name is not displayed in connection prompt in Valora app when user tries to connect the celo tax  to valora app

**Expected Behavior:** “Celo Tax ” dapp name must be displayed in connection prompt in Valora app when user tries to connect the celo tax  to valora app

**Attachment:** 
[Celo Tax.jpg](https://drive.google.com/file/d/1msVLi6VxrNDZ6Zm_gNjgZh_8VuRG1FFw/view?usp=sharing) 
[Celo Tax prompt .jpg](https://drive.google.com/file/d/19fW410tuAkguQLwR0Ii1ON-HxJAtLLVV/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA this is likely an issue with Celo Tax; it appears the app was submitted to the Dapp List in this [PR](https://github.com/valora-inc/dapp-list/pull/46) so we'll have to dig up some contact information for Celo Tax.
