### ISSUE TITLE
"QR code read fail.." error is displayed when user scan QR code using revo.market browser tab from the scan section of connected apps. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2237]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.28.1, iOS Test flight Release Build V1.28.1 
**Repro on devices:**  iPhone 13 mini (15.1.1), Samsung Galaxy A9 Pro(8.0), iPhone 6+(12.5.5)

**Pre-condition:** 

 1. User must have opened https://revo.market/#/zap in Browser.
 2. User must have opened the Valora wallet QR code by tapping on the connect to a wallet button.
 3. User must be on the Connected Apps screen from Settings.
 
**Repro Steps:**

 1. Tap on the “Scan” button from the Connected Apps screen.
 2. Scan the QR code from revo.market browser tab and observe.

**Bug:** ”QR code read fail.." error is displayed when user scan QR code using revo.market from the scan section of connected apps.

**Expected Behavior:** User must be able to scan QR code using revo.market from the scan section of connected apps.

**Impact**: Bad user experience as the user is not able to connect the wallet by scanning QR code.

**Investigation:** 
1. User is able to connect the revo wallet to the application via deep linking through the mobile browser.
2. User is not able to see revo dapp in the connected app screen.
3. User is not able to see impact market dapp in the connected app screen. [Impact market.mp4](https://drive.google.com/file/d/1d7GJ52YNsLjKBdtvJyrmAwl8rAJakN1v/view?usp=sharing) 

**Attachment:** [QR code.mp4](https://drive.google.com/file/d/18hp7Q5N9C8LfRkPWn4WaDEdtStA98Vhj/view?usp=sharing)

**Comment by MuckT** [comment]
@cajubelt can you take at the first two items? I was also unable to connect via desktop to mobile.
- User is able to connect the revo wallet to the application via deep linking through the mobile browser.
- User is not able to see revo dapp in the connected app screen.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Test Flight Release Build V1.29.2 and Android Internal Release Build V 1.29.2 observed the following:

- ”QR code read fail.." error is displayed when user scan QR code using app.ubeswap.org from the scan section of connected apps.
- "QR code is not generated when user browse https://www.impactmarket.com/ in Web browser while tapping on Wallet connect button.
**Note** : User is able to connect Impactmarket dapp by deeplinking from mobile browser.

**Attachment:**
[Ubeswap.mp4](https://drive.google.com/file/d/1G8t5Pez2zS9iJ7J7TC3WRfcr1K0zKepZ/view?usp=sharing)
[TalentProtocol.mp4](https://drive.google.com/file/d/1AEyncZHY7GAyk7qwjdVrOmgTVitWY-wC/view?usp=sharing)
Thanks..!!
