### ISSUE TITLE
Block OFAC countries in onboarding

### ISSUE THREAD

**Issue by hdenisse** [valora-inc/wallet#2243]
New guidance from Julie and our AML compliance consultant requires us to take every effort possible to ensure we're not providing access to users in 4 countries on the OFAC list:
Cuba
North Korea
Iran
Syria

We already do not list the app in those countries on the app and play store.

We now need to remove these 4 countries from the dropdown for country code selection currently in onboarding, and in the future for verification.
If there are other things that we can implement to block users in these countries (IP blocking based on geo for instance) we should consider them.

currently, we have the following user numbers:
Cuba 11
North Korea 0
Iran 115
Syria 5

AC
- Remove the above countries from the phone verification country list.

**Comment by cajubelt** [comment]
> If there are other things that we can implement to block users in these countries (IP blocking based on geo for instance)

We could do that

**Comment by cajubelt** [comment]
though I can't speak to whether it will be worth the time

**Comment by cajubelt** [comment]
should Russia be on here? (Laura will follow up on this)

**Comment by cajubelt** [comment]
fine to hardcode in the wallet for now

**Comment by cajubelt** [comment]
needs separate issue:
- Suggest, if applicable, other things we can do to block users in these specific countries. Implementation not required.
