### ISSUE TITLE
[Query] : Sorting of the token is also applicable on view assets page similar to seen on enter amount page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2262]
**Frequency :** 100%

**Repro on build version:** Android Internal Release Build V:1.29.0,iOS Internal TestFlight Release Build V:1.29.0
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone SE 2020(14.8.1), iPhone 7(13.3)

**Pre-condition:**
1] User must have downloaded the application 
2] User must have multiple token balance in the account 
3] User must be on homepage

**Repro Steps:**
1] Tap on view assets from homepage 
2] Observe the sorting of the tokens

**Query :** 
- Sorting of tokens is also applicable on view assets page as we are able to see the highest token balance on top of the list
- It should appear similar to the sorting seen on enter amount page after clicking on multitoken pill
 
**Current Behavior :** The highest token balance is seen on top of the list on view assets page 

**Attachment :** [sorting](https://drive.google.com/file/d/1YidHoRHllrkGT-kWeyy4q3Q3-lrsioWt/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA The token balances screen should have the same order logic as before and the new order should only be applied when selecting a token to send.
