### ISSUE TITLE
“Transaction failed. Please retry” error appears in red banner on Sending screen when user tries to send Max cREAL token.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2263]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.29.0, V1.29.1, iOS Test flight Release Build V1.28.1, V1.29.0, V1.29.1
**Repro on devices:** Google Pixel 2XL (11.0), iPhone SE 2020 (14.8.1), iPhone 13 mini (15.1.1)

**Does Not Repro on build version:** iOS Test flight Release Build V1.29.0, Android Internal Release Build V1.29.1
**Does Not Repro on devices:** iPhone 7 (13.3), Redmi note 7 Pro (10.0)

**Pre-condition:** 
1.User must have completed on boarding flow
2.User must have valid cREAL balance.
3.User must be on “Enter amount” screen and selected cREAL from multi-token popup

**Repro Steps:**
1.Tap on “Max” button on Enter Amount screen.
2.Tap on “Review”  button.
3. Tap on “Send” button on sending screen & observe

**Bug:**  “Transaction failed. Please retry” error appears in red banner on Sending screen when user tries to send Max cREAL token.

**Expected Behavior:**  No error should appear on Sending screen when user tries to send Max cREAL token & user should be able to send cREAL by tapping on Max button.

**Investigation:** 

- This issue is not reproducible when user tries to send valid cREAL amount less than Max amount by entering amount in Enter amount screen.

- This issue is not reproducible when user tries to send Max amount for cUSD, cEUR, CELO & Test tokens

**Impact:** Bad user impact as user is not able send Max cREAL after tapping on max button.

**Attachment:** [Max cREAL issue.mp4](https://drive.google.com/file/d/1lR--nuTfu_62ugi9CiRj9WfQjj12yL2_/view?usp=sharing )

**Comment by MuckT** [comment]
@Gonza could this be fee estimation?

**Comment by ValoraQA** [comment]
Hey @MuckT,  We have verified this issue on Latest Android Internal Release Build V1.29.2, Test flight Release Build V1.29.2 & observed that the issue is fixed now, User is able to send Max cREAL by tapping on MAx button and completing the send flow successfully without an error.
Hence we are closing this issue.

**Devices:** iPhone 13 mini (15.1.1), Google Pixel 4a (12.0), iPhone SE 2020 (14.8.1)
**Attachment:** [Max cREAL sent.mp4](https://drive.google.com/file/d/1nOW9H4tVM4RfzhgfV-7woaRqH7jV1R60/view?usp=sharing) 
Thanks..!!
