### ISSUE TITLE
[CI improvements] Reduce e2e test flake from wallet connect tests

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2272]
### Description

It was mentioned in several retros that flakey e2e test results are causing trust issues in the CI, and genuine errors caught by the CI are sometimes ignored because of this. As we do not have an easy way to track the success rate of each test individually, we are acting on anecdotal feedback and starting improvements with the perceived most flakey test: Wallet connect.

### Acceptance criteria
- [ ] On iOS and Android, running the wallet connect tests 10 times consecutively should yield at least 9 successful runs

### Eng details
Perhaps @MuckT has some pointers on where to start investigation

**Comment by MuckT** [comment]
Fixed by #2277.
