### ISSUE TITLE
Run e2e tests locally with one command

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2273]
### Description

It was mentioned at retro that it is difficult to run the e2e tests locally, some team members have lost whole days trying to do this. To reduce the friction and improve developer experience, minimise the amount of manual set up work that needs to be done.

### Acceptance criteria
- [ ] Set up and launch the end to end tests locally with minimal steps, ideally with one command 
- [ ] Review existing README instructions and ensure they are up to date

**Comment by MuckT** [comment]
@kathaypacific will be covered in #2277!

**Comment by kathaypacific** [comment]
thanks @MuckT ! i pulled this into the sprint, it'd be great if you could put an estimate on :)

**Comment by MuckT** [comment]
Running the e2e tests takes two commands as seen in [e2e/README.md](https://github.com/valora-inc/wallet/tree/main/packages/mobile/e2e#running-the-tests).
