### ISSUE TITLE
[Spike or fix] E2E test flake in blockchain-api

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2274]
### Description
It's reported that the e2e tests for the blockchain-api project are failing with test flake a lot in the CI (but not locally). This makes it more difficult and frustrating to merge code, and reduces confidence in the test results.

Previously @dievazqu had spent some time investigating but could not find the root cause easily, so creating this ticket to block time to properly investigate.

### Acceptance criteria

- As we are unsure of the root cause, timebox this work to x days.
- At the minimum, find the root cause. If time allows, fix the issue as part of this task or else create a new task to be prioritised.
- the desired outcome is that tests should have at least 90% reliability (9/10 retries should be successful)

**Comment by MuckT** [comment]
@dievazqu @kathaypacific I'd be happy to take a look at this code and see if I can help!
