### ISSUE TITLE
“There was an error loading..” error  is displayed when the user tries to scan the QR code from Merchant Payment url while creating the account while skipping the phone number.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2275]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.29.2, v1.29.1, V1.29.0 , iOS Test flight Release Build V1.29.2, V1.29.0, V1.29.1
**Repro on devices:** Google Pixel 2XL (11.0), iPhone 7(143.3), iPhone 13 mini (15.1.1), Google Pixel 4a(12.0)

**Pre-condition:** 

 1. User must have installed the app.
 2. User must have skipped the phone number verification
 3. User must be on the Homepage.
 4. User must have some funds in the account.
 
**Repro Steps:**

 1.Navigate to the website "https://prod-celo-demo-store.demo.firstdag.com/" on the desktop browser.
 2.Tap on Pay with cUSD for any product , QR code will be seen generated
 3.Tap on the QR code scanner from the Homepage.
 4.Scan the QR code and observe.

**Bug:** “There was an error loading..” error  is displayed when the user tries to scan the QR code from Merchant Payment url while creating the account while skipping the phone number.

**Expected Behavior:**  User should be able to scan the QR code and transaction should be performed and no error should be displayed.

**Investigation:**
1. When the user has created the account by skipping the Phone number and has a $0.00 balance and when the user tries to scan the QR code the same error is displayed.
2. "Your payment failed to submit" error appears , transaction fails & user redirects to home screen when user taps on Send button and complete sending flow after scanning QR code from merchant payment website for both iOS & android platforms after creating account & confirming phone number. [Attachment](https://drive.google.com/file/d/1zadpSf6Hi7gTmUh_q8P2g-ZRC_abc9b6/view?usp=sharing)
**Impact:** User is blocked from completing the send flow by scanning the QR code even if the user has a valid balance in the account.

**Attachment:** [MerchantPayment.mp4](https://drive.google.com/file/d/1sWw2Alxu-5CSBQM_fMa2Ib6oeD6Lo9g0/view?usp=sharing )

**Comment by ValoraQA** [comment]
Hey @MuckT , as per the attachment we have funds in our account and when we scan the QR code for purchasing the product then error is seen 
Ideally it should redirect to send amount page and after purchasing the product success message should be seen 
Thanks..!!

**Comment by MuckT** [comment]
@ValoraQA I see this error once or twice before the merchant payments work correctly on an unverified number, would you able to attach your logs for this issue?

**Comment by ValoraQA** [comment]
Hey @MuckT,We have verified & attached the logs as below.

**Logs:** [Logs.txt](https://drive.google.com/file/d/1iSi9KaZeR9kYs2ASLkSsQhLDP91vnykn/view?usp=sharing) 
**Device:** Google Pixel XL (10.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Android Internal Release Build, Test Flight Release Build V1.30.1 , with new merchant pay [url](https://prod-celo-demo-store.eu-west-1.demo.firstdag.com/) & observed that issue is fixed now. 
- User is able to complete merchant payment flow by given [url](https://prod-celo-demo-store.eu-west-1.demo.firstdag.com/) by scanning QR code & order get placed.

Hence we are closing this issue.

**Devices:** iPhone 13 mini (15.1.1), Google Pixel XL(10.0) 
**Attachment:** [Merchant Payment.mp4](https://drive.google.com/file/d/1IIrJfSX43jhCE0Y8yUmDy2SIoRJmtDah/view?usp=sharing)
Thanks..!!
