### ISSUE TITLE
User not able to see the same entered data on the “Restore my Account” page when the user redirects back from the “Restore Existing Wallet” page.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#228]
**Frequency:** 100%
**Repro on Devices:** Samsung Galaxy A5(7.0), iPhone XR (14.4), iPhone SE (14.2)
**Repro version :** Play store build V1.12.2 , App store build V1.12.2
**Login credential :** (515) 808 5659 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B69)
**Repro Steps:**

1. Launch the application and tap on “Restore my account” option.
2. Now upload profile picture, enter name & tap on “Next” button.
3. Now the user should be on the “Restore Existing Wallet” page.
4. Now tap on the “Cancel” button on the top left side.
5. Now again tap on “Restore my account” option.
6. Now the user should redirect back to the “Restore my Account” page.
7. Observed that,

**Actual Result:** Only the uploaded profile is displayed & Name gets removed from Full name field.
**Expected Result:** All details should display the same as entered before after redirecting back to Restore my Account page.
**Attachment:** [AllFieldDataNotDisplayedAfterRedirectingBack.mp4](https://drive.google.com/file/d/10vWvusJoVFl3RArWLqIzwgdA5G6p1-0Y/view?usp=sharing)

**Comment by gnardini** [comment]
This does look like a bug :)

**Comment by Celoqa** [comment]
Thank you so much @gnardini for comment :)
