### ISSUE TITLE
Crash on the reCAPTCHA - Older Android Devices

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2292]
### Current behavior
When completing onboarding with an Android 5 device. Valora crashes on reCAPTCHA.

### Desired behavior

Users should be able to onboard with an Android 5 device.

### Steps to Reproduce

Prerequisites: Android 5 device in In release mode.
1. Attempt to complete onboarding with an Android 5 device.
2. Observe crash on reCAPTCHA.

### Versions
Likely all versions after [Valora 1.24.1](https://github.com/valora-inc/wallet/releases/tag/valora-v1.24.1).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Playstore build V 1.35.0 and observed that we are not facing crash issue on captcha screen

Attachment : [No_Crash.mp4](https://drive.google.com/file/d/1_b5oeb6yj4n3p6oW1vlFmdm6ybj_-xaV/view?usp=sharing)

Thanks.!!

**Comment by ellenwoconnor** [comment]
captcha is not in CPV experience
