### ISSUE TITLE
SPIKE: investigate reported latency issues

### ISSUE THREAD

**Issue by ellenwoconnor** [valora-inc/wallet#2293]
We have received some complaints from users about app performance (https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/support-issues/44). We have a separate epic for holistic investigation into app performance (https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/wallet/1355). In the meantime we'd like to see if there are any quick fixes or obvious problems that we can identify. 

This spike is for a timeboxed investigation into app performance. The outcome is:
* write tickets for fixes to discovered problems describing the nature of the fix, the impact we expect it to have, and how confident we are about the impact
* write tickets for instrumentation to be added to any extra suspected problem areas on top of #1462

**Comment by jh2oman** [comment]
Another more recent complaint about app performance: https://app.zenhub.com/workspaces/support-60957db9f70419001370b620/issues/valora-inc/support-issues/121
