### ISSUE TITLE
Select Asset from Send/Request flow cannot handle large text or long token names

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2295]
### Current behavior
When using the select asset bottom sheet from the send or request flow, long token names and/or large font break the layout of the bottom sheet.

### Desired behavior
Layout should be handled with two columns with ellipses being uses to truncate longer text.

### Steps to Reproduce
Prerequisites: Have multiple assets in Valora.
1. Begin the send flow and select a contact or address.
2. On the Send amount screen tap on token selection to bring up the Select Asset bottom sheet.
3. Observe layout.

### Versions
All versions since at least [1.22.0](https://github.com/valora-inc/wallet/releases/tag/valora-v1.22.0).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue on Latest Android Internal Release build and Latest iOS TestFlight Release build V:1.29.2 and we are able to reproduce the issue as per the mentioned step above.

Attachment : [overlapp.mp4](https://drive.google.com/file/d/1hcAYXgJk6KBUvpPybyMMiMoywT6zINO0/view)

Device : iPhone 12(14.7.1) , Google Pixel 2XL(11.0)
