### ISSUE TITLE
[Query] Should “Keep your funds safe. Set up your recovery phrase now.” CTA appear at the first position even if the user has the Pending token request CTA present.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2299]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.29.2 , iOS Test flight Build V1.29.2
**Repro on devices:** Google Pixel XL (10.0), iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel 2XL (11.0)

**PR link:** [Link](https://github.com/valora-inc/wallet/pull/1942)

**Pre-conditions:** 
1.User must have complete onboarding flow
2.User must have not set up the recovery phrase.
3.User must have at least one pending token request CTA.

**Repro Steps:**
1.Launch the app
2.On home screen swipe CTA from RHS to LHS and observe.

**Query:**  Should “Keep your funds safe .Set up your recovery phrase now.” CTA appear at the position even if the user has the Pending token request CTA present.

**Expected Behavior:** Pending token request CTA should be displayed at the first position.

**Investigation:** “Token request” CTA appear at Second Position after “Recovery phrase setup” CTA in both Android & iOS

**Attachment:** [Request CTA.mp4](https://drive.google.com/file/d/1NMQ7uVLOQONEVZMEz6Krpeqo7UOAQHsn/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA The priority of CTA's can be found in [here](https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/home/NotificationBox.tsx#L42-L48.). The higher the priority the further to the left it should display. As seen in this file, we would expected backup when not completed to always show up first as it has a priority of 1000 vs pending token requests priority of 900. Based on the code the described behavior is correct.

**Comment by ValoraQA** [comment]
Hey @MuckT, Thank you very much for the information. We will update testcases accordingly. Hence we are closing this query.
Thanks..!!
