### ISSUE TITLE
Dapps browser shows error ERR_UNKOWN_URL_SCHEME when connecting Valora

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#2306]
### Current behavior

This is happening on a Nexus 5, with Android 6.0.1
I personnally saw 2 other users at CeloConnect with this issue.

https://user-images.githubusercontent.com/57791/162963214-d4d52533-3f0c-4412-afd4-6d36fa6b4cf8.mp4

### Desired behavior

The dapp should connect to Valora without showing the error in the in-app browser.

### Steps to Reproduce

1. Open Ubeswap from the Dapps page
2. Tap to Connect Valora (sometimes Ubeswap triggers this directly on load).
3. Notice the error ERR_UNKNOWN_URL_SCHEME displayed in the webview

Note that it only affects specific devices / Android versions. I'm unable to reproduce this on a Pixel 4 running Android 11.

### Versions

Valora v1.29.2 on Android 6.0.1 (Nexus 5)

**Comment by kathaypacific** [comment]
One user at CC was able to repro this with Pixel 3A running Android 12. I could not repro using the Pixel 3A/Android 12 emulator, on Samsung A52s running Android 12 (physical device)
