### ISSUE TITLE
Wallet call fetchFiatConnectProviders and display

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2332]
AC:
* Wallet calls the new fetchFiatConnectProviders cloud function and quotes are displayed correctly on the SelectPayments screen

ENG:
* For now, tapping on the provider in the Select Payments screen need not do anything. (this ticket is just getting the quotes/providers to show up)

[Figma](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A16749)

![Screen Shot 2022-04-19 at 3.25.25 PM.png](https://images.zenhubusercontent.com/6185a7c8cdc62006d4e266fa/ea739dd7-831a-4a2e-baae-9be81c0676ba)

**Comment by cajubelt** [comment]
removing this from the sprint, since it is blocked by stuff that's unlikely to all be done in time
