### ISSUE TITLE
Enter Fiat Details Screen

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2333]
AC:
* After a user taps on a FiatConect provider in the SelectPayments screen they are taken to a new screen to enter their fiat account details
* A user can enter their account details, click 'Save & Continue', and their fiatAccount details are saved with the fiatconnect partner.
* All[ response types and error codes from the spec](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#33312-responses) are handled or logged including success, ResourceExists, UnsupportedSchema, InvalidSchema
* For the first FiatAccount schema add basic syntax checking. (Should be some in the schema)

ENG:
* Tapping 'Save & Continue' does not need to take the user to the next screen yet. 
* Run the "Validation" when the user presses 'Save and Continue'

[Figma](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A17381)

![Screen Shot 2022-04-19 at 3.26.21 PM.png](https://images.zenhubusercontent.com/6185a7c8cdc62006d4e266fa/72e0e62a-55b9-4d15-9140-a2ad2bc51e40)

**Comment by cajubelt** [comment]
estimated 3 points rolling over into next sprint
