### ISSUE TITLE
Cash In/Out Review Screen UI

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2334]
* After a user successfully enters in their fiat Information, they are taken to a Review Purchase page
* The Review purchase screen shows them their estimated fees and payment method.

ENG:
* The payment method does not need to be tappable yet
* Buy Now button does not need to do anything

[Figma](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=940%3A17381)

![Screen Shot 2022-04-19 at 3.27.07 PM.png](https://images.zenhubusercontent.com/6185a7c8cdc62006d4e266fa/3c0e7212-df1f-44ca-acd4-7ccecc846f49)

**Comment by lvsuttie** [comment]
laura and nitya to modify this screen for cash out specific review screen
