### ISSUE TITLE
Bug - Fix Ramp Availability

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#2343]
Ramp does not support bank transfers in the US, but currently we display it for the US.

AC:
* Ramp does not show up as a Bank Account cash-in option in the US

**Comment by cajubelt** [comment]
should also message Ramp to ask them to not give quotes for payment types that don't actually work

**Comment by jh2oman** [comment]
This is actually a bug in the wallet which will be fixed by https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/2196. Closing ticket
