### ISSUE TITLE
Decrease number of errors sent to Sentry

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2350]
### Description
It costs money to send errors to Sentry. Since we started sending all errors to Sentry, we've had to upgrade our plan continuously which is unscalable as we grow. We exceeded 1M errors in 10 days in April. 

The intended outcome of this task is to reduce noise in Sentry and keep the error count below 1M for the month, of course this will be hard to know during implementation so this issue is just a start. Sort errors in Sentry by number of events, tackle the errors with the high frequency. evaluate if we want to keep seeing them, if the answer is no then update the wallet to prevent them from being sent to Sentry. If root cause is known, we can fix or create issues to fix later.

### Acceptance Criteria
- [ ] Identify errors that occur frequently that do not add value in Sentry
- [ ] Either fix the errors (if straightforward) or update them to stop sending to Sentry
- [ ] Add a way to silence errors on the fly (e.g. we do this via remote config for network errors, we could add a similar approach for all other errors)

**Comment by silasbw** [comment]
Some chatty errors to silence:
* [Network error: Network request failed](https://sentry.io/organizations/valora-inc/issues/3010115802/?project=1250733&query=is%3Aunresolved&sort=freq&statsPeriod=30d)
* [Reading from Firebase @ tokensInfo timed out.](https://sentry.io/organizations/valora-inc/issues/2965970959/events/latest/?project=1250733&query=is%3Aunresolved&statsPeriod=30d)
* [Geth initializtion timed out. Will retry.](https://sentry.io/organizations/valora-inc/issues/3117197611/?project=1250733&query=is%3Aunresolved&statsPeriod=30d)
