### ISSUE TITLE
Redesign of Add Funds flow

### ISSUE THREAD

**Issue by tarikbellamine** [valora-inc/wallet#237]
Redesign add fund flows based off these designs: https://www.figma.com/file/3snvsYgTmgv4sNMIUpA4mM/CICO-2?node-id=2153%3A31

**Comment by gnardini** [comment]
I see this :(

![Screen Shot 2021-04-14 at 12.54.23.png](https://images.zenhubusercontent.com/5f903be75ae85a85a7e33752/6a7e0304-be33-48ec-8579-0a0da9ccee9a)

**Comment by Celoqa** [comment]
Hey @tarikbellamine FYI: We are also facing same error using celoqa@lodestoneco.com can you please do the needful.
**Attachment:** [FigmaError.png](https://drive.google.com/file/d/16uJJHOXsODXYq6oqt1stJMFol2rh98oa/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Closing because this is stale
