### ISSUE TITLE
Extra white space is seen below review button when user comes back from scan QR code page to withdraw Amount page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2377]
**Frequency :** 100%

**Repro on build version:** Android Internal Release Build V:1.30.1 Android Playstore Build V:1.30.1 
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0)

**Does not Repro on build :** iOS Internal TestFlight Release Build V:1.30.1,iOS Appstore Build V:1.30.1
**Does not Repro on device :** iPhone 12(14.7.1), iPhone 13 mini(15.1.1)

**Pre-condition:**
1] User must have installed the application
2] User must have completed onboarding process
3] User must have funds in the account
4] User must be on CELO landing page

**Repro Steps:**
1] Click on Withdraw CELO
2] click on account address field 
3] keyboard will be seen opened
4] now click on scan qr code 
5] scan a wrong QR code and observe the withdraw CELO page 

**Bug :** Extra white space is seen when user uses device back to come back to CELO withdrawal page

**Expected Behavior :** No extra space should be seen and review button should be seen on its original place

**Investigation :** 
- it works fine on iOS application as review button is seen on its original place

**Impact :** Bad user experience 

**Attachment :** [space.mp4](https://drive.google.com/file/d/1vlnycokZUDiqke2W_WzkOpNbVR1sBcoo/view?usp=sharing)

**Comment by pedro-rivas** [comment]
@ValoraQA a good first issue?
