### ISSUE TITLE
initiate transfer out implementation

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#2387]
As an end-user, I need to be able to initiate a transfer out from the review page.

Our existing FiatConnect partners do not require a waiting period between creating a transfer and sending the crypto for a transfer out. (Should confirm this explicitly with BitSSA and PayChant before beginning work on this.) So let's avoid over-optimizing for potential future partners that *do* require this, and add in the extra complexity if/when the need arises.

AC: Tapping "confirm" on the transfer review screen should
- submit a transfer out request to the provider
- send crypto to the provider
- show a spinny wheel until the tx is confirmed
- show a catch-all error screen with a retry button if the request to initiate a transfer fails, or if the tx fails for some reason
- show a success screen once the tx is confirmed, similar to this one for transfers in:

ENG:
* Verify using the mock provider in alfajores
* If the transaction fails because they don't have enough gas, send out a new quote for the total - gas fees.

![image.png](https://images.zenhubusercontent.com/6111ac24d41f1f9b126e0988/a2fa57ee-01b0-42fd-840f-529458d8d69d)

**Comment by lisaqyli** [comment]
I feel the actual initiating a tranfer out request to the provider should happen on the prev screen, it would be really weird if that request failed and we showed the user "Your cUSD is on the way"
