### ISSUE TITLE
[Device Specific] Uploaded Photo not shown in profile icon on Create Account page.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#239]
**Frequency:** 100%
**Repro on build version:** Play Store build V1.12.2
**Does not repro version:** App store build V1.12.2
**Repro on devices:** Samsung Galaxy S4(4.4.2)
**Does not repro devices** HTC Desire 526G+ (4.4.2) , samsung galaxy S4(5.0.1), LG K7i(6.0), Samsung  Galaxy A5(7.0), Samsung  Galaxy M31 (10.0) , iPhone XR (14.4.1), iPhone 6+ (12) 
 **Repro Steps:**
1. Launch the application & select “Create Account” option.
2. Now tap on “Add Photo” icon & upload photo by selecting “Choose from Gallary” option.
3. Observed that, 
**Current Behavior:**  Uploaded photo not displayed in profile icon.
**Expected Behavior:**  Uploaded photos should display in the Profile icon.
**Impact:** Users are not able to see uploaded photos.
**Investigation:** Also we have observed same issue for editing profile through Settings option.
**Attachment:**  [ProfilePhotoNotBeingUploaded.mp4](https://drive.google.com/file/d/1myyf1Cli7PG8IWB1tN4J1QNC_cpEhwCv/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D74](https://valora.testquality.com/project/12128/result/2450313/defect/7999).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D83](https://valora.testquality.com/project/12128/result/2450767/defect/8025).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D84](https://valora.testquality.com/project/12128/result/2450768/defect/8026).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D87](https://valora.testquality.com/project/12128/result/2450818/defect/8030).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above on Android Internal Release build V 1.37.1 and observed that issue is not reproducible

Device : Samsung Galaxy A3(5.0.2)

Thanks..!
