### ISSUE TITLE
[Generating NFTs] #3 NTF deployer script

### ISSUE THREAD

**Issue by dievazqu** [valora-inc/wallet#2417]
### Description

Create a script that given a list of image urls and its metadata files urls which are stored in a ipfs (output of the image uploader service), deploys an ntf contract (erc-721) that allows those list of images be minted (I think only one address will be able to mint) .

### Questions
* From which address are we gonna deploy this?
create a new HSM - deploy from this address
* Who should be able to mint? The same address that deploys the contract is the only one that can mint?
only the HSM should be able to mint

### Acceptance Criteria
- [ ] When running the deployer, it reads a json containing the images and metadata urls, and deploys the nft contract (and returns the address of the deployed contract to be stored in firebase rtdb?). This has to be configurable to run in alfajores or mainnet.
- [ ] Test smart contract with https://hardhat.org/ - learn how to do this and share with the team
- [ ] create HSM

**Comment by kathaypacific** [comment]
@dievazqu will link example contract
