### ISSUE TITLE
Mocking in E2E Tests

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2421]
### Description
Currently our E2E tests don't rely on any mocks - this is good in some ways as we are fully testing integrations; however, bad in some ways as we cannot tests error responses and developers could have different results based on their location when running the e2e tests locally.

Some options on mocking: 
- Use the `isE2Eenv` within the code to return static responses as seen [here](https://github.com/valora-inc/wallet/pull/2403/files#diff-5ef00ffab335d316cb5502b5180170678be6a2e39efe72e802698fedecb527bc).
- Run an express server and point the e2e tests to hit these endpoints when testing locally.

#### External Links
- [Mocking network requests in detox E2E tests](https://brainsandbeards.com/blog/mocking-network-requests-in-detox-e2e-tests)
- [Mocking API backend, no effect? #2700](https://github.com/wix/Detox/issues/2700#issuecomment-826471598)
- [Detox Mocking Guide](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md)

### User Stories 
As a developer I want to be able to run the e2e tests locally and have the same results regardless of location, so that I can be sure that the tests that I write when testing locally will pass in CI.

### Acceptance Criteria
-  [ ] E2E tests do not have different results based on user location
-  [ ] E2E tests can test multiple response types from endpoints: 200's, 500's, 404's. (stretch)

**Comment by lisaqyli** [comment]
Some thoughts: I would prefer to somehow configure a deterministic app state for the e2e testing environment. location might be part of it, maybe there are other states to be configured as well.

**Comment by MuckT** [comment]
It would be great to be able to send different responses from a mock server in the e2e tests to test app state based on various server responses e.g. load the supercharge page when we have an amount to claim, when there nothing to claim, when there is an error response from the server.
