### ISSUE TITLE
[In-app swaps] Create 0x Api services for price and quote

### ISSUE THREAD

**Issue by dievazqu** [valora-inc/wallet#2424]
### Description

Create a service/wrapper over the 0x api in valora-rest-api, that the swap screen can use.
It must provide:
* a method to fetch the swap rate between 2 tokens: https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-price
* a method that executes the swap: https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-quote (it would be nice if this method receives the expected price for the swap, so we can avoid sending the transaction if the price changed too much).
* use signed message as authentication for both endpoints

### Acceptance Criteria
- [ ] Method for fetching exchange rates
- [ ] Method for executing the swap

**Comment by kathaypacific** [comment]
There is a rate limit of 3 requests/second for the 0x API - do we want to wrap this api (more flexibility) or call directly from the app (less rate limit issues)? @silasbw curious for your opinion

**Comment by kathaypacific** [comment]
@dievazqu will get Denisse's contact's advice
