### ISSUE TITLE
Automatically add new tokens to the GH list

### ISSUE THREAD

**Issue by dievazqu** [valora-inc/wallet#2425]
### Description

Create a cron (a cloud function or in blockchain-api), that checks for new tokens, and if there is a new token, it submits a PR to https://github.com/valora-inc/address-metadata adding the new token.

### Questions
* How do we decide which tokens to add?
  * We could check the liquidity pools in Ubeswap, if the token is present in some liquidity pool with more than $20k of liquidity, we add it.
  * Other ideas?

### Acceptance Criteria
- [ ] Create cron

**Comment by kathaypacific** [comment]
As the initial experiment will focus on only the CELO native tokens, let's tackle this task as part of a follow up
