### ISSUE TITLE
Contact list is never re-imported

### ISSUE THREAD

**Issue by tarikbellamine** [valora-inc/wallet#243]
### Expected Behavior
When a user adds a new contact to their phone's contact list, that new contact is also searchable in Valora.

### Current Behavior
Contact list is only imported once when the user installs the app. Any new contacts added to a user's contact list after Valora has been installed won't show up in Valora's contact options.

**Comment by etuleu** [comment]
One possible idea would be to store a hash of the entire phonebook and if it changed trigger a reimport. Or something along those lines.
