### ISSUE TITLE
Received CELO push notification is not received on User B’s device when User A withdraws CELO to User B.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2430]
**Frequency:** 100%

**Repro on build version:** Android Internal build V1.31.0, iOS Test flight build V1.31.0, iOS Appstore Build V1.31.0, Android Play store build V 1.30.1
**Repro on devices:** Moto G40 fusion (11.0), Redmi Note 5 pro (9.0), Google Pixel 2XL (11.0), iPhone 12 mini (15.4.1), iPhone 13 mini (15.1.1), Redmi Note 7 Pro(10.0)

**Pre-condition:** 
1. User A and user B must have completed the onboarding flow.
2. User B must have opened the app and backgrounded the valora app.
3. User A must have valid CELO balance & must be on withdraw CELO Screen. 

**Repro Steps:**
1.User A: Complete the withdraw CELO flow by scanning the User B’s qr code.
2.User B: Navigate to notifications screen and observe.

**Bug:**  Received Celo push notification is not received on User B’s device when User A withdraws CELO and User B opens and backgrounds the app

**Expected Behavior:**  Received Celo push notification must be received on User B’s device when User A withdraws CELO and User B opens and backgrounds the app

**Impact:** Bad user impact as user will not get idea of received CELO if app is in background state.

**Attachment:** [CELO push issue.mp4](https://drive.google.com/file/d/1blvu82f3xKsQiJj4tKjmYPAhbetasiU2/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Android Internal Release Build, iOS Test flight Release Build V1.32.0 & observed that the issue is fixed now.

- User B receives the Received CELO push notification when User A withdraws CELO to User B.

Hence we are closing this issue.

Devices: iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel XL (10.0), iPhone 12 (14.7.1)
Attachment: [CELO Push.mp4](https://drive.google.com/file/d/1JyZXpiTR5HWeTsPMgHagO7R7MpdDbz8t/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue Latest Android Internal build V1.34.0, Test flight release build V1.34.0 & iOS App store build V 1.34.0 and observed the following:

**Observation:**
- 
User B does not Received CELO push notification when User A withdraws CELO to User B.

Hence we are reopening the issue.

**Devices:** iPhone 12 mini(15.5), Google Pixel 4a (12.0), iPhone 7(13.3)

**Attachment:** [Push notification.mp4](https://drive.google.com/file/d/1SAc_Q-uQgAV0rG9nBM5zXJ7Mh_iq1_Te/view?usp=sharing)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Android Internal Release Build, iOS App store Build V1.35.0 & observed that the issue is fixed now.

- User B receives the Received CELO push notification when User A withdraws CELO to User B.

Hence we are closing this issue.

**Devices**: iPhone 13 mini (15.1.1), Google Pixel XL (10.0), Google Pixel 4a(12.0)

**Attachment:** [CELO Push.mp4](https://drive.google.com/file/d/1XsMXXuvt2dYZ4MJ0GUIXCISAf_pRbbc4/view?usp=sharing)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue on Latest Android Internal Release build V1.41.1 and Test flight release build V1.41.1 and observed the following:

**Observation**:
- 
For Android Platform: User B is not receiving CELO push notification when User A withdraws CELO to User B.
- 
For iOS Platform: User B receives the Received CELO push notification when User A withdraws CELO to User B.

Hence we are reopening the issue.

**Devices**: Google Pixel 4a (12.0), iPhone 13 mini(15.1.1), Google Pixel 2XL (11.0)

**Attachment**: [Android push notification.mp4](https://drive.google.com/file/d/1GE54LpxexqE9c8I40Y9mosQNYiQ-t_OK/view?usp=sharing)

Thanks..!!

**Comment by ellenwoconnor** [comment]
No withdraw flow anymore on CELO page
