### ISSUE TITLE
Pressing Back on Send From Confirm Account Address Prevents User From Sending

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2431]
### Current behavior

When users attempts to Send via Secure Send through the last four of the account number once they have successfully entered the values and arrived at the send screen pressing back takes them to the 'Confirm Account Address' Screen and they are unable to proceed.

### Desired behavior
User should be able to re-enter the last four digits and/or the previously entered values should be present.

### Steps to Reproduce
- Send to a phone number with multiple addresses mapped to it `+12057368924` (alfajores)
- Select 'Confirm Account Address'
- Type in the last four of the account address `FD08` and submit.
- From send navigate back to the 'Confirm Account Address' Screen.
- Resubmit - Nothing happens

### Video
https://user-images.githubusercontent.com/26950305/167182886-53d4702b-ce95-4870-a74d-5bef7a50226a.mov

### Versions
Valora 1.31.0

### Workarounds 
- Going back to the 'Please confirm your contact's account' Screen and proceeding forward through the steps works.

**Comment by ValoraQA** [comment]
Hey @MuckT we have already raised a bug for the above scenario and the ticket id is 
**Ticket id :** [link](https://github.com/valora-inc/wallet/issues/106)
Thanks..!

**Comment by MuckT** [comment]
Closing in favor of #106.
