### ISSUE TITLE
Batched updates for fiatconnect tooling

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#2449]
to bring them in sync with the spec as of today

**Comment by lisaqyli** [comment]
Checklist example -> https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/2359

**Comment by lisaqyli** [comment]
commits that goes into this task: https://github.com/fiatconnect/specification/commit/a8b8b638ac14579451c4cbccfff02029e046901a
https://github.com/fiatconnect/specification/commit/814e6c7214866d0b28ec00addcd2568800d7e5a0
https://github.com/fiatconnect/specification/commit/e3bcaaab5bcec5c13bfcbbe52e31969b387a36a2

also updated TransferStatusEnum

**Comment by cajubelt** [comment]
any reason this commit wasn't included @lisaqyli ? it's between two of the ones you have in that list https://github.com/fiatconnect/specification/commit/6ae3719c1189d20591a1153512247dd1298f22f4

**Comment by cajubelt** [comment]
My understanding is that all commits up thru May 10 should be included in the batch update. But it looks like this commit from before then is not https://github.com/fiatconnect/specification/commit/e175ee9acd92a462d8f3669278992ac10b40ac99
