### ISSUE TITLE
Pin pad scroll on iOS 

### ISSUE THREAD

**Issue by etuleu** [valora-inc/wallet#248]
### Expected Behavior

Pin pad should not be scrollable.

### Current Behavior

> the pin pad on iOS is scrollable. When tapping my pin, i often end up scrolling by mistake and the input is not captured (video attached). Can we remove the scroll gesture capture on this screen?

Thread: https://celo-org.slack.com/archives/C018VLA3YAK/p1609877824085600

**Comment by ValoraQA** [comment]
Hey @tarikbellamine   , We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Gsuite.
*GSuite Link:* https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1462650076

*Verified On Devices:* OnePlus 7t (11.0) , iPhone 6+ (12.5.4), Redmi note 8 (10.0), iPhone 12 (14.7.1)

*Observation:* 
- Scroll bar is not seen where ever PIN pages are applicable
Attachment : [Scrollbarnotseen.mp4](https://drive.google.com/drive/folders/1Hsc6JVEIpwTsOM10wNg_mbclisw8DTRJ)
*Verified on Devices* : iPhone 6+ (12.5.4), iPhone 12 (14.7.1)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R85](https://valora.testquality.com/project/12128/testcase/299598/requirement/11856).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**iOS (13.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485054

**Verified On Devices:** iPhone SE (13.6.1)
