### ISSUE TITLE
Push notification is not received for user B when user A taps on remind button from Waiting In-app cta

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2484]
**Frequency :** 100%

**Repro on build version:** Android Internal Release Build V:1.32.0, iOS, Test Flight Release Build V:1.32.0
**Repro on device :** Google Pixel 2XL(11.0), iPhone 12(14.7.1) , iPhone 13 mini(15.1.1) , Google Pixel 4a(12.0)

**Pre-condition:**

 1] User must have installed the application
 2] User must have completed onboarding process
 3] User A must have requested valid amount to user B and requested CTA must be present in user B account and waiting CTA must be presented in user A account
4] Background the app for User B 

**Repro Steps:**

 1]. For User A : Tap on Remind button from In-app CTA
 2]. Observe the Push notification for user B

**Bug :**  Push notification is not received

**Expected Behavior :** Push notification should be received

**Investigation:**
-  Payment request push notification is received for User B when user A Proceed for Payment request.

**Impact :**  User did not get the idea about received payment if an app is in background.

**Attachment:** [Push Notification.MP4](https://drive.google.com/file/d/1ZXpld81S4B0IsJWooOJAT_lUJIYJePqm/view?usp=sharing)

**Comment by ellenwoconnor** [comment]
Request for a triggered push, we probably will not do this as there is possibility for scams/hacks
