### ISSUE TITLE
 Invited amount is not getting updated in Total Balance section when user B creates the account with the same phone number invited by the user A

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2510]
**Frequency:** 80%

**Repro on build version:** Android Internal Release Build V1.32.2, iOS Test flight Release Build V1.32.2, Android Play store Build V 1.31.0
**Repro on devices:** Google Pixel 4a(12.0), iPhone 13 mini(15.1.1), Google Pixel 2XL(11.0), One Plus 7t(11.0)

**Pre-condition:** 

 1. For User A:  User A must have invite link to User B with some funds
 2. For User B: User B must have be on confirm screen page while creating the account with same phone number invited by user A
 
**Repro Steps:**

 1. For User B : Enter the valid confirmation code 
 2. For User B: Wait for sometime and observe
 
**Bug:** Invited amount is not getting updated when user B creates the account with the same phone number invited by the user A

**Expected Behavior:** Invited amount should get updated when user B creates the account with the same phone number invited by the user A

**Investigation:** 

 1. Escrow payment received is seen in the recent activity page and balance is not seen updated.
 2. If the user kills and relaunches the application then also balance is not seen updated.
 3. If the user refreshes the page then also balance is not seen updated.
 
**Impact:** Bad User Impact as balance is not getting updated 

**Attachment:** [Recent Activity .jpg](https://drive.google.com/file/d/1UBMNHOLRkYYWn1dPeuFRQjeTNy5JiO4i/view?usp=sharing ) 
[Balance.mp4](https://drive.google.com/file/d/16qW2Vh-yAJlx9C5EE9tpvbt6B5AF1pPv/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA can we retest to confirm that it's not a temporary issue with Blockscout.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have re-verified this issue using Latest Android Internal Release Build V1.32.2, iOS Test flight Release Build V1.32.2 & observed that the issue is fixed now.

- Invited amount is getting credited and also updated in Total Balance section when user B created the account with same phone number invited by user A.

Hence we are closing this issue.

**Devices:** Google Pixel 4a (12.0), Google Pixel 2XL (11.0), iPhone 13 mini (15.1.1)
**Attachment:** [Invites amount credited.mp4](https://drive.google.com/file/d/1-t1d780SF3FkShDZg503urWpntqbPZEU/view?usp=sharing)
Thanks..!!
