### ISSUE TITLE
Remove Account Name from Bank Account Info Withdraw flow

### ISSUE THREAD

**Issue by lvsuttie** [valora-inc/wallet#2520]
For FC, we currently have a required field in our spec for "account name" which is meant as a "nickname" for the Bank Account Name. My preference would be to only expose truly required fields to the user, as we do not want to introduce confusion about what "account name" is, and where do I find "account name" on my banking site. etc.

AC:

- [ ] Remove "account name" from the FE, so that a user is not required to manually enter it in. (we may also use the account name for displaying linked bank accounts in various places)

ENG:

- [ ] Use obfuscated account number for friendly account name

**Comment by lisaqyli** [comment]
Slack thread on this https://valora-app.slack.com/archives/C029MMTD529/p1652824837890179

**Comment by lvsuttie** [comment]
this is a dupe of #600
