### ISSUE TITLE
[Query] Should Authenticate to retrieve secret pop-up open when user locks and unlock the phone after trying many wrong attempts 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2558]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.33.0, Android Alfajores Build V1.33.0
**Repro on devices:** Google Pixel 4a (12.0), Google Pixel XL(10.0), Google Pixel 2XL (11.0)

**Pre-condition:** 

 1.User must have installed the app.
 2. User must be on Secure your wallet page 
 
**Repro Steps:**

 1. Tap on the “Turn on Fingerprint recognition” button.
 2. Enter the wrong attempts 4-5 times.
 3. Lock the phone 
 4. Now unlock the phone and tap on the “Turn on Fingerprint recognition” button and observe.
 
**Query:** Should Authenticate to retrieve secret pop-up should open when user locks and unlock the phone after trying many wrong attempts 

**Expected Behavior:**  Authenticate to retrieve a secret pop-up should open when the user locks and unlock the phone after trying many wrong attempts. 

**Investigation:** 

- Authenticate to retrieve a secret pop-up is not opening when the user locks and unlock the phone after trying many wrong attempts and tapping on the “Turn on fingerprint recognition” button user is redirected to the Phone number screen.

**Attachment:** [Fingerprint Biometric.mp4](https://drive.google.com/file/d/1CLfTmxMLQ9bq4Rvzkz9DzNqRDfz26oZA/view?usp=sharing)

**Comment by MuckT** [comment]
@kathaypacific it looks like we've failed to setup fingerprint verification; however, after completing the above reproduction steps fingerprint verification is enabled.
