### ISSUE TITLE
 [Query] Should the amount field on “Withdraw Funds” screen be pre-filled with the amount entered on the withdraw CELO screen when a user wants to withdraws CELO

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2567]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.33.0, Test Flight Release Build V1.33.0
**Repro on devices:** Google Pixel XL (10.0), iPhone 13 mini (15.1.1), Google Pixel 4a (12.0), iPhone 12 (14.7.1)

**Pre-condition:** 
1. User must have installed app and completed the onboarding flow.
2. User must be on “Withdraw CELO” screen after tapping on Next button , selecting CELO from withdraw funds screen 

**Repro Steps:**
1.Enter valid CELO amount in Amount field & tap on Next button.
2.Tap on “View exchanges” link on “Select Withdraw Method ” screen.
3.Tap on “Withdraw CELO” button at the bottom of “Exchanges” screen.

**Query:**  Should the amount field on “Withdraw Funds” screen be pre-filled with the amount entered on the withdraw CELO screen when a user wants to withdraws CELO

**Expected Behavior:** The  amount field on “Withdraw Funds” screen must be pre-filled with the amount entered on the withdraw CELO screen when a user wants to withdraws CELO

**Impact:** Bad user impact as user needs to enter CELO amount twice to perform withdraw CELO flow.

**Attachment:** [Withdraw CELO.mp4](https://drive.google.com/file/d/1kUi7xAPCQd1WW28djcGQJUuuRJzFyIqV/view?usp=sharing)

**Comment by MuckT** [comment]
@jh2oman should we pass the amount of Celo to that is entered in the Withdraw celo screen to the old celo send flow, skip the first Withdraw Celo screen, or leave it as is for now?
