### ISSUE TITLE
Homefeed improvement: make total balance in sync with transaction feed

### ISSUE THREAD

**Issue by kathaypacific** [valora-inc/wallet#2578]
### Description
The total balance displayed is not in sync with the transaction feed. We are refreshing both independently, which means sometimes a new transaction can appear on the homefeed without the total balance refreshing. This is a clunky and incorrect experience, and may lead to confusion.

### Considerations
- Users can pull to refresh on the homescreen to re-sync the feed and balance. i.e. there is a workaround
- Does the upcoming homefeed design refresh and potentially hiding balance decrease the priority of this work?

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our comment on PR : #2818
