### ISSUE TITLE
Flickering on the screen is observed when the user taps on the Dismiss button from the Dapps page  

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2588]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.34.0
**Repro on devices:** Google Pixel 4a (12.0), Google Pixel XL(10.0), Google Pixel 2XL (11.0)

**Does Not Repro on build version:** iOS Test Flight Release Build V1.34.0
**Does Not Repro on devices:** iPhone 13 mini(15.1.1), iPhone 12(14.7.1)

**Pre-condition:** 

 1. User must have installed the app and completed the onboarding flow.
 2. User must be on Homepage
 3. User must be on Dapps page
 
**Repro Steps:**

 1. Tap on the “Ubeswap” dapp option.
 2. Tap on “Go to Ubeswap” button from the popup
 3. Tap on the triple dot from the bottom right corner.
 4. Tap on Dismiss button & observe
 
**Bug:** Flickering on the screen is observed when the user taps on the Dismiss button from the Dapps page.

**Expected Behavior:** Flickering on the screen should not be observed when the user taps on the Dismiss button from the Dapps page.

**Investigation:** 

1. This issue is not reproducible on iOS platform. [iOS behaviour.mp4](https://drive.google.com/file/d/1FnxxNZphCcoZ2rDpQ58TH8Rhf9aSbQEZ/view?usp=sharing)
2. This issue is reproducible for all other dapps on android platform

**Impact:** Bad user impact 

**Attachment:** [Android flickering.mp4](https://drive.google.com/file/d/1ElhVVQW5j3LoDpr7gK0YzuQGEWZ6N0hZ/view?usp=sharing)

**Comment by MuckT** [comment]
In the attached video it is clearest to see it on the third dismiss of the modal.
