### ISSUE TITLE
Should In-app Amount Request CTA not disappear after the transaction fails when user tries to send amount by tapping on send button from request CTA for token having zero balance. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2622]
**Frequency:** 100%

**Repro on build version:** Android Internal Build V1.34.0, iOS Test flight Build V1.34.0
**Repro on devices:** Google Pixel XL (10.0), iPhone 7 (13.3)

**Pre-condition:** 
1. User must have completed the onboarding flow.
2. User must have a valid one token balance only [Eg: cUSD].
3. User must have some pending amount request In-app CTA’s.

**Repro Steps:**
1. Tap on the “Send” button Request CTA.
2. Tap on the “Edit” link from the Sending screen.
3. Select token with Zero balance & complete Sending flow.
4. After redirecting to Home screen, swipe to Request In-app CTA & observe.

**Query:** Should In-app Amount Request CTA not disappear after the transaction fails when user tries to send amount by tapping on send button from request CTA for token having zero balance.  

**Expected Behavior:**  In-app Amount Request CTA must not disappear after transaction fails when user tries to send amount by tapping on send button from request CTA for token having zero balance.

**Impact:** Bad user impact as the transaction fails due to zero balance, than also the request CTA disappears.

**Attachment:** [In app CTA.mp4](https://drive.google.com/file/d/1UrWNb5QABFulDE03arCAJBjFtdfnw-wg/view?usp=sharing )

**Comment by MuckT** [comment]
This looks like a valid bug to me!

> Select token with Zero balance & complete Sending flow. 

This should show an error for attempting to send a zero balance and prevent the attempt to send.
