### ISSUE TITLE
Wallet connect pop-up is not opening after tapping on “Connect with Valora” button for second time when user taps on Cancel button from Wallet connect prompt for the first time  

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2625]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.34.0, Test Flight Release Build V1.34.0, iOS App store Build V1.34.0
**Repro on devices:** Google Pixel 4a (12.0), Google Pixel XL(10.0), iPhone 7(13.3)

**Pre-condition:** 

 1.User must have installed the app and completed the onboarding flow.
 2.User must be on Homepage
 3. User must be on Dapps page
 
**Repro Steps:**

 1. Tap on the “Flywallet” dapp option.
 2. Tap on “Go to Flywallet” button from the popup
 3. Tap on “Connect with Valora” button from in-app browser
 4. Tap on “Connect” button from wallet connect pop-up
 5. Tap on the “Cancel” button from wallet connect prompt in the app
 6. Again tap on “Connect with Valora” button from in-app browser and observe
 
**Bug:** Wallet connect pop-up is not opening after tapping on “Connect with Valora” button for second time when user taps on Cancel button from Wallet connect prompt for the first time.

**Expected Behavior:** Wallet connect pop-up should open after tapping on the “Connect with Valora” button for a second time  and the user should be able to connect to a wallet.

**Investigation:** 

- For Plastiks dapp continuous loading indicator is seen on "Connect your wallet" pop-up after tapping on "Connect Wallet" button for second time when user taps on cancel button from Wallet connect prompt for the first time. [Platiks dapp.mp4](https://drive.google.com/file/d/1YNQ--UvmXb94pwygISMTHdIg313vfrUA/view?usp=sharing)

**Impact:** Bad user impact as user is not able to connect to the wallet second time after cancelling it for the first time.

**Attachment:** [Flywallet Dapp.mp4](https://drive.google.com/file/d/1xRDhktcqrkAHcVtpZN-S-985fjAK7BOL/view?usp=sharing)

**Comment by kathaypacific** [comment]
Hi @ValoraQA I don't think this is a valid bug for Valora, because it is the FlyWallet interface that stops working after this interaction. I am also unable to repro this behaviour with other dapps, so would infer that the issue is with the dapp instead of with Valora.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.35.0 & Test Flight Release Build V1.35.0 and observed that the issue is fixed now. Wallet connect pop-up is opening after tapping on “Connect with Valora” button for second time after refreshing the page when user taps on Cancel button from Wallet connect prompt for the first time.
Hence we are closing the issue.

**Devices:** Google Pixel 4a(12.0), iPhone 12(14.7.1)

**Attachments:** [Flywalletdapp.mp4](https://drive.google.com/file/d/1-h8EnULvhkoDF49ZIuVJvo79op2Ulnf8/view?usp=sharing)

Thanks..!!
