### ISSUE TITLE
Dialog box appears briefly when user navigates to phone number screen while creating the account

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2636]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.34.0, Android Play store Build V1.34.0
**Repro on devices:** Google Pixel 4a (12.0), Google Pixel XL(10.0)

**Does Not Repro on build version:** Test Flight Release Build V 1.34.0 , iOS App store Build V1.34.0
**Does Not Repro on devices:** iPhone 13 mini(15.1.1), iPhone 6+(12.5.4)

**Pre-condition:** 

 1.User must have installed the app 
 2. User must be on “Secure your wallet Step 3 of 4” screen while creating account 
 
**Repro Steps:**

 1. Tap on “Turn on Fingerprint recognition” button
 2. Scan the correct fingerprint .
 3. Now observe on the phone number screen page

**Query:** Dialog - box appears for few seconds when user navigated to Phone number screen while creating the account.

**Expected Behavior:** Dialog - box should not appear for few seconds when user navigated to Phone number screen while creating the account.

**Investigation:** 

- For android platform Dialog-box appears for few seconds when user navigates to Phone number screen while restoring the account.

**Attachment:** [Dialog-box.mp4](https://drive.google.com/file/d/14Str_0gxrE4xV3vEzlD248xXnRy00iMF/view?usp=sharing)

**Comment by MuckT** [comment]
I'd consider this a bug as the screen flash is unexpected.
