### ISSUE TITLE
[Query] Different screens are appearing when we try to connect the wallet to valora application along with different details seen on the approval page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2647]
**Frequency :** 100%

**Repro on build version:** iOS Internal TestFlight Release Build V:1.35.0, Android internal release build V:1.35.0
**Repro on device :** iPhone 12(14.7.1), Google Pixel 2XL(11.0) , iPhone 13 mini (15.1.1) , Google Pixel XL(10.0) 

**Pre-condition:**
1] User must have installed the application
2] User must be on homepage
3] User must have some funds in the account
4] User must be on Dapps page

**Repro Steps :**
1] tap on any Dapp and visit the Dapp site
2] tap on connect a wallet
3] select wallet connect / Valora and it will redirect to Valora app and observe

**Query :** 
- For few Dapps we are able to see different screen where 2 logo , a small description text , cancel and allow button (can be checked for mentofi)
- For few dapps we are able to see different screen where no logo , transaction detail , cancel and allow button ( can be checked for Moola)

**Expected Behavior :** For connecting a wallet it should show 2 logo , a small description text , cancel and allow button page
whereas for performing a transaction it should show transaction detail , account address , cancel and allow button 

**Observation :** 
- The screens are appearing randomly as there is no specific way we can identify on which Dapp , which screen will appear
- It would create a confusion among the user as for few Dapps it shows transaction screen however user is only connecting the wallet to the Dapp
- Also observe that when confirming ubeswap transaction , there is no account address seen on the transaction approval screen 

**Attachment :** [confusion.mp4](https://drive.google.com/file/d/1-60Csz-a9Va20-PKTLq2lVmASDPeEr6D/view?usp=sharing)

**Comment by kathaypacific** [comment]
Hi @ValoraQA I think this is not a valid issue.

Dapps can either connect to Valora using WalletConnect, or DappKit. For dapps using WalletConnect, we will see a dapp logo because it is part of the WalletConnect protocol for dapps to to provide a logo. For dapps using DappKit (e.g. Moola), it is not part of the protocol to include an image so this is why you do not see the image in the connection/transaction requests. this has always been the behaviour even before this code change.

we have tried to include dapp logos for **all** dapps in an experiment - this experiment is only on in Alfajores. if you try to connect to Moola in Alfajores, you will see the dapp logos there. the experiment is not yet active in mainnet.

**Comment by ValoraQA** [comment]
Hey @kathaypacific thanks for the explanation but i guess the query is 
1] When we try to connect to mento fi using wallet connect / Dapp kit we get to see [Valora app , mentofi logo, mentofi would like to connect... with Cancel and allow button]
2] When we try to connect moola using Valora / Dapp kit we get to see [Moola wants to perform the transaction.. screen] although we are just connecting the wallet 

So there are two different screens coming up while connecting the wallet to Valora Application , 
Also there is no mentioning of checking the PR in the Alfajores build explicitly , if that is the case please try to mention in future PR's to avoid these type of confusion

CC: @MuckT 

Thanks..!

**Comment by MuckT** [comment]
@jeanregisser @kathaypacific - In the second example shown the first screen seen with the DappKit and Moola is to approve a transaction. I believe this where the confusion is coming from.

**Comment by ellenwoconnor** [comment]
Feature request for more readable tx metadata and clearer transaction signing experience
