### ISSUE TITLE
  User is redirected to Ramp provider web page when user taps on Add Funds button from Add Funds pop-up screen on the Homepage

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2648]
**Frequency:** 100%

**Repro on build version:** Test Flight Release Build V1.35.0, Android Internal Release Build V1.35.0
**Repro on devices:**  iPhone 13 mini(15.1.1), iPhone 12(14.7.1),Google Pixel 4a (12.0), Google Pixel 2XL(11.0)

**Pre-condition:** 

 1. User must have installed the app 
 2. User must be on confirm phone number screen with 2 codes pasted while creating the account
 3. User must have connected VPN to US location 

**Repro Steps:**

  1.  Enter the third confirmation code & wait
  2.  Tap on "Add funds" button from the Add Funds pop-up screen and observe

**Bug:** User is redirected to Ramp provider web page when user taps on Add Funds button from Add Funds pop-up screen on the Homepage

**Expected Behavior:** User should redirected to Add Funds screen when user taps on Add Funds button from Add Funds pop-up screen on the Homepage

**Investigation:** 

- For android platform user is redirected to Add Funds screen when user taps on Add Funds button from Add funds pop-up screen while creating the account [Android behaviour.mp4](https://drive.google.com/file/d/17fDyC34HNhhGub2ek0MH9WYvqvFjjMym/view?usp=sharing) 
- For android platform when user kill and relaunch the application and taps on Add funds button user is redirected to Ramp provider web page [Android.mp4](https://drive.google.com/file/d/1_M0JWmc_gfbfCLcR27jt6BW1hy3j7s2H/view?usp=sharing)

**Impact:** Bad user impact as user is redirected to Ramp provider web page instead of Add funds screen
 
**Attachment:** [Add Funds.mp4](https://drive.google.com/file/d/1Exqt3dzLeLT57TWg3DEp7oGZZDeP0w7X/view?usp=sharing)

**Comment by cajubelt** [comment]
@ValoraQA this is expected

**Comment by ValoraQA** [comment]
Hey @cajubelt, Thank you very much for the information. We will update the test plan accordingly.
