### ISSUE TITLE
Clicking on create account after connecting the wallet is showing a transaction approval screen in Valora application

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2654]
**Frequency :** 100%

**Repro on build version:** iOS Internal TestFlight Release Build V:1.35.0, Android internal release build V:1.35.0
**Repro on device :** iPhone 12(14.7.1), Google Pixel 2XL(11.0) , iPhone 13 mini (15.1.1) , Google Pixel XL(10.0) 

**Pre-condition:**
1] User must have installed the application
2] User must be on homepage
3] User must have some funds in the account
4] User must be on Dapps page

**Repro Steps :**
1] tap on Churito Dapp and visit the Dapp site
2] tap on connect a wallet
3] select wallet connect / Valora and it will redirect to Valora app 
4] Click on allow 
5] Click on create account and observe 

**Bug :** It is showing transaction approval screen instead of redirecting to new account creation page , also after allowing it shows the same create account page 

**Expected Behavior :** It should redirect to new account creation page instead of redirecting to valora app with transaction approval screen

**Attachment :** [churito.mp4](https://drive.google.com/file/d/17JjOHNUNPsRDw0EeuajLO4_g_T4SCyol/view?usp=sharing)

**Comment by jeanregisser** [comment]
This is the expected behavior. Creating an account for staking Celo requires sending a transaction.
Though the dapp should probably show a loading indicator until the transaction has been fully processed.

Moving this issue to ChurritoFi

**Comment by ValoraQA** [comment]
Hey @jeanregisser, Thank you very much for the information.
