### ISSUE TITLE
“Please use a stronger PIN” wrong error message appears instead of “The PIN’s didn’t match” error when user enter invalid PIN again on “Enter your PIN again to confirm” screen .

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2665]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.35.0, iOS Test flight Release Build V1.35.0

**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel 4a (12.0), Google Pixel XL (10.0), One plus 9 5G (12.0)

**Does Not Repro on build version:** Android Play store Build V1.34.0, iOS Test Flight Release Build V1.34.0

**Does Not Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1) Google Pixel 4a (12.0), One plus 9 5G (12.0)

**Pre-condition:** 
1.User must have installed the latest build.
2.User must be on “Create a PIN Step 2 of 4” screen while creating account

**Repro Steps:**
1. Enter a valid pin on “Create a PIN Step 2 of 4” screen [Eg: 122222]
2. Enter different pin than valid pin on “Enter your PIN again to confirm” screen. [Eg: 121212] & observe the error message 

**Bug:** “Please use a stronger PIN” wrong error message appears instead of “The PIN’s didn’t match” error when user enter invalid PIN again on “Enter your PIN again to confirm” screen .

**Expected Behavior:**  “The PIN’s didn’t match” error must appear when user enter invalid PIN again on “Enter your PIN again to confirm” screen .

**Investigation:** This issue is reproducible in Restore account flow also on both android and iOS platforms.

**Impact:** Bad user impact as same error appears when user enter invalid pin different than valid pin entered previously or entering such invalid pins like “123456” or “111111”.

**Attachment:** 
[Wrong error message issue.mp4](https://drive.google.com/file/d/1ZGLfyvubQO_EsOF3BU5f3Ig5CvDVRsY_/view)

[Not repro on 1.34.0 .mp4](https://drive.google.com/file/d/1hgmMX9AsR6GrWF5Eb1kN3uI5SGnCXhRt/view)

**Comment by MuckT** [comment]
@ValoraQA this is a valid bug and should be fixed in 1.36.0 by https://github.com/valora-inc/wallet/pull/2629.

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above issue on Latest iOS Test Flight release build, Android Internal Release build V1.36.0 and observed that issue is fixed.
We have provided our comment and observations in the PR https://github.com/valora-inc/wallet/pull/2629
Hence we are closing this issue.
