### ISSUE TITLE
User is not able to send / receive money while sending money to another user using Valora App

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2693]
**Frequency :** 100%

**Repro on build version:** Android internal release build V:1.36.0, iOS TestFlight build V:1.36.0 , Android Playstore build V:1.35.0 , iOS AppStore build V:1.35.0
**Repro on device :** Google Pixel 2XL(11.0) Google Pixel XL(10.0), OnePlus 7T(11.0),iPhone 12(14.7.1), iPhone 13 mini (15.1.1) 

**Pre-condition:**
1] User must have installed the application
2] User must be on homepage
3] User must have some funds in the account
4] User must be on send amount page 

**Repro Steps :**
1] enter a valid amount
2] Next button will be seen enabled
3] Click on next button
4] Click on send button from send amount page 

**Bug :** "Transaction failed please retry" error is faced while sending the amount to another user

**Expected Behavior :** The transaction must have completed properly and user should have received the money in the wallet

**Investigation:**
1] Same error is also faced while receiving money from another user
2] "The Celo network is experiencing an outage. Your funds are safe. We apologize for the temporary inconvenience and we will have more information for you soon." we found this statement on Social Media Platform.

**Attachment :** [send.mp4](https://drive.google.com/file/d/16meKsyXbrHlzudd4HUksM2FPcblEmZFL/view?usp=sharing)
Bug Observed at 1.39 seconds

**Comment by kathaypacific** [comment]
Hi @ValoraQA this sounds related to the celo network stall yesterday. The issue has been resolved by the cLabs team as of this morning. please confirm and close this ticket if it's no longer relevant :)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in Android internal release build V:1.36.0, iOS TestFlight build V:1.36.0 and observed that issue is fixed hence we are closing the issue 

Observation : user is able to send money to other user and user is able to receive money from another user 

Devices : Google Pixel 2XL(11.0) Google Pixel XL(10.0), iPhone 12(14.7.1)

Attachment : [send&receive](https://drive.google.com/file/d/1ZlBkcWS9ZlWLrG_DfFYht0Ccs06XbA9W/view?usp=sharing)

Cc: @kathaypacific 

Thanks..!
