### ISSUE TITLE
[Query] : Phone number page is not seen when user is creating / restoring an account. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2720]
**Frequency :** 100%

**Repro on build version :** iOS TestFlight build V:1.37.0 , Android Internal Release build V:1.37.0
**Repro on device :** iPhone 12(14.7.1), iPhone 13 mini (15.1.1) , LG K7i(6.0), Google Pixel XL (10.0)

**Does not Repro on build version:** Android internal release build V:1.37.0
**Does not Repro on device :** Google Pixel 2XL(11.0) ,OnePlus 7T(11.0), Google Pixel 4a(12.0)

**Pre-condition:**
1] User must have installed the application

**Repro Steps :**
1] On carousel page tap on next 3 times
2] Click on create account button
3] Click on agree on terms and condition page
4] Enter valid pin and setup the PIN
5] Enable / Disable Face ID 

**Query :** After face id , it is redirecting User directly to homepage instead of Phone number entering page

**Expected Behavior :** It should redirect to Phone number entering page

**Investigation :**
- Same issue is also faced when user is trying to restore the account

**Attachment :** [phonenumber.mp4](https://drive.google.com/file/d/1fEf_dzG706ULCHPjjWGSjoG2Y6iGkQNL/view?usp=sharing)

**Comment by MuckT** [comment]
This is due to the experiment with 'skipVerification' and is expected.
