### ISSUE TITLE
User is not able to proceed to review page once user has linked the bank account and comes back to bank details page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2724]
**Frequency :** 100%

**Repro on build version:** Android internal Alfajores build V:1.37.0, iOS TestFlight Alfajores build V:1.37.0
**Repro on device :** Google Pixel 2XL(11.0) Google Pixel XL(10.0),iPhone 12(14.7.1), iPhone 13 mini (15.1.1) 

**Pre-condition:**
1] User must have installed the application
2] User must be have funds in the account
3] User must be on withdraw funds page 

**Repro Steps :**
1] Select celo Dollar
2] Tap on next 
3] Enter valid amount and proceed to select payment page
4] Click on bank account from select payment page
5] Now enter bank details and proceed to review page 
6] Now from review page click on < arrow
7] It will redirect to enter bank detail page 
8] again click on next button

**Bug:** User gets stuck as it would not allow user to proceed ahead as it shows error "You have already linked this account to valora" and cannot proceed ahead

**Expected Behavior :** It should allow user to proceed ahead without showing any error

**Investigation :**
- Same behavior is also faced when user clicks on cancel button from review page 
- User needs to kill the app and relaunch in order to complete the flow
- Cross button on enter bank detail page is not seen properly aligned (can be seen in the attachment)

**Attachment :** [bank.mp4](https://drive.google.com/file/d/1k4wFtiFalC0VOaaa1PpzIW_6A8NB-28M/view?usp=sharing)
Bug observed at 0.30 seconds

**Comment by MuckT** [comment]
Related to: https://github.com/valora-inc/wallet/pull/2673

**Comment by jh2oman** [comment]
Going to be fixed in https://linear.app/valora/issue/ACT-364/back-button-try-again-around-the-review-screen

**Comment by ValoraQA** [comment]
Hi @MuckT, We have verified that above issue on Android Alfa jores Build V1.37.1, iOS Test flight Alfa jores Build V1.37.1 & observed the following.

- "X" button is not appearing properly aligned after entering data into the "Bank Name" & "Account number" fields on "Enter Bank Details" screen.

- On tapping "X" button after entering data into the "Bank Name" & "Account number" fields on "Enter Bank Details" screen, the data is not getting removed.  

**Devices:** Google Pixel XL (10.0), Google Pixel 4a (12.0), iPhone 7 (13.3)
**Attachment:** [X button not fuctioning.mp4](https://drive.google.com/file/d/1R02quXVcGASwIBPTEJQS0PoVEiboNc0i/view?usp=sharing)

Thanks..!!
