### ISSUE TITLE
Account address is not seen properly once the transaction is completed for withdraw funds flow using Bank account as payment method

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2725]
Frequency : 100%

Repro on build version: Android internal Alfajores build V:1.37.0, iOS TestFlight Alfajores build V:1.37.0
Repro on device : Google Pixel 2XL(11.0) Google Pixel XL(10.0),iPhone 12(14.7.1), iPhone 13 mini (15.1.1) 

Pre-condition:
1] User must have installed the application
2] User must be have funds in the account
3] User must be on withdraw funds page 

Repro Steps :
1] Select celo Dollar
2] Tap on next 
3] Enter valid amount and proceed to select payment page
4] Click on bank account from select payment page
5] Now enter bank details and proceed to review page 
6] Complete the payment and click on continue 
7] User will be redirected to homepage 
8] Observe the transaction activity 

Bug: "Dead.. beef" is seen written in the account address on recent transaction activity page and on transaction detail page

Expected Behavior : It should show proper account address instead of wrong address

Investigation :
- When we copy address and paste it we are able to see dead beef words repeated multiple times

Attachment : [transaction.mp4](https://drive.google.com/file/d/1dRjbWEisYTv7vEeaXsGgkpRUommWxd4i/view?usp=sharing)
Bug Observed at 0.05 seconds

**Comment by jophish** [comment]
@MuckT @ValoraQA This is actually intended behavior; 0xdeadbeef... is a test/dummy address we use to send funds to for transfers out on Alfajores; it's currently hardcoded into our mock backend service. When integrating with _real_ providers, this address will be a real address, owned by the provider the user is cashing out with.

**Comment by ValoraQA** [comment]
@jophish @MuckT we are currently keeping this Bug in an open state, once we test it in real environment we will close it with an attachment of real account address seen
Thanks.!
