### ISSUE TITLE
Handle Varying Font Size and Ambiguous Text Lengths due to Localization

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#277]
### Expected Behavior

Text which would overflow its containing elements should be truncated with ellipses where possible and/or resized to display within its parent container. If text needs to be displayed in full such as `Account No.` The parent element should expand to contain this larger text

### Current Behavior

Text of varying lengths and sizes either by adjusted font size or localization changes can sometimes break out of its containing elements. Alternatively the large text displays within the correctly sized container; however, it is cropped by the originally sized parent container.

### Existing Issues
| Issue Title | Link |
| ------ | ------ |
| Amount’s digits gets truncated when user enters too large value in Amount field & taps on < arrow on “Add Funds” screen |  #77 |
| [Device Specific] Description not fit to screen when user enters particular pattern of letter & special characters in Sending screen while sending money | #124 |
| Notification Box does not handle large texts properly | #149 |
| [Device Specific] “Please buy and sell responsibly” walkthrough screen’s description overlaps on Carousel from CELO walkthrough screens. | #240 |
| Add photo icon overlaps on Step 1 of 5 text on Create Account page while onboarding | [Monorepo #7071](https://github.com/celo-org/celo-monorepo/issues/7071) |
| “Account Number” alignment is not proper when the user taps on Hamburger Menu from the Home screen. | [Monorepo #7187](https://github.com/celo-org/celo-monorepo/issues/7187) |

**Comment by isabellewei** [comment]
@coreycelo mentioned we might want to look into media queries for app responsiveness https://www.npmjs.com/package/react-native-media-query
