### ISSUE TITLE
Can we have a Search/Filter option on "Homepage>Activity" section to get the transaction conveniently

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2781]
Pre-condition:
1.User must have completed the onboarding flow.
2.User must have multiple transaction activities in recent activity section

Repro Steps:

1] Tap on search and enter any valid text to search for transaction
2] Observe the filter providing appropriate results as per entered text

Suggestion : Can we have a search filter on homepage so that user can search for transaction conveniently and able to see appropriate results 

Current Behavior: No search button implemented yet

Impact: User can directly search there transaction and get results accordingly rather than scrolling the page which would require time and page loading too

Attachment  : [homepage.jpg](https://drive.google.com/file/d/1thnOjN0TAwIF56BqQiLKS65Fa-1Tly-0/view?usp=sharing)

**Comment by ellenwoconnor** [comment]
Thanks for the input, I'll note this suggestion down for the future.
