### ISSUE TITLE
“You have no NFT’s “ message appears on NFT viewer page when user taps on Received NFT activity from recent activity section

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2789]
**Frequency:** 100%

**Repro on build version:** iOS Test Flight Release Build V1.38.2, Android Internal Release Build V1.38.2
**Repro on devices:** iPhone 13 mini (13.1.1), iPhone 12 (14.7.1), Google Pixel 4a(12.0), Google Pixel XL(10.0)

**Pre-condition:** 

 1. User must have installed the latest build
 2. User must have funds in their account
 3. User must have connected wallet to https://celostrials.com/#/
 4. User must have purchased NFT 
 
**Repro Steps:**
 1. Tap on the Received NFT activity from the recent activity section
 2. Now observe the NFT Viewer page

**Bug:** “You have no NFT’s “ message appears on NFT viewer page when user taps on Received NFT activity from recent activity section
 
**Expected Behavior:** Purchased NFT should be seen on NFT viewer page when user taps on Received NFT from recent activity screen

Note : We even checked after 30 minutes to 1 hour and still we didn't get to see purchased NFT
**Impact:** Bad user impact as user is not able to see purchased NFT on NFT viewer page

**Attachment:** [NFT viewer.mp4](https://drive.google.com/file/d/1HZY3lqBpM3LD6i8VljiUeT6pqKhXxJ8v/view?usp=sharing) 
Bug Observed at 0.04 seconds

**Comment by ellenwoconnor** [comment]
Temporary problem - eventually the indexer should catch up. Improvements to indexer will help with this.

**Comment by ellenwoconnor** [comment]
Consider a copy update
