### ISSUE TITLE
Application gets crashed when user taps on the Hamburger menu from the “Your Recovery Phrase” page after the user sets up the recovery phrase

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2804]
**Frequency:** 100%

**Repro on build version:** iOS Test Flight Release Build V1.39.0, Android Internal Release Build V1.39.0
**Repro on devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel 4a(12.0), Google Pixel XL(10.0), iPhone 6+(12.5.5)

**Pre-condition:**
 
 1. User must have installed the latest build and completed the onboarding flow
 2. User must be have recovery phrase screen  
 
**Repro Steps:**

 1. Enter 24 keywords on the Recovery phrase page
 2. Tap on the Submit button
 3. Tap on the Hamburger menu and observe

**Bug:** Application gets crashed when taps on the Hamburger menu from the “Your Recovery Phrase” page after user sets up the recovery phrase. 
 
**Expected Behavior:** Application should not get crashed when user sets up the recovery phrase and taps on the Hamburger menu from the Your Recovery phrase page

**Investigation:**

1. If the user taps on <  header back then we get to see the "you are all set " screen and there is no way the user can go to any other screen , it gets stuck until the user kills the app and relaunches it. [Recovery phrase.mp4](https://drive.google.com/file/d/1Z7y-NBVr88jYwDnjeqoT_CrJj2I-QOVW/view?usp=sharing) 

2. When user taps on Learn about your recovery phrase button and redirects to all walkthrough screens and taps on Hamburger menu application gets crash

**Impact:** Bad user impact as app gets crashed when user taps on Hamburger menu

**Attachment:** [App crashes.mp4](https://drive.google.com/file/d/1ukKYrmYTpLcq5PLDeLJkLfNhUwHTB3Q6/view?usp=sharing) 
 [Crash logs](https://drive.google.com/file/d/1tsn43YW-6Z4aPgEA9s56n5rkiZcJ4f8c/view?usp=sharing) 
Bug Observed at 0:37 seconds

**Comment by MuckT** [comment]
We should write an e2e tests to ensure this behavior doesn't resurface when we attempt to move the recovery phrase again in the future.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.39.1 & Test Flight Release Build V1.39.1 and observed that the issue is fixed now. Application is not getting crashed after the user sets up the recovery phrase and taps on the Hamburger menu from the “Your Recovery Phrase” page.

Hence we are closing the issue.

**Devices**: Google Pixel 2XL (11.0), Google Pixel XL (10.0), iPhone 13 mini(15.1.1), iPhone 12(14.7.1)

**Attachments**: [Recovery Phrase.mp4](https://drive.google.com/file/d/1H8fFD6Ydm0HVU-El7LU4XtEdsGTIzR1z/view?usp=sharing)

Thanks..!!
