### ISSUE TITLE
[Query] While sending an invite link the URL appears as "https://vlra.app/invite" via application whereas URL seen on Figma screen is : "https://vlara.app/vDewFH..." which URL is correct ?

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2843]
Frequency : 100%

Repro on build version: iOS alfajores build V 1.40.0, Android Alfajores build V 1.40.0
Repro on device version : Google Pixel 2XL(11.0) , iPhone 12(14.7.1)

Pre-condition:
1] User must have downloaded Alfajores build
2] User must have restored account 
3] User must be on homepage
4] User must be have some funds in the account
5] User must have provided access to contacts

Repro Steps :
1] Tap on send button from homepage 
2] Select a contact / enter valid mobile number (Which is non valora user)
3] User will be redirected to enter amount page and then on send invite page
4] tap on send invite link and share the message on 3rd party app 
5] Observe the URL

Query : URL shared via App is different as compared with Figma screen design when compared

Expected Behavior : URL should appear as https://vlara.app/vDewFH. as seen in Figma screen

Investigation : 
- Learn more link is not seen on send invite page as it is seen in Figma screen [attachment](https://www.figma.com/file/8ig95B4sfsYIDIpg3JGP03/Phone-Verification?node-id=1378%3A21270)

Attachment : [URL.mp4](https://www.figma.com/file/8ig95B4sfsYIDIpg3JGP03/Phone-Verification?node-id=1378%3A21227)
[Figma screen URL](https://www.figma.com/file/8ig95B4sfsYIDIpg3JGP03/Phone-Verification?node-id=1378%3A21227)

**Comment by MuckT** [comment]
@ValoraQA this is expected based on the AC from RET-379.
