### ISSUE TITLE
Extra space is seen on "Your Recovery Phrase" page after user has completed setting up of the recovery phrase

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2844]
**Frequency :** 100%

**Repro on build version:** iOS Alfajores build V 1.40.0, Android Alfajores build V 1.40.0
**Repro on device version :** Google Pixel 2XL(11.0) , iPhone 12(14.7.1), iPhone 13 mini(15.1.1)

**Pre-condition:**
1] User must have downloaded Alfajores build
2] User must have created a new account
3] User should not have set up the recovery phrase 

**Repro Steps :**
1] Tap on Hamburger Menu
2] Select Recovery phrase option
3] set up the recovery phrase by completing the flow
4] Observe the recovery phrase page once the setup is completed 

**Bug :** Extra space is seen on "Recovery Phrase" page after user has completed the setup 

**Expected Behavior :** Extra space should not be seen on Recovery phrase page 
 
**Attachment :** [RP.mp4](https://drive.google.com/file/d/13FVD-iM41b5-ah63f-0VdyDSa8HzN8rI/view?usp=sharing)

**Comment by MuckT** [comment]
Closing as this is no longer reproducible.
