### ISSUE TITLE
Green colored line is seen on send invite page when user A is trying to send invite to User B 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2852]
**Frequency :** 100%

**Repro on build version:** Android Alfajores build V 1.40.0
**Repro on device version :** Google Pixel 2XL(11.0), Google Pixel 4a(12.0)

**Does not Repro on build version :** iOS Alfajores build V 1.40.0
**Does not Repro on device version :** iPhone 12(14.7.1), iPhone 13 mini(15.1.1)

**Pre-condition:**
1] User A must have downloaded the alfajores build
2] User A must have completed onboarding flow
3] User A must be on homepage 

**Repro Steps :**
1] Tap on send button 
2] enter a valid number / select a valid contact (non valora user)
3] it will redirect to enter amount page with loader seen on review page 
4] User A will be redirected to send invite page 

**Bug :** Green colored line is seen on send invite page

**Expected Behavior :** Send invite page should be seen properly as compared with iOS 

**Investigation**:

- For Android 12 platform user is able to see Review button on Send invite page when User A is trying to send invite to User B. [Android 12.jpg](https://drive.google.com/file/d/1Xa_cKpVmHppOFBPLgdCdvHj2UZd4H8Q8/view?usp=sharing)

**Attachment :** [android .jpg](https://drive.google.com/file/d/1rcXQrmh0xPKBIE_aZuPyLj3x2X1_RYCM/view?usp=sharing)
[iOS.jpg](https://drive.google.com/file/d/1PVJSR2wCPFg3Ebd9GGoiygq_hwUaluhh/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA are you able to tap the button and proceed to send the amount to a non Valora user phone number?

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Internal Release build V 1.40.1 and observed that review button is clickable from send invite page

Observation : When user enters amount while loader is seen on send amount page , review button is seen enabled on send invite page and we can complete the flow for invite

Attachment : [send invite alfajores.mp4](https://drive.google.com/file/d/1Pk2uE8FWJvBfig3yqt6Ep1RE2FFz-K1h/view?usp=sharing)

Device : Google pixel 4a(12.0)
Thanks.!

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our comment in PR #2858 
thanks,!
