### ISSUE TITLE
[Query] Fiat connect flow is not seen if we do not connect VPN to US server and also if we connect VPN to US server 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2876]
Frequency : 100%

**Repro on build version:** Android Alfajores build V 1.40.1 ,iOS Alfajores build V 1.40.1
**Repro on device version:** Google Pixel 2XL(11.0) , OnePlus 7T (11.0), Google Pixel 4a(12.0), iPhone 12(14.7.1), iPhone 13mini (15.1.1) 

**Pre-condition:**
1] User must have downloaded Alfajores build
2] User must have connected to US VPN 
3] User must have completed onboarding process
4] User must have funds in the account balance
5] User must be on add and withdraw funds landing page

**Repro Steps :**
1] Tap on withdraw funds
2] Select Celo Dollar (cUSD) option
3] Tap on next button
4] Enter valid amount
5] Tap on next button
6] On Select Payment page bank account is not seen 

**Query :** Fiat connect flow is not seen if we do not connect VPN to US server and also if we connect VPN to US server 

**Expected Behavior :** Fiat connect should be visible with/ without US VPN server 

**Attachment :** [fiatconnect.mp4](https://drive.google.com/file/d/1wb__9vUaf3tDJSNUbsrK1JJTqzSFqPci/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA the fiat connect flow displaying is dependent on the use of an even number for the amount. Can you confirm this is working as expected this might be why you're not seeing the mock provider.

#### Will display the mock provider
Add & Withdraw > Withdraw Funds > cUSD > Amount - $2 > mock provider displayed

#### Will not display the mock provider
Add & Withdraw > Withdraw Funds > cUSD > Amount - $1 > mock provider not displayed

**Comment by ValoraQA** [comment]
Hey @MuckT we have checked the above query using the steps you have mentioned above and we are able to see mock provider i.e Fiat connect flow hence we are closing the query

Device : iPhone 12(14.7.1), Google Pixel 2XL(11.0)
