### ISSUE TITLE
[Query] : After Setting up recovery phrase user is redirected to homepage instead of redirecting to recovery phrase page 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2883]
**Frequency :** 100%

**Repro on build version:** Android Internal Release build V 1.41.0 ,iOS Test Flight build V 1.41.0, Android Internal Release build V 1.40.1, iOS Test Flight build V 1.40.1, 
**Repro on device version:** Google Pixel 2XL(11.0) , OnePlus 7T (11.0), Google Pixel 4a(12.0), iPhone 12(14.7.1), iPhone 13mini (15.1.1) 

**Pre-condition:**
1] User must have downloaded mainnet build
2] User must have created a new account 
3] User must be on homepage

**Repro Steps :**
1] Tap on Hamburger Menu
2] Tap on Recovery Phrase 
3] Go through carousels and set up the recovery phrase
4[ You are all set page will be seen 

**Query :** User is redirected to homepage instead of staying on the recovery phrase page 

**Expected Behavior :** User should be staying on the recovery phrase page 

**Investigation:**
- The above behavior was also observed in V 1.40.0 , V 1.40.1 
- In V 1.39.1 After setting up recovery phrase user is staying on same page instead of redirecting to homepage

**Attachment :** [Homepage.mp4](https://drive.google.com/file/d/1344AQeBqG8awWOVaHVZImxExdaHcCZbE/view?usp=sharing) 
**Compared with :** [recovery phrase.mp4](https://drive.google.com/file/d/15Ot6KH20tp_ftCq6y4WFmypdsgVsL0uF/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA it's expected that it should redirect to the home page this change was introduced in #2814.
