### ISSUE TITLE
[Query] Should Valora icon be seen beside “Address copied to clipboard” toast message when user taps on Tap to Copy text below Account address from the Hamburger menu.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2896]
**Frequency:** 100%

**Repro on build version:** Android internal release build V1.41.0
**Repro on devices:** Google Pixel 4a (12.0)

**Does Not Repro on build version:** iOS test flight release build V1.41.0, Android Internal release build V1.41.0, Android Play store Build V1.40.1
**Does Not Repro on devices:** Google Pixel 2XL (11.0), Google Pixel XL(10.0), One Plus 9(12.0) iPhone 13 mini(15.1.1), iPhone 
12(14.7.1)

**Pre-condition:** 

 1. User must have installed the latest build and completed the onboarding flow
 2. User must be on Homepage
 
**Repro Steps:**

 1. Tap on the Hamburger menu
 2. Tap on Tap to copy text below Account address
 3.  Now observe the toast message
 
**Query:** Should Valora icon be seen beside “Address copied to clipboard” toast message when user taps on Tap to Copy text below Account address from the Hamburger menu.

**Expected Behavior:** Valora icon should not be seen beside “Address copied to clipboard” toast message when user taps on Tap to Copy text below Account address from the Hamburger menu.

**Attachment:** [Account address.mp4](https://drive.google.com/file/d/1rNV0VXTZSyAfQvQ_sSJcAGECo7pruDpi/view?usp=sharing ) 
Query Observed at 0.06 seconds

**Comment by MuckT** [comment]
This looks to be specific to Android 12 functionality letting users know when their clipboard is modified by an app.
