### ISSUE TITLE
Old design of send secure flow is seen when user tries to send amount to the same number as registered number and has two accounts associated with same number

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2900]
**Frequency :** 100%

**Repro on build version:** iOS Test Flight build V 1.41.0, Android Internal Release build V 1.41.0 , iOS Appstore build V 1.40.1
**Repro on device version:** iPhone 12(14.7.1), iPhone 13mini (15.1.1), Google Pixel 2XL(11.0) , OnePlus 7T (11.0), Google Pixel 4a(12.0)

**Number used :** +91 8655473065 , +91 7021332967

**Pre-condition:**
1] User must have multiple accounts associated with same number
2] User must have restored an account
3] User must have some funds in the account
4] User must be on homepage
5] User must have provided access to contacts

**Repro Steps :**
1] tap on send button from homepage
2] enter the same number as the registered number 
3] Enter valid amount 
4] Tap on confirm account address link and observe 

**Bug:**
- Old design of enter account address page is seen when users tries to send money to himself / herself with number having multiple accounts 

**Expected Behavior :** 
- User should be able to see new design page instead of old design of enter account address page

**Investigation:**
- If User A has only one account associated with same number and tries to send to User B who has multiple account with same number then new design of enter account address is seen 
- If User A has who has multiple account with same number and tries to send money to user B who has multiple account with same number then old design is seen 
- If User enters account address in search bar then it redirects to send amount page 

**Attachment :** [multiple.mp4](https://drive.google.com/file/d/1TJ6MY3-77fj-eWbuQkW4UBgKyeMvVe56/view?usp=sharing) 

bug observed at 0.58 seconds

**Comment by MuckT** [comment]
@ValoraQA this doesn't appear to be bug, but is working as intended.

@kathaypacific / @jeanregisser will this full address validation still be served with centralized phone verification?

**Comment by kathaypacific** [comment]
> @ValoraQA this doesn't appear to be bug, but is working as intended.
> 
> @kathaypacific / @jeanregisser will this full address validation still be served with centralized phone verification?

yes i think so, since we'll still allow multiple addresses to be registered against a phone number

**Comment by ValoraQA** [comment]
Hey @MuckT thanks for explanation we are closing this bug as it works as intended
Thanks.!
