### ISSUE TITLE
[Query] Can we redirect user to homepage when user tries to invite a friend using inapp-CTA and with zero balance instead of staying on enter amount page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2901]
**Frequency :** 100%

**Repro on build version:** iOS Test Flight build V 1.41.0, Android Internal Release build V 1.41.0 , iOS Appstore build V 1.40.1
**Repro on device version:** iPhone 12(14.7.1), iPhone 13mini (15.1.1), Google Pixel 2XL(11.0) , OnePlus 7T (11.0), Google Pixel 4a(12.0)

**Pre-condition:**
1] User must have downloaded mainnet application
2] User must have completed onboarding process'
3] User must have created a new account
4] User must be on homepage

**Repro Steps :**
1] on homepage send button will be seen disabled
2] navigate to invite friend CTA 
3] Tap on invite friend button 
4] redirects to select contact page 
5] Enter contact number / select a non valora contact
6] On review page loader will be seen 

**Query :** 
Loader takes a long time and then there is no redirection so Whether user will be redirected to send invite page or it will stay on enter amount page 

**Expected Behavior :** 
- It should redirect back to homepage stating that "you have very low balance to make a transaction"

**Attachment :** [invite.mp4](https://drive.google.com/file/d/197cVxA32SLJTRKHx2eRTXG9DRGQbv9vY/view)

**Comment by MuckT** [comment]
@ValoraQA this is a valid concern, but with the changes to the invite flow in #2911 this shouldn't be an issue anymore once invite referral links are fully rolled out.
