### ISSUE TITLE
”Error loading page” error is displayed when user navigates to alities.io page via Dapps page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2963]
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.42.0, iOS Test flight Release Build V1.42.0 
**Repro on devices:** iPhone 13 mini (15.1.1), Google Pixel 4a(12.0), Google Pixel 2XL(11.0), iPhone 6+(12.5.5), Google Pixel XL(10.0)

**Pre-condition:** 

 1. User must have installed the app & completed onboarding flow.
 2. User must be on the Homepage.
 
**Repro Steps:**

 1. Tap on Hamburger menu.
 2. Tap on the Dapp option.
 3. Tap on the “alities” dapp option.
 4. Tap on “Go to alities” button from the popup and observe

**Bug:** ”Error loading page” error is displayed when user navigates to alities.io page via Dapps page   

**Expected Behavior:**”Error loading page” error should not be displayed when user navigates to alities.io page via Dapps page  
 
**Impact:** Bad user impact as error loading page is seen

**Attachment:** [alities dapp.mp4](https://drive.google.com/file/d/1LfTvO2Fip2KTTYMQsbsX1dsPwj7FIpi4/view?usp=sharing)
Bug observed at 0.11 seconds

**Comment by MuckT** [comment]
Closing as Alities was removed from the [Dapp Lis](https://github.com/valora-inc/dapp-list)t in https://github.com/valora-inc/dapp-list/pull/318.
