### ISSUE TITLE
User is able to save blank space in name field in Edit profile page from the Settings page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2964]
**Frequency:**  100%

**Repro on build version:** Android Internal Release Build V1.42.0, iOS Test flight Release Build V1.42.0
**Repro on devices:** iPhone 6+(12.5.5), Google Pixel XL(10.0), iPhone 13 mini(15.1.1), Google Pixel 4a(12.0), Google Pixel 2XL(11.0)

**Pre-condition:**

  1. User must have installed the app & completed onboarding flow.
  2. User must be on settings page.

**Repro Steps:**

 1. Tap on the Edit profile from the settings page.
 2. Tap on the name field and remove the text till the name field is clear
 3. Tap on space button from the key pad.
 4. Tap on save button on top right corner and observe

**Bug:** User is able to save blank space in name field in Edit profile page from the Settings screen

**Expected Behavior:** Error message should be shown as user can not save an empty or null space in the name field.

**Impact:** Bad user impact as blank name field could be saved and seen.

**Observation:** This issue is also repro when internet is turned off.

**Attachment:** [Blank field.mp4](https://drive.google.com/file/d/12MC7Yee2CnqjWDmCVCRkCvpuBij4MoVe/view)
Bug observed at 0.14 seconds

**Comment by MuckT** [comment]
Saving `' '` is a valid name - WAI.
