### ISSUE TITLE
Add the Ability to Scan a QR Code from the Photo Gallery

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#308]
### What would you like?
The ability to scan a QR code from the photo gallery.

### Why is this needed?
Users can scan QR codes with the device camera; however, users are unable to scan QR codes from the photo gallery. Adding **this feature would allow QR's sent through external apps or SMS to be scanned in-app.** Additionally, users may only have one device so scanning a QR from another device might not be possible. Adding this feature would extend the QR capabilities already implemented providing extra functionality for minimal development effort.

**Comment by Celoqa** [comment]
Thanks @MuckT for accepting suggestion and creating enhancement ticket  :)
