### ISSUE TITLE
continuous loading indicator is shown on Second & third fields when user auto paste attestations. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#313]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.13.1(1004294349) 
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7) , Redmi Note 8 (9.0)
**Pre-Condition:** Make user codes should paste automatically
   **Repro Steps:**

1. Launch the application 
2. Complete on boarding education
3. Tap on create new account 
4. Enter pin
5. Enter phone number 
6. Tap on start button 
7. Wait for phone number confirmation fields 
8. Make sure codes should auto paste 
9. Observe continuous loading indicator is shown on Second & third fields 

**Current Behavior:**  Continuous loading indicator is shown 
**Expected Behavior:**  Codes should auto paste & user should redirect to connect contacts screen. 
**Observation:** Codes are not auto pasted in ios. 
**Impact:** User  blocked to confirm phone number . 
**Attachment:**  [ContinuousLoadingIndicator.mp4](https://drive.google.com/file/d/1MmfuDGEXoMju7xSb8gFAvazWE-kwBFWG/view?usp=sharing)

**Comment by Celoqa** [comment]
@etuleu  here is the logs for the same 
[celo_logs (1).txt](https://github.com/celo-org/wallet/files/6423035/celo_logs.1.txt)

**Comment by MuckT** [comment]
@etuleu here is the [Log](https://drive.google.com/file/d/1DyimrU1o9enUHDgZrEI-T8sXaI0wm9zs/view?usp=sharing)

**Comment by MuckT** [comment]
@etuleu this looks like the UI bug we were debugging.

**Workaround**: Close and relaunch Valora - The user's phone number should load in a verified state.

**Comment by MuckT** [comment]
https://valora.testquality.com defect [D2](https://valora.testquality.com/project/12128/result/2397005/defect/7765). Do not remove or edit.

**Comment by Celoqa** [comment]
Hey @MuckT I have verified this issue using Android internal build & Test Flight Build V1.14.2 & observed following:
- User is able to see loading indicator for short time while pasting second code automatically. Also it is observed that user stays on paste attestation codes (for ~10 sec) even pasted all codes successfully. [Attachement](https://drive.google.com/file/d/1gDdrvkia78gotDzc1kvW49Xq3-t5eDOk/view?usp=sharing)

 Can you please let us know is this expected or we need to raise a ticket for same ?

**Comment by Celoqa** [comment]
Hey @gnardini I have verified this issue using latest Android  internal  build  V1.14.3 & observed following:
**Observations:**

- [ ] User able to see Blank space  for second field after auto pasting all codes on "Confirm" screen.Hence reopening issue.
**Attachment:** [SecondAttestationIssue.mp4](https://drive.google.com/file/d/1qTyDo01PatU-SVRk22jj7sAgHNj1OKe7/view?usp=sharing)
**Verified On Devices:**  Redmi Note 8 (9.0) , One plus 6T (10)

**Comment by gnardini** [comment]
This is a bit different than the original issue.

In the original issue, the second and third codes were never getting completed.

In the video you shared, the codes are being completed, but the UI glitches and it shows as if not. As you see, if you wait a bit the codes are still confirmed so this looks like a UI-only issue. this will be fixed in 1.15 by this PR: https://github.com/celo-org/wallet/pull/432

**Comment by Celoqa** [comment]
Hi @gnardini thanks for the clarification.
Yes, As you said in the above user is able to complete the verification flow the only issue is UI glitches.
Sure we will verify this in in 1.15 by this PR: #432

**Comment by MuckT** [comment]
@Celoqa can you retest on v1.17.0

**Comment by Celoqa** [comment]
Sure @MuckT we will retest this issue on V1.17.0 and will update the ticket once we received builds.

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on latest build Android internal V1.17.0 and observed the followings:
- User not able to see the loading indicator after auto pasting.
- White blank filed is shown on second filed when user auto paste the codes

**Comment by ValoraQA** [comment]
Hey, @MuckT We have verified this issue using Android internal build V1.22.1 & observed that the user is able to see a blank field for the third field after completion of the auto-post of attestation codes.
**Verified On Devices:** Redmi Note 8(9.0)
