### ISSUE TITLE
Claimed escrow payments are appearing as reclaimable

### ISSUE THREAD

**Issue by tarikbellamine** [valora-inc/wallet#32]
### Expected Behavior
When an escrow transaction is claimed by the recipient, the sender should not see the escrow payment as reclaimable.

### Current Behavior
Claimed escrow payments are appearing as reclaimable.

Context: https://celo-org.slack.com/archives/C018VLA3YAK/p1613602576385500

**Comment by jeanregisser** [comment]
Should be part of celo-org/celo-monorepo#6999

**Comment by MuckT** [comment]
Escrow payments removed in https://github.com/valora-inc/wallet/pull/3303.
