### ISSUE TITLE
Store payment request amounts in native currency rather than cUSD

### ISSUE THREAD

**Issue by tarikbellamine** [valora-inc/wallet#33]
### Expected Behavior
When a user makes a payment request in a non-USD currency (e.g., request of 1000 pesos), then the payment request should always be for that amount (e.g., 1000 pesos).

### Current Behavior
Given Valora only currently supports cUSD, payment request conversion rates are made at a point-in-time and therefore are liable to exchange rate movements. For example, if a user makes a payment request for 1000 pesos today, then the conversion rate for pesos goes down tomorrow then their request may only be for 995 pesos.

If we store payment requests in the native currency, we can ensure that a payment request for 1000 pesos will always be 1000 pesos when it's fulfilled. The downside is that this puts extra emphasis on our exchange rates being available and correct.

**Comment by MuckT** [comment]
Closing as requests are no longer supported: https://github.com/valora-inc/wallet/pull/4308
