### ISSUE TITLE
“Confirmation error” popup is shown on the confirming screen when user cancel the first confirmation & again tap on start button from Phone number page. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#330]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.13.1(1004294349) 
**Does not repro version** App Store build 1.12.2 , Play Store build 1.12.2, Test Flight build V1.13.1(56).
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7) , 
**Does not Repro on devices:** iPhone XR (14.2), iPhone 6+(12.4.5)
**Pre-Condition:** Make user user should cancel the first confirmation 
   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. Enter phone number 
6. Tap on start button 
7. Wait for phone number confirming screen
8. Tap on cancel button
9. Tap on Start button again on Phone number page 
10. Observe “Confirmation error” is shown 

**Current Behavior:**  Confirmation error is shown
**Expected Behavior:**  Confirmation error should not show and user should able to redirect to ‘Confirm” page
**Observation:** User is able to complete the verification flow without canceling for first time . 
**Impact:** User  blocked to confirm phone number . 
**Attachment:**  [ConfirmationError.mp4](https://drive.google.com/file/d/18dNh17NbjsX1pT6ARKsPSpy56rYxnjnK/view?usp=sharing)
[Logs](https://drive.google.com/file/d/1bUwCQnjTqXAuz2co1hGSlctkrdox0h_n/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D10](https://valora.testquality.com/project/12128/result/2411775/defect/7822). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D32](https://valora.testquality.com/project/12128/result/2418315/defect/7875).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D33](https://valora.testquality.com/project/12128/result/2418316/defect/7876).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D40](https://valora.testquality.com/project/12128/result/2423220/defect/7891).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D88](https://valora.testquality.com/project/12128/result/2455406/defect/8031).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D175](https://valora.testquality.com/project/12128/result/2513923/defect/8317).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D800](https://valora.testquality.com/project/12128/result/2595278/defect/9478).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D857](https://valora.testquality.com/project/12128/result/2609994/defect/9600).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D858](https://valora.testquality.com/project/12128/result/2609984/defect/9601).
