### ISSUE TITLE
Phone number displayed instead of invited user’s name on “Reclaim Payment” screen 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#356]
**Frequency:** 100%
**Repro on build version:**Android internal build V1.14.0 (1004294350) , Test Flight build V1.14.0(58)
**Repro on devices:** iPhone SE (14.2), Redmi Note 8 (9.0), iPhone 6+(12.4.5) 
**Testing Account:**   (680) 333 1978 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
**Pre-condition:** Users must have been invited to user B who’s contact sould saved in Device.
**Repro Steps:**
1. Launch the application & login with the test account.
2. Go to “Pending Invitation” In-app CTA & observe user B’s profile name should be displayed.
3. Tap on the “Reclaim” button.
4. Now user should on “Reclaim Payment” screen
5. Observed that, 
**Current Behavior:** Phone number displayed twice on  “Reclaim Payment” screen
**Expected Behavior:**  Invited user’s name should be displayed instead of the phone number twice.
**Impact:** Bad user experience.
**Investigation:** Also it is observed that, in previous builds “Unknown” text displayed as profile name.
**Attachment:**  [NameNotDisplayedInReclaimPaymentScreen.mp4](https://drive.google.com/file/d/11U5cm-y_o-qKtXQBRk9uusMHoAuSoWgm/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D16](https://valora.testquality.com/project/12128/result/2413690/defect/7859).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D41](https://valora.testquality.com/project/12128/result/2423255/defect/7892).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in latest android internal release build and latest iOS testflight build V:1.29.2 and observed that issue is still reproducible

Device : Google Pixel 2XL(11.0) , iPhone 12(14.7.1)
thanks..!!
