### ISSUE TITLE
"Account number watermark text” is not fit to the account number field. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#379]
**Frequency:** 100%
**Repro on build version:** internal  build V1.14.1, Test Flight build V1.14.1(59),
**Repro on devices:** Vivo V11 pro (10), iPhone 6+(12.4.5).
**Testing Account:**  (680) 333 1978 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
**Pre-condition:** Make sure user should trigger send secure flow.

  **Repro Steps:**

1. Make sure user is on send secure flow
2. Tap on Account number button
3. Observe Account number water mark text 

**Current Behavior:**  Account number watermark text is not fit.
**Expected Behavior:** account number water mark text is not fit to the account number filed 
 **Impact:** Bad user experience 
**Attachment:**  [AccountNumberWaterMarkText.PNG](https://drive.google.com/file/d/13ent3eSjGlCshgeYjR8D07VCbvjKiLba/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D23](https://valora.testquality.com/project/12128/result/2413781/defect/7866).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in latest android internal release build and latest iOS Testflight release build V:1.29.2 and observed the issue is fixed

Observation : Now only user has to enter only 4 last letters of the account address

attachment : [sendsecure.jpg](https://drive.google.com/file/d/11e74F1rB17vbJliViz_DKi2nD9wWoLN2/view?usp=sharing)

Device :  Google Pixel 2XL(11.0) , iPhone 12(14.7.1)

Thanks..!
