### ISSUE TITLE
"Submit” button is shown enabled even when the user has not entered the account number.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#380]
**Frequency:** 100%
**Repro on build version:** internal  build V1.14.1, Test Flight build V1.14.1(59),
**Repro on devices:** iPhone SE (14.2), Redmi Note 8 (9.0), iPhone 6+(12.4.5)
**Testing Account:**  (680) 333 1978 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
**Pre-condition:** Make sure user should trigger send secure flow.

  **Repro Steps:**

1. Make sure user is on send secure flow
2. Tap on Account number button
3. Observe submit button enables 

**Current Behavior:**  Submit button shows enabled .
**Expected Behavior:** Submit button should show disable when user not entered account number . 
 **Impact:** Bad user experience 
**Attachment:**  [SumbitButton.png](https://drive.google.com/file/d/1LHAHRIFZCjY6tuqyE-HVO_8Bu0GS0WZX/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D22](https://valora.testquality.com/project/12128/result/2413781/defect/7865).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android internal release build and latest iOS testflight release build V:1.29.2  and observed that submit button is seen enabled

Observation : Submit button is seen enabled , however if we click on submit button then error is seen 
Is the above flow fine please confirm

Attachment : [submit.mp4](https://drive.google.com/file/d/1fal4HVTCT5GBk9J8Ba8S4SFJ6Tc-ov5_/view?usp=sharing)

Device : Google Pixel 2XL(11.0) , iPhone 12(14.7.1)

thanks..!!
