### ISSUE TITLE
“Confirmation” error is shown when a user try to verify the phone number after changing the number

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#381]
**Frequency:** 100%
**Repro on Devices:** iPhone 6+ (12.4.5), Vivo V11 (10), one plus 6T (10)
**Repro on build version:**  Android internal build V1.14.1 (1004294351) , Test Flight build V1.14.1(59), Play Store & app store builds V1.13.1

**Repro Steps:**

1. Launch the application and complete education
2. Tap on create new account 
3. add name 
4. Enter phone number 
5. Tap on start button 
6. Make sure user should receive 3 attestation codes 
7. Get back to phone number page 
8. Change the phone number 
9. & try to verify phone number 
10. 
**Current Behavior:** Confirmation error is shown when user try to verify phone number after changing phone number.
**Expected Behavior:** User should be able to continue & complete verification flow if user change the phone number.
**Impact;** User get blocked to complete verification flow
**Attachment:** [ConfirmationErrorAfterchangingPhoneNumber.mp4](https://drive.google.com/file/d/1BDkXlEq1Eo9MUVypzJqtsC61tFRikDYe/view?usp=sharing )
[Logs](https://drive.google.com/file/d/1Kc8RLk05vBXE7_L5Gv53cshBhhpA_ZYt/view?usp=sharing)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R20](https://valora.testquality.com/project/12128/testcase/282097/requirement/11274). Do not remove or edit.

**Comment by Celoqa** [comment]
Hi @MuckT thank you so much for query clarification.
- We are converting into a bug.

**Comment by Celoqa** [comment]
Hi @MuckT  We have verified this issue on latest android internal build v1.14.2 & Test Flight Build V1.14.2 and observe the followings:
- User is able to complete the verification flow after changing the phone number.

**Comment by MuckT** [comment]
https://valora.testquality.com defect [D9](https://valora.testquality.com/project/12128/result/2404491/defect/7794). Do not remove or edit.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser @MuckT We have verified this issue on latest Android internal build V1.14.3 & Testflight build V1.14.3 (62) and found issue is again repro.
Repro steps: 
- Launch the app
-  Walkthrough tutorials 
-  Tap on create new account
- Add name & Photo and tap on next 
- Setup valid pin
- Enter valid phone number 
- Tap on start button & Complete captcha 
- Make sure user should on Confirming screen
- Tap on close button
- change the phone number 
- Again try to complete verification flow
- Observe 
Attachments: [ConfirmationError.mp4](https://drive.google.com/file/d/15-PVKah_vW8C7pRoNGY4nZktgYOrIj4M/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D150](https://valora.testquality.com/project/12128/result/2508206/defect/8276).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D151](https://valora.testquality.com/project/12128/result/2508216/defect/8277).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D154](https://valora.testquality.com/project/12128/result/2508226/defect/8280).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D157](https://valora.testquality.com/project/12128/result/2510245/defect/8285).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D158](https://valora.testquality.com/project/12128/result/2510794/defect/8294).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D159](https://valora.testquality.com/project/12128/result/2510798/defect/8295).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D162](https://valora.testquality.com/project/12128/result/2510877/defect/8298).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D164](https://valora.testquality.com/project/12128/result/2510857/defect/8300).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D168](https://valora.testquality.com/project/12128/result/2510867/defect/8304).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D169](https://valora.testquality.com/project/12128/result/2513127/defect/8305).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D176](https://valora.testquality.com/project/12128/result/2513920/defect/8318).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D177](https://valora.testquality.com/project/12128/result/2513950/defect/8319).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D180](https://valora.testquality.com/project/12128/result/2514776/defect/8331).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D181](https://valora.testquality.com/project/12128/result/2514806/defect/8332).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D196](https://valora.testquality.com/project/12128/result/2515783/defect/8352).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D198](https://valora.testquality.com/project/12128/result/2515793/defect/8354).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D223](https://valora.testquality.com/project/12128/result/2515763/defect/8393).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D232](https://valora.testquality.com/project/12128/result/2515813/defect/8402).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D251](https://valora.testquality.com/project/12128/result/2515803/defect/8421).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D254](https://valora.testquality.com/project/12128/result/2515773/defect/8437).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D502](https://valora.testquality.com/project/12128/result/2552372/defect/8841).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D507](https://valora.testquality.com/project/12128/result/2552382/defect/8846).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D516](https://valora.testquality.com/project/12128/result/2554914/defect/8866).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D525](https://valora.testquality.com/project/12128/result/2554924/defect/8877).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D539](https://valora.testquality.com/project/12128/result/2566499/defect/9021).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D573](https://valora.testquality.com/project/12128/result/2566509/defect/9056).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D574](https://valora.testquality.com/project/12128/result/2566529/defect/9057).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D575](https://valora.testquality.com/project/12128/result/2566519/defect/9058).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D692](https://valora.testquality.com/project/12128/result/2581367/defect/9341).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D705](https://valora.testquality.com/project/12128/result/2586922/defect/9364).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D707](https://valora.testquality.com/project/12128/result/2586952/defect/9368).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D720](https://valora.testquality.com/project/12128/result/2586962/defect/9381).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D721](https://valora.testquality.com/project/12128/result/2586932/defect/9382).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D723](https://valora.testquality.com/project/12128/result/2586912/defect/9384).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D782](https://valora.testquality.com/project/12128/result/2586972/defect/9448).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D795](https://valora.testquality.com/project/12128/result/2594449/defect/9471).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D799](https://valora.testquality.com/project/12128/result/2594439/defect/9476).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D802](https://valora.testquality.com/project/12128/result/2595268/defect/9483).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D806](https://valora.testquality.com/project/12128/result/2597019/defect/9501).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D807](https://valora.testquality.com/project/12128/result/2595278/defect/9502).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D812](https://valora.testquality.com/project/12128/result/2597009/defect/9507).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D813](https://valora.testquality.com/project/12128/result/2601376/defect/9536).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D816](https://valora.testquality.com/project/12128/result/2604533/defect/9556).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D817](https://valora.testquality.com/project/12128/result/2603785/defect/9557).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D822](https://valora.testquality.com/project/12128/result/2605492/defect/9562).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D829](https://valora.testquality.com/project/12128/result/2606080/defect/9570).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D831](https://valora.testquality.com/project/12128/result/2607256/defect/9572).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D832](https://valora.testquality.com/project/12128/result/2606668/defect/9573).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D851](https://valora.testquality.com/project/12128/result/2609403/defect/9594).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D860](https://valora.testquality.com/project/12128/result/2618017/defect/9614).
