### ISSUE TITLE
User redirects to account key page with blank account key when user tap on < in Enter pin page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#393]
**Frequency:** 100%
**Repro on build version:** internal  build V1.14.2, Test Flight build V1.14.2(61)
**Does not Repro on build version:** Play Store V1.12 & App store V1.12
**Repro on devices:** iPhone 6+ (12.4.5), Redmi Note 8 (9.0), One plus 6T (10), iPhone SE (14.2)
**Testing Account:**  (680) 333 1978 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
**Pre-condition:** Enter Pin page is shown when user kill R relaunch the app once after fresh install 

  **Repro Steps:**

1. Install the app & login with test account
2. Kill & Relaunch the app after fresh install 
3. Go to settings page 
4. Tap on Reset button
5. Tap on Continue button
6. Tap on < button on Enter pin page 
7. Observe

**Current Behavior:**  User redirects to account key page with blank account key when user tap on < in Enter pin page
**Expected Behavior:** User should redirect back to the settings page instead of the account key page .
 **Impact:** Bad user experience & User get blocked to see account key. 
**Attachment:**  [BlankAccountKey.MOV](https://drive.google.com/file/d/1DkYK8Q-UJiQ6q4ZMjdwmg4-aLNSqT-ON/view?usp=sharing )

**Comment by gnardini** [comment]
Reducing priority to P2 since this only happens if the user presses the back button in one specific flow and there's an easy workaround (just put in the PIN).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D21](https://valora.testquality.com/project/12128/result/2413750/defect/7864).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D125](https://valora.testquality.com/project/12128/result/2471215/defect/8208).
