### ISSUE TITLE
User not able to see 3 of 5 step after proceeding from 2 of 5 while creating account.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#394]
**Frequency:** 100%
**Repro on Devices:** iPhone 6+ (12.4.5), Vivo V11 (10), one plus 6T (10)
**Repro on build version:** Android internal build V1.14.2, Test Flight V 1.14.2(61) Android internal build V1.14.0 (1004294350) , Test Flight build V1.14.0(58), Play Store build V1.13.1

**Repro Steps:**

1. Launch the application and complete education
2. Tap on create new account 
3. Add name [User should able to see 1 o0 5 in add photo page]
4. Tap on Next button
5. Enter pin page should show [2of5 is shown in enter pin page]
6. Enter valid pin 
7. Observed that, 
**Actual Result:** 4 of 5 step is shown on phone number page 
**Expected Result:** 3 of 5 should show on second time entering pin
**Observation:** .User is able to see all pages while restoring accounts
**Attachment:** 
[CreateNewAccount.MP4](https://drive.google.com/file/d/15voJo0RfX3YciQ_-0IIr1otZqNeG66UB/view?usp=sharing)
[RestoreAccount.MP4](https://drive.google.com/file/d/17blGdGULGRoyWylYjrNaNyzW_D9YAnMp/view?usp=sharing )

**Comment by ValoraQA** [comment]
Hi, We have verified this issue on Latest Android internal build V1.17.0 & Test flight build V1.17.0 and observed that issue is still reproducible.
**Devices:** iPhone 12 (14.7.1), Google Pixel 4a (11.0)

**Comment by lisaqyli** [comment]
@ValoraQA Can you help to give me access to the attachments? I cannot access them with my Valora account
