### ISSUE TITLE
Valora wallet (android) BROKEN: does not receive transactions from connected dapps.

### ISSUE THREAD

**Issue by paro-paro** [valora-inc/wallet#4044]
Our valora wallet users have reported a disruption of service a few days ago.

### Current behavior

Sending transactions to the valora wallet after a successful connexion to a(ny) dapp (using wallet-connect v2) wont prompt any confirmation within the wallet. Getting a time out error in most cases.

I have tried connecting other mobile wallets (Metamask and TrustWallet) to the same dapps through wallet-connect and transactions are received properly (so I guess its not a wallet-connect v2 issue).

### Desired behavior

Valora wallet will prompt users for transaction confirmation (as usual). 

### Steps to Reproduce

Connect any dapp to valora. I have tried connecting dapps to valora from both the browser and integrated dapps within valora > dapps section.

After a successful connexion, try to launch any transaction. Valora will not prompt the user for confirmation, showing a time out error in most cases.

### Versions

Valora android latest version 1.63.0

![photo_2023-08-08_00-26-55](https://github.com/valora-inc/wallet/assets/43136874/4b684ad0-340d-4529-a139-28c9f9136311)
![photo_2023-08-08_00-28-35](https://github.com/valora-inc/wallet/assets/43136874/c0959eda-a2c3-4bba-a38d-383787cd4866)

**Comment by MuckT** [comment]
Tagging the related discussion: https://github.com/orgs/WalletConnect/discussions/3291

**Comment by paro-paro** [comment]
Hey @MuckT thanks for pointing me to the related discussion. 

I have read it and I am still not quite sure how to proceed. Do we have to tell all our users to re-install and re-import their Valora wallet? From the discussion:

"But for real users, the only option to recover from this is to reinstall Valora and re-import their account. Which is a big problem."

This will definitively be a terrible pain. 

Anything we can do at the dapp level to try to fix it? Or is it a wallet-connect issue at the wallet side?  

Any help will be really appreciate it since we have lots of users affected by this at this moment.

**Comment by MuckT** [comment]
@paro-paro this should be fixed in the latest release [1.64.2](https://github.com/valora-inc/wallet/releases/tag/valora-v1.64.2) which is rolling out now. If you're able to update would you please kindly confirm the fix? Thanks in advance! 🙏

**Comment by paro-paro** [comment]
Thanks @MuckT and sorry for my late reply. Seems that everything is working fine now.
