### ISSUE TITLE
[Device specific]User automatically redirects to the First walkthrough screen when trying to add photo.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#412]
**Frequency:** 100%
**Repro on build version:** internal  build V1.14.2,Playstore build V1.12
**Repro on device:** Samsung Galaxy J7 pro (8 OS), Samsung Galaxy J5 Prime (8.0)
**Does not Repro on devices:** Vivo Y83 pro(8 Os) ,iPhone 6+ (12.4.5), Redmi Note 8 (9.0), One plus 6T (10), iPhone SE (14.2)
  **Repro Steps:**

1. Install the app 
2. Walkthrough tutorials 
3. Tap on create new account 
4. Try to add photo 
5. Observe after tapping on right mark

**Current Behavior:**  User redirects to First walkthrough screen after adding photo 
**Expected Behavior:** User should stay on Add photo page.
**Observation:** User able to add the photo 
 **Impact:** Bad user experience. 
**Attachment:**  [RedirectsToFirstWalkthroughScreen.mp4](https://drive.google.com/file/d/1Bw6WNPjLYpGpkkTtVnyKGGkSG9xMV0W4/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D78](https://valora.testquality.com/project/12128/result/2450318/defect/8013).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D79](https://valora.testquality.com/project/12128/result/2450334/defect/8014).

**Comment by ValoraQA** [comment]
Hey I have verified this issue using Alfajores build V1.18.3 & observed that issue is still reproduced.
**Verified On Devices:** Samsung Galaxy J5 Prime (8.0)
**Attachment:** [RedirectToFirstScreenAfterUploadingPhoto](https://drive.google.com/file/d/1hHGxMEaWcdCAYuYuMg2BG9Rope_96c4e/view?usp=sharing)
