### ISSUE TITLE
Two different  popups are shown when user decrease amount in “Amount” field on “Add Funds” screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#421]
**Frequency:** 100%
**Repro on build version:** Test Flight build V1.14.2(61), Android  internal  build V1.14.2
**Repro on devices:** iPhone SE (13.6.1) , iPhone SE (14.2), iPhone 6+(12.4.5),  Redmi Note 8 (9.0),Samsung Galaxy J5 Prime (8.0.0)
**Testing Account:**   (484) 299-7470/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)   
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Hamburger Menu 
3. Tap on “Add and Withdraw” & Select “Add Funds” option
4. Select “Celo Dollar(cUSD) as digital currency & Pay with “Debit Card” & tap on “Next” button.
5. Now the user is on the “Add Funds” screen.
6. Now tap on the “Next” button by entering a large amount(e.g.500000) & observe popup.
7. “Our providers do not support larger than $100301. Please enter smaller amount” popup displayed
8. Now decrease the amount value by removing one digit & observe popup
9. User able to see popup regarding increase daily send limit
**Current Behavior:**  User able to see two different popup depending on amount entered
**Expected Behavior:**  Users should be  able to see the same popup even user decreased values from any range.
**Investigation:**
We have observed the issue in Android for boundry value of limit.  i.e. when user enters amount as 500000 then user able to see "providers not support larger than $5000. And user able to see increase daily limit popup for $5000 as amount
**Impact:** Bad user experience.
**Attachment:**  [iOS_PopupBasedOnValues.wmv](https://drive.google.com/file/d/1ydJ9zqHkJbmmXZbL4gSrsaytNZe47-kj/view?usp=sharing)
                            [Android_IssueForBoundryValue](https://drive.google.com/file/d/1IJ2GSLucd_6h14I9epj0Jv1j3bI3X3-s/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D12](https://valora.testquality.com/project/12128/result/2413707/defect/7847). Do not remove or edit.

**Comment by Celoqa** [comment]
Related issue

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D13](https://valora.testquality.com/project/12128/result/2413707/defect/7848). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D14](https://valora.testquality.com/project/12128/result/2413713/defect/7854). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D36](https://valora.testquality.com/project/12128/result/2418370/defect/7881).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D45](https://valora.testquality.com/project/12128/result/2430750/defect/7921).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D58](https://valora.testquality.com/project/12128/result/2433551/defect/7948).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D62](https://valora.testquality.com/project/12128/result/2433557/defect/7952).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D90](https://valora.testquality.com/project/12128/result/2457587/defect/8055).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D91](https://valora.testquality.com/project/12128/result/2457593/defect/8057).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D92](https://valora.testquality.com/project/12128/result/2455495/defect/8059).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D118](https://valora.testquality.com/project/12128/result/2471121/defect/8197).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D120](https://valora.testquality.com/project/12128/result/2471127/defect/8199).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.28.1 & Test flight Release Build V 1.28.1 and observed that the issue is fixed now. Same popups are shown when user decrease amount in “Amount” field on “Add Funds” screen, hence we are closing the issue.

**Devices:** Samsung Galaxy A9 pro(8.0), iPhone 13 mini(15.1.1), iPhone 6+(12.5.5), Redmi Note 7 Pro(10.0)

**Attachments:** [Popup.mp4](https://drive.google.com/file/d/1CZyP5qvD3eHV7sirps3apeR3-9muUxxM/view?usp=sharing) 

Thanks..!!
