### ISSUE TITLE
 User not redirects to “Add Funds” page when user taps on “</Valora” button on “kotnipay.com” page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#422]
**Frequency:** 100%
**Repro on build version:** Test Flight build V1.14.2(61).Android  internal  build V1.14.2
**Repro on devices:** iPhone SE (13.6.1) , iPhone SE (14.2), iPhone 6+(12.4.5), Redmi Note 8 (9.0),  Samsung Galaxy J5 Prime (8.0.0), Samsung Galaxy J7 pro (8.0)
**Test Account:** +254 60 05334/[Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B5)
**Pre-condition:** Make sure that user should login with Kenya country phone number 
**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Hamburger Menu 
3. Tap on “Add and Withdraw” & Select “Add Funds” option
4. Select “Celo Dollar(cUSD) as digital currency & Pay with “M-PESA Kotni Pay” & tap on “Next” button.
5. Now user should be on “kotanipay.com” page
6. Now tap on “<” (for android) or “<Valora” (for iOS ) button & observed that, 
**Actual Result:** User redirect to Home screen after tapping on back button.
**Expected Result** User should redirect back to “Add Funds” screen when user taps on back button
**Attachment:**[UserNotRedirectToPreviousPageForKenya.wmv](https://drive.google.com/file/d/13ILcjb9SGXQZjWhkkwg5IdArFSSs2qMi/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D15](https://valora.testquality.com/project/12128/result/2413717/defect/7858).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D18](https://valora.testquality.com/project/12128/result/2413728/defect/7861).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D19](https://valora.testquality.com/project/12128/result/2413731/defect/7862).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D20](https://valora.testquality.com/project/12128/result/2413734/defect/7863).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D49](https://valora.testquality.com/project/12128/result/2430760/defect/7925).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D52](https://valora.testquality.com/project/12128/result/2430771/defect/7928).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D53](https://valora.testquality.com/project/12128/result/2430774/defect/7929).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D54](https://valora.testquality.com/project/12128/result/2430777/defect/7930).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D64](https://valora.testquality.com/project/12128/result/2433561/defect/7955).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D66](https://valora.testquality.com/project/12128/result/2433572/defect/7957).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D67](https://valora.testquality.com/project/12128/result/2433575/defect/7958).

**Comment by ValoraQA** [comment]
Hey I have verified this issue using latest Test Flight build V1.17.0 & Android internal build V1.17.0 & observed that issue is reproduced.
**Verified On Devices:** iPhone SE (14.2), Redmi Note 8 (9.0)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D494](https://valora.testquality.com/project/12128/result/2545806/defect/8829).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D495](https://valora.testquality.com/project/12128/result/2545797/defect/8830).
