### ISSUE TITLE
 Phone number does not gets deleted on tapping on mobile keypad remove button after entering indian phone number in confirm phone number page.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#461]
**Frequency:** 100%
**Repro on build version:** Playstore Build V1.14.3 internal build V1.15.1, Testflight build V1.15.1(64) appstore build V1.14
 **Repro on devices:** Redmi note 8 (10.0), Vivo V11 pro (10), Iphone SE2 (14.2), iPhone 6+ (12.4.5)
**Account details:** Enter any india number +91 7673907656

**Pre-condition:** 
 - Make sure user should enter india number & tap on mobile keypad remove button.

  **Repro Steps:**

1. Launch the application 
2. Complete education
3. Complete Add photo page 
4. Select india country & Enter Indian phone number 
5. Tap on mobile keypad remove button 2 times 
6. Observe number not get removed 

**Current Behavior:**  Phone number does not gets deleted on tapping remove button. *Expected Behavior:* Phone number must get removed on tapping remove button. 
**Investigation:**
1.  Also it is observed that, on continuously tapping remove button oo removing two digits of phone number, it automatically gets replaced by 91 digits repeatedly.
2. This issue is not repro on selecting “United states” from country flag drop down menu.
**Impact:** Users may be confused on phone number not getting removed on tapping remove button.
**Attachment:** [RemoveEnteredNumber.mp4](https://drive.google.com/file/d/14cUIvu8Qpwn2D28u7tgW29Fbbvu5BX9y/view?usp=sharing )

**Comment by MuckT** [comment]
Looks to be related to onFocus and related to [Entered phone number is not removed when user tap on “X” in the Phone number field. #7069](https://github.com/celo-org/celo-monorepo/issues/7069)

**Comment by tarikbellamine** [comment]
These two issues do indeed appear to be the same. Can we consolidate into one as to not bloat the backlog @MuckT?

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D31](https://valora.testquality.com/project/12128/result/2418110/defect/7874).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue on android internal build V:1.23.3 and observed that issue is still reproducible 
**Observation** :  When user taps on the back key( from phone keyboard) it does not delete the numbers completely , the country code repeats on the phone number field

**Attachment** : [Phonenumber.mp4](https://drive.google.com/file/d/1mp-yFez9oZY_FRD0xjvYo8YQxmmagoVg/view?usp=sharing)
**Device** : OnePlus 7T(11.0)
