### ISSUE TITLE
Facing issues to complete transaction/order for different staging providers from “Add Funds” screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#479]
**Frequency:** 100%
**Repro on build version:** Alfajores Build V1.14.3 & V1.14.3 (62)
**Repro on devices:** iPhone SE (14.2), iPhone 6+(12.4.5), Redmi Note 8 (9.0), One plus 6T (10)
**Test Account:** (408) 657 3238 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B71) 
**Pre Condition:** Make sure that user should redirect to  “Add Funds” page with below providers:
1. Transak
2. Xanpool
3. Ramp
4. Moonpay
5. Simplex
**Repro Steps:**

- **For Transak:**

1. Tap on Transak provider & redirect to “staging.global.transak.com” page
2. Tap on the country flag in the “You pay” field.
3. Observed that, nothing happens after tapping on the flag & the user is unable to change currency. [Attachment](https://drive.google.com/file/d/1wwfh2gogUFWUSDuHdTbQAID1uW6dcPMB/view?usp=sharing)
4. Moreover, if the user redirects to the “Confirm Your Order” page & tries to confirm the order then “Card Payment option  not available in your Country” error message displayed. Also, users have by default selected only one “Card Payment” method shown & hence users are not able to complete orders. [Attachment](https://drive.google.com/file/d/1UwjWU2Jt8QjRT_yrZmtAPWfXvmEUqaIN/view?usp=sharing)

- **For Moonpay:**

1. Tap on Moonpay provider & redirect to “Make your payment” page by tapping continue on “Buy cUSD” page.
2. Check IN in MoonPay’s terms & conditions checkbox
3. Wait for some time & observed that, “Transaction processing Failed” message displayed in order tracking map instead of Order confirmed screen. [Attachment](https://drive.google.com/file/d/1wj8ndedZRDTbTDaLAFVWvh_4IEGSB40H/view?usp=sharing)
**FYI:** As of now we are testing Moonpay order on “https://buy-staging.moonpay.com/” this web page as discussed with Tom

- **For Simplex:**

1. Tap on Simplex provider & fill all proper details in both “Order Summary” & “Billing Address” page & redirect to “Upload identity document” page
2. Upload image of selected document & select expiry date & tap on “Upload Document” button.
3. Observed that , user redirect to screen with different options like “AUTHENTICATION SUCCESSFUL, FAILED, ...etc. & user able to submit order only by tapping on “AUTHENTICATION SUCCESSFUL” option is this expected ? [Attachment](https://drive.google.com/file/d/1n6p9wL9Dr1EwMcs2w3yKDlqtx42qlShZ/view?usp=sharing)

- **For Xanpool:** 

1. Tap on Xanpool provider & redirect to “chekout.sandbox.xanpool.com” page.
2. Tap on the “Next” button & Complete “Sign Up” or “Login” process.
3. Complete verification process by uploading documents, photos, videos & tap on “Next” button
4. Observed that , user redirects to “We are verifying your account it will take at most 10 minutes” processing message displayed for longer time 7 hence user is unable to complete order.[Attachment](https://drive.google.com/file/d/1pbPhIQstGBLSzoKRy0ajgKpvY9xNo-yS/view?usp=sharing)
**Note:** Can you please provide us with a sample video to upload for testing purposes ?

- **For Bidali:** 

1. Redirect to Bidali screen & select product (whose amount is less than or equal to present account balance) & enter mail address by tapping on “PURCHASE”  button.
2. Tap on “Next” button
3. Observed that, Error screen displaying instead of order confirmed screen. [Attachmenet](https://drive.google.com/file/d/1nu-UI7FJuYbOrpOF2II90OSg9sz8dDno/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D26](https://valora.testquality.com/project/12128/result/2418068/defect/7869).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D27](https://valora.testquality.com/project/12128/result/2418069/defect/7870).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D28](https://valora.testquality.com/project/12128/result/2418071/defect/7871).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D29](https://valora.testquality.com/project/12128/result/2418072/defect/7872).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D30](https://valora.testquality.com/project/12128/result/2418074/defect/7873).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D42](https://valora.testquality.com/project/12128/result/2423275/defect/7894).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D46](https://valora.testquality.com/project/12128/result/2430751/defect/7922).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D47](https://valora.testquality.com/project/12128/result/2430755/defect/7923).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D48](https://valora.testquality.com/project/12128/result/2430756/defect/7924).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D51](https://valora.testquality.com/project/12128/result/2430766/defect/7927).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D60](https://valora.testquality.com/project/12128/result/2433750/defect/7950).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D61](https://valora.testquality.com/project/12128/result/2433556/defect/7951).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D63](https://valora.testquality.com/project/12128/result/2433557/defect/7953).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D65](https://valora.testquality.com/project/12128/result/2433565/defect/7956).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D95](https://valora.testquality.com/project/12128/result/2457598/defect/8109).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D119](https://valora.testquality.com/project/12128/result/2471122/defect/8198).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D121](https://valora.testquality.com/project/12128/result/2471132/defect/8200).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D122](https://valora.testquality.com/project/12128/result/2471137/defect/8201).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D129](https://valora.testquality.com/project/12128/result/2479385/defect/8215).
