### ISSUE TITLE
Error: • TypeError: Invalid argument type in ToBigInt operation. when trying to sign a transaction

### ISSUE THREAD

**Issue by meetkosiso** [valora-inc/wallet#4805]
### Current behavior
Submitting transactions on some Valora wallets via our dapp throws out an exception of `TypeError: Invalid argument type in
ToBigInt operation`,  so we have some users experiencing issues submitting transactions via the Valora wallet. 

Please see the screenshots below:
![8b25e865-62a0-4abd-ad66-0ce73cfbf515](https://github.com/valora-inc/wallet/assets/20558092/3780f7fa-7e5b-4a56-92b5-b82ebbc2093c)
![e24b3de7-444b-4263-bcd9-6e3bab7f8c62](https://github.com/valora-inc/wallet/assets/20558092/783c228e-079f-48ec-ae93-b3f3db3daa23)

I also want to clarify that this exception does not throw for all Valora users on our dapp, but it happens to some users

### Desired behavior
The desired behavior is for users to successfully sign and complete the transaction on the Valora wallet.

### Steps to Reproduce
On our dapp we are sending some call data to the Valora wallet, the user has to sign in to complete the transaction, please see sample data below:

{
    "from": "0xb9c48b52fbebfbb667bc3c983cba2ebadf14b251",
    "to": "0x918146359264c492bd6934071c6bd31c854edbc3",
    "data": "0x095ea7b3000000000000000000000000970b12522ca9b4054807a2c5b736149a5be6f67000000000000000000000000000000000000000000000003635c9adc5dea00000",
    "value": "0x00",
    "gasPrice": "0x02ad741300"
}

When some users try to sign this call data, the Valora wallet throws `TypeError: Invalid argument type in
ToBigInt operation`.
![8b25e865-62a0-4abd-ad66-0ce73cfbf515](https://github.com/valora-inc/wallet/assets/20558092/2640a2d5-bcb7-4278-aa79-a88f00bd397f)

### Versions
OS: iOS 16.7.4
Valora Version:  1.75.1
Browser: Safari

**Comment by jeanregisser** [comment]
Thanks for reporting!

This should be fixed with https://github.com/valora-inc/wallet/pull/4864
And is now available in Valora >= 1.77

Let me know if you still see issues.
