### ISSUE TITLE
Fix phone number formatting on Send screen

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#486]
### Current behavior
In the Send screen phone number formatting is inconsistent, even for US phone numbers that are stored similarly in contacts.

See https://celo-org.slack.com/archives/C018VLA3YAK/p1623436627075500

**Comment by MuckT** [comment]
Related PR: _Display contact phone numbers in the same format they are saved in_ #410

Clarification on the acceptance criteria would be helpful: [QA query](https://github.com/celo-org/wallet/pull/410#issuecomment-854394070).
