### ISSUE TITLE
Create function for showing amounts in local currency

### ISSUE THREAD

**Issue by isabellewei** [valora-inc/wallet#492]
### What would you like?
A function equivalent of `<CurrencyDisplay />` so we can format money amounts as text only

### Why is this needed?

https://github.com/celo-org/wallet/pull/452#discussion_r647306859

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R53](https://valora.testquality.com/project/12128/testcase/292843/requirement/11547).
