### ISSUE TITLE
Account Key Truncated When Large Accessibility Text is Used

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#502]
### Current behavior

- When using large accessibility text on iOS the account key is truncated on obscured. On Android 'Learn about Account Keys' overlaps account key text.

**iOS:**
![iOS-AccountKey-AccessibilityText](https://user-images.githubusercontent.com/26950305/122267871-3ed9b680-ce90-11eb-8b73-3dcd80c18d75.png)

**Android:** 
![Android-AccountKey-AccessibilityText](https://user-images.githubusercontent.com/26950305/122267900-46995b00-ce90-11eb-8c15-9aac81434381.png)

### Desired behavior

- Account Key displays in it's entirety unobscured for all text sizes.

### Steps to Reproduce
- Set font size to the largest size on iOS or Android: Settings > Accessibility > Font Size
- Observe the Account Key in Valora.

**Comment by Celoqa** [comment]
Hi @MuckT 
FYI: We have raised same issue in the past https://github.com/celo-org/celo-monorepo/issues/6357
