### ISSUE TITLE
[Device Specific] App get crashed when user trying to perform “Buy/Sell” CELO action from “CELO  price” page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#506]
**Frequency:** 100%
**Repro on build version:**  Android Internal build 1.15.1
**Repro on device:** Samsung Galaxy S4(4.4.2)
**Does Not repro On Devices:** Samsung Galaxy S4 (5.0.1), Samsung Galaxy A5(7), Samsung Galaxy J5 Prime (8.0.0), Redmi Note 8 (10)
**Test Account:** (680) 333 1978 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
**Pre Condition:** Make sure that the user should be able to see both “Buy” and “Sell” buttons on the CELO page.
 **Repro Steps:**
1. Launch the application and login with the test account & redirect to Home screen.
2. Tap on “CELO” from Hamburger menu.
3. Tap on “Buy” button 
4. Now user should be on “Buy CELO” page
5. Enter valid amount & make sure that “Review” button should get enabled
6. Wait for some time & observed that,
**Actual Result:** App get crashed & users thrown out of the application.
**Expected Result:** User should be able to proceed to perform Exchange without any crash
**Investigation:** Also we have observed the same issue on the “Sell CELO” page.
**Attachment:** [AppCrashOnBuyCELOPage.mp4](https://drive.google.com/file/d/1DhgIZp7Wvt6M2HTE1E7fFK1kBmJKDOuO/view?usp=sharing)
[Crash_Logs](https://drive.google.com/file/d/19tsm-MTIgLYaVwT4_dN6C3dtxWXeQ1Xa/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D39](https://valora.testquality.com/project/12128/result/2420895/defect/7888).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest Android Internal release build V:1.37.1 and observed that issue is fixed

Device : Samsung Galaxy A3(5.0.2)

Thanks..!
