### ISSUE TITLE
Allow type value to send a coin or token in fiat or that token.

### ISSUE THREAD

**Issue by luisalrp** [valora-inc/wallet#5145]
### Allow users to say how much tokens they want to send, writing it in their fiat or cUSD or cEUR value.

It was how it was done before. You can type how much tokens you want to send in those tokens or on fiat value.

### Why is this needed?

It was really helpful as a day to day wallet to use it for paying for coffee or whatever.

**Comment by lisaw-valora** [comment]
Hi @luisalrp, this is a great idea. Thank you for posting!

To get this in front of our product team, please submit it through our [feature request form](https://support.valoraapp.com/hc/p/feature-request?utm_source=github&utm_medium=support&utm_campaign=feature_requests).

We are excited to hear more about this and any other ideas you have for improving Valora.
