### ISSUE TITLE
Update daily limit from 500 to 1000 in the notification

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#515]
Context: https://valora-app.slack.com/archives/C0134SBQTQR/p1623879963023400

**Comment by dievazqu** [comment]
I think this was already done here: https://github.com/valora-inc/wallet/commit/31c44cfc2429046ce9bb11f28936303457c8b257
I tested locally, and it's using 1000 as limit
@jeanregisser I think we can close this

**Comment by ValoraQA** [comment]
Hey @aleksey-nov  , We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Gsuite.

**GSuite Link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1462650076

**Verified On Devices:** OnePlus 7t (11.0) , iPhone 6+ (12.5.4), Redmi note 8 (10.0), iPhone 12 (14.7.1)

CC: @jeanregisser

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R82](https://valora.testquality.com/project/12128/testcase/299595/requirement/11853).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**Android (9.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485115

**Verified On Devices:** Redmi Note 8 (9.0) 
CC: @dievazqu
