### ISSUE TITLE
Improve the display of account keys to reduce copy errors

### ISSUE THREAD

**Issue by nategraf** [valora-inc/wallet#52]
Account key mnemonics are currently displayed in a text box without any major formatting. As a result it is difficult to accurately copy down all 24 words correctly and in order without missing any.

With a structured display of the account key mnemonic, such as 4 words per row in 6 rows, it would be easier and quicker to copy down the words and avoid mistakes that could lead to being unable to recall the account key in the future.

### Related

https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/3250

**Comment by coreycelo** [comment]
Doesn't look like I can assign myself to this, but I've worked on this and would love to sync up.
