### ISSUE TITLE
Language selection overlaps with "Connecting..." banner on Welcome onboarding screen

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#559]
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1, IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** Samsung Galaxy A5 (7.0, iPhone 6 (12.4.7),iPhone 11(14.0)
**Precondition:** Make sure connecting banner should shown on walk-through screen 
**Repro Steps:**

1. Launch the fresh installed Application 
2. Select English language from Select Language screen
3.  Tap on English text top right corner and change language to Espanol
4. Make sure user will be redirected back to “Send and receive money instantly” walk-through screen
5. Observe

**Current Behavior:** “Espanol..” text overlapped with the “Connecting…” banner
**Expected Behavior:** Text should be displayed without overlapping
**Attachment:** [SelectlanguageTextOverlappingIssue.png](https://drive.google.com/file/d/1kYxDtfkL2lRnVtxeEmIKodqScBuyfbc3/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @MuckT @aleksey-nov we have verified this issue on latest builds Android internal build V1.16.1 & Testflight build V1.16.1(67) and observe the followings.
-  “Espanol..” text overlapped with the “Connecting…” banner when user as bad connection 
- "Portuges.. " text overlapped with the “Connecting…” banner when user as bad connection

**Devices:** iPhone 6+ (12.4.5). iPhone SE  (14.6), Vivo v11 pro (10), Google pixel 4a (11), Samsung Galaxy S4(4)

**Comment by MuckT** [comment]
@ValoraQA this should be resolved by #913.
