### ISSUE TITLE
Prompt Users to Complete an Account Key Quiz

### ISSUE THREAD

**Issue by nityas** [valora-inc/wallet#560]
### Expected Behavior

Remind users to enter their account key to confirm they still have it

### Current Behavior

We currently don't prompt user/communicate to them that they should have the account key in their possession (designs to be added)

### What's important about this?
Users have been forgetting their account key after setup, this issue attempts to patch this problem while larger account key structural changes are coming.

### What is "done"?

Figma designs implemented: https://www.figma.com/file/7UvvzrKLXpS7iaNcZb4NX1/Account-Key?node-id=223%3A1557

### What's involved in doing this work?

[see figma]

**Comment by kathaypacific** [comment]
Closing for backlog spring clean May 2022
