### ISSUE TITLE
Review button gets enabled on adding value even account balance is $0.00

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#564]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V 1.10.1(1004294336), Testflight build 1.10.1(46) 
**Does not repro version** Android Internal Build V 1.10.1(1004294335), Testflight build 1.10.1(45) 
**Repro on devices:** Samsung Galaxy A5(7.0),iPhone XR(14.2), iPhone SE(13.4.1)
Testing Account:  (517) 236-8556/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B11) 
**Pre-condition:** Users should have a $0.00 balance in account.
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on the Send button on the home screen.
3. Now search for any user number & select that user.
4. Now the user is on the Send screen.
5. Now enter any amount in the amount field.
6. Observed that,

**Current Behavior:**  “Review"  button gets enabled even if the user has 0 balance.
**Expected Behavior:**  “Review” button should not be enabled & proper error message should display.
**Impact:** Bad user experience.
**Attachment:**  [ReviewEnableEvenZeroBalance.mp4](https://drive.google.com/file/d/1Hndv9onmCSBZsGzMs8akBp9M5Km7q2L7/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We are closing this issue as when user have $0 balance than send button will not get enabled as per new feature. [Link1](https://github.com/valora-inc/wallet/issues/1757#issuecomment-1014606960) , 
[Link2](https://github.com/valora-inc/wallet/pull/1809)
Thanks..!!
