### ISSUE TITLE
User is not redirected to the “Settings” screen after updating the user name from the “Edit profile” option

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#566]
**Frequency:** 100%
** Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Does not repro on:** App store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)

**Repro Steps:** 

1) Launch app and login with tested account
2) Tap on the hamburger menu. 
3) Tap on setting option. 
4) tap on edit profile option. 
5) tap on Edit name 
6) Update the username and tap on the return button on Keypad. 
7) Observe the user's stay on the Edit name screen. 
**Current Behavior:** User is not redirected to the “Settings” screen

**Expected Behavior:** Users should be redirected to the settings screen after updating username. 
**Impact:** Users need to put in manual efforts to see changes. 
**Attachment:** [EditNameIssue.mp4](https://drive.google.com/file/d/1Y-zGLch7ZL_AxQEhjW8vZFPcWZBQhXBc/view?usp=sharing) (Bug Observed at 14 sec)

**Comment by MuckT** [comment]
User is redirected to settings after saving a name edit.

https://user-images.githubusercontent.com/26950305/193934161-ff487857-d741-44d6-8ff9-c31d0fc11933.mov
