### ISSUE TITLE
“Syncing Completed” message is shown when the user “Deny” button from contact access pop up. 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#568]
**Frequency:** 100%
**Repro on build version:**  v1.6.0(1004294326)  and Test Flight build v1.6.0(37)
**Repro on devices:** iPhone SE 2 (14.2) , Google Pixel Xl (8.1) 

**Repro Steps:**

1. Launch the application & start the onboard flow.
2. Complete phone number verification flow. 
3. Make sure the user is on the Connect Contacts screen. 
4. Tap on the Deny button for contact access. 
5. Observe status of sync contact. 

**Current Behavior:**  Syncing Completed message is shown 
**Expected Behavior:**  Syncing completed messages should not show and status can be shown as pending. 

**Impact:** User may be get confused that they have denied access but still contacts are synced. 

**Attachment:**  Contact_PermissionIssue.mp4 [https://drive.google.com/file/d/1IzQBN4My22v4iohA_QJEWomVSN2KHAhs/view?usp=sharing](Bug observed at 04 sec)

**Comment by ValoraQA** [comment]
Hey @MuckT Since connect contact screen is not shown as per the information shared in the PR ,hence we are closing this issue 

PR link : [link](https://github.com/valora-inc/wallet/issues/1073)

Thanks.!
