### ISSUE TITLE
“Incorrect PIN” Message is shown when user taps on < back from Enter PIN screen while proceeding to withdraw CELO 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#569]
**Frequency:** 100%
**Repro on build version:** v1.5.2 (31) and Play store internal build 1.5.2 (1004294320)
**Repro on devices:** iPhone SE 2 (14.1) , Google Pixel (8.1) 
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on hamburger menu 
3. Tap on CELO. 
4. Tap on Withdraw CELO
5. Paste Address and enter Amount. 
6. Tap on the Review button. 
7. Tap on the Withdraw button. 
8. Tap on < from enter PIn screen
9. Observed. 

**Current Behavior:**  “Incorrect PIN” Message is shown
**Expected Behavior:**  Transaction fail appropriately message should be shown 
**Investigation:** User is not able  to proceed to send CELO after navigating back from enter PIN 
**Impact:** Bad user experience, Inappropriate message is shown 
**Attachment:**  [Inccorect_Pin.mp4](https://drive.google.com/file/d/1IWrf9cBPGyIgcaDgKLcdGUI56_d6toWP/view?usp=sharing)(Bug observed at sec)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest Android Internal release build and latest iOS testflight release build V:1.29.2 and observed that there should be no alert seen incase if user does not enter any pin and clicks on < from Pin page
hence we are closing this issue

Attachment : [pin](https://drive.google.com/file/d/1Fjj-pNrZZT-_3J_OSsRAuT08Wj34QWI4/view?usp=sharing)

Devices : Google Pixel 2XL (11.0) , iPhone 12(14.7.1)

CC: @gnardini 
Thanks..!
