### ISSUE TITLE
upgrade contractkit (and friends)

### ISSUE THREAD

**Issue by aaronmgdr** [valora-inc/wallet#5733]
Hi, 

I see this seemingly supported repo is using a [deprecated version of celo contractkit. ](https://github.com/valora-inc/wallet/blob/536d87f0c2c98eda625ddbace9d4a2ad0b343575/package.json#L74
)

This version of contractkit only [supports transaction type](https://github.com/celo-org/txtypes?tab=readme-ov-file#scheduled-for-deprecation-on-celo) that will cease to function when celo completes its L2 transition.

The minimum supported version of contract kit is [@celo/contractkit@8.1.0](https://github.com/celo-org/developer-tooling/releases/tag/%40celo%2Fcontractkit%408.1.0)

I recommend upgrading within the next 3 months.

**Comment by lisaw-valora** [comment]
Thank you for posting and letting us know. Our team is looking into it.
