### ISSUE TITLE
  Entered phone number is not removed when user tap on “X” in the Phone number field.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#576]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.10.1(1004294336), Test Flight Build V1.10.1(46)
**Does not repro version** Android Internal Build V1.10.0(1004294335), Test Flight Build V1.10.0(45)
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone XR(14.2),  iPhone 6+ (12.4.5)

  **Repro Steps:**

1.  Launch the application 
2. Go through signup flow
3. Enter phone number on phone number filed
4. Tap on X button
5. Observe 

**Current Behavior:**  Entered phone number is not removed when tapping on X.
**Expected Behavior:** Entered phone number should removed when tapping on X .
**Investigation:** Also it is observed that keyboard gets removed instead of entered numbers when user taps on X button.
**Impact:** User get blocked to remove phone number by tapping on X.
**Attachment:**  [NotRemovedPhonenumber.mp4](https://drive.google.com/file/d/1Ao05YgiEdRapU4kfs0hlt73WWEocxXNi/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D83](https://valora.testquality.com/project/12128/result/2450760/defect/8024).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D103](https://valora.testquality.com/project/12128/result/2470895/defect/8178).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D103](https://valora.testquality.com/project/12128/result/2470895/defect/8181).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D125](https://valora.testquality.com/project/12128/result/2471208/defect/8206).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D125](https://valora.testquality.com/project/12128/result/2471208/defect/8207).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D126](https://valora.testquality.com/project/12128/result/2471208/defect/8211).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D140](https://valora.testquality.com/project/12128/result/2485256/defect/8259).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D257](https://valora.testquality.com/project/12128/result/2524691/defect/8443).

**Comment by ValoraQA** [comment]
Hey @MuckT, This feature has been removed as per PR [link](https://github.com/valora-inc/wallet/pull/1283), So we are closing this issue.
Thanks..!!
