### ISSUE TITLE
Proper permission popup should display when the user taps on “Choose from gallery” & “Take photo” options if the user Deny camera permission while uploading profile picture on Create Account page.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#589]
**Frequency:** 100%
**Repro on build version:**  Android Internal Build V1.10.1(1004294336), Test Flight Build V1.10.1(46)
**Repro on devices:** iPhone XR(14.2), Samsung Galaxy A5(7.0), iPhone SE 2(14.2)
 **Pre-condition:** Users should tap on "Don’t ask again" on Camera permission popup.
  **Repro Steps:**
1. Launch the application & go to Create Account screen.
2. Tap on Add photo icon.
3. Select “Choose from Gallery” option.
4. Now camera permission popup should be displayed.
5. Now click on the Deny button & again perform the same step.
6. Now users are able to see the “Don’t ask again” option in permission popup.
7. Now select that option & tap on the Deny button.
8. Now again tap on Add photo icon & select “Choose from Gallery” option.
9. Observed that,
**Current Behavior:**  Nothing happens when the user selects the option.
**Expected Behavior:**  Proper message with Setting & Cancel button should display to enable camera permission from phone  settings.
**Investigation:** Also we have observed the same issue when users select the “ Take Photo” option.
**Impact:** Users are not able to upload profile photos.
**Attachment:**  [CameraPermissionMessageNotDsiplaying.mp4](https://drive.google.com/file/d/1qPDEwRe5YkEOLkvkdlnRxq1wR51rWCD-/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D83](https://valora.testquality.com/project/12128/result/2450745/defect/8022).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D83](https://valora.testquality.com/project/12128/result/2455396/defect/8023).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D94](https://valora.testquality.com/project/12128/result/2455396/defect/8088).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D96](https://valora.testquality.com/project/12128/result/2457598/defect/8110).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D101](https://valora.testquality.com/project/12128/result/2470904/defect/8166).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D103](https://valora.testquality.com/project/12128/result/2470887/defect/8179).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D125](https://valora.testquality.com/project/12128/result/2471192/defect/8204).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D125](https://valora.testquality.com/project/12128/result/2471192/defect/8205).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D126](https://valora.testquality.com/project/12128/result/2471203/defect/8209).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D126](https://valora.testquality.com/project/12128/result/2471205/defect/8210).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D139](https://valora.testquality.com/project/12128/result/2485248/defect/8252).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D255](https://valora.testquality.com/project/12128/result/2524682/defect/8440).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D294](https://valora.testquality.com/project/12128/result/2525000/defect/8506).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D436](https://valora.testquality.com/project/12128/result/2545886/defect/8738).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D454](https://valora.testquality.com/project/12128/result/2545650/defect/8763).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D459](https://valora.testquality.com/project/12128/result/2545670/defect/8775).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D642](https://valora.testquality.com/project/12128/result/2573681/defect/9255).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D732](https://valora.testquality.com/project/12128/result/2590420/defect/9395).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9621).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9622).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9623).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9624).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9625).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D864](https://valora.testquality.com/project/12128/result/2616360/defect/9626).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D865](https://valora.testquality.com/project/12128/result/2616360/defect/9629).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D865](https://valora.testquality.com/project/12128/result/2616364/defect/9630).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D866](https://valora.testquality.com/project/12128/result/2613875/defect/9641).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D868](https://valora.testquality.com/project/12128/result/2613651/defect/9664).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D868](https://valora.testquality.com/project/12128/result/2613651/defect/9665).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D868](https://valora.testquality.com/project/12128/result/2613654/defect/9666).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D871](https://valora.testquality.com/project/12128/result/2613665/defect/9670).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D873](https://valora.testquality.com/project/12128/result/2613668/defect/9673).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D890](https://valora.testquality.com/project/12128/result/2616227/defect/9695).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D890](https://valora.testquality.com/project/12128/result/2616227/defect/9696).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D896](https://valora.testquality.com/project/12128/result/2615542/defect/9704).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D899](https://valora.testquality.com/project/12128/result/2612825/defect/9711).
