### ISSUE TITLE
[Device Specific] “Require PIN on APP Open” or  “Enable Data Saver” toggle gets cut when user changes language to “Espanol(America Latina)" or "Portugues(Brasil)”

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#598]
**Frequency:** 100%
**Repro on build version:** Play Store Build V1.7.2 , Android Internal Build V1.8.0.(1004294330)
**Repro on devices:** Samsung Galaxy A5(7.0)
**Does not repro devices** Google Pixel (10)
**Testing Account:**  517-236-8556/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B9)
**Pre-condition:** User should login in application by selecting English language.
 **Repro Steps:**
1. Launch the application and login with a test account.
2. Now go to settings from Hamburger Menu & tap on Langauge.
3. Now the user should be on the Select Language page.
4. Now select “Espanol(America Latina)” language 
5. Observed that 
**Current Behavior:**  “Require PIN cuando la app este abierta”(Require PIN on APP Open)toggle gets cut.
**Expected Behavior:**  “Require PIN cuando la app este abierta”(Require PIN on APP Open) toggle should not cut.
**Investigation:** Also it is observed that “Ativar o modo de Economia de Dados” (Enable Data Saver) toggle gets cut when the user selects “Portugues(Brasil)” language.
**Impact:** Bad user experience.
**Attachment:**  [Setting_UI.png](https://drive.google.com/file/d/1rtaJUZ-0rqECcU8hu-91K1HnEigBvTrw/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi I have verified this issue using latest Android Play store build V1.15.2 & observed that issue is still reproduced
**Verified On Devices:** Samsung Galaxy A5(7.0)

**Comment by Celoqa** [comment]
Hey @MuckT I have verified this issue using latest Android internal build V1.16.1  & observed that issue is still reproduced
**Verified On Devices:** Samsung Galaxy A5(7.0)

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using Android internal build V1.19.0 & observed that issue is fixed now. Also we have updated our observations for above ticket in below Gsuite.
**Gsuite sheet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1375251486
**Attachment:** [ForSGA5(7.0)Device](https://drive.google.com/file/d/1cSEQBpgttVdc6NSFRcnviFtKw3-mKsBF/view?usp=sharing)
**Verified On Devices:** Redmi note 8 (10.0) iPhone 12 (14.7.1)  Samsung Galaxy J5 Prime (8.0)  , Samsung Galaxy A5 (7.0)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R84](https://valora.testquality.com/project/12128/testcase/299597/requirement/11855).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**iOS (13.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485053

Verified On Devices: iPhone SE (13.6.1)

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:
Android (9.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485117


**Verified On Devices:** Redmi Note 8 (9.0) ,
