### ISSUE TITLE
Remove @celo/rainbowkit recommendation

### ISSUE THREAD

**Issue by aaronmgdr** [valora-inc/wallet#5983]
Now that Valora is in the official Rainbowkit package. Remove the recommendation to use @celo/rainbowkit-celo from valora docs. 

instead just recommend rainbowkit. 

https://github.com/valora-inc/wallet/blob/c50c7b729829de1a1f419f5506823cbbbce45844/docs/connecting-dapps.md?plain=1#L5

**Comment by aaronmgdr** [comment]
@jeanregisser

**Comment by bakoushin** [comment]
@aaronmgdr any chance the [celo docs example](https://docs.celo.org/developer/rainbowkit-celo) to be updated to rainbowkit? then we can still mention it.

**Comment by aaronmgdr** [comment]
@bakoushin lets see if dev rel accepts https://github.com/celo-org/docs/pull/1462
