### ISSUE TITLE
Valora slowing down over time

### ISSUE THREAD

**Issue by etuleu** [valora-inc/wallet#60]
### Expected Behavior

App should not slow down over time.

### Current Behavior

From Alex:

Anyone seen issues with Valora slowing down over time? Ran into doing this while doing testing with dappKit recently and it was almost unusable (lagging badly, > 5 seconds to register touch events). After re installing everything was OK again.

**Comment by etuleu** [comment]
Possible source of slowdown from Isabelle:

<img width="1680" alt="Screen Shot 2021-03-01 at 7 58 37 AM" src="https://user-images.githubusercontent.com/674143/109523298-0d191d00-7a64-11eb-863f-44e83ca133f3.png">

**Comment by aleksey-nov** [comment]
Related to: https://github.com/celo-org/celo-monorepo/issues/6284

**Comment by aleksey-nov** [comment]
Related to: https://app.zenhub.com/workspaces/wallet-backlog-board-60092d006a84e3001d0d5936/issues/celo-org/wallet/38

**Comment by aleksey-nov** [comment]
Related to: https://github.com/celo-org/wallet/issues/38
