### ISSUE TITLE
“Confirm” & Dismiss” buttons gets truncated on in App notification if user increase the font size from device settings 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#601]
**Frequency:** 100%
**Repro on build version:** V1.7.2(1004294329)
**Repro on devices:** iPhone 6+ (12.4.5)
**Testing Account:  / Backup Key:**  (680) 256-0169
Frequent mom supreme illness plastic fog floor review lion cruise hurt movie game dentist zero iron crime drill scout face abandon mother beyond marble 

**Pre-condition:** Font size should be large 

**Repro Steps:**

- Launch the application and login with a test account.
- Increase the font size
- Observe confirm & dismiss buttons on in app notification

**Current Behavior:** “Confirm” & Dismiss” buttons gets truncated on in App notification .
**Expected Behavior:**  “Confirm” & Dismiss” buttons should fit to screen.
**Impact:** Bad user experience/ UI.
**Investigation:** Below are the few issues which are truncated by increasing font size.

1. Add & with draw get truncated on menu bar 
2. Learn Account key text gets truncated with text on account key page 

**Attachment:** 
[Add&Withdraw.jpeg](https://drive.google.com/file/d/1knHyFePqlTXh_-c9dwXko1e8ElYeFPKy/view?usp=sharing)
[Confirm&Dismiss.jpeg](https://drive.google.com/file/d/1-ndTewhHsIP8RPCQ--JwjBkTi1pECjuM/view?usp=sharing )
[LearnAccountKey.jpeg](https://drive.google.com/file/d/14QaM5-ULi0xdG3gK7x57FBSXN2vistU8/view?usp=sharing )

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R73](https://valora.testquality.com/project/12128/testcase/295329/requirement/11617).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.17.0 & Test flight build V1.17.0 and updated the status in test quality tool.

**Test quality tool link:**

- **Android:**
     - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450229
     
- **iOS:**
    - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450220

**Query:** 

- We have observed this UI change fall largest font in [iOS](https://drive.google.com/file/d/1fobLskpK7Mh9SB1wrydQd28G7_aNLEB9/view?usp=sharing) & [Android](https://drive.google.com/file/d/15w9RoF4h3MywGnlG56Bhe_7tbTz-tTi9/view?usp=sharing) also. 
- Also we have observed [In app CTA UI change](https://drive.google.com/file/d/1iG3sDHbUzC1HotyyD_Ggmd7eIOnjJedx/view?usp=sharing). Hence we are reopening this issue

**Verified On Devices:** iPhone SE (14.2), Samsung Galaxy S4 (4.4.2), iPhone 6+(12.5.4)

CC: @gnardini

**Comment by MuckT** [comment]
@Celoqa This layout of the CTA is expected with large font sizes. This will be refined in #913, but as we cannot maintain the same layout with larger text sizes on CTA's **the expected behavior** is that all text is displayed and CTA's cards remain a constant size across all CTA cards present.

For the settings menu options text being truncated with ellipsis I will check with the design team to get acceptance criteria.

**Comment by Celoqa** [comment]
Thank you @MuckT for update. Sure, we will now only concentrate on Hamburger Menu contents truncate with ellipsis once we will get acceptance criteria:-)

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Android internal build & Test Flight build V1.20.2 & observed that issue is fixed now.
**Verified On Devices:** Redmi Note 8 (9.0) , iPhone 6+ (12.4.5)
