### ISSUE TITLE
QR code texture changes on the “ My code “ screen when a user enters too long name in the Name field from the Edit Profile page

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#612]
**Frequency:** 100%
**Repro on build version:** Android internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27)
**Repro on devices:** Samsung Galaxy Note 5(7.0) , IPone SE2 (13.5)
Testing Account: (680)9898865  / Back up Key:
https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0
**Repro Steps:**
1. Launch the application and login with valid credentials.
2. Go to the QR code section on the ‘My code’ screen & observe the texture of QR code.
3. Now go to the Setting option from the Hamburger Menu.
4. Go to the Edit profile section & enter too long profile name in the Name field with spaces between words.
5. Now again go to the QR code section on the ‘My code’ screen.
6. Observed that QR code texture changes as compared to previous one.
**Current Behaviour:** QR code texture changes as user enter too long Profile name
**Expected Behaviour:** QR code texture should not be changed if user enter too long name
**Attachment:** [QRCodeTextureChange.png](https://drive.google.com/file/d/1ZnSgcAfh1KF1fhus9LeSrrCOiZWghUJ7/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @nityas, We have verified this issue using latest released Android Playstore Build V1.15.2 & Appstore Build V1.15.2 and observed that issue is still reproduced.
**Repro on devices:** Redmi Note 8 (10.0), iPhone SE 1st Generation (14.6)
