### ISSUE TITLE
‘Adjust Date’ screen is displayed for a while when the user launches the application after changing the date from the phone setting.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#615]
**Frequency:** 80%
**Repro App version:** Test Flight build v1.2.0 (26) 
**Repro on devices:** iPhone 11 (14.0)
**Does not repro on devices:** Samsung Galaxy A50s(10.0) , Samsung Galaxy A3(5.0.2) , iPhone Xs max (13.0)
**Repro Steps:** 
1. Change date from setting.
2. Launch the application.
3. Refresh the application.
4. Observed that Adjust date screen is displaying for a short period.

**Current Behavior:** ‘Adjust Date’ screen is displayed for a while.

**Expected Behavior:** Screen should be displayed until the user taps on the ‘Adjust Date’ button.

**Impact:** User is not able to understand whether the date is correct or not.

**Attachment:** [AdjustDateNotDisplaying.mp4](https://drive.google.com/file/d/1LD_2Vf6XqDsFfJm7iBe1OqRKmavXstOO/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser, we have verified this issue using latest Test flight Release build v1.29.2 and observed following.
**Observation**:
- User is not able to see Adjust Date screen.

**Devices**: iPhone 13 mini(15.1.1), iPhone 6+(12.5.5)
**Attachment**: [AdjustDatenotseen.mp4](https://drive.google.com/file/d/1GYl2xHaYwIOrrGPENzfyWGSod-x54H_l/view?usp=sharing)
Thanks!!
