### ISSUE TITLE
Application does not get restarted automatically when the user taps on the ‘Restart to Switch’ button from ‘Enable Data Saver’ toggle.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#618]
**Frequency:** 100%
**Repro App version:**  Android internal build 1.2.0(1004294313) 
**Repro on device:** Samsung Galaxy M31(10), Google pixel 3a(11)
**Does not repro on devices** Google pixel 3XL(9)
**Test Account:** Backup Key: +1(650)2356686
**Repro Steps:**

1. Launch the Application 
2. Sign in with test account
3. Tap on Hamburger Menu and go to Settings option
4. Tap on ‘Enable Data Saver’ toggle to switch on it.
5. Again tap on  ‘Enable Data Saver’ toggle to switch off it.
6. User will redirect to the popup window ‘Restart To Switch Off Data Saver’.
7. Tap on the ‘Restart to Switch’ option.
8. Observe that application does not get started automatically.

**Current Behavior:** Application does not restart automatically when the user taps on the ‘Restart to Switch’ option  from ‘Enable Data Saver’ toggle.

**Expected Behavior:** Application should be restarted automatically when the user taps on the ‘Restart to Switch’ option  from ‘Enable Data Saver’ toggle.

**Impact:**  User has to restart the application by manually.

**Attachment:** [AppNotRestartingAutomatically.mp4](https://drive.google.com/file/d/1aLEhSAvO02XTdHvw6htYS9B7i61wWApE/view?usp=sharing) [issue observed at 0.10 sec]

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D455](https://valora.testquality.com/project/12128/result/2545816/defect/8765).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D896](https://valora.testquality.com/project/12128/result/2615537/defect/9703).

**Comment by ValoraQA** [comment]
Hey @MuckT since data saver toggle has been removed as per the in the mentioned below PR we are closing this issue

PR link : [link](https://github.com/valora-inc/wallet/pull/1839)

Thanks..!!
CC : @silasbw
