### ISSUE TITLE
Onboarding Registration screen is not fitting to the screen when froms are in focus

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#623]
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** Samsung Galaxy A5(7.0),  Samsung galaxy S4(4.0)
**Does not repro:** iPhone 7+ (13.3.1)

**Repro Steps:**
1. Launch the Application 
2. Complete the walk through screen. 
3. Tap on create a new account. 
4. Enter Full name. 
5. Tap on Phone number field
6. Observe. 

**Current Behavior:** Account info page is not fit to the screen
**Expected Behavior:**  Page should correct after opening the keypad.  
**Investigation:** issue also repro when user taps on i have an account and navigate to Account info screen. 
**Impact:** UI issue, Account Info screen is not properly. 
**Attachment:** [UI_AccountInfo.mp4 ](https://drive.google.com/file/d/17NxK-1Y0O4VEmUk01fEpoHmEOYO-EGZg/view)(Bug observe at 07 sec)

**Comment by MuckT** [comment]
@ValoraQA can you take a look at this issue and see if it is still reproducing. I believe this has been fixed, but please update this ticket with your findings.
