### ISSUE TITLE
Android: [4 os specific] App get crash when user tapping on search bar from “Send” page 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#627]
**Frequency:** 100%
**Repro App version:**  V1.0.0(10)
**Repro on device:** Samsung galaxy S4(4.4.2)
**Does not Repro:** Samsung Galaxy Grand Prime(5.1.1), Google Pixel XL (8.1) ,Samsung Galaxy A5(7.0)
**Repro Steps:**
1. Launch the Application and signup with test account
2. Tap on the Send button from the home screen. 
3. Tap on the Search bar to search a contact user. 
4. Observe app crashes. 

**Current Behavior:** The app crashes by tapping on the Search bar. 
**Expected Behavior:** Users should be able to search contact users. 
**Impact:** Users are blocked to search contact users.  

**Attachment:** 
1. [AppCrash_SearcBarIssue.MOV](https://drive.google.com/file/d/1GMQ4uldAXKaVZ0fU9BUkUMytZYuWCLI4/view?usp=sharing)
2. [celo_logs (2).txt](https://github.com/celo-org/celo-monorepo/files/5075118/celo_logs.2.txt)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D77](https://valora.testquality.com/project/12128/result/2450354/defect/8002).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D77](https://valora.testquality.com/project/12128/result/2450354/defect/8003).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D77](https://valora.testquality.com/project/12128/result/2450354/defect/8004).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D77](https://valora.testquality.com/project/12128/result/2450354/defect/8005).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D78](https://valora.testquality.com/project/12128/result/2450354/defect/8007).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D78](https://valora.testquality.com/project/12128/result/2450356/defect/8008).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D78](https://valora.testquality.com/project/12128/result/2450287/defect/8009).
