### ISSUE TITLE
Need loading state for contact importing on Send screen to avoid “No Contacts Found” being shown while import is in progress

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#629]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Tested Account:** 503 447 5958 / Backup Key

Pre-condition: Application is launch after cold launch the app. 

**Repro Steps:** 
1) Launch app and login with tested account 
2) Tap on Hamburger menu. 
3) Tap on Invite option. 
4) Observe.  

**Current Behavior:**  “No contact found” screen is shown for while 
**Expected Behavior:** “Fecting contact” should be display if contact are syncing in device

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=6490%3A97)
<img width="379" alt="Screen Shot 2020-06-26 at 11 23 52 AM" src="https://user-images.githubusercontent.com/51388535/85889052-9672a400-b79f-11ea-81f3-1e94d83606ef.png">

**Attachment:** [ContactIssue .mp4 ](https://drive.google.com/file/d/1AxwbmTv-9Val9P3jLc7Cuwa7YKjU4y8i/view?usp=sharing)(Bug observed at 25 sec)

**Comment by Celoqa** [comment]
Hi @tarikbellamine We have verified this issue on latest android internal build V1.15.2 & Testflight build V1.15.2 (65) and observed issue is still repro.
 “No Contact” text is shown for while on “Contact Screen” when user open contact screen after cold the launch the app.
Verified On: Iphone 6+ (12.4.5), Vivo V11 pro (10)
