### ISSUE TITLE
Account Key box is empty after going through the Backup Quiz.

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#634]
### Expected Behavior

User can see their Account Key after going through the backup quiz.

### Current Behavior

If the user takes too long to go through the quiz, once they finish it and they're redirected to the `BackupIntroduction` they see an empty box instead of the Account Key.

**Comment by ValoraQA** [comment]
Hey @gnardini We have verified this issue using Android internal build and iOS test flight build V:1.22.2  & observed that issue is still reproduced
**Verified On Devices:** Redmi Note 8(9.0), iPhone 6+ (12.5.4)
Thanks..!!
