### ISSUE TITLE
Auto-focus to phone number after selecting country code

### ISSUE THREAD

**Issue by dominiquejane** [valora-inc/wallet#713]
### Expected Behavior
During onboarding, the app should auto-focus to the phone number textbox after selecting the country code.

Related work: celo-org/celo-monorepo#6220  Auto-focus when confirming recipient's account in the Send flow.

### Current Behavior
User needs to tap the phone number textbox in order to input anything.

**Comment by MuckT** [comment]
This issue is no longer reproducible - closing.

https://user-images.githubusercontent.com/26950305/193935807-9115ae3f-f97d-4d22-91b8-dc4ff7a3b5be.mov
