### ISSUE TITLE
Daily Limit error should also display remaining balance in cUSD and CELO.

### ISSUE THREAD

**Issue by dominiquejane** [valora-inc/wallet#747]
### Expected Behavior

Daily Limit error should also display remaining balance in cUSD and CELO.

### Current Behavior

Only cUSD is shown.

[Slack thread.](https://celo-org.slack.com/archives/CL7BVQPHB/p1613365584330700)

**Comment by MuckT** [comment]
Closing as the daily limit has been removed https://github.com/valora-inc/wallet/pull/2830.
