### ISSUE TITLE
User should stay on the same page when the user taps on the “I understand” button from “Contact to support” popup

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#79]
**Frequency:** 100%
**Repro on Devices:** Samsung Galaxy A5(7.0),  iPhone XR (14.4), iPhone 6s (14.2), Samsung Galaxy J7 pro (8.0)
**Repro version :** Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47)
**Login credential :** (484) 299-7470/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)  
**Repro Steps:**
1. Launch the application & login with a test account.
2. Now tap on Hamburger Menu & tap on “Add & Withdraw” option.
3. Now go to the “Add Funds” section & select “Celo dollar(cUSD)” from Select digital Currency field & “Debit card or bank account” from Pay with field.
4. Now enter too large an amount in the amount field & tap on Next button.
5. Now “You are about to purchase more than the daily send limit of 500 cUSD.” popup should display with the “Contact” & “I understand” button.
6. Now tap on the “I understand” button.
7. Observed that, 
**Actual Result:** User proceed further & able to redirect to Add funds screen with Simplex option.
**Expected Result :**  User should stay on the same page & should not be able to proceed until the user does not enter an amount less than 500 cUSD.
**Attachment:** [UserProceedEvenEnterAmountMoreThan500cUSD.mp4](https://drive.google.com/file/d/1-qSdHMGAROWcE8wpEDwdbnH4ZCQ2XS7r/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi I have verified this issue using Android Play store build V1.15.2 & App store build V1.15.2 & observed that issue is still reproduced.
**Observations:** Also it is observed that user is able to see popup when user enter exact boundary value in amount field (i.e. 5000)
**Verified On Devices:**  iPhone SE (14.2), Redmi Note 8 (9.0)
**Attachment:** [UserShouldStayOnSamePage.mp4](https://drive.google.com/file/d/1J8S4RCzUR0P3sER1-t8eIu6BwVNxwpis/view?usp=sharing)

**Comment by ValoraQA** [comment]
hi @MuckT we have verified the above issue on latest android internal release build V:1.29.2 and iOS testflight release build V:1.29.2 and observed the issue is not replicable

Observation : The pop is changed and after clicking on Ok user stays on the amount page 

Attachment : [popup.mp4](https://drive.google.com/file/d/1ouukZyfdMRQcpBtsw8RN5h7nX83ToBRa/view?usp=sharing)

Device :  Google Pixel 2XL(11.0) , iPhone 12 (14.7.1)

Thanks..!
