### ISSUE TITLE
Add component tests for pincode handling

### ISSUE THREAD

**Issue by cmcewen** [valora-inc/wallet#797]
### Expected Behavior

e2e tests handle different pincode situations

### Current Behavior

no e2e coverage

**Comment by MuckT** [comment]
Seems like a good candidate for a component test.

**Comment by MuckT** [comment]
### E2E Tests for PIN
[Changing Pin](https://github.com/valora-inc/wallet/blob/main/packages/mobile/e2e/src/usecases/PINChange.js)
[Require Pin](https://github.com/valora-inc/wallet/blob/main/packages/mobile/e2e/src/usecases/PINRequire.js)

### Component Tests for PIN
[Pin Code Enter](https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/pincode/PincodeEnter.test.tsx)
[Pin Code Set](https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/pincode/PincodeSet.test.tsx)
[Pin Code Lock](https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/pincode/PincodeLock.test.tsx)
