### ISSUE TITLE
Add Zendesk chat for user support via webview

### ISSUE THREAD

**Issue by hdenisse** [valora-inc/wallet#82]
### Expected Behavior

Users will be able to chat live with support directly from valoraapp.com via a Zendesk chat widget. Via a webview from Valora, users should be able to access this from the app.

### Current Behavior
User has to send an email from Valora to contact support (difficult for some users don't have an email client on their phones) or they have to chat with support via FB Messenger

Web services team has prioritized adding the Zendesk chat by March 11 
https://www.notion.so/clabsco/Adding-Zendesk-live-chat-for-support-with-JS-widget-on-valoraapp-com-fef3809db5044bd58e32dbb9a9812776

**Comment by coreycelo** [comment]
Will this be in addition to the email option or replace email?

**Comment by MuckT** [comment]
@hdenisse is this still a valid issue for adding the widget in Valora?
