### ISSUE TITLE
User not able to see detailed exact amount after decimal point for USD currency in red error message on Send amount screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#848]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.0 , Test Flight Build V1.16.0(66)
**Repro on devices:** iPhone SE (14.2), Redmi Note 8 (9.0), iPhone 6+(12.4.5), Vivo V11 pro (10)
**Testing Account:** (680) 333-1978/ [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
**Pre-condition:**  Make sure that the user should have some balance in their account. Also user should select USD currency from Settings
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Go to Send contact screen & select contact 
3. Now enter amount more than available  balance 
4. Observed that,
**Actual Result:** Amount displayed in the red error banner is upto two decimal places after decimal point. 
**Expected Result:** User should able to see more than 6 digits after decimal point for USD currency
**Investigation:** It is observed that, for other currency like PHP, EUR, KSh user is able to see more than 6 digits after decimal point
**Attachment:** [DetailsAmountNotShownForUSDcurrency.mp4](https://drive.google.com/file/d/1MHf4IhpLCYuqtqNAOB7MWQuQX334DR02/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D55](https://valora.testquality.com/project/12128/result/2432215/defect/7932).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D57](https://valora.testquality.com/project/12128/result/2432224/defect/7935).
