### ISSUE TITLE
User not receive "Your issue has been successfully reported! Expect an email response soon!" message after submitting logs by shaking device.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#849]
**Frequency:** 100%
**Repro on build version:** Playstore build 1.15.2 , Android internal build V1.16.0
**Does not repro on build:** Appstore build V1.15.2 & Testflight build V1.16.0(66)
**Repro on devices:** Redmi note 8 (10.0), Vivo v11 pro (10)
 **Does not repro on Devices:** iPhone SE 1st Generation, iPhone 6+(12.4.5),

**Pre-condition:**
- Make sure user should submit the logs through shake device feature 

 **Repro Steps:**
1. Launch the application & login with test account.
2. Shake the device 
3. Tap on Contact support button 
4. enter message & tap on submit button 
5. Tap on send button in mail page 
6. Observe Confirm message is not shown 

**Current Behavior:**  User not receive "Your issue has been successfully reported! Expect an email response soon!" message after submitting logs by shaking device.
**Expected Behavior:** User should able to see "Your issue has been successfully reported! Expect an email response soon!" message after submitting logs by shaking device.
**Observation:** 
- Issue observed when user go through Help>Contact 
- User not redirected to Home page after submitting the logs 
- Issue does not repro on iOS
**Impact:** Bad User experience & user think that he not submitted logs.
**Attachment:**  [Android_ConfirmMessage.mp4](https://drive.google.com/file/d/1NSbCsNDEUFTHIzlOf9hjVDVlajQ5yodE/view?usp=sharing)
[iOS_ConfirmMessage.PNG](https://drive.google.com/file/d/1pJwwofdH30MuCmeJ7WwQX4-lKQyIVn59/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D56](https://valora.testquality.com/project/12128/result/2432159/defect/7933).
