### ISSUE TITLE
User is not redirected to the external browser when the user taps on the “Open” button  of “Enjoying Valora?” In-app CTA from Home screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#859]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.1
**Does not repro version**  Test Flight build V1.16.1(67) 
**Repro on devices:** Redmi Note 8 (9.0),Redmi Note 8 (10.0), Vivo V11 pro (10)
**Does not repro devices** iPhone 6+(12.4.5), iPhone SE 1st Generation (14.6), iPhone SE (14.2)
**Testing Account:**   (484) 299-7470/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)  
  **Repro Steps:**
1. Launch the application & login with the test account.
2. Go to home screen & start swiping In-app CTA’s from RHS to LHS
3. Make sure that the user should see “Enjoying Valora? Help us by clicking here to rate the app in App Store / Google Pay” In-app CTA with “Open” & “Dismiss” button.
4. Tap on "Open" button & observed that, 
**Current Behavior:**  User is redirected to the “valoraapp.co” page in-app web view.
**Expected Behavior:**  User should redirect to external browser to rate an application according to PR 473
**Investigation:** Also it is observed that user is not able to rate the application in Android
**Attachment:**  [RateIn-appCTANotOpeningInExternalBrowser.mp4](https://drive.google.com/file/d/1b1trN1EgdNQKyGn-wMdc2DzC1B4VHe98/view?usp=sharing)

**Comment by MuckT** [comment]
@Pedro-vk I believe this was included in the v1.16.1 release, would you be able to take a look?

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using  Android Internal Build V1.22.4 & Observed that the issue is fixed. On tapping "Open" button from the "Enjoying Valora? " CTA, user is redirected to Valora app page on playstore. Hence we are closing the issue.

**Devices:** Redmi Note 8(11.0), Samsung Galaxy J5 prime (8.0)
**Attachment:** [CTA issue fixed.mp4](https://drive.google.com/file/d/10BkqCV6385qPZml7n7LhfvPn7Ef8e_91/view?usp=sharing)
