### ISSUE TITLE
Error banner for insufficient funds should correctly reflect the chosen asset.

### ISSUE THREAD

**Issue by dominiquejane** [valora-inc/wallet#864]
The value in the banner should show either cUSD or cEUR, not $.

![IMG_1287.PNG](https://images.zenhubusercontent.com/5f90946ef9d04239a5f05896/69d31689-0be5-4d02-ba88-3192e4871f4e)
![IMG_1286.PNG](https://images.zenhubusercontent.com/5f90946ef9d04239a5f05896/4e2351fc-5a78-4ae2-9511-a6caba401dba)

**Comment by MuckT** [comment]
@dominiquejane, I believe right now we display values in the users selected currency regardless of the coin. If the selected currency was EUR it would display with `€`

**Comment by dominiquejane** [comment]
@MuckT Hmmm...I think you're right. Then we should at least be more clear about the requirements in the error banner.  Perhaps something like "you should have $1001 worth of cEUR" or "you should have $1001 in cEUR", or "your cEUR balance needs to be at least $1001".
Dealing with multiple currencies at the same time is a super confusing mechanism in the app, so I think we should be explicit wherever possible.
