### ISSUE TITLE
User is not able to perform Wallet Connect action succesfully from “use-contractkit.vercel.app” page

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#871]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.1 , Test Flight Build V1.16.1(67)
**Repro on devices:** iPhone SE (14.2), Redmi Note 8 (9.0), iPhone 6+(12.4.5), Vivo V11 pro (10)
**Testing Account:**   (484) 299-7470/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)   
 
**Pre-condition:** Make sure that user should have installed valora application
  **Repro Steps:**
1. Launch the application & login with the test account
2. Now open external browser & launch the “use-contractkit.vercel.app” URL 
3. Scroll down & go to “try it out” section
4. Select appropriate Network from dropdown & tap on”Connect” button
5. Select “Wallet Connect” from option
6. For iOS: User is able to see “Connect withWalletConnect” button
7. Tap  on that button & observed that,

**Current Behavior:**  Nothing happens when the user taps on the “Connect withWalletConnect” button.
**Expected Behavior:**  User should proceed & QR code should be displayed to scan & connect wallet
**Impact:** User gets blocked to connect wallet
**Investigation:** Also in android we have observed that blank screen displayed when user selects “Wallet Connect” from option
**Attachment:**  [iOS_NothingHappensWhenUserTryTOConnectWallet.wmv](https://drive.google.com/file/d/1EpR6oRj814wW46emEw59KSCllrbs3AsW/view?usp=sharing)
[Android_BlankScreenWhenTryToConnectWallet.mp4](https://drive.google.com/file/d/1ysLGI0NjlJwr0FiH6qliino3LwbkVUXD/view?usp=sharing)

**Comment by MuckT** [comment]
@AlexBHarley can you confirm if the above steps with the Connect withWalletConnect are expected or if this is a valid defect?

**Comment by AlexBHarley** [comment]
We are testing this heavily right now @MuckT. You should use a mainnet build of Valora.

https://use-contractkit-q4e9pl7ee-alexbharley.vercel.app/ is the branch for testing.

If something is _not_ working please reach out to me on Slack as we need to immediately investigate.
