### ISSUE TITLE
[Device Specific] Phone number confirmation not asked & user redirects to home screen from enter PIN screen while creating new account

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#878]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.1 
**Does not repro version** Test Flight Build V1.16.1(67)
**Repro on devices:** Samsung Galaxy S4 (4.4.2)
**Does not repro devices** Samsung Galaxy S4 (5.0.1), LG K7i (6.0), Samsung Galaxy A5 (7.0),Galaxy J5 Prime (8.0.1), Redmi Note 8 (9.0), Redmi Note 10 (9.0)
  **Repro Steps:**
1. Launch the application & Complete Onboarding flow
2. Now user should be on “Enter PIN” screen
3. Set valid PIN & observed that,
**Current Behavior:**  User directly redirect to Home screen without asking verification flow after setting PIN
**Expected Behavior:**  Verification flow should be asked & user should be able to complete verification flow
**Investigation:** 
    1. Also we have observed user redirects to "Phone Number Currently not available in your country" screen displayed when user taps  on "Restore" button
    2. Also users are not able to see the confirm phone number option in Settings & In-app CTA as well.
**Impact:** User get blocked to confirm phone number 
**Attachment:**  [PhoneNumberConfirmatioNotAsking.mp4](https://drive.google.com/file/d/15VgL4bhmNn6VXA7vtMTyC01D44wsJo-G/view?usp=sharing)
    3. Also we have observed same issue while earning Rewards.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D75](https://valora.testquality.com/project/12128/result/2450312/defect/8000).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D76](https://valora.testquality.com/project/12128/result/2450331/defect/8001).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D85](https://valora.testquality.com/project/12128/result/2450770/defect/8027).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D86](https://valora.testquality.com/project/12128/result/2450771/defect/8028).
