### ISSUE TITLE
“Having trouble?” popup does not open on shaking the phone while “Invite a friend” popup is open.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#881]
**Frequency:** 100%
**Repro on build version:** Test Flight Build V1.16.2(68)
**Repro on devices:** iPhone SE 1st Generation (14.6),  iPhone 6+ (12.4.5)
**Does not repro version** Android Internal Build V1.16.0
**Does not repro devices** Redmi Note 8 (10.0), Google Pixel 4a (11.0)
**Pre-condition:** Make sure user has installed and login into the application
**Repro Steps:**
Launch the application 
Open the Hamburger menu.
Tap on “Invite” option in hamburger menu.
Shake the phone when “Invite a friend” popup is open & Observe the bug
**Current Behavior:**  “Having trouble?” popup does not open on shaking the phone.
**Expected Behavior:**  “Having trouble?” popup must open on shaking the phone while “Invite a friend” popup is open

**Impact:** Bad user experience as user is blocked to open contact screen.
**Investigation:** The above issue is not reproducible in Android platform.
**Attachment:** 
 [iOS Having Trouble Popup issue.mp4](https://drive.google.com/file/d/1peq6zSg91q22YwafFRVzeflHZc61EFCb/view?usp=sharing)

[Android Behaviour.mp4](https://drive.google.com/file/d/1vi9pU8p1yD4hJNnz_pBYZKefOHDT6dcg/view?usp=sharing)

**Comment by MuckT** [comment]
Based on the feedback from the [bugapalooza](https://docs.google.com/document/d/1_E3fc2Gxyvefhe419_8WEUNnh8Xx2giMHyBYofokzVE/edit#) appears to reproduce with with the shake to support feature when any pop-up is modal is currently on the screen. @isabellewei can you take a look?

**Comment by ValoraQA** [comment]
Hey @MuckT, This feature has been removed as per [PR](https://github.com/valora-inc/wallet/pull/1045) link, So we are closing this issue.
Thanks..!!
