### ISSUE TITLE
"Permita que seus contatos encontrem você” (Allow contacts to find you) toggle text get cut when user verified phone number in Portuguese language on “Confirm” screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#906]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.2
**Does not Repro on build version:** Test Flight Build V1.16.2(68)
**Repro on devices:** Vivo V11 pro (10), Redmi Note 8 (9.0), Redmi Note 8 (10.0), 
**Does not repro devices** iPhone SE (14.2), iPhone 6+(12.4.5), iPhone SE 1st Generation (14.6), 
**Pre-condition:** Make sure the user has changed the app language to “Português (Brasil)” while onboarding.
**Repro Steps:**
1. Launch the application & change the app language to “Português (Brasil)” 
2. Complete Onboarding & verification process
3. Now user should on “Number de telefono”(Phone Number) page
4. Observe text behind toggle
**Current Behavior:**  "Permita que seus contatos encontrem você" toggle text gets cut 
**Expected Behavior:** "Permita que seus contatos encontrem você"  should be display without any cut in text
**Impact:** Bad user experience
**Investigation:** Also it is observed that, for Espanol (America Latina) the “Permite que los contactos te encuentren” toggle text gets cut for iOS
**Attachment:** [Android_Portugues](https://drive.google.com/file/d/1z12rTQEpn7zf3xXk5K6bHVExlblzlK1h/view?usp=sharing)
  [Android_Espanol](https://drive.google.com/file/d/1MG8i-1uDvDn8qUblPu6k3TVF3TlVSPUV/view?usp=sharing)
[iOS_Portugues](https://drive.google.com/file/d/14Wmdkfzzfog6hPcPorKUGbiW1mjtbZIV/view?usp=sharing)
[iOS_Espanol](https://drive.google.com/file/d/1vJ08Z1l-tmGshs1sygNSWjIkTIkXEPjM/view?usp=sharing)

**Comment by MuckT** [comment]
Closing as this screen is no longer served.

**Comment by ValoraQA** [comment]
Hey @MuckT, thank you very much for the information.
Thanks..!!
