### ISSUE TITLE
“Withdrawal from escrow failed”  error message displayed when user restore account with same phone number & account key on “Connect Contacts” screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#907]
**Frequency:** 100% 
**Repro on build version:** Android internal build V1.16.2,  Test Flight Build V1.16.2(68)
App Store Build V1.16.2
**Does not repro build version:** Play store build V1.15.2
**Repro On Devices:** iPhone SE (14.2), iPhone 6+(12.4.5), Vivo V11 pro (10), Redmi Note 8 (9.0), Redmi Note 8 (10.0), iPhone SE 1st Generation (14.6)
**Testing account:** (515) 808 5659  / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B73)
**Pre-condition:** Make sure that user should have verified account key with same phone  number (which was verified earlier)
**Repro Steps:**
1. Launch the application & complete onboarding education flow
2. Tap on “Restore My Account” button
3. Paste verified account key & enter same number 
4. Now user should on Confirming screen with timer
5. Wait for some time & user redirects to “Connect Contacts” screen
6. Again wait for some time & observed that, 
**Current Behavior:**  “Withdrawal from escrow failed” red error banner displayed after successfully restoring account.
**Expected Behavior:**  User should able to restore account without any error banner
**Impact:** Bad user experience
**Attachment:** [WithdrawFromEscrowFailedErrorMessage.mp4](https://drive.google.com/file/d/1U3afvGSjvHxGJgGYMCgXaEbVr6FzwUFC/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D69](https://valora.testquality.com/project/12128/result/2440988/defect/7966).

**Comment by Celoqa** [comment]
Hi @MuckT we have verified this issue on latest build Android internal build V1.17.0 & Testflight build V1.17.0(71) and observed issue is still repro.
**Devices:**   iPhone SE (14.2), iPhone 6+(12.4.5), Vivo V11 pro (10), Redmi Note 8 (9.0), Redmi Note 8 (10.0), iPhone SE 1st Generation (14.6)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D80](https://valora.testquality.com/project/12128/result/2450338/defect/8015).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D81](https://valora.testquality.com/project/12128/result/2450332/defect/8016).

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.18.0 and updated the status in test quality tool.

Test quality tool link:

Android (11):
https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469327

Verified on Devices: Google Pixel 4a (11.0)

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest Android Internal build V1.18.0 and updated the status in test quality tool.

Test quality tool link:

Android (10):

https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469316

**Verified on Devices:** Redmi Note 8 (10.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest Android Internal build V1.18.0 and Testflight build V1.18.0 updated the status in test quality tool.

Test quality tool link:

Android (10):

https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469316
iPhone 6+(12.5.4):

https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469283
Verified on Devices: Redmi Note 8 (10.0), iPhone 6+(12.5.4)
Thanks..!!

**Comment by ValoraQA** [comment]
Hi I have verified this issue on Latest Testflight build V1.18.0 updated the status in test quality tool.
**Test quality tool link:**
- https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469272

**Verified On Device:** iPhone SE (13.6.1)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.29.0 & Test Flight Release Build V 1.29.0 & observed that the issue is still repro. “Withdrawal from escrow failed” error message is displayed when user restore account with same phone number & account key on “Home” screen as Connect Contact feature has been removed.

**Devices:** Samsung Galaxy A9 pro (8.0), iPhone 13 mini(15.1.1), Google Pixel XL(10.0), iPhone 6+(12.5.5)

**Attachments:** [WithdarwFromEscrowFailed.mp4](https://drive.google.com/file/d/1oO44B3-MouUpqEQMGo6Yoiia6aLwmcf8/view?usp=sharing)

Thanks..!!
