### ISSUE TITLE
“Account Number” displayed instead of “Account address” for feed transactions activity & Add & Withdraw exchange screen

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#921]
**Frequency:** 100%
**Repro on build version:** Test flight build V1.17.0 & Android internal build V1.17.0
**Repro on devices:** iPhone SE (14.2), iPhone 6+(12.4.5), Vivo V11 pro (10), Redmi Note 8 (9.0), iPhone 12 (14.4.1), Google Pixel 4a (11.0), Samsung Galaxy S4 (4.4.2)
**Testing Account:**   (680) 333 1978/ [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
**Pre-condition:** Make sure that user should have some transaction history in account
**Repro Steps:**
1. Launch the application & login with test account 
2. Open any payment sent activity from the “Recent” feed.
3. Tap on “Sent to” dropdown
4. Observed that,
**Current Behavior:**  “Account No.” text field displayed with account address & “Tap to Copy” text.
**Expected Behavior:**  “Account address” text field should be displaye with address & “Tap to Copy” text according to PR 910
**Investigation:** 
     1. Also we have observed that same issue repro for Payment Received activity & Add and Withdraw exchange screen
     2. Also we have observed that “Account address” text only displayed in Hamburger Menu
**Attachment:** [AccountAddressTextNotfieldNotDisplayed](https://drive.google.com/file/d/1CTt57EdnCTS0zhQX4tVDpigQcfjVjCmm/view?usp=sharing)

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D71](https://valora.testquality.com/project/12128/result/2450265/defect/7994).

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D72](https://valora.testquality.com/project/12128/result/2450278/defect/7995).

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in latest android internal release build and latest iOS Test flight release build V:1.29.2 and observed the issue is fixed

**Observation:**: “Account address” text field is displayed with address & “Tap to Copy” text for Transaction activity and Add and Withdraw exchange screen.

**Device:** Samsung Galaxy A9 pro(8.0), iPhone 13 mini(15.1.1)

**Attachment :** [Account Address.mp4](https://drive.google.com/file/d/1qCC3GoowfiJcmmgc7w3XdSQWe2icwr8a/view?usp=sharing)

Thanks..!
