### ISSUE TITLE
[Device Specific] UI of whole application get disturbed & too much overlapping happens when user change font size from Settings

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#923]
**Frequency:** 100%
**Repro on build version:**  Test flight build V1.17.0
**Does not repro build version**  Android internal build V1.17.0
**Repro on devices:** iPhone SE (14.2), iPhone 6+(12.4.5), iPhone 12 (14.4.1)
**Does not repro devices** Vivo V11 pro (10), Redmi Note 8 (9.0),Google Pixel 4a (11.0), Samsung Galaxy S4 (4.4.2) 
**Pre-condition:** Make sure that user should change application font size to largest from Settings
**Repro Steps:**
1. Launch the application 
2. Select Language
3. Observed that, Language name gets truncated on top RHS 
**Current Behavior:**  Language name displayed as truncated at top RHS
**Expected Behavior:**  Language name should be displayed as it is with larger text 
**Impact:** Bad user experience
**Investigation:** 1. Also it is observed that, UI get disturbed while creating , restoring account & Setting PIN
2. Also, UI get disturbed for Home screen & Hamburger Menu , Settings, etc
**Attachment:** [UIDisturbedForLargestFont.wmv](https://drive.google.com/file/d/1AkRaQSDJ6wmZIMd2zG4wlhY9y4szd_AP/view?usp=sharing)

**Comment by Celoqa** [comment]
We have observed same related below issue
- Earn button truncated on hamburger menu when user increases text size [EarnButton.PNG](https://drive.google.com/file/d/1X-m55DjGIRisvPSpV4m1piewjgdvc_U8/view?usp=sharing)

**Comment by ValoraQA** [comment]
We have verified issue on Testflight Build V:1.19.0 and observed that issue is still repro

***Observation***
- We have observed UI disturbance issue throughout the app 
- Also we have observed text truncation is seen after clicking on learn more (CTA's) on timer page

 *Attachment*

Repro on device : iPhone 6+ (12.5.4)

**Comment by ValoraQA** [comment]
Hey @MuckT ,We have verified issue on Testflight Build V:1.19.0 and observed that issue is still repro and hence we are reopening this ticket 

***Observation***:
   - We have observed UI disturbance issue throughout the app
    - Also we have observed text truncation is seen after clicking on learn more (CTA's) on timer page

***Attachment***

***Repro on device***: iPhone 6+ (12.5.4)
***Does not repro on device*** : iPhone 12 (14.7.1)

FYI : We are reducing the priority to P3 because it is replicating only in one device

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R89](https://valora.testquality.com/project/12128/testcase/299699/requirement/11860).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R90](https://valora.testquality.com/project/12128/testcase/299700/requirement/11861).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R91](https://valora.testquality.com/project/12128/testcase/299701/requirement/11862).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R92](https://valora.testquality.com/project/12128/testcase/299702/requirement/11863).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R93](https://valora.testquality.com/project/12128/testcase/299703/requirement/11864).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R94](https://valora.testquality.com/project/12128/testcase/299704/requirement/11865).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R95](https://valora.testquality.com/project/12128/testcase/299705/requirement/11866).

**Comment by ValoraQA** [comment]
Hey @MuckT ,We have verified issue on Testflight Build V:1.19.0 and observed that issue is still repro and hence we are reopening this ticket

Observation:

 We have observed UI disturbance issue throughout the app

 Also we have observed text truncation is seen after clicking on learn more (CTA's) on timer page

Attachments :
[Confirmationscreen_SE.jp](https://drive.google.com/file/d/1NqrySU8rh98ROU7LsSlejWtl0Ea5i6Ky/view?usp=sharing)
Repro on Devices: iPhone SE (13.6.1)

[Createpin_SE.jpeg](https://drive.google.com/file/d/19rSbDsw6k9qJqo4FpUVq9dOrrmC1g0Qo/view?usp=sharing)
Repro on device: iPhone SE (13.6.1)

[hamburgerscreen_SE.jpeg](https://drive.google.com/file/d/1zFN0TP2OO79gNStjddGhsOT7KNSfcjSa/view?usp=sharing)
Repro on Devices: iPhone SE (13.6.1)

[LearmoreCTA_SE.jpeg](https://drive.google.com/file/d/149V9p8175yFAfLyTm4HjQ53DFrL0Vspb/view?usp=sharing)
Repro on Devices: iPhone SE (13.6.1)

[phonenumerscreen_SE.jpeg](https://drive.google.com/file/d/1NNK1sj6jcZ6t3ou2WdblHlvuNIoc1K09/view?usp=sharing)
Repro on Devices: iPhone SE (13.6.1)

**Comment by MuckT** [comment]
@ValoraQA can we breakout the following into their own tickets.

- Confirmation Screen.
- Learn More CTA.
- Phone Number screen.

**Comment by ValoraQA** [comment]
Hey @MuckT  we have created separate tickets for the components as instructed in the above comment

1] **Phone number verification page :** [Link](https://github.com/valora-inc/wallet/issues/1666)
2] **Homepage :** [Link](https://github.com/valora-inc/wallet/issues/1667)
3] **CELO page :** [Link](https://github.com/valora-inc/wallet/issues/1668)

Please let us know if anything required from our end.
Thanks..!

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D897](https://valora.testquality.com/project/12128/result/2612897/defect/9708).
