### ISSUE TITLE
User Automatically redirects to the home page after Resetting the date & time.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#930]
**Frequency:** 100%
**Repro on build version:**  Android internal build V1.17.0
**Does not repro build version** Playstore build V1.16 & Testflight build V1.17.0(71)
**Repro on devices:** Vivo V11 pro (10),  Redmi Note 8 (9.0)
**Does not repro devices** iPhone 6+(12.5.4), iPhone 12 (14.7.1)
**Pre-condition:** Make sure the user should set the wrong date & time before opening the app after fresh install. 
**Repro Steps:**

1. Launch the application 
2. Set wrong time & date 
3. Open the app
4. make sure user should see adjust date page 
5. Click on adjust date button & set the correct time & date 
6. Open the app from background 
7. Observe user redirects to home page 

**Current Behavior:**  User automatically redirects to home page 
**Expected Behavior:**  User should stay on education 
**Impact:** Bad user experience & signed in with different account.
**Attachment:** [AdjustScreen.mp4](https://drive.google.com/file/d/1teRfo8G-fFhbuBwTGiAsC0D-OqAhUPEp/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D77](https://valora.testquality.com/project/12128/result/2450196/defect/8006).
