### ISSUE TITLE
"Select Language" page does not appear on opening the android app & iOS app after fresh install 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#931]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.17.0
**Repro on devices:** Google Pixel 4a (11.0), Samsung Galaxy J5 Prime (8.0) , iPhone 6+(12.5.4), Samsung Galaxy M40(10.0),Google Pixel 2XL (11.0)
**Does not Repro Devices:** iPhone 12 (14.7.1)
**Does not Repro build version:** Test flight build V1.17.0

**Precondition:** Make sure user has freshly installed the application.
**Repro Steps:**
1. Launch the freshly installed application.
2. Observe that.

**Current Behavior:** "Select Language" page does not appear on opening the freshly installed app.
**Expected Behavior:** "Select Language" page must appear on opening the freshly installed app.
**Impact:** Bad user experience.
Attachment: [Select Language Page Issue Android.mp4](https://drive.google.com/file/d/1XqQpmFG-ppUFJaNMK9THUcFBMVrBrff2/view?usp=sharing)
[Select Language Page Appear For iOS.mp4](https://drive.google.com/file/d/1whXcFToE5nKxlTgxohqGa5hlK9m7tFsW/view?usp=sharing)
[language_page_not_seen.mp4](https://drive.google.com/file/d/1XXZngT9s2Amsrt71qDu9GbmS9Hob98gW/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi, We have verified this issue in Latest Android Internal Build V1.17.0 & the issue is repro on Android 7.0 & does not not repro on Android 6.0.
**Repro Device:** Samsung Galaxy A5 (7.0)
**Does Not Repro Device:** LG  K7i (6.0)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D99](https://valora.testquality.com/project/12128/result/2468995/defect/8156).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D128](https://valora.testquality.com/project/12128/result/2479300/defect/8214).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D130](https://valora.testquality.com/project/12128/result/2481953/defect/8221).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D178](https://valora.testquality.com/project/12128/result/2514529/defect/8329).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D185](https://valora.testquality.com/project/12128/result/2515575/defect/8340).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D301](https://valora.testquality.com/project/12128/result/2525031/defect/8521).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D305](https://valora.testquality.com/project/12128/result/2535198/defect/8532).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D498](https://valora.testquality.com/project/12128/result/2552304/defect/8837).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D499](https://valora.testquality.com/project/12128/result/2552306/defect/8838).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D528](https://valora.testquality.com/project/12128/result/2566374/defect/9004).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D579](https://valora.testquality.com/project/12128/result/2571300/defect/9131).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D580](https://valora.testquality.com/project/12128/result/2571302/defect/9132).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D673](https://valora.testquality.com/project/12128/result/2581213/defect/9317).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D674](https://valora.testquality.com/project/12128/result/2581209/defect/9318).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D695](https://valora.testquality.com/project/12128/result/2586688/defect/9354).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D711](https://valora.testquality.com/project/12128/result/2586686/defect/9372).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D775](https://valora.testquality.com/project/12128/result/2586694/defect/9441).

**Comment by MuckT** [comment]
Not a bug, if we can detect the device langauge.
