### ISSUE TITLE
“Connecting……” text is shown continuously for longer time when user purchased celo.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#935]
**Frequency:** 100%
**Repro on build version:**  Android internal build V1.17.0, Playstore build V1.16 & Testflight build V1.17.0(71), Appstore build V1.1
**Repro on devices:** Vivo V11 pro (10),  Redmi Note 8 (9.0),iPhone 6+(12.5.4), iPhone 12 (14.7.1)
**Testing Account:**     (680) 333 1978/ [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
**Pre-condition:** Make sure user should wait for 3-5mins after purchase on the activity screen. 
**Repro Steps:**

1. Launch the application & Login with test account 
2. Go to celo buy/Sell page 
3. Tap on Buy button 
4. enter valid amount 
5. Tap on review button 
6. Tap on celo buy button
7. wait for 5mins on activity & observe 

**Current Behavior:**  Connecting activity is shown for longer time
**Expected Behavior:**  Activity should confirm after some time 
**Observations** 

- Sold activity is shown confirmed after some time 
- Amount get updated after some time for purchased 
- Activity is not shown after kill & relaunch when it was in connecting state 

**Impact:** Bad user experience 
**Attachment:** [ConnectingText.mp4](https://drive.google.com/file/d/1_Ethdnum-TToshiQXOOqrj1EiVcvRfTe/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D82](https://valora.testquality.com/project/12128/result/2450418/defect/8017).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D93](https://valora.testquality.com/project/12128/result/2464175/defect/8064).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D104](https://valora.testquality.com/project/12128/result/2470969/defect/8183).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D105](https://valora.testquality.com/project/12128/result/2470987/defect/8184).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D112](https://valora.testquality.com/project/12128/result/2471065/defect/8191).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D113](https://valora.testquality.com/project/12128/result/2471068/defect/8192).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D114](https://valora.testquality.com/project/12128/result/2471081/defect/8193).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D115](https://valora.testquality.com/project/12128/result/2471088/defect/8194).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D116](https://valora.testquality.com/project/12128/result/2471091/defect/8195).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D117](https://valora.testquality.com/project/12128/result/2471104/defect/8196).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D131](https://valora.testquality.com/project/12128/result/2481989/defect/8222).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D136](https://valora.testquality.com/project/12128/result/2483351/defect/8244).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D137](https://valora.testquality.com/project/12128/result/2483369/defect/8245).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D140](https://valora.testquality.com/project/12128/result/2485620/defect/8260).

**Comment by ValoraQA** [comment]
Hey, We have verified this issue with Latest Android internal build V1.19.0 & Test flight Build V1.19.0, We have observed that.

Instead of "Connecting..." text appearing before, Now "Confirming....." text appears continuously for longer time when user purchased CELO.

**Devices:** Redmi Note 8(10.0), iPhone 12 (14.7.1)  

**Attachments:** 
[Confirming Text.jpg](https://drive.google.com/file/d/1nQ3LLgHLwcklm2Zcv2rPaRDc6Da4rQoq/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D144](https://valora.testquality.com/project/12128/result/2507071/defect/8269).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D145](https://valora.testquality.com/project/12128/result/2507075/defect/8270).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D146](https://valora.testquality.com/project/12128/result/2508143/defect/8271).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D147](https://valora.testquality.com/project/12128/result/2508147/defect/8272).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D148](https://valora.testquality.com/project/12128/result/2508149/defect/8273).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D149](https://valora.testquality.com/project/12128/result/2508153/defect/8274).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D152](https://valora.testquality.com/project/12128/result/2508155/defect/8278).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D153](https://valora.testquality.com/project/12128/result/2508159/defect/8279).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D155](https://valora.testquality.com/project/12128/result/2510220/defect/8282).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D156](https://valora.testquality.com/project/12128/result/2510224/defect/8284).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D160](https://valora.testquality.com/project/12128/result/2510806/defect/8296).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D161](https://valora.testquality.com/project/12128/result/2510810/defect/8297).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D163](https://valora.testquality.com/project/12128/result/2510800/defect/8299).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D165](https://valora.testquality.com/project/12128/result/2510794/defect/8301).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D166](https://valora.testquality.com/project/12128/result/2510798/defect/8302).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D167](https://valora.testquality.com/project/12128/result/2510804/defect/8303).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D170](https://valora.testquality.com/project/12128/result/2513102/defect/8306).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D171](https://valora.testquality.com/project/12128/result/2513106/defect/8307).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D172](https://valora.testquality.com/project/12128/result/2513773/defect/8314).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D173](https://valora.testquality.com/project/12128/result/2513777/defect/8315).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D174](https://valora.testquality.com/project/12128/result/2513791/defect/8316).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D182](https://valora.testquality.com/project/12128/result/2514625/defect/8333).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D184](https://valora.testquality.com/project/12128/result/2514629/defect/8335).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D187](https://valora.testquality.com/project/12128/result/2515655/defect/8343).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D192](https://valora.testquality.com/project/12128/result/2515659/defect/8348).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D221](https://valora.testquality.com/project/12128/result/2515643/defect/8390).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D222](https://valora.testquality.com/project/12128/result/2515647/defect/8392).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D228](https://valora.testquality.com/project/12128/result/2515673/defect/8398).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D229](https://valora.testquality.com/project/12128/result/2515677/defect/8399).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D244](https://valora.testquality.com/project/12128/result/2515667/defect/8414).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D245](https://valora.testquality.com/project/12128/result/2515671/defect/8415).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D252](https://valora.testquality.com/project/12128/result/2515649/defect/8422).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D253](https://valora.testquality.com/project/12128/result/2515653/defect/8423).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D288](https://valora.testquality.com/project/12128/result/2530814/defect/8500).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D312](https://valora.testquality.com/project/12128/result/2535232/defect/8541).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D316](https://valora.testquality.com/project/12128/result/2535140/defect/8546).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D317](https://valora.testquality.com/project/12128/result/2535146/defect/8547).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D654](https://valora.testquality.com/project/12128/result/2573787/defect/9275).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D666](https://valora.testquality.com/project/12128/result/2573893/defect/9304).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D667](https://valora.testquality.com/project/12128/result/2573896/defect/9305).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D668](https://valora.testquality.com/project/12128/result/2573909/defect/9306).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D684](https://valora.testquality.com/project/12128/result/2581261/defect/9328).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D685](https://valora.testquality.com/project/12128/result/2581265/defect/9329).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D689](https://valora.testquality.com/project/12128/result/2581273/defect/9338).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D690](https://valora.testquality.com/project/12128/result/2581277/defect/9339).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D699](https://valora.testquality.com/project/12128/result/2586772/defect/9358).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D700](https://valora.testquality.com/project/12128/result/2586776/defect/9359).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D701](https://valora.testquality.com/project/12128/result/2586784/defect/9360).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D702](https://valora.testquality.com/project/12128/result/2586788/defect/9361).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D712](https://valora.testquality.com/project/12128/result/2586766/defect/9373).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D713](https://valora.testquality.com/project/12128/result/2586770/defect/9374).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D724](https://valora.testquality.com/project/12128/result/2586796/defect/9385).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D725](https://valora.testquality.com/project/12128/result/2586800/defect/9386).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D776](https://valora.testquality.com/project/12128/result/2586802/defect/9442).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D777](https://valora.testquality.com/project/12128/result/2586806/defect/9443).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.29.2 & Test flight Release Build V 1.29.2 and observed that the issue is fixed now. "Confirming....." text is not appearing for longer time when user purchased CELO, hence we are closing the issue.

**Devices:** Samsung Galaxy A9 pro (8.0), iPhone 13 mini(15.1.1), iPhone 7(13.3), Redmi Note 7 Pro(10.0)

**Attachments:** [Confirming.mp4](https://drive.google.com/file/d/1731Q1FKXY_cohyYWrV_MDNLYn0kBI4L2/view?usp=sharing)

Thanks..!!
