### ISSUE TITLE
User redirects to safari browser on tapping “< ” button in top left corner in the App store. 

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#943]
**Frequency:** 100%
**Repro on build version:** Test flight Build V1.17.0, V1.16.2
**Does not repro build version**Android Internal Build V1.17.0, Test flight Build V1.15.2
**Repro on devices:** iPhone 12 (14.7.1), iPhone 6+ (12.4.5)
**Does not repro devices:** Google Pixel 4a (11),Samsung Galaxy S4 (4.4.2),  LG K7i (6.0), iPhone 12 (14.7.1) 

**Pre-condition:**
1. User must have installed the application and logged in.
2. User must have "Enjoying Valora? Help us by clicking ..“ In-app CTA along with Open & Dismiss buttons

**Repro Steps:**
1. Launch the application. 
2. Tap on “Open” button form "Enjoying Valora? Help us by clicking ..“ In-app CTA 
3. Tap on Back Button at top left corner after getting redirected to appstore.
4. Observe that.

**Current Behavior:**  User redirects to safari page on tapping back button in top left in App store.
**Expected Behavior:**  User should redirect to Valora App on tapping back button in top left in App store.
**Impact:** Bad user experience as user redirects to Safari page on tapping back 
**Investigation:** This issue is not reproducible in Android Platform, in android user redirects to home page in valora app on tapping device back button.

**Attachment:** 
[iOS back button issue.mp4](https://drive.google.com/file/d/1in3ntFdE4lCQHXqQ-etkupZ_WO_R5aJP/view?usp=sharing)
[Android Behaviour.mp4](https://drive.google.com/file/d/1vQVDhBX4-NKrmUCfV6hTjgDLnDjZ93ir/view?usp=sharing )

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D89](https://valora.testquality.com/project/12128/result/2457339/defect/8036).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D103](https://valora.testquality.com/project/12128/result/2470967/defect/8182).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D449](https://valora.testquality.com/project/12128/result/2545932/defect/8757).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D653](https://valora.testquality.com/project/12128/result/2573785/defect/9274).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D879](https://valora.testquality.com/project/12128/result/2611175/defect/9682).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Test flight Release Build V1.29.2 & observed the following.

**Observation:**
- User redirects to Privacy policy page on tapping back button in top left in App store.
- This issue is not reproducible in Android Platform, in android user redirects to home page in valora app on tapping device back button.

**Devices:** iPhone 13 mini(15.1.1), iPhone 6+(12.5.5)

**Attachments:** [iOS behaviour.mp4](https://drive.google.com/file/d/1VQwe8BIOZKn-y4K6G9eRaVu8rLysc5rU/view?usp=sharing)

Thanks..!!
