### ISSUE TITLE
“Invite Sent” activity displayed in a "Recent" feed on the home screen even though the user has not completed the invitation flow successfully

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#970]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.17.0, Test flight build V1.17.0
**Repro on devices:** iPhone 6+(12.4.5), Google Pixel 4a (11.0) iPhone 12(14.7.1), Vivo V11 pro (10), iPhone SE (14.2)
**Testing Account:**   (680) 333 1978 / [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9)
**Pre-condition:** Make sure that the user should have more than one option to share an invitation.
**Repro Steps:**
1.  Launch the application & login with the test account.
2. Tap on “Send” button & search for unverified valid number for invitation
3. Select number & redirect to Sending screen with “Send & Invite” button by sending some amount
4. Tap on the “Send & Invite” button.
5. Tap on “Invite” button on Invite popup
6. Now user is on sharing options screen 
7. Now tap on anywhere & make sure that no sharing options should be selected
8. Now user redirects to Home screen & observed that, 
**Current Behavior:**  “Invite Sent” activity displayed in home screen with phone number & amount even user has not selected sharing option
**Expected Behavior:**  Users should redirect to the Home screen without any “Invite Sent” activity as invitations are not done successfully.
**Impact:** User may feel like he invited to User B as activity with money deducted display in Home screen but actually not.
**Investigation:** Also we have observed that money is not actually deducted from the account. Only visible on the Home screen.
**Attachment:** [InviteSentFeedEvenNotInvited.mp4](https://drive.google.com/file/d/1rnQSRibbzMIexhde2R29VPcSkQGwoz_f/view?usp=sharing)

**Comment by MuckT** [comment]
Invitations are sent and then the messages are shared manually. There is not currently a way for us to know if the user has manually sent the invitation. In the attached video the user starts with a cEUR balance of 5.31 send the invite then has 5.29 cEUR left.

**Comment by ValoraQA** [comment]
Thanks @MuckT for Confirmation. Sure we will take a note of it & will test for way to check manually sent invitation in future once we will find it..!!

**Comment by ValoraQA** [comment]
Hey @MuckT need some clarification to us hence reopening this ticket.
**Observation:**
- In our application currently user not able to see from exactly which option user has sent invitation as user not selected any sharing option but still money gets deducted & activity displayed for same.
- So it would be great that if we do changes like user should only able to see activity for invite in Recent feed only after successfully completion of invite flow.
- Also if user performed this interrupting invitation flow from sharing option then that activity should not be performed (both money should not deduct & activity should not display in Home feed) as user has not selected sharing option
**Verified On Devices:** Samsung Galaxy F41 (11.0) , Samsung Galaxy M01 Core (10.0), Samsung Galaxy J5 Prime (8.0)
**Attachment:** [InviteSentFeedEvenNotInvited.mp4](https://drive.google.com/file/d/1JQ4EqmUGzINOEBsp0cjeAfaF9ckdQq4M/view?usp=sharing)
