### ISSUE TITLE
Label invite rewards correctly in the feed

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#986]
### Current behavior
Rewards received from inviting others show up as "Payment received" in the feed

### Desired behavior
They should say "Reward received"

### Steps to Reproduce
Invite someone to Valora (in alfajores only for now) verify with their phone number, receive the reward and check the copy.

### Versions
All

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Android Alfajores build V1.20.1, Test flight Alfajores build 1.20.1 (163277387) & updated the status in below sheet.

**Sheet Link:** https://docs.google.com/spreadsheets/d/1kJdb-eT69OM35LQUIpBKMI5MXNG-oXVaYoflX6XmGfA/edit#gid=1803698288

**Devices:** iPhone 12 (14.7.1), Redmi Note 8 (10.0), iPhone 6+ (12.5.4), OnePlus 7t (11.0)

**New Bug:** [Link](https://github.com/valora-inc/wallet/issues/1193)

CC: @gnardini

**Comment by gnardini** [comment]
Answered in #1193

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Test flight Alfajores build 1.20.1 (163277387) & updated the status in below  Test Quality tool. 
**Test Qulity Tool link:**
- https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516245
**Verified On Devices:** iPhone Xs Max(13.5.1)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using latest testflight build V1.20.1 & updated the status in the test quality tool & observed that the issue of "Reward received" activity not displayed in invite sender's recent activity is still reproducible.

**Test Quality Tool link:**

**iOS(15):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516253
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516254

**Devices:** iPhone 12 (15.0)
CC: @gnardini
