### ISSUE TITLE
[analytics] Add analytics events to transaction signing

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#991]
We have no events that tell us when users sign a transaction. Add them!

**Comment by grvalora** [comment]
Test comment

**Comment by grvalora** [comment]
Hi @gnardini , 
Could you please use the following naming convention and parameters for this specific event. 

event name : 
transaction_signing_succesful  : event is triggered when the signing in valora for third party apps are succesful 
Parameters : 
transactions_amount : the amount to validate as float in. If Not for amount send the value as `0`
transaction_type : The type of signin requested, examples include swapping, farming_pool, reward_claim 
transaction_currency : send the code of the coin type being uses as per the celo standards ex: celo, cusd, ceur etc
user_address : send the address of the user 
country_code : send the iso format of the country code in alpha 2 format  as per the mobile number of user ex US, GB, DE etc

Let me know if you need more information. 

Regards,
Gowtham Reddy

**Comment by aleksey-nov** [comment]
I would also add next parameters:
- Address of the smart contract that user interacts with;
- The name of the function in the smart contract being called

**Comment by grvalora** [comment]
@gnardini : Finalised parameter and event names

event name :
transaction_signing_succesful : event is triggered when the signing in valora for third party apps are succesful
Parameters :
transactions_amount : the amount to validate as float in. If Not for amount send the value as 0
transaction_type : The type of signin requested, examples include swapping, farming_pool, reward_claim
transaction_currency : send the code of the coin type being uses as per the celo standards ex: celo, cusd, ceur etc
user_address : send the address of the user
country_code : send the iso format of the country code in alpha 2 format as per the mobile number of user ex US, GB, DE etc
smart_contract_address: Address of the smart contract that user interacts with
function_name : The name of the function in the smart contract being called
