### ISSUE TITLE
Add cEUR support for Bidali

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#999]
Bidali now supports purchasing gift card with cEUR from their website

To do: allow purchasing Bidali vouchers using cEUR from the Valora app.

**Comment by aleksey-nov** [comment]
Gonza shared with me that Bidali guys have already raised a PR to implement this change. Will need to review it and make sure that it is included in the next app release.

**Comment by ValoraQA** [comment]
Hi @gnardini , We have verified this task on latest Alphajores build V1.19.0 and updated the status in below sheet.
**Note:** We have skipped for Android as we do not have the latest alphajores build V1.19.0, the latest alphajores build for android is V1.18.3
**Sheet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1706198817

**Devices:** iPhone 12 (14.7.1)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R99](https://valora.testquality.com/project/12128/testcase/299602/requirement/11870).

**Comment by ValoraQA** [comment]
Hi @gnardini , We have verified this task on latest Alphajores build V1.19.0 and updated the status in Test Quality tool
Note: We have skipped for Android as we do not have the latest alphajores build V1.19.0, the latest alphajores build for android see is V1.18.3

**Test Quality tool link:**

**iOS (13.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485154

**Verified on Devices:** iPhone SE(13.6.1)
